// Generated by HLC 4.0.0 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <kha/graphics4/Graphics2.h>
#include <kha/graphics4/FragmentShader.h>
#include <kha/Shaders.h>
#include <kha/graphics4/VertexShader.h>
void kha_graphics2_Graphics_new(kha__graphics2__Graphics);
int kha_graphics4_Graphics2_set_color(kha__graphics4__Graphics2,int);
extern hl_type $t_fun_235f082;
extern hl_type $t_kha_graphics4_ImageShaderPainter;
void kha_graphics4_ImageShaderPainter_new(kha__graphics4__ImageShaderPainter,vvirtual*);
extern hl_type $t_kha_graphics4_ColoredShaderPainter;
void kha_graphics4_ColoredShaderPainter_new(kha__graphics4__ColoredShaderPainter,vvirtual*);
extern hl_type $t_kha_graphics4_TextShaderPainter;
void kha_graphics4_TextShaderPainter_new(kha__graphics4__TextShaderPainter,vvirtual*);
int kha_graphics2_Graphics_get_fontSize(kha__graphics2__Graphics);
extern hl_type $t_kha_math_FastMatrix4;
void kha_math_FastMatrix4_new(kha__math__FastMatrix4,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float);
void kha_graphics4_Graphics2_setProjection(kha__graphics4__Graphics2);
extern kha__graphics4__$Graphics2 $g__kha_graphics4_Graphics2;
kha__graphics4__VertexStructure kha_graphics4_Graphics2_createImageVertexStructure(void);
kha__graphics4__PipelineState kha_graphics4_Graphics2_createImagePipeline(kha__graphics4__VertexStructure);
extern kha__$Shaders $g__kha_Shaders;
void kha_graphics4_PipelineState_compile(kha__graphics4__PipelineState);
#include <kha/Framebuffer.h>
extern hl_type $t_fun_4dc72d5;
extern kha__$Framebuffer $g__kha_Framebuffer;
bool Std_is(vdynamic*,vdynamic*);
bool kha_Image_get_nonPow2Supported(void);
extern hl_type $t_fun_bf7849e;
void kha_graphics4_ImageShaderPainter_setProjection(kha__graphics4__ImageShaderPainter,kha__math__FastMatrix4);
void kha_graphics4_ColoredShaderPainter_setProjection(kha__graphics4__ColoredShaderPainter,kha__math__FastMatrix4);
void kha_graphics4_TextShaderPainter_setProjection(kha__graphics4__TextShaderPainter,kha__math__FastMatrix4);
void kha_graphics4_ImageShaderPainter_end(kha__graphics4__ImageShaderPainter);
void kha_graphics4_TextShaderPainter_end(kha__graphics4__TextShaderPainter);
double kha_graphics2_Graphics_get_opacity(kha__graphics2__Graphics);
void kha_graphics4_ColoredShaderPainter_fillRect(kha__graphics4__ColoredShaderPainter,float,int,double,double,double,double,double,double,double,double);
extern String $s_End_before_you_begin;
extern hl_type $t_fun_58e3acc;
void kha_graphics4_Graphics2_clear(kha__graphics4__Graphics2,vdynamic*);
void kha_graphics4_Graphics2_flush(kha__graphics4__Graphics2);
extern hl_type $t_i32;
extern hl_type $t_fun_5967954;
#include <kha/graphics4/ColoredShaderPainter.h>
extern kha__graphics4__$ColoredShaderPainter $g_59e5fb3;
void kha_graphics4_ColoredShaderPainter_drawTriBuffer(kha__graphics4__ColoredShaderPainter,bool);
void kha_graphics4_ColoredShaderPainter_drawBuffer(kha__graphics4__ColoredShaderPainter,bool);
extern hl_type $t_fun_4c7a70a;
extern String $s_Begin_before_you_end;
extern hl_type $t_kha_graphics4_VertexStructure;
void kha_graphics4_VertexStructure_new(kha__graphics4__VertexStructure);
extern String $s_vertexPosition;
void kha_graphics4_VertexStructure_add(kha__graphics4__VertexStructure,String,int);
extern String $s_texPosition;
extern String $s_vertexColor;
extern hl_type $t_kha_graphics4_PipelineState;
void kha_graphics4_PipelineState_new(kha__graphics4__PipelineState);
#include <hl/natives.h>
hl__types__ArrayObj hl_types_ArrayObj_alloc(varray*);

void kha_graphics4_Graphics2_new(kha__graphics4__Graphics2 r0,vvirtual* r1) {
	kha__graphics4__FragmentShader r28;
	kha__graphics4__PipelineState r25;
	vvirtual *r4;
	kha__math__FastMatrix4 r8;
	kha__$Shaders r29;
	kha__graphics4__VertexShader r30;
	kha__graphics4__ImageShaderPainter r5;
	kha__graphics4__TextShaderPainter r7;
	kha__graphics4__ColoredShaderPainter r6;
	float r9, r10, r11, r12, r13, r14, r15, r16, r17, r18, r19, r20, r21, r22, r23, r24;
	kha__graphics4__VertexStructure r27;
	kha__graphics4__$Graphics2 r26;
	int r3;
	kha_graphics2_Graphics_new(((kha__graphics2__Graphics)r0));
	r3 = -1;
	r3 = kha_graphics4_Graphics2_set_color(r0,r3);
	r0->canvas = r1;
	if( r1 == NULL ) hl_null_access();
	if( hl_vfields(r1)[4] ) r4 = ((vvirtual* (*)(vdynamic*))hl_vfields(r1)[4])(r1->value); else {
		r4 = (vvirtual*)hl_dyn_call_obj(r1->value,&$t_fun_235f082,-483397588/*get_g4*/,NULL,NULL);
	}
	r0->g = r4;
	r5 = (kha__graphics4__ImageShaderPainter)hl_alloc_obj(&$t_kha_graphics4_ImageShaderPainter);
	r4 = r0->g;
	kha_graphics4_ImageShaderPainter_new(r5,r4);
	r0->imagePainter = r5;
	r6 = (kha__graphics4__ColoredShaderPainter)hl_alloc_obj(&$t_kha_graphics4_ColoredShaderPainter);
	r4 = r0->g;
	kha_graphics4_ColoredShaderPainter_new(r6,r4);
	r0->coloredPainter = r6;
	r7 = (kha__graphics4__TextShaderPainter)hl_alloc_obj(&$t_kha_graphics4_TextShaderPainter);
	r4 = r0->g;
	kha_graphics4_TextShaderPainter_new(r7,r4);
	r0->textPainter = r7;
	r7 = r0->textPainter;
	if( r7 == NULL ) hl_null_access();
	r3 = kha_graphics2_Graphics_get_fontSize(((kha__graphics2__Graphics)r0));
	r7->fontSize = r3;
	r8 = (kha__math__FastMatrix4)hl_alloc_obj(&$t_kha_math_FastMatrix4);
	r3 = 1;
	r9 = (float)r3;
	r3 = 0;
	r10 = (float)r3;
	r3 = 0;
	r11 = (float)r3;
	r3 = 0;
	r12 = (float)r3;
	r3 = 0;
	r13 = (float)r3;
	r3 = 1;
	r14 = (float)r3;
	r3 = 0;
	r15 = (float)r3;
	r3 = 0;
	r16 = (float)r3;
	r3 = 0;
	r17 = (float)r3;
	r3 = 0;
	r18 = (float)r3;
	r3 = 1;
	r19 = (float)r3;
	r3 = 0;
	r20 = (float)r3;
	r3 = 0;
	r21 = (float)r3;
	r3 = 0;
	r22 = (float)r3;
	r3 = 0;
	r23 = (float)r3;
	r3 = 1;
	r24 = (float)r3;
	kha_math_FastMatrix4_new(r8,r9,r10,r11,r12,r13,r14,r15,r16,r17,r18,r19,r20,r21,r22,r23,r24);
	r0->projectionMatrix = r8;
	kha_graphics4_Graphics2_setProjection(r0);
	r26 = (kha__graphics4__$Graphics2)$g__kha_graphics4_Graphics2;
	r25 = r26->videoPipeline;
	if( r25 ) goto label$30de1a7_1_82;
	r27 = kha_graphics4_Graphics2_createImageVertexStructure();
	r25 = kha_graphics4_Graphics2_createImagePipeline(r27);
	r26 = (kha__graphics4__$Graphics2)$g__kha_graphics4_Graphics2;
	r26->videoPipeline = r25;
	r26 = (kha__graphics4__$Graphics2)$g__kha_graphics4_Graphics2;
	r25 = r26->videoPipeline;
	if( r25 == NULL ) hl_null_access();
	r29 = (kha__$Shaders)$g__kha_Shaders;
	r28 = r29->painter_video_frag;
	r25->fragmentShader = r28;
	r26 = (kha__graphics4__$Graphics2)$g__kha_graphics4_Graphics2;
	r25 = r26->videoPipeline;
	if( r25 == NULL ) hl_null_access();
	r29 = (kha__$Shaders)$g__kha_Shaders;
	r30 = r29->painter_video_vert;
	r25->vertexShader = r30;
	r26 = (kha__graphics4__$Graphics2)$g__kha_graphics4_Graphics2;
	r25 = r26->videoPipeline;
	if( r25 == NULL ) hl_null_access();
	kha_graphics4_PipelineState_compile(r25);
	label$30de1a7_1_82:
	return;
}

int kha_graphics4_Graphics2_upperPowerOfTwo(int r0) {
	int r1, r2, r3;
	--r0;
	r3 = 1;
	r2 = ((unsigned)r0) >> r3;
	r1 = r0 | r2;
	r3 = 2;
	r2 = ((unsigned)r1) >> r3;
	r1 = r1 | r2;
	r3 = 4;
	r2 = ((unsigned)r1) >> r3;
	r1 = r1 | r2;
	r3 = 8;
	r2 = ((unsigned)r1) >> r3;
	r1 = r1 | r2;
	r3 = 16;
	r2 = ((unsigned)r1) >> r3;
	r1 = r1 | r2;
	r0 = r1;
	++r0;
	return r0;
}

void kha_graphics4_Graphics2_setProjection(kha__graphics4__Graphics2 r0) {
	vvirtual *r2, *r27;
	kha__math__FastMatrix4 r7;
	bool r5;
	kha__$Framebuffer r6;
	kha__graphics4__ImageShaderPainter r28;
	kha__graphics4__TextShaderPainter r30;
	kha__graphics4__ColoredShaderPainter r29;
	float r9, r12, r13, r14, r15, r16, r17, r18, r19, r20, r21, r22, r23, r24, r25, r26;
	double r8, r11;
	int r1, r4, r10;
	r2 = r0->canvas;
	if( r2 == NULL ) hl_null_access();
	if( hl_vfields(r2)[2] ) r1 = ((int (*)(vdynamic*))hl_vfields(r2)[2])(r2->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r2->value,&$t_fun_4dc72d5,235672157/*get_width*/,NULL,&ret);
		r1 = (int)ret.v.i;
	}
	r2 = r0->canvas;
	if( r2 == NULL ) hl_null_access();
	if( hl_vfields(r2)[3] ) r4 = ((int (*)(vdynamic*))hl_vfields(r2)[3])(r2->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r2->value,&$t_fun_4dc72d5,-221022288/*get_height*/,NULL,&ret);
		r4 = (int)ret.v.i;
	}
	r2 = r0->canvas;
	r6 = (kha__$Framebuffer)$g__kha_Framebuffer;
	r5 = Std_is(((vdynamic*)r2),((vdynamic*)r6));
	if( !r5 ) goto label$30de1a7_3_81;
	r7 = r0->projectionMatrix;
	r9 = (float)r1;
	r9 = -r9;
	r8 = (double)r9;
	r11 = (double)r1;
	r8 = r8 / r11;
	r9 = (float)r8;
	r12 = (float)r4;
	r12 = -r12;
	r8 = (double)r12;
	r10 = 0;
	r12 = (float)r10;
	r13 = (float)r4;
	r12 = r12 - r13;
	r11 = (double)r12;
	r8 = r8 / r11;
	r12 = (float)r8;
	r8 = -1.0002000200020003;
	r13 = (float)r8;
	r8 = 2.;
	r11 = (double)r1;
	r8 = r8 / r11;
	r14 = (float)r8;
	r10 = 0;
	r15 = (float)r10;
	r10 = 0;
	r16 = (float)r10;
	r10 = 0;
	r17 = (float)r10;
	r8 = 2.;
	r10 = 0;
	r18 = (float)r10;
	r19 = (float)r4;
	r18 = r18 - r19;
	r11 = (double)r18;
	r8 = r8 / r11;
	r18 = (float)r8;
	r10 = 0;
	r19 = (float)r10;
	r10 = 0;
	r20 = (float)r10;
	r10 = 0;
	r21 = (float)r10;
	r8 = -0.0020002000200020002;
	r22 = (float)r8;
	r10 = 0;
	r23 = (float)r10;
	r10 = 0;
	r24 = (float)r10;
	r10 = 0;
	r25 = (float)r10;
	r10 = 1;
	r26 = (float)r10;
	if( r7 == NULL ) hl_null_access();
	r7->_00 = r14;
	r7->_10 = r15;
	r7->_20 = r16;
	r7->_30 = r9;
	r7->_01 = r17;
	r7->_11 = r18;
	r7->_21 = r19;
	r7->_31 = r12;
	r7->_02 = r20;
	r7->_12 = r21;
	r7->_22 = r22;
	r7->_32 = r13;
	r7->_03 = r23;
	r7->_13 = r24;
	r7->_23 = r25;
	r7->_33 = r26;
	goto label$30de1a7_3_224;
	label$30de1a7_3_81:
	r5 = kha_Image_get_nonPow2Supported();
	if( r5 ) goto label$30de1a7_3_87;
	r10 = kha_graphics4_Graphics2_upperPowerOfTwo(r1);
	r1 = r10;
	r10 = kha_graphics4_Graphics2_upperPowerOfTwo(r4);
	r4 = r10;
	label$30de1a7_3_87:
	r27 = r0->g;
	if( r27 == NULL ) hl_null_access();
	if( hl_vfields(r27)[22] ) r5 = ((bool (*)(vdynamic*))hl_vfields(r27)[22])(r27->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r27->value,&$t_fun_bf7849e,226317528/*renderTargetsInvertedY*/,NULL,&ret);
		r5 = (bool)ret.v.i;
	}
	if( !r5 ) goto label$30de1a7_3_154;
	r7 = r0->projectionMatrix;
	r9 = (float)r1;
	r9 = -r9;
	r8 = (double)r9;
	r11 = (double)r1;
	r8 = r8 / r11;
	r9 = (float)r8;
	r12 = (float)r4;
	r12 = -r12;
	r8 = (double)r12;
	r11 = (double)r4;
	r8 = r8 / r11;
	r12 = (float)r8;
	r8 = -1.0002000200020003;
	r13 = (float)r8;
	r8 = 2.;
	r11 = (double)r1;
	r8 = r8 / r11;
	r14 = (float)r8;
	r10 = 0;
	r15 = (float)r10;
	r10 = 0;
	r16 = (float)r10;
	r10 = 0;
	r17 = (float)r10;
	r8 = 2.;
	r11 = (double)r4;
	r8 = r8 / r11;
	r18 = (float)r8;
	r10 = 0;
	r19 = (float)r10;
	r10 = 0;
	r20 = (float)r10;
	r10 = 0;
	r21 = (float)r10;
	r8 = -0.0020002000200020002;
	r22 = (float)r8;
	r10 = 0;
	r23 = (float)r10;
	r10 = 0;
	r24 = (float)r10;
	r10 = 0;
	r25 = (float)r10;
	r10 = 1;
	r26 = (float)r10;
	if( r7 == NULL ) hl_null_access();
	r7->_00 = r14;
	r7->_10 = r15;
	r7->_20 = r16;
	r7->_30 = r9;
	r7->_01 = r17;
	r7->_11 = r18;
	r7->_21 = r19;
	r7->_31 = r12;
	r7->_02 = r20;
	r7->_12 = r21;
	r7->_22 = r22;
	r7->_32 = r13;
	r7->_03 = r23;
	r7->_13 = r24;
	r7->_23 = r25;
	r7->_33 = r26;
	goto label$30de1a7_3_224;
	label$30de1a7_3_154:
	r7 = r0->projectionMatrix;
	r9 = (float)r1;
	r9 = -r9;
	r8 = (double)r9;
	r11 = (double)r1;
	r8 = r8 / r11;
	r9 = (float)r8;
	r12 = (float)r4;
	r12 = -r12;
	r8 = (double)r12;
	r10 = 0;
	r12 = (float)r10;
	r13 = (float)r4;
	r12 = r12 - r13;
	r11 = (double)r12;
	r8 = r8 / r11;
	r12 = (float)r8;
	r8 = -1.0002000200020003;
	r13 = (float)r8;
	r8 = 2.;
	r11 = (double)r1;
	r8 = r8 / r11;
	r14 = (float)r8;
	r10 = 0;
	r15 = (float)r10;
	r10 = 0;
	r16 = (float)r10;
	r10 = 0;
	r17 = (float)r10;
	r8 = 2.;
	r10 = 0;
	r18 = (float)r10;
	r19 = (float)r4;
	r18 = r18 - r19;
	r11 = (double)r18;
	r8 = r8 / r11;
	r18 = (float)r8;
	r10 = 0;
	r19 = (float)r10;
	r10 = 0;
	r20 = (float)r10;
	r10 = 0;
	r21 = (float)r10;
	r8 = -0.0020002000200020002;
	r22 = (float)r8;
	r10 = 0;
	r23 = (float)r10;
	r10 = 0;
	r24 = (float)r10;
	r10 = 0;
	r25 = (float)r10;
	r10 = 1;
	r26 = (float)r10;
	if( r7 == NULL ) hl_null_access();
	r7->_00 = r14;
	r7->_10 = r15;
	r7->_20 = r16;
	r7->_30 = r9;
	r7->_01 = r17;
	r7->_11 = r18;
	r7->_21 = r19;
	r7->_31 = r12;
	r7->_02 = r20;
	r7->_12 = r21;
	r7->_22 = r22;
	r7->_32 = r13;
	r7->_03 = r23;
	r7->_13 = r24;
	r7->_23 = r25;
	r7->_33 = r26;
	label$30de1a7_3_224:
	r28 = r0->imagePainter;
	if( r28 == NULL ) hl_null_access();
	r7 = r0->projectionMatrix;
	kha_graphics4_ImageShaderPainter_setProjection(r28,r7);
	r29 = r0->coloredPainter;
	if( r29 == NULL ) hl_null_access();
	r7 = r0->projectionMatrix;
	kha_graphics4_ColoredShaderPainter_setProjection(r29,r7);
	r30 = r0->textPainter;
	if( r30 == NULL ) hl_null_access();
	r7 = r0->projectionMatrix;
	kha_graphics4_TextShaderPainter_setProjection(r30,r7);
	return;
}

int kha_graphics4_Graphics2_get_color(kha__graphics4__Graphics2 r0) {
	int r1;
	r1 = r0->myColor;
	return r1;
}

int kha_graphics4_Graphics2_set_color(kha__graphics4__Graphics2 r0,int r1) {
	r0->myColor = r1;
	return r1;
}

void kha_graphics4_Graphics2_fillRect(kha__graphics4__Graphics2 r0,double r1,double r2,double r3,double r4) {
	hl__types__ArrayObj r8;
	kha__graphics4__ImageShaderPainter r6;
	kha__graphics4__TextShaderPainter r7;
	kha__graphics4__ColoredShaderPainter r43;
	float r15, r17, r18, r20, r21, r23, r24, r25, r27, r28, r30, r31, r32, r34, r35, r37, r38, r39, r40, r41, r44;
	double r14, r16, r22, r29, r36, r42, r45, r46, r47, r48, r49, r50;
	vdynamic *r12;
	kha__math__FastMatrix3 r11, r19, r26, r33;
	varray *r13;
	int r9, r10;
	r6 = r0->imagePainter;
	if( r6 == NULL ) hl_null_access();
	kha_graphics4_ImageShaderPainter_end(r6);
	r7 = r0->textPainter;
	if( r7 == NULL ) hl_null_access();
	kha_graphics4_TextShaderPainter_end(r7);
	r8 = r0->transformations;
	if( r8 == NULL ) hl_null_access();
	r9 = r0->transformationIndex;
	r10 = r8->length;
	if( ((unsigned)r9) < ((unsigned)r10) ) goto label$30de1a7_6_13;
	r11 = NULL;
	goto label$30de1a7_6_16;
	label$30de1a7_6_13:
	r13 = r8->array;
	r12 = ((vdynamic**)(r13 + 1))[r9];
	r11 = (kha__math__FastMatrix3)r12;
	label$30de1a7_6_16:
	r15 = (float)r1;
	r14 = r2 + r4;
	r17 = (float)r14;
	if( r11 == NULL ) hl_null_access();
	r18 = r11->_02;
	r18 = r18 * r15;
	r20 = r11->_12;
	r20 = r20 * r17;
	r18 = r18 + r20;
	r20 = r11->_22;
	r18 = r18 + r20;
	r20 = r11->_00;
	r20 = r20 * r15;
	r21 = r11->_10;
	r21 = r21 * r17;
	r20 = r20 + r21;
	r21 = r11->_20;
	r20 = r20 + r21;
	r14 = (double)r20;
	r16 = (double)r18;
	r14 = r14 / r16;
	r20 = r11->_01;
	r20 = r20 * r15;
	r21 = r11->_11;
	r21 = r21 * r17;
	r20 = r20 + r21;
	r21 = r11->_21;
	r20 = r20 + r21;
	r16 = (double)r20;
	r22 = (double)r18;
	r16 = r16 / r22;
	r20 = (float)r16;
	r21 = (float)r14;
	r8 = r0->transformations;
	if( r8 == NULL ) hl_null_access();
	r9 = r0->transformationIndex;
	r10 = r8->length;
	if( ((unsigned)r9) < ((unsigned)r10) ) goto label$30de1a7_6_56;
	r19 = NULL;
	goto label$30de1a7_6_59;
	label$30de1a7_6_56:
	r13 = r8->array;
	r12 = ((vdynamic**)(r13 + 1))[r9];
	r19 = (kha__math__FastMatrix3)r12;
	label$30de1a7_6_59:
	r23 = (float)r1;
	r24 = (float)r2;
	if( r19 == NULL ) hl_null_access();
	r25 = r19->_02;
	r25 = r25 * r23;
	r27 = r19->_12;
	r27 = r27 * r24;
	r25 = r25 + r27;
	r27 = r19->_22;
	r25 = r25 + r27;
	r27 = r19->_00;
	r27 = r27 * r23;
	r28 = r19->_10;
	r28 = r28 * r24;
	r27 = r27 + r28;
	r28 = r19->_20;
	r27 = r27 + r28;
	r16 = (double)r27;
	r22 = (double)r25;
	r16 = r16 / r22;
	r27 = r19->_01;
	r27 = r27 * r23;
	r28 = r19->_11;
	r28 = r28 * r24;
	r27 = r27 + r28;
	r28 = r19->_21;
	r27 = r27 + r28;
	r22 = (double)r27;
	r29 = (double)r25;
	r22 = r22 / r29;
	r27 = (float)r22;
	r28 = (float)r16;
	r8 = r0->transformations;
	if( r8 == NULL ) hl_null_access();
	r9 = r0->transformationIndex;
	r10 = r8->length;
	if( ((unsigned)r9) < ((unsigned)r10) ) goto label$30de1a7_6_98;
	r26 = NULL;
	goto label$30de1a7_6_101;
	label$30de1a7_6_98:
	r13 = r8->array;
	r12 = ((vdynamic**)(r13 + 1))[r9];
	r26 = (kha__math__FastMatrix3)r12;
	label$30de1a7_6_101:
	r22 = r1 + r3;
	r30 = (float)r22;
	r31 = (float)r2;
	if( r26 == NULL ) hl_null_access();
	r32 = r26->_02;
	r32 = r32 * r30;
	r34 = r26->_12;
	r34 = r34 * r31;
	r32 = r32 + r34;
	r34 = r26->_22;
	r32 = r32 + r34;
	r34 = r26->_00;
	r34 = r34 * r30;
	r35 = r26->_10;
	r35 = r35 * r31;
	r34 = r34 + r35;
	r35 = r26->_20;
	r34 = r34 + r35;
	r22 = (double)r34;
	r29 = (double)r32;
	r22 = r22 / r29;
	r34 = r26->_01;
	r34 = r34 * r30;
	r35 = r26->_11;
	r35 = r35 * r31;
	r34 = r34 + r35;
	r35 = r26->_21;
	r34 = r34 + r35;
	r29 = (double)r34;
	r36 = (double)r32;
	r29 = r29 / r36;
	r34 = (float)r29;
	r35 = (float)r22;
	r8 = r0->transformations;
	if( r8 == NULL ) hl_null_access();
	r9 = r0->transformationIndex;
	r10 = r8->length;
	if( ((unsigned)r9) < ((unsigned)r10) ) goto label$30de1a7_6_141;
	r33 = NULL;
	goto label$30de1a7_6_144;
	label$30de1a7_6_141:
	r13 = r8->array;
	r12 = ((vdynamic**)(r13 + 1))[r9];
	r33 = (kha__math__FastMatrix3)r12;
	label$30de1a7_6_144:
	r29 = r1 + r3;
	r37 = (float)r29;
	r29 = r2 + r4;
	r38 = (float)r29;
	if( r33 == NULL ) hl_null_access();
	r39 = r33->_02;
	r39 = r39 * r37;
	r40 = r33->_12;
	r40 = r40 * r38;
	r39 = r39 + r40;
	r40 = r33->_22;
	r39 = r39 + r40;
	r40 = r33->_00;
	r40 = r40 * r37;
	r41 = r33->_10;
	r41 = r41 * r38;
	r40 = r40 + r41;
	r41 = r33->_20;
	r40 = r40 + r41;
	r29 = (double)r40;
	r36 = (double)r39;
	r29 = r29 / r36;
	r40 = r33->_01;
	r40 = r40 * r37;
	r41 = r33->_11;
	r41 = r41 * r38;
	r40 = r40 + r41;
	r41 = r33->_21;
	r40 = r40 + r41;
	r36 = (double)r40;
	r42 = (double)r39;
	r36 = r36 / r42;
	r40 = (float)r36;
	r41 = (float)r29;
	r43 = r0->coloredPainter;
	if( r43 == NULL ) hl_null_access();
	r36 = kha_graphics2_Graphics_get_opacity(((kha__graphics2__Graphics)r0));
	r44 = (float)r36;
	r9 = kha_graphics4_Graphics2_get_color(r0);
	r36 = (double)r21;
	r42 = (double)r20;
	r45 = (double)r28;
	r46 = (double)r27;
	r47 = (double)r35;
	r48 = (double)r34;
	r49 = (double)r41;
	r50 = (double)r40;
	kha_graphics4_ColoredShaderPainter_fillRect(r43,r44,r9,r36,r42,r45,r46,r47,r48,r49,r50);
	return;
}

void kha_graphics4_Graphics2_begin(kha__graphics4__Graphics2 r0,bool* r1,vdynamic* r2) {
	String r7;
	hl__types__ArrayObj r9;
	vvirtual *r8;
	bool r3;
	kha__graphics4__Graphics2 r5;
	kha__graphics4__$Graphics2 r6;
	if( r1 ) goto label$30de1a7_7_3;
	r3 = true;
	goto label$30de1a7_7_4;
	label$30de1a7_7_3:
	r3 = *r1;
	label$30de1a7_7_4:
	r6 = (kha__graphics4__$Graphics2)$g__kha_graphics4_Graphics2;
	r5 = r6->current;
	if( r5 ) goto label$30de1a7_7_10;
	r6 = (kha__graphics4__$Graphics2)$g__kha_graphics4_Graphics2;
	r6->current = r0;
	goto label$30de1a7_7_12;
	label$30de1a7_7_10:
	r7 = (String)$s_End_before_you_begin;
	hl_throw((vdynamic*)r7);
	label$30de1a7_7_12:
	r8 = r0->g;
	if( r8 == NULL ) hl_null_access();
	r9 = NULL;
	if( hl_vfields(r8)[29] ) ((void (*)(vdynamic*,hl__types__ArrayObj))hl_vfields(r8)[29])(r8->value,r9); else {
		void *args[] = {r9};
		hl_dyn_call_obj(r8->value,&$t_fun_58e3acc,-262805217/*begin*/,args,NULL);
	}
	if( !r3 ) goto label$30de1a7_7_18;
	kha_graphics4_Graphics2_clear(r0,r2);
	label$30de1a7_7_18:
	kha_graphics4_Graphics2_setProjection(r0);
	return;
}

void kha_graphics4_Graphics2_clear(kha__graphics4__Graphics2 r0,vdynamic* r1) {
	vvirtual *r3;
	vdynamic *r4, *r6, *r7;
	int r5;
	kha_graphics4_Graphics2_flush(r0);
	r3 = r0->g;
	if( r3 == NULL ) hl_null_access();
	if( r1 ) goto label$30de1a7_8_7;
	r5 = -16777216;
	r4 = hl_alloc_dynamic(&$t_i32);
	r4->v.i = r5;
	goto label$30de1a7_8_8;
	label$30de1a7_8_7:
	r4 = r1;
	label$30de1a7_8_8:
	r6 = NULL;
	r7 = NULL;
	if( hl_vfields(r3)[27] ) ((void (*)(vdynamic*,vdynamic*,vdynamic*,vdynamic*))hl_vfields(r3)[27])(r3->value,r4,r6,r7); else {
		void *args[] = {r4,r6,r7};
		hl_dyn_call_obj(r3->value,&$t_fun_5967954,140210839/*clear*/,args,NULL);
	}
	return;
}

void kha_graphics4_Graphics2_flush(kha__graphics4__Graphics2 r0) {
	kha__graphics4__$ColoredShaderPainter r6;
	bool r8;
	kha__graphics4__ImageShaderPainter r2;
	kha__graphics4__TextShaderPainter r3;
	kha__graphics4__ColoredShaderPainter r4;
	int r5, r7;
	r2 = r0->imagePainter;
	if( r2 == NULL ) hl_null_access();
	kha_graphics4_ImageShaderPainter_end(r2);
	r3 = r0->textPainter;
	if( r3 == NULL ) hl_null_access();
	kha_graphics4_TextShaderPainter_end(r3);
	r4 = r0->coloredPainter;
	r6 = (kha__graphics4__$ColoredShaderPainter)$g_59e5fb3;
	r5 = r6->triangleBufferIndex;
	r7 = 0;
	if( r7 >= r5 ) goto label$30de1a7_9_14;
	if( r4 == NULL ) hl_null_access();
	r8 = false;
	kha_graphics4_ColoredShaderPainter_drawTriBuffer(r4,r8);
	label$30de1a7_9_14:
	r6 = (kha__graphics4__$ColoredShaderPainter)$g_59e5fb3;
	r5 = r6->bufferIndex;
	r7 = 0;
	if( r7 >= r5 ) goto label$30de1a7_9_21;
	if( r4 == NULL ) hl_null_access();
	r8 = false;
	kha_graphics4_ColoredShaderPainter_drawBuffer(r4,r8);
	label$30de1a7_9_21:
	return;
}

void kha_graphics4_Graphics2_end(kha__graphics4__Graphics2 r0) {
	String r5;
	vvirtual *r2;
	kha__graphics4__Graphics2 r3;
	kha__graphics4__$Graphics2 r4;
	kha_graphics4_Graphics2_flush(r0);
	r2 = r0->g;
	if( r2 == NULL ) hl_null_access();
	if( hl_vfields(r2)[23] ) ((void (*)(vdynamic*))hl_vfields(r2)[23])(r2->value); else {
		hl_dyn_call_obj(r2->value,&$t_fun_4c7a70a,5047259/*end*/,NULL,NULL);
	}
	r4 = (kha__graphics4__$Graphics2)$g__kha_graphics4_Graphics2;
	r3 = r4->current;
	if( r3 != r0 ) goto label$30de1a7_10_11;
	r3 = NULL;
	r4 = (kha__graphics4__$Graphics2)$g__kha_graphics4_Graphics2;
	r4->current = r3;
	goto label$30de1a7_10_13;
	label$30de1a7_10_11:
	r5 = (String)$s_Begin_before_you_end;
	hl_throw((vdynamic*)r5);
	label$30de1a7_10_13:
	return;
}

kha__graphics4__VertexStructure kha_graphics4_Graphics2_createImageVertexStructure() {
	String r2;
	int r3;
	kha__graphics4__VertexStructure r0;
	r0 = (kha__graphics4__VertexStructure)hl_alloc_obj(&$t_kha_graphics4_VertexStructure);
	kha_graphics4_VertexStructure_new(r0);
	r2 = (String)$s_vertexPosition;
	r3 = 2;
	kha_graphics4_VertexStructure_add(r0,r2,r3);
	r2 = (String)$s_texPosition;
	r3 = 1;
	kha_graphics4_VertexStructure_add(r0,r2,r3);
	r2 = (String)$s_vertexColor;
	r3 = 3;
	kha_graphics4_VertexStructure_add(r0,r2,r3);
	return r0;
}

kha__graphics4__PipelineState kha_graphics4_Graphics2_createImagePipeline(kha__graphics4__VertexStructure r0) {
	kha__graphics4__FragmentShader r3;
	kha__graphics4__PipelineState r1;
	hl__types__ArrayObj r6;
	hl_type *r8;
	kha__$Shaders r4;
	kha__graphics4__VertexShader r5;
	int r9;
	varray *r7;
	r1 = (kha__graphics4__PipelineState)hl_alloc_obj(&$t_kha_graphics4_PipelineState);
	kha_graphics4_PipelineState_new(r1);
	r4 = (kha__$Shaders)$g__kha_Shaders;
	r3 = r4->painter_image_frag;
	r1->fragmentShader = r3;
	r4 = (kha__$Shaders)$g__kha_Shaders;
	r5 = r4->painter_image_vert;
	r1->vertexShader = r5;
	r8 = &$t_kha_graphics4_VertexStructure;
	r9 = 1;
	r7 = hl_alloc_array(r8,r9);
	r9 = 0;
	((kha__graphics4__VertexStructure*)(r7 + 1))[r9] = r0;
	r6 = hl_types_ArrayObj_alloc(r7);
	r1->inputLayout = r6;
	r9 = 1;
	r1->blendSource = r9;
	r9 = 5;
	r1->blendDestination = r9;
	r9 = 1;
	r1->alphaBlendSource = r9;
	r9 = 5;
	r1->alphaBlendDestination = r9;
	return r1;
}

kha__graphics4__VertexStructure kha_graphics4_Graphics2_createColoredVertexStructure() {
	String r2;
	int r3;
	kha__graphics4__VertexStructure r0;
	r0 = (kha__graphics4__VertexStructure)hl_alloc_obj(&$t_kha_graphics4_VertexStructure);
	kha_graphics4_VertexStructure_new(r0);
	r2 = (String)$s_vertexPosition;
	r3 = 2;
	kha_graphics4_VertexStructure_add(r0,r2,r3);
	r2 = (String)$s_vertexColor;
	r3 = 3;
	kha_graphics4_VertexStructure_add(r0,r2,r3);
	return r0;
}

kha__graphics4__PipelineState kha_graphics4_Graphics2_createColoredPipeline(kha__graphics4__VertexStructure r0) {
	kha__graphics4__FragmentShader r3;
	kha__graphics4__PipelineState r1;
	hl__types__ArrayObj r6;
	hl_type *r8;
	kha__$Shaders r4;
	kha__graphics4__VertexShader r5;
	int r9;
	varray *r7;
	r1 = (kha__graphics4__PipelineState)hl_alloc_obj(&$t_kha_graphics4_PipelineState);
	kha_graphics4_PipelineState_new(r1);
	r4 = (kha__$Shaders)$g__kha_Shaders;
	r3 = r4->painter_colored_frag;
	r1->fragmentShader = r3;
	r4 = (kha__$Shaders)$g__kha_Shaders;
	r5 = r4->painter_colored_vert;
	r1->vertexShader = r5;
	r8 = &$t_kha_graphics4_VertexStructure;
	r9 = 1;
	r7 = hl_alloc_array(r8,r9);
	r9 = 0;
	((kha__graphics4__VertexStructure*)(r7 + 1))[r9] = r0;
	r6 = hl_types_ArrayObj_alloc(r7);
	r1->inputLayout = r6;
	r9 = 1;
	r1->blendSource = r9;
	r9 = 5;
	r1->blendDestination = r9;
	r9 = 1;
	r1->alphaBlendSource = r9;
	r9 = 5;
	r1->alphaBlendDestination = r9;
	return r1;
}

kha__graphics4__VertexStructure kha_graphics4_Graphics2_createTextVertexStructure() {
	String r2;
	int r3;
	kha__graphics4__VertexStructure r0;
	r0 = (kha__graphics4__VertexStructure)hl_alloc_obj(&$t_kha_graphics4_VertexStructure);
	kha_graphics4_VertexStructure_new(r0);
	r2 = (String)$s_vertexPosition;
	r3 = 2;
	kha_graphics4_VertexStructure_add(r0,r2,r3);
	r2 = (String)$s_texPosition;
	r3 = 1;
	kha_graphics4_VertexStructure_add(r0,r2,r3);
	r2 = (String)$s_vertexColor;
	r3 = 3;
	kha_graphics4_VertexStructure_add(r0,r2,r3);
	return r0;
}

kha__graphics4__PipelineState kha_graphics4_Graphics2_createTextPipeline(kha__graphics4__VertexStructure r0) {
	kha__graphics4__FragmentShader r3;
	kha__graphics4__PipelineState r1;
	hl__types__ArrayObj r6;
	hl_type *r8;
	kha__$Shaders r4;
	kha__graphics4__VertexShader r5;
	int r9;
	varray *r7;
	r1 = (kha__graphics4__PipelineState)hl_alloc_obj(&$t_kha_graphics4_PipelineState);
	kha_graphics4_PipelineState_new(r1);
	r4 = (kha__$Shaders)$g__kha_Shaders;
	r3 = r4->painter_text_frag;
	r1->fragmentShader = r3;
	r4 = (kha__$Shaders)$g__kha_Shaders;
	r5 = r4->painter_text_vert;
	r1->vertexShader = r5;
	r8 = &$t_kha_graphics4_VertexStructure;
	r9 = 1;
	r7 = hl_alloc_array(r8,r9);
	r9 = 0;
	((kha__graphics4__VertexStructure*)(r7 + 1))[r9] = r0;
	r6 = hl_types_ArrayObj_alloc(r7);
	r1->inputLayout = r6;
	r9 = 3;
	r1->blendSource = r9;
	r9 = 5;
	r1->blendDestination = r9;
	r9 = 3;
	r1->alphaBlendSource = r9;
	r9 = 5;
	r1->alphaBlendDestination = r9;
	return r1;
}

