// Generated by HLC 4.0.0 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <kha/graphics4/ImageShaderPainter.h>
extern kha__graphics4__$ImageShaderPainter $g_a0efbdf;
kha__graphics4__VertexStructure kha_graphics4_Graphics2_createImageVertexStructure(void);
kha__graphics4__PipelineState kha_graphics4_Graphics2_createImagePipeline(kha__graphics4__VertexStructure);
void kha_graphics4_PipelineState_compile(kha__graphics4__PipelineState);
extern hl_type $t_kha_graphics4_PipelineCache;
void kha_graphics4_PipelineCache_new(kha__graphics4__PipelineCache,kha__graphics4__PipelineState);
#include <kha/arrays/Uint32ArrayPrivate.h>
extern hl_type $t_kha_graphics4_VertexBuffer;
void kha_graphics4_VertexBuffer_new(kha__graphics4__VertexBuffer,int,kha__graphics4__VertexStructure,int,int*,bool*);
kha__arrays__Float32ArrayPrivate kha_graphics4_VertexBuffer_lock(kha__graphics4__VertexBuffer,vdynamic*,vdynamic*);
extern hl_type $t_kha_graphics4_IndexBuffer;
void kha_graphics4_IndexBuffer_new(kha__graphics4__IndexBuffer,int,int,bool*);
kha__arrays__Uint32ArrayPrivate kha_graphics4_IndexBuffer_lock(kha__graphics4__IndexBuffer);
#include <hl/natives.h>
void kha_graphics4_IndexBuffer_unlock(kha__graphics4__IndexBuffer);
extern hl_type $t_i32;
void kha_graphics4_VertexBuffer_unlock(kha__graphics4__VertexBuffer,vdynamic*);
extern hl_type $t_fun_a561c62;
extern hl_type $t_fun_46c6b6e;
extern hl_type $t_fun_c80ec77;
extern hl_type $t_fun_04e2896;
extern hl_type $t_fun_4ad9aaa;
extern hl_type $t_fun_896f717;
extern hl_type $t_fun_8305be0;

void kha_graphics4_ImageShaderPainter_setProjection(kha__graphics4__ImageShaderPainter r0,kha__math__FastMatrix4 r1) {
	r0->projectionMatrix = r1;
	return;
}

void kha_graphics4_ImageShaderPainter_initShaders() {
	kha__graphics4__PipelineState r4;
	kha__graphics4__PipelineCache r3;
	kha__graphics4__$ImageShaderPainter r2;
	kha__graphics4__VertexStructure r1;
	r2 = (kha__graphics4__$ImageShaderPainter)$g_a0efbdf;
	r1 = r2->structure;
	if( r1 ) goto label$b78fc65_2_6;
	r1 = kha_graphics4_Graphics2_createImageVertexStructure();
	r2 = (kha__graphics4__$ImageShaderPainter)$g_a0efbdf;
	r2->structure = r1;
	label$b78fc65_2_6:
	r2 = (kha__graphics4__$ImageShaderPainter)$g_a0efbdf;
	r3 = r2->standardImagePipeline;
	if( r3 ) goto label$b78fc65_2_18;
	r2 = (kha__graphics4__$ImageShaderPainter)$g_a0efbdf;
	r1 = r2->structure;
	r4 = kha_graphics4_Graphics2_createImagePipeline(r1);
	if( r4 == NULL ) hl_null_access();
	kha_graphics4_PipelineState_compile(r4);
	r3 = (kha__graphics4__PipelineCache)hl_alloc_obj(&$t_kha_graphics4_PipelineCache);
	kha_graphics4_PipelineCache_new(r3,r4);
	r2 = (kha__graphics4__$ImageShaderPainter)$g_a0efbdf;
	r2->standardImagePipeline = r3;
	label$b78fc65_2_18:
	return;
}

void kha_graphics4_ImageShaderPainter_initBuffers(kha__graphics4__ImageShaderPainter r0) {
	bool *r8;
	kha__graphics4__VertexBuffer r2;
	kha__graphics4__IndexBuffer r12;
	kha__graphics4__$ImageShaderPainter r3;
	kha__arrays__Float32ArrayPrivate r9;
	kha__arrays__Uint32ArrayPrivate r13;
	vdynamic *r10, *r11;
	int *r7;
	vbyte *r16;
	kha__graphics4__VertexStructure r5;
	int r4, r6, r14, r15, r17;
	r3 = (kha__graphics4__$ImageShaderPainter)$g_a0efbdf;
	r2 = r3->rectVertexBuffer;
	if( r2 ) goto label$b78fc65_3_110;
	r2 = (kha__graphics4__VertexBuffer)hl_alloc_obj(&$t_kha_graphics4_VertexBuffer);
	r4 = 6000;
	r3 = (kha__graphics4__$ImageShaderPainter)$g_a0efbdf;
	r5 = r3->structure;
	r6 = 1;
	r7 = NULL;
	r8 = NULL;
	kha_graphics4_VertexBuffer_new(r2,r4,r5,r6,r7,r8);
	r3 = (kha__graphics4__$ImageShaderPainter)$g_a0efbdf;
	r3->rectVertexBuffer = r2;
	r3 = (kha__graphics4__$ImageShaderPainter)$g_a0efbdf;
	r2 = r3->rectVertexBuffer;
	if( r2 == NULL ) hl_null_access();
	r10 = NULL;
	r11 = NULL;
	r9 = kha_graphics4_VertexBuffer_lock(r2,r10,r11);
	r3 = (kha__graphics4__$ImageShaderPainter)$g_a0efbdf;
	r3->rectVertices = r9;
	r12 = (kha__graphics4__IndexBuffer)hl_alloc_obj(&$t_kha_graphics4_IndexBuffer);
	r4 = 9000;
	r6 = 0;
	r8 = NULL;
	kha_graphics4_IndexBuffer_new(r12,r4,r6,r8);
	r3 = (kha__graphics4__$ImageShaderPainter)$g_a0efbdf;
	r3->indexBuffer = r12;
	r3 = (kha__graphics4__$ImageShaderPainter)$g_a0efbdf;
	r12 = r3->indexBuffer;
	if( r12 == NULL ) hl_null_access();
	r13 = kha_graphics4_IndexBuffer_lock(r12);
	r4 = 0;
	label$b78fc65_3_33:
	r14 = 1500;
	if( r4 >= r14 ) goto label$b78fc65_3_106;
	r6 = r4;
	++r4;
	r15 = 4;
	r14 = r6 * r15;
	if( r13 == NULL ) hl_null_access();
	r16 = r13->self;
	r17 = 3;
	r15 = r6 * r17;
	r17 = 2;
	r15 = r15 * r17;
	hl_kore_uint32array_set(r16,r15,r14);
	r15 = 4;
	r14 = r6 * r15;
	r15 = 1;
	r14 = r14 + r15;
	r16 = r13->self;
	r17 = 3;
	r15 = r6 * r17;
	r17 = 2;
	r15 = r15 * r17;
	r17 = 1;
	r15 = r15 + r17;
	hl_kore_uint32array_set(r16,r15,r14);
	r15 = 4;
	r14 = r6 * r15;
	r15 = 2;
	r14 = r14 + r15;
	r16 = r13->self;
	r17 = 3;
	r15 = r6 * r17;
	r17 = 2;
	r15 = r15 * r17;
	r17 = 2;
	r15 = r15 + r17;
	hl_kore_uint32array_set(r16,r15,r14);
	r15 = 4;
	r14 = r6 * r15;
	r16 = r13->self;
	r17 = 3;
	r15 = r6 * r17;
	r17 = 2;
	r15 = r15 * r17;
	r17 = 3;
	r15 = r15 + r17;
	hl_kore_uint32array_set(r16,r15,r14);
	r15 = 4;
	r14 = r6 * r15;
	r15 = 2;
	r14 = r14 + r15;
	r16 = r13->self;
	r17 = 3;
	r15 = r6 * r17;
	r17 = 2;
	r15 = r15 * r17;
	r17 = 4;
	r15 = r15 + r17;
	hl_kore_uint32array_set(r16,r15,r14);
	r15 = 4;
	r14 = r6 * r15;
	r15 = 3;
	r14 = r14 + r15;
	r16 = r13->self;
	r17 = 3;
	r15 = r6 * r17;
	r17 = 2;
	r15 = r15 * r17;
	r17 = 5;
	r15 = r15 + r17;
	hl_kore_uint32array_set(r16,r15,r14);
	goto label$b78fc65_3_33;
	label$b78fc65_3_106:
	r3 = (kha__graphics4__$ImageShaderPainter)$g_a0efbdf;
	r12 = r3->indexBuffer;
	if( r12 == NULL ) hl_null_access();
	kha_graphics4_IndexBuffer_unlock(r12);
	label$b78fc65_3_110:
	return;
}

void kha_graphics4_ImageShaderPainter_drawBuffer(kha__graphics4__ImageShaderPainter r0) {
	kha__Image r12;
	kha__graphics4__PipelineState r9;
	vvirtual *r7, *r11;
	kha__math__FastMatrix4 r17;
	bool r14;
	kha__graphics4__PipelineCache r10;
	kha__graphics4__VertexBuffer r2;
	kha__graphics4__IndexBuffer r8;
	kha__graphics4__$ImageShaderPainter r3;
	kha__arrays__Float32ArrayPrivate r20;
	int *r18, *r19;
	vdynamic *r6, *r21;
	int r4, r5, r13, r15, r16;
	r3 = (kha__graphics4__$ImageShaderPainter)$g_a0efbdf;
	r2 = r3->rectVertexBuffer;
	if( r2 == NULL ) hl_null_access();
	r3 = (kha__graphics4__$ImageShaderPainter)$g_a0efbdf;
	r4 = r3->bufferIndex;
	r5 = 4;
	r4 = r4 * r5;
	r6 = hl_alloc_dynamic(&$t_i32);
	r6->v.i = r4;
	kha_graphics4_VertexBuffer_unlock(r2,r6);
	r7 = r0->g;
	if( r7 == NULL ) hl_null_access();
	r3 = (kha__graphics4__$ImageShaderPainter)$g_a0efbdf;
	r2 = r3->rectVertexBuffer;
	if( hl_vfields(r7)[2] ) ((void (*)(vdynamic*,kha__graphics4__VertexBuffer))hl_vfields(r7)[2])(r7->value,r2); else {
		void *args[] = {r2};
		hl_dyn_call_obj(r7->value,&$t_fun_a561c62,-278953801/*setVertexBuffer*/,args,NULL);
	}
	r7 = r0->g;
	if( r7 == NULL ) hl_null_access();
	r3 = (kha__graphics4__$ImageShaderPainter)$g_a0efbdf;
	r8 = r3->indexBuffer;
	if( hl_vfields(r7)[11] ) ((void (*)(vdynamic*,kha__graphics4__IndexBuffer))hl_vfields(r7)[11])(r7->value,r8); else {
		void *args[] = {r8};
		hl_dyn_call_obj(r7->value,&$t_fun_46c6b6e,-43737183/*setIndexBuffer*/,args,NULL);
	}
	r7 = r0->g;
	if( r7 == NULL ) hl_null_access();
	r10 = r0->myPipeline;
	if( r10 == NULL ) hl_null_access();
	r9 = r10->pipeline;
	if( hl_vfields(r7)[7] ) ((void (*)(vdynamic*,kha__graphics4__PipelineState))hl_vfields(r7)[7])(r7->value,r9); else {
		void *args[] = {r9};
		hl_dyn_call_obj(r7->value,&$t_fun_c80ec77,467961459/*setPipeline*/,args,NULL);
	}
	r7 = r0->g;
	if( r7 == NULL ) hl_null_access();
	r10 = r0->myPipeline;
	if( r10 == NULL ) hl_null_access();
	r11 = r10->textureLocation;
	r3 = (kha__graphics4__$ImageShaderPainter)$g_a0efbdf;
	r12 = r3->lastTexture;
	if( hl_vfields(r7)[6] ) ((void (*)(vdynamic*,vvirtual*,kha__Image))hl_vfields(r7)[6])(r7->value,r11,r12); else {
		void *args[] = {r11,r12};
		hl_dyn_call_obj(r7->value,&$t_fun_04e2896,-239080103/*setTexture*/,args,NULL);
	}
	r7 = r0->g;
	if( r7 == NULL ) hl_null_access();
	r10 = r0->myPipeline;
	if( r10 == NULL ) hl_null_access();
	r11 = r10->textureLocation;
	r4 = 2;
	r5 = 2;
	r14 = r0->bilinear;
	if( !r14 ) goto label$b78fc65_4_44;
	r13 = 1;
	goto label$b78fc65_4_45;
	label$b78fc65_4_44:
	r13 = 0;
	label$b78fc65_4_45:
	r14 = r0->bilinear;
	if( !r14 ) goto label$b78fc65_4_49;
	r15 = 1;
	goto label$b78fc65_4_50;
	label$b78fc65_4_49:
	r15 = 0;
	label$b78fc65_4_50:
	r14 = r0->bilinearMipmaps;
	if( !r14 ) goto label$b78fc65_4_54;
	r16 = 2;
	goto label$b78fc65_4_55;
	label$b78fc65_4_54:
	r16 = 0;
	label$b78fc65_4_55:
	if( hl_vfields(r7)[3] ) ((void (*)(vdynamic*,vvirtual*,int,int,int,int,int))hl_vfields(r7)[3])(r7->value,r11,r4,r5,r13,r15,r16); else {
		void *args[] = {r11,&r4,&r5,&r13,&r15,&r16};
		hl_dyn_call_obj(r7->value,&$t_fun_4ad9aaa,357382632/*setTextureParameters*/,args,NULL);
	}
	r7 = r0->g;
	if( r7 == NULL ) hl_null_access();
	r10 = r0->myPipeline;
	if( r10 == NULL ) hl_null_access();
	r11 = r10->projectionLocation;
	r17 = r0->projectionMatrix;
	if( hl_vfields(r7)[9] ) ((void (*)(vdynamic*,vvirtual*,kha__math__FastMatrix4))hl_vfields(r7)[9])(r7->value,r11,r17); else {
		void *args[] = {r11,r17};
		hl_dyn_call_obj(r7->value,&$t_fun_896f717,460303235/*setMatrix*/,args,NULL);
	}
	r7 = r0->g;
	if( r7 == NULL ) hl_null_access();
	r4 = 0;
	r18 = &r4;
	r3 = (kha__graphics4__$ImageShaderPainter)$g_a0efbdf;
	r5 = r3->bufferIndex;
	r13 = 2;
	r5 = r5 * r13;
	r13 = 3;
	r5 = r5 * r13;
	r19 = &r5;
	if( hl_vfields(r7)[25] ) ((void (*)(vdynamic*,int*,int*))hl_vfields(r7)[25])(r7->value,r18,r19); else {
		void *args[] = {r18,r19};
		hl_dyn_call_obj(r7->value,&$t_fun_8305be0,-519327652/*drawIndexedVertices*/,args,NULL);
	}
	r7 = r0->g;
	if( r7 == NULL ) hl_null_access();
	r10 = r0->myPipeline;
	if( r10 == NULL ) hl_null_access();
	r11 = r10->textureLocation;
	r12 = NULL;
	if( hl_vfields(r7)[6] ) ((void (*)(vdynamic*,vvirtual*,kha__Image))hl_vfields(r7)[6])(r7->value,r11,r12); else {
		void *args[] = {r11,r12};
		hl_dyn_call_obj(r7->value,&$t_fun_04e2896,-239080103/*setTexture*/,args,NULL);
	}
	r13 = 0;
	r3 = (kha__graphics4__$ImageShaderPainter)$g_a0efbdf;
	r3->bufferIndex = r13;
	r3 = (kha__graphics4__$ImageShaderPainter)$g_a0efbdf;
	r2 = r3->rectVertexBuffer;
	if( r2 == NULL ) hl_null_access();
	r6 = NULL;
	r21 = NULL;
	r20 = kha_graphics4_VertexBuffer_lock(r2,r6,r21);
	r3 = (kha__graphics4__$ImageShaderPainter)$g_a0efbdf;
	r3->rectVertices = r20;
	return;
}

void kha_graphics4_ImageShaderPainter_end(kha__graphics4__ImageShaderPainter r0) {
	kha__Image r5;
	kha__graphics4__$ImageShaderPainter r3;
	int r2, r4;
	r3 = (kha__graphics4__$ImageShaderPainter)$g_a0efbdf;
	r2 = r3->bufferIndex;
	r4 = 0;
	if( r4 >= r2 ) goto label$b78fc65_5_5;
	kha_graphics4_ImageShaderPainter_drawBuffer(r0);
	label$b78fc65_5_5:
	r5 = NULL;
	r3 = (kha__graphics4__$ImageShaderPainter)$g_a0efbdf;
	r3->lastTexture = r5;
	return;
}

void kha_graphics4_ImageShaderPainter_new(kha__graphics4__ImageShaderPainter r0,vvirtual* r1) {
	bool r3;
	kha__graphics4__PipelineCache r2;
	kha__graphics4__$ImageShaderPainter r5;
	int r4;
	r2 = NULL;
	r0->myPipeline = r2;
	r3 = false;
	r0->bilinearMipmaps = r3;
	r3 = false;
	r0->bilinear = r3;
	r0->g = r1;
	r4 = 0;
	r5 = (kha__graphics4__$ImageShaderPainter)$g_a0efbdf;
	r5->bufferIndex = r4;
	kha_graphics4_ImageShaderPainter_initShaders();
	r5 = (kha__graphics4__$ImageShaderPainter)$g_a0efbdf;
	r2 = r5->standardImagePipeline;
	r0->myPipeline = r2;
	kha_graphics4_ImageShaderPainter_initBuffers(r0);
	return;
}

