// Generated by HLC 4.0.0 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <_std/StringTools.h>
#include <hl/natives.h>
#include <hl/types/ArrayObj.h>
hl__types__ArrayObj String_split(String,String);
String hl_types_ArrayObj_join(hl__types__ArrayObj,String);

bool StringTools_startsWith(String r0,String r1) {
	bool r4;
	vbyte *r5, *r6;
	int r2, r3, r7, r8;
	if( r0 == NULL ) hl_null_access();
	r2 = r0->length;
	if( r1 == NULL ) hl_null_access();
	r3 = r1->length;
	if( r2 < r3 ) goto label$de37252_1_19;
	r5 = r0->bytes;
	r2 = 0;
	r6 = r1->bytes;
	r3 = 0;
	r7 = r1->length;
	r8 = 1;
	r7 = r7 << r8;
	r2 = hl_bytes_compare(r5,r2,r6,r3,r7);
	r3 = 0;
	if( r2 == r3 ) goto label$de37252_1_17;
	r4 = false;
	goto label$de37252_1_18;
	label$de37252_1_17:
	r4 = true;
	label$de37252_1_18:
	return r4;
	label$de37252_1_19:
	r4 = false;
	return r4;
}

bool StringTools_endsWith(String r0,String r1) {
	bool r6;
	vbyte *r7, *r8;
	int r2, r3, r4, r5, r9, r10;
	if( r1 == NULL ) hl_null_access();
	r2 = r1->length;
	if( r0 == NULL ) hl_null_access();
	r3 = r0->length;
	if( r3 < r2 ) goto label$de37252_2_20;
	r7 = r0->bytes;
	r4 = r3 - r2;
	r5 = 1;
	r4 = r4 << r5;
	r8 = r1->bytes;
	r5 = 0;
	r10 = 1;
	r9 = r2 << r10;
	r4 = hl_bytes_compare(r7,r4,r8,r5,r9);
	r5 = 0;
	if( r4 == r5 ) goto label$de37252_2_18;
	r6 = false;
	goto label$de37252_2_19;
	label$de37252_2_18:
	r6 = true;
	label$de37252_2_19:
	return r6;
	label$de37252_2_20:
	r6 = false;
	return r6;
}

String StringTools_replace(String r0,String r1,String r2) {
	String r3;
	hl__types__ArrayObj r4;
	if( r0 == NULL ) hl_null_access();
	r4 = String_split(r0,r1);
	if( r4 == NULL ) hl_null_access();
	r3 = hl_types_ArrayObj_join(r4,r2);
	return r3;
}

