// Generated by HLC 4.0.0 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <_std/Type.h>
#include <hl/natives.h>
extern hl_bytes_map* $g___types__;
extern hl_type $t_hl_Class;
extern hl_type $t_dyn;
extern hl_type $t_String;
void Type_register(vbyte*,hl__BaseType);
extern hl_type $t_hl_Enum;
extern hl_type $t_hl_types_ArrayObj;
void hl_types_ArrayObj_new(hl__types__ArrayObj);
extern hl_type $t_i32;
int hl_types_ArrayObj_push(hl__types__ArrayObj,vdynamic*);
extern hl_type $t_hl_BaseType;
extern hl__Class $g__hl_Class;
bool Std_is(vdynamic*,vdynamic*);
#include <hl/Enum.h>
extern hl__$Enum $g__hl_Enum;
extern hl_type $t_hl_types_ArrayAccess;
extern hl_type $t_hl_types_ArrayDyn;
void hl_types_ArrayDyn_new(hl__types__ArrayDyn);
hl__types__ArrayDyn hl_types_ArrayDyn_copy(hl__types__ArrayDyn);
void hl_types_ArrayDyn_unshift(hl__types__ArrayDyn,vdynamic*);
vdynamic* Reflect_callMethod(vdynamic*,vdynamic*,hl__types__ArrayDyn);
extern hl_type $t_nul_i32;
extern String $s_Unknown_enum_constructor_;
String String___add__(String,String);
extern String $s_5058f1a;
vdynamic* Type_createEnumIndex(hl__BaseType,int,hl__types__ArrayDyn);
#include <hl/types/ArrayBase.h>
extern String $s_Invalid_enum_index_;
String String___alloc__(vbyte*,int);
int hl_types_ArrayDyn_get_length(hl__types__ArrayDyn);
extern String $s_Constructor_;
extern String $s__takes_parameters;
extern hl_type $t_hl_types_ArrayBase;
extern String $s__does_not_takes_;
extern String $s__parameters;
hl__types__ArrayObj hl_types_ArrayObj_copy(hl__types__ArrayObj);

void Type_init() {
	hl_bytes_map *r1;
	r1 = hl_hballoc();
	$g___types__ = (hl_bytes_map*)r1;
	return;
}

hl__Class Type_initClass(hl_type* r0,hl_type* r1,vbyte* r2) {
	String r7;
	hl__Class r4;
	bool r6;
	vdynamic *r3;
	int r8;
	r3 = hl_alloc_obj(r0);
	r4 = (hl__Class)hl_dyn_castp(&r3,&$t_dyn,&$t_hl_Class);
	r6 = hl_type_set_global(r1,((vdynamic*)r4));
	if( r4 == NULL ) hl_null_access();
	r4->__type__ = r1;
	r7 = (String)hl_alloc_obj(&$t_String);
	r7->bytes = r2;
	r8 = 0;
	r8 = hl_ucs2length(r2,r8);
	r7->length = r8;
	r4->__name__ = r7;
	Type_register(r2,((hl__BaseType)r4));
	return r4;
}

hl__Enum Type_initEnum(hl_type* r0,hl_type* r1) {
	String r8;
	hl__types__ArrayObj r12;
	bool r16;
	hl_bytes_map *r10, *r11;
	hl__Enum r3;
	vdynamic *r2;
	int r9, r13, r14, r15;
	vbyte *r6, *r7;
	varray *r5;
	r2 = hl_alloc_obj(r0);
	r3 = (hl__Enum)hl_dyn_castp(&r2,&$t_dyn,&$t_hl_Enum);
	if( r3 == NULL ) hl_null_access();
	r3->__type__ = r1;
	r5 = hl_type_enum_values(r1);
	r3->__evalues__ = r5;
	r6 = hl_type_name(r1);
	if( r6 ) goto label$9fea9d9_3_10;
	r8 = NULL;
	goto label$9fea9d9_3_15;
	label$9fea9d9_3_10:
	r8 = (String)hl_alloc_obj(&$t_String);
	r8->bytes = r6;
	r9 = 0;
	r9 = hl_ucs2length(r6,r9);
	r8->length = r9;
	label$9fea9d9_3_15:
	r3->__ename__ = r8;
	r10 = hl_hballoc();
	r3->__emap__ = r10;
	r12 = (hl__types__ArrayObj)hl_alloc_obj(&$t_hl_types_ArrayObj);
	hl_types_ArrayObj_new(r12);
	r3->__constructs__ = r12;
	r5 = hl_type_enum_fields(r1);
	r9 = 0;
	r13 = r5->size;
	label$9fea9d9_3_24:
	if( r9 >= r13 ) goto label$9fea9d9_3_42;
	r14 = r9;
	++r9;
	r7 = ((vbyte**)(r5 + 1))[r14];
	if( r3 == NULL ) hl_null_access();
	r11 = r3->__emap__;
	r2 = hl_alloc_dynamic(&$t_i32);
	r2->v.i = r14;
	hl_hbset(r11,r7,r2);
	r12 = r3->__constructs__;
	r8 = (String)hl_alloc_obj(&$t_String);
	r8->bytes = r7;
	r15 = 0;
	r15 = hl_ucs2length(r7,r15);
	r8->length = r15;
	if( r12 == NULL ) hl_null_access();
	r15 = hl_types_ArrayObj_push(r12,((vdynamic*)r8));
	goto label$9fea9d9_3_24;
	label$9fea9d9_3_42:
	if( r3 == NULL ) hl_null_access();
	r8 = r3->__ename__;
	if( r8 == NULL ) hl_null_access();
	r7 = r8->bytes;
	Type_register(r7,((hl__BaseType)r3));
	r16 = hl_type_set_global(r1,((vdynamic*)r3));
	return r3;
}

void Type_register(vbyte* r0,hl__BaseType r1) {
	hl_bytes_map *r3;
	r3 = (hl_bytes_map*)$g___types__;
	hl_hbset(r3,r0,((vdynamic*)r1));
	return;
}

hl__Class Type_getClass(vdynamic* r0) {
	hl__Class r6;
	hl_type *r1, *r4;
	vdynamic *r2;
	int r3, r5;
	r1 = r0 ? ((vdynamic*)r0)->t : &hlt_void;
	r3 = r1->kind;
	r5 = 15;
	if( r3 != r5 ) goto label$9fea9d9_5_7;
	r2 = hl_get_virtual_value(r0);
	r4 = r2 ? ((vdynamic*)r2)->t : &hlt_void;
	r1 = r4;
	label$9fea9d9_5_7:
	r3 = r1->kind;
	r5 = 11;
	if( r3 != r5 ) goto label$9fea9d9_5_13;
	r2 = hl_type_get_global(r1);
	r6 = (hl__Class)hl_dyn_castp(&r2,&$t_dyn,&$t_hl_Class);
	return r6;
	label$9fea9d9_5_13:
	r6 = NULL;
	return r6;
}

hl__Class Type_resolveClass(String r0) {
	hl__BaseType r4;
	hl__Class r6;
	bool r5;
	hl_bytes_map *r2;
	vdynamic *r1;
	vbyte *r3;
	r2 = (hl_bytes_map*)$g___types__;
	if( r0 == NULL ) hl_null_access();
	r3 = r0->bytes;
	r1 = hl_hbget(r2,r3);
	r4 = (hl__BaseType)hl_dyn_castp(&r1,&$t_dyn,&$t_hl_BaseType);
	if( !r4 ) goto label$9fea9d9_6_9;
	r6 = (hl__Class)$g__hl_Class;
	r5 = Std_is(((vdynamic*)r4),((vdynamic*)r6));
	if( r5 ) goto label$9fea9d9_6_11;
	label$9fea9d9_6_9:
	r6 = NULL;
	return r6;
	label$9fea9d9_6_11:
	r6 = (hl__Class)hl_dyn_castp(&r4,&$t_hl_BaseType,&$t_hl_Class);
	return r6;
}

hl__BaseType Type_resolveEnum(String r0) {
	hl__BaseType r4, r5;
	bool r6;
	hl_bytes_map *r2;
	hl__$Enum r7;
	vdynamic *r1;
	vbyte *r3;
	r2 = (hl_bytes_map*)$g___types__;
	if( r0 == NULL ) hl_null_access();
	r3 = r0->bytes;
	r1 = hl_hbget(r2,r3);
	r4 = (hl__BaseType)hl_dyn_castp(&r1,&$t_dyn,&$t_hl_BaseType);
	if( !r4 ) goto label$9fea9d9_7_9;
	r7 = (hl__$Enum)$g__hl_Enum;
	r6 = Std_is(((vdynamic*)r4),((vdynamic*)r7));
	if( r6 ) goto label$9fea9d9_7_11;
	label$9fea9d9_7_9:
	r5 = NULL;
	return r5;
	label$9fea9d9_7_11:
	return r4;
}

vdynamic* Type_createInstance(hl__Class r0,hl__types__ArrayDyn r1) {
	hl_type *r3, *r4;
	hl__types__ArrayDyn r5;
	vdynamic *r6, *r7, *r8;
	if( r0 == NULL ) hl_null_access();
	r3 = r0->__type__;
	r4 = &$t_hl_types_ArrayAccess;
	if( hl_same_type(r3,r4) != 0 ) {} else goto label$9fea9d9_8_7;
	r5 = (hl__types__ArrayDyn)hl_alloc_obj(&$t_hl_types_ArrayDyn);
	hl_types_ArrayDyn_new(r5);
	return ((vdynamic*)r5);
	label$9fea9d9_8_7:
	r6 = hl_alloc_obj(r3);
	r7 = r0->__constructor__;
	if( !r7 ) goto label$9fea9d9_8_18;
	r7 = r0->__constructor__;
	r7 = hl_no_closure(r7);
	if( r1 == NULL ) hl_null_access();
	r5 = hl_types_ArrayDyn_copy(r1);
	if( r5 == NULL ) hl_null_access();
	hl_types_ArrayDyn_unshift(r5,r6);
	r8 = NULL;
	r8 = Reflect_callMethod(r8,r7,r5);
	label$9fea9d9_8_18:
	return r6;
}

vdynamic* Type_createEmptyInstance(hl__Class r0) {
	hl_type *r2;
	vdynamic *r1;
	if( r0 == NULL ) hl_null_access();
	r2 = r0->__type__;
	r1 = hl_alloc_obj(r2);
	return r1;
}

vdynamic* Type_createEnum(hl__BaseType r0,String r1,hl__types__ArrayDyn r2) {
	String r7, r9;
	hl_bytes_map *r5;
	hl__Enum r3;
	vdynamic *r4, *r8;
	int r10;
	vbyte *r6;
	r3 = (hl__Enum)hl_dyn_castp(&r0,&$t_hl_BaseType,&$t_hl_Enum);
	if( r3 == NULL ) hl_null_access();
	r5 = r3->__emap__;
	if( r1 == NULL ) hl_null_access();
	r6 = r1->bytes;
	r4 = hl_hbget(r5,r6);
	r8 = (vdynamic*)hl_dyn_castp(&r4,&$t_dyn,&$t_nul_i32);
	if( r8 ) goto label$9fea9d9_10_15;
	r7 = (String)$s_Unknown_enum_constructor_;
	r9 = r3->__ename__;
	r7 = String___add__(r7,r9);
	r9 = (String)$s_5058f1a;
	r7 = String___add__(r7,r9);
	r7 = String___add__(r7,r1);
	hl_throw((vdynamic*)r7);
	label$9fea9d9_10_15:
	r10 = r8 ? r8->v.i : 0;
	r4 = Type_createEnumIndex(r0,r10,r2);
	return r4;
}

vdynamic* Type_createEnumIndex(hl__BaseType r0,int r1,hl__types__ArrayDyn r2) {
	String r7, r8;
	hl__types__ArrayObj r6;
	hl_type *r18;
	bool r16;
	hl__types__ArrayBase r17;
	hl__Enum r3;
	hl__types__ArrayDyn r12;
	vdynamic *r11, *r15;
	int *r9;
	varray *r13, *r14;
	vbyte *r10;
	int r4, r5, r19, r20;
	r3 = (hl__Enum)hl_dyn_castp(&r0,&$t_hl_BaseType,&$t_hl_Enum);
	r5 = 0;
	if( r1 < r5 ) goto label$9fea9d9_11_8;
	if( r3 == NULL ) hl_null_access();
	r6 = r3->__constructs__;
	if( r6 == NULL ) hl_null_access();
	r5 = r6->length;
	if( r1 < r5 ) goto label$9fea9d9_11_20;
	label$9fea9d9_11_8:
	r7 = (String)$s_Invalid_enum_index_;
	if( r3 == NULL ) hl_null_access();
	r8 = r3->__ename__;
	r7 = String___add__(r7,r8);
	r8 = (String)$s_5058f1a;
	r7 = String___add__(r7,r8);
	r4 = r1;
	r9 = &r4;
	r10 = hl_itos(r4,r9);
	r8 = String___alloc__(r10,r4);
	r7 = String___add__(r7,r8);
	hl_throw((vdynamic*)r7);
	label$9fea9d9_11_20:
	if( !r2 ) goto label$9fea9d9_11_25;
	if( r2 == NULL ) hl_null_access();
	r4 = hl_types_ArrayDyn_get_length(r2);
	r5 = 0;
	if( r4 != r5 ) goto label$9fea9d9_11_52;
	label$9fea9d9_11_25:
	r13 = r3->__evalues__;
	r5 = r13->size;
	if( r1 < r5 ) goto label$9fea9d9_11_30;
	r15 = NULL;
	goto label$9fea9d9_11_32;
	label$9fea9d9_11_30:
	r14 = r3->__evalues__;
	r15 = ((vdynamic**)(r14 + 1))[r1];
	label$9fea9d9_11_32:
	if( r15 ) goto label$9fea9d9_11_51;
	r7 = (String)$s_Constructor_;
	r8 = r3->__ename__;
	r7 = String___add__(r7,r8);
	r8 = (String)$s_5058f1a;
	r7 = String___add__(r7,r8);
	r6 = r3->__constructs__;
	if( r6 == NULL ) hl_null_access();
	r5 = r6->length;
	if( ((unsigned)r1) < ((unsigned)r5) ) goto label$9fea9d9_11_44;
	r8 = NULL;
	goto label$9fea9d9_11_47;
	label$9fea9d9_11_44:
	r14 = r6->array;
	r15 = ((vdynamic**)(r14 + 1))[r1];
	r8 = (String)r15;
	label$9fea9d9_11_47:
	r7 = String___add__(r7,r8);
	r8 = (String)$s__takes_parameters;
	r7 = String___add__(r7,r8);
	hl_throw((vdynamic*)r7);
	label$9fea9d9_11_51:
	return r15;
	label$9fea9d9_11_52:
	r12 = r2;
	r17 = r2->array;
	if( r17 == NULL ) hl_null_access();
	r16 = ((bool (*)(hl__types__ArrayBase))r17->$type->vobj_proto[16])(r17);
	if( r16 ) goto label$9fea9d9_11_78;
	r17 = r2->array;
	if( r17 == NULL ) hl_null_access();
	r4 = r17->length;
	r18 = &$t_dyn;
	r13 = hl_alloc_array(r18,r4);
	r14 = r13;
	r5 = 0;
	r17 = r2->array;
	if( r17 == NULL ) hl_null_access();
	r19 = r17->length;
	label$9fea9d9_11_67:
	if( r5 >= r19 ) goto label$9fea9d9_11_77;
	r20 = r5;
	++r5;
	if( r12 == NULL ) hl_null_access();
	r17 = r12->array;
	if( r17 == NULL ) hl_null_access();
	r11 = ((vdynamic* (*)(hl__types__ArrayBase,int))r17->$type->vobj_proto[0])(r17,r20);
	((vdynamic**)(r14 + 1))[r20] = r11;
	goto label$9fea9d9_11_67;
	label$9fea9d9_11_77:
	goto label$9fea9d9_11_83;
	label$9fea9d9_11_78:
	r17 = r2->array;
	r6 = (hl__types__ArrayObj)hl_dyn_castp(&r17,&$t_hl_types_ArrayBase,&$t_hl_types_ArrayObj);
	if( r6 == NULL ) hl_null_access();
	r13 = r6->array;
	r14 = r13;
	label$9fea9d9_11_83:
	if( r3 == NULL ) hl_null_access();
	r18 = r3->__type__;
	if( r12 == NULL ) hl_null_access();
	r17 = r12->array;
	if( r17 == NULL ) hl_null_access();
	r5 = r17->length;
	r11 = hl_alloc_enum_dyn(r18,r1,r14,r5);
	if( r11 ) goto label$9fea9d9_11_116;
	r7 = (String)$s_Constructor_;
	r8 = r3->__ename__;
	r7 = String___add__(r7,r8);
	r8 = (String)$s_5058f1a;
	r7 = String___add__(r7,r8);
	r6 = r3->__constructs__;
	if( r6 == NULL ) hl_null_access();
	r5 = r6->length;
	if( ((unsigned)r1) < ((unsigned)r5) ) goto label$9fea9d9_11_102;
	r8 = NULL;
	goto label$9fea9d9_11_105;
	label$9fea9d9_11_102:
	r13 = r6->array;
	r15 = ((vdynamic**)(r13 + 1))[r1];
	r8 = (String)r15;
	label$9fea9d9_11_105:
	r7 = String___add__(r7,r8);
	r8 = (String)$s__does_not_takes_;
	r7 = String___add__(r7,r8);
	r4 = r14->size;
	r9 = &r4;
	r10 = hl_itos(r4,r9);
	r8 = String___alloc__(r10,r4);
	r7 = String___add__(r7,r8);
	r8 = (String)$s__parameters;
	r7 = String___add__(r7,r8);
	hl_throw((vdynamic*)r7);
	label$9fea9d9_11_116:
	return r11;
}

hl__types__ArrayObj Type_getEnumConstructs(hl__BaseType r0) {
	hl__types__ArrayObj r2;
	hl__Enum r1;
	r1 = (hl__Enum)hl_dyn_castp(&r0,&$t_hl_BaseType,&$t_hl_Enum);
	if( r1 == NULL ) hl_null_access();
	r2 = r1->__constructs__;
	if( r2 == NULL ) hl_null_access();
	r2 = hl_types_ArrayObj_copy(r2);
	return r2;
}

