// Auto-generated
let project = new Project('gamepad-tester');

project.addSources('Sources');
project.addLibrary("C:/armorySDK1910winEdits/armory");
project.addLibrary("C:/armorySDK1910winEdits/iron");
project.addParameter('armory.trait.internal.CanvasScript');
project.addParameter("--macro keep('armory.trait.internal.CanvasScript')");
project.addParameter('arm.GamepadTester');
project.addParameter("--macro keep('arm.GamepadTester')");
project.addShaders("build_gamepad-tester/compiled/Shaders/*.glsl", { noembed: false});
project.addShaders("build_gamepad-tester/compiled/Hlsl/*.glsl", { noprocessing: true, noembed: false });
project.addAssets("build_gamepad-tester/compiled/Assets/**", { notinlist: true });
project.addAssets("build_gamepad-tester/compiled/Shaders/*.arm", { notinlist: true });
project.addAssets("Bundled/canvas/gamepadTester.files", { notinlist: true });
project.addAssets("Bundled/canvas/gamepadTester.json", { notinlist: true });
project.addAssets("Bundled/gamepad-a.png", { notinlist: true });
project.addAssets("Bundled/gamepad-b.png", { notinlist: true });
project.addAssets("Bundled/gamepad-down.png", { notinlist: true });
project.addAssets("Bundled/gamepad-home.png", { notinlist: true });
project.addAssets("Bundled/gamepad-l1-lb.png", { notinlist: true });
project.addAssets("Bundled/gamepad-l2-lt.png", { notinlist: true });
project.addAssets("Bundled/gamepad-l3.png", { notinlist: true });
project.addAssets("Bundled/gamepad-l3stick.png", { notinlist: true });
project.addAssets("Bundled/gamepad-left.png", { notinlist: true });
project.addAssets("Bundled/gamepad-option.png", { notinlist: true });
project.addAssets("Bundled/gamepad-r1-rb.png", { notinlist: true });
project.addAssets("Bundled/gamepad-r2-rt.png", { notinlist: true });
project.addAssets("Bundled/gamepad-r3.png", { notinlist: true });
project.addAssets("Bundled/gamepad-r3stick.png", { notinlist: true });
project.addAssets("Bundled/gamepad-right.png", { notinlist: true });
project.addAssets("Bundled/gamepad-share.png", { notinlist: true });
project.addAssets("Bundled/gamepad-tester.png", { notinlist: true });
project.addAssets("Bundled/gamepad-up.png", { notinlist: true });
project.addAssets("Bundled/gamepad-x.png", { notinlist: true });
project.addAssets("Bundled/gamepad-y.png", { notinlist: true });
project.addAssets("C:/armorySDK1910winEdits/armory/Assets/brdf.png", { notinlist: true });
project.addAssets("C:/armorySDK1910winEdits/armory/Assets/smaa_area.png", { notinlist: true });
project.addAssets("C:/armorySDK1910winEdits/armory/Assets/smaa_search.png", { notinlist: true });
project.addAssets("epad-a.png", { notinlist: true });
project.addAssets("epad-b.png", { notinlist: true });
project.addAssets("epad-down.png", { notinlist: true });
project.addAssets("epad-l1-lb.png", { notinlist: true });
project.addAssets("epad-l2-lt.png", { notinlist: true });
project.addAssets("epad-l3.png", { notinlist: true });
project.addAssets("epad-l3stick.png", { notinlist: true });
project.addAssets("epad-left.png", { notinlist: true });
project.addAssets("epad-option.png", { notinlist: true });
project.addAssets("epad-r1-rb.png", { notinlist: true });
project.addAssets("epad-r2-rt.png", { notinlist: true });
project.addAssets("epad-r3.png", { notinlist: true });
project.addAssets("epad-r3stick.png", { notinlist: true });
project.addAssets("epad-right.png", { notinlist: true });
project.addAssets("epad-share.png", { notinlist: true });
project.addAssets("epad-tester.png", { notinlist: true });
project.addAssets("epad-up.png", { notinlist: true });
project.addAssets("epad-x.png", { notinlist: true });
project.addAssets("epad-y.png", { notinlist: true });
project.addLibrary("C:/armorySDK1910winEdits/lib/zui");
project.addAssets("C:/armorySDK1910winEdits/armory/Assets/font_default.ttf", { notinlist: false });
project.addDefine('arm_deferred');
project.addDefine('arm_csm');
project.addDefine('rp_hdr');
project.addDefine('rp_renderer=Deferred');
project.addDefine('rp_shadowmap');
project.addDefine('rp_shadowmap_cascade=1024');
project.addDefine('rp_shadowmap_cube=512');
project.addDefine('rp_background=World');
project.addDefine('rp_render_to_texture');
project.addDefine('rp_compositornodes');
project.addDefine('rp_antialiasing=SMAA');
project.addDefine('rp_supersampling=1');
project.addDefine('rp_ssgi=SSAO');
project.addDefine('rp_resolution_filter=Linear');
project.addDefine('arm_audio');
project.addDefine('arm_noembed');
project.addDefine('arm_soundcompress');
project.addDefine('arm_ui');
project.addDefine('arm_skin');
project.addDefine('arm_particles');


resolve(project);
