// Generated by HLC 4.0.0 (HL v4)
#ifndef INC_iron__data__Geometry
#define INC_iron__data__Geometry
typedef struct _iron__data__$Geometry *iron__data__$Geometry;
typedef struct _iron__data__Geometry *iron__data__Geometry;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <kha/graphics4/VertexStructure.h>
#include <kha/arrays/Int16ArrayPrivate.h>
#include <kha/graphics4/VertexBuffer.h>
#include <haxe/ds/StringMap.h>
#include <hl/types/ArrayObj.h>
#include <hl/types/ArrayBytes_Int.h>
#include <iron/data/MeshData.h>
#include <kha/arrays/Float32ArrayPrivate.h>


struct _iron__data__$Geometry {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
	vclosure* getVertexStructure;
	vclosure* buildVertices;
};
struct _iron__data__Geometry {
	hl_type *$type;
	kha__graphics4__VertexBuffer vertexBuffer;
	haxe__ds__StringMap vertexBufferMap;
	hl__types__ArrayObj indexBuffers;
	int start;
	int count;
	String name;
	bool ready;
	kha__arrays__Int16ArrayPrivate vertices;
	hl__types__ArrayObj indices;
	int numTris;
	hl__types__ArrayBytes_Int materialIndices;
	kha__graphics4__VertexStructure _struct;
	int structLength;
	String structStr;
	int usage;
	kha__graphics4__VertexBuffer instancedVB;
	bool instanced;
	int instanceCount;
	kha__arrays__Int16ArrayPrivate positions;
	kha__arrays__Int16ArrayPrivate normals;
	kha__arrays__Int16ArrayPrivate uvs;
	kha__arrays__Int16ArrayPrivate uvs1;
	kha__arrays__Int16ArrayPrivate cols;
	kha__arrays__Int16ArrayPrivate tangents;
	kha__arrays__Int16ArrayPrivate bones;
	kha__arrays__Int16ArrayPrivate weights;
	iron__data__MeshData data;
	kha__arrays__Int16ArrayPrivate skinBoneCounts;
	kha__arrays__Int16ArrayPrivate skinBoneIndices;
	kha__arrays__Int16ArrayPrivate skinBoneWeights;
	hl__types__ArrayObj skeletonTransformsI;
	hl__types__ArrayObj skeletonBoneRefs;
	kha__arrays__Float32ArrayPrivate skeletonBoneLens;
	haxe__ds__StringMap actions;
	haxe__ds__StringMap mats;
};
#endif

