// Generated by HLC 4.0.0 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <iron/data/Geometry.h>
extern hl_type $t_kha_graphics4_VertexStructure;
void kha_graphics4_VertexStructure_new(kha__graphics4__VertexStructure);
extern String $s_pos;
void kha_graphics4_VertexStructure_add(kha__graphics4__VertexStructure,String,int);
extern String $s_nor;
extern String $s_tex;
extern String $s_tex1;
extern String $s_col;
extern String $s_tang;
extern String $s_bone;
extern String $s_weight;
extern String $s_ipos;
extern String $s_irot;
extern String $s_iscl;
int kha_graphics4_VertexStructure_byteSize(kha__graphics4__VertexStructure);
extern hl_type $t_kha_graphics4_VertexBuffer;
void kha_graphics4_VertexBuffer_new(kha__graphics4__VertexBuffer,int,kha__graphics4__VertexStructure,int,int*,bool*);
kha__arrays__Float32ArrayPrivate kha_graphics4_VertexBuffer_lock(kha__graphics4__VertexBuffer,vdynamic*,vdynamic*);
#include <hl/natives.h>
void kha_graphics4_VertexBuffer_unlock(kha__graphics4__VertexBuffer,vdynamic*);
#include <iron/data/TVertexElement.h>
int String___compare(String,vdynamic*);
#include <hl/types/ArrayDyn.h>
#include <haxe/Log.h>
extern String $s_;
String String___add__(String,String);
vdynamic* haxe_ds_StringMap_get(haxe__ds__StringMap,String);
kha__arrays__Int16ArrayPrivate kha_graphics4_VertexBuffer_lockInt16(kha__graphics4__VertexBuffer,vdynamic*,vdynamic*);
void haxe_ds_StringMap_set(haxe__ds__StringMap,String,vdynamic*);
extern haxe__$Log $g__haxe_Log;
extern String $s_Armory_Warning_Geometry_;
extern String $s__is_missing_UV_map;
extern hl_type $t_vrt_329ffa8;
extern String $s_Sources_iron_data_Geometry_hx;
extern hl_type $t_String;
extern hl_type $t_i32;
extern String $s_iron_data_Geometry;
extern String $s_get;
extern hl_type $t_vrt_eaa6a3b;
extern String $s__is_missing_vertex_colors;
#include <kha/arrays/Uint32ArrayPrivate.h>
#include <kha/graphics4/IndexBuffer.h>
#include <iron/data/TMeshData.h>
extern hl_type $t_kha_graphics4_IndexBuffer;
hl__types__ArrayObj hl_types_ArrayObj_alloc(varray*);
void kha_graphics4_IndexBuffer_new(kha__graphics4__IndexBuffer,int,int,bool*);
kha__arrays__Uint32ArrayPrivate kha_graphics4_IndexBuffer_lock(kha__graphics4__IndexBuffer);
void kha_graphics4_IndexBuffer_unlock(kha__graphics4__IndexBuffer);
int hl_types_ArrayObj_push(hl__types__ArrayObj,vdynamic*);
#include <iron/data/Armature.h>
extern hl_type $t_vrt_7235b40;
extern hl_type $t_hl_types_ArrayObj;
void iron_data_Geometry_addAction(iron__data__Geometry,hl__types__ArrayObj,String);
#include <iron/data/TObj.h>
#include <iron/data/TTransform.h>
#include <iron/math/Mat4.h>
extern hl_type $t_haxe_ds_StringMap;
void haxe_ds_StringMap_new(haxe__ds__StringMap);
extern hl_type $t_dyn;
extern hl_type $t_iron_data_TObj;
extern hl_type $t_iron_math_Mat4;
void iron_math_Mat4_new(iron__math__Mat4,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float);
#include <kha/graphics4/VertexElement.h>

kha__graphics4__VertexStructure iron_data_Geometry_getVertexStructure(bool* r0,bool* r1,bool* r2,bool* r3,bool* r4,bool* r5,bool* r6,bool* r7) {
	String r18;
	bool r8, r9, r10, r11, r12, r13, r14, r15;
	int r19;
	kha__graphics4__VertexStructure r16;
	if( r0 ) goto label$b7ac406_1_3;
	r8 = false;
	goto label$b7ac406_1_4;
	label$b7ac406_1_3:
	r8 = *r0;
	label$b7ac406_1_4:
	if( r1 ) goto label$b7ac406_1_7;
	r9 = false;
	goto label$b7ac406_1_8;
	label$b7ac406_1_7:
	r9 = *r1;
	label$b7ac406_1_8:
	if( r2 ) goto label$b7ac406_1_11;
	r10 = false;
	goto label$b7ac406_1_12;
	label$b7ac406_1_11:
	r10 = *r2;
	label$b7ac406_1_12:
	if( r3 ) goto label$b7ac406_1_15;
	r11 = false;
	goto label$b7ac406_1_16;
	label$b7ac406_1_15:
	r11 = *r3;
	label$b7ac406_1_16:
	if( r4 ) goto label$b7ac406_1_19;
	r12 = false;
	goto label$b7ac406_1_20;
	label$b7ac406_1_19:
	r12 = *r4;
	label$b7ac406_1_20:
	if( r5 ) goto label$b7ac406_1_23;
	r13 = false;
	goto label$b7ac406_1_24;
	label$b7ac406_1_23:
	r13 = *r5;
	label$b7ac406_1_24:
	if( r6 ) goto label$b7ac406_1_27;
	r14 = false;
	goto label$b7ac406_1_28;
	label$b7ac406_1_27:
	r14 = *r6;
	label$b7ac406_1_28:
	if( r7 ) goto label$b7ac406_1_31;
	r15 = false;
	goto label$b7ac406_1_32;
	label$b7ac406_1_31:
	r15 = *r7;
	label$b7ac406_1_32:
	r16 = (kha__graphics4__VertexStructure)hl_alloc_obj(&$t_kha_graphics4_VertexStructure);
	kha_graphics4_VertexStructure_new(r16);
	if( !r8 ) goto label$b7ac406_1_38;
	r18 = (String)$s_pos;
	r19 = 6;
	kha_graphics4_VertexStructure_add(r16,r18,r19);
	label$b7ac406_1_38:
	if( !r9 ) goto label$b7ac406_1_42;
	r18 = (String)$s_nor;
	r19 = 5;
	kha_graphics4_VertexStructure_add(r16,r18,r19);
	label$b7ac406_1_42:
	if( !r10 ) goto label$b7ac406_1_46;
	r18 = (String)$s_tex;
	r19 = 5;
	kha_graphics4_VertexStructure_add(r16,r18,r19);
	label$b7ac406_1_46:
	if( !r11 ) goto label$b7ac406_1_50;
	r18 = (String)$s_tex1;
	r19 = 5;
	kha_graphics4_VertexStructure_add(r16,r18,r19);
	label$b7ac406_1_50:
	if( !r12 ) goto label$b7ac406_1_54;
	r18 = (String)$s_col;
	r19 = 6;
	kha_graphics4_VertexStructure_add(r16,r18,r19);
	label$b7ac406_1_54:
	if( !r13 ) goto label$b7ac406_1_58;
	r18 = (String)$s_tang;
	r19 = 6;
	kha_graphics4_VertexStructure_add(r16,r18,r19);
	label$b7ac406_1_58:
	if( !r14 ) goto label$b7ac406_1_62;
	r18 = (String)$s_bone;
	r19 = 6;
	kha_graphics4_VertexStructure_add(r16,r18,r19);
	label$b7ac406_1_62:
	if( !r15 ) goto label$b7ac406_1_66;
	r18 = (String)$s_weight;
	r19 = 6;
	kha_graphics4_VertexStructure_add(r16,r18,r19);
	label$b7ac406_1_66:
	return r16;
}

void iron_data_Geometry_applyScale(iron__data__Geometry r0,double r1,double r2,double r3) {
	iron__data__MeshData r4;
	float r5, r6;
	r4 = r0->data;
	if( r4 == NULL ) hl_null_access();
	r5 = r4->scalePos;
	r6 = (float)r1;
	r5 = r5 * r6;
	r4->scalePos = r5;
	return;
}

void iron_data_Geometry_setupInstanced(iron__data__Geometry r0,kha__arrays__Float32ArrayPrivate r1,int r2,int r3) {
	bool *r18;
	String r7;
	bool r6;
	kha__graphics4__VertexBuffer r14;
	float r22;
	kha__arrays__Float32ArrayPrivate r10;
	double r11, r12, r13;
	vdynamic *r19, *r20;
	int *r17;
	vbyte *r23;
	int r8, r9, r15, r16, r21;
	kha__graphics4__VertexStructure r4;
	r4 = (kha__graphics4__VertexStructure)hl_alloc_obj(&$t_kha_graphics4_VertexStructure);
	kha_graphics4_VertexStructure_new(r4);
	r6 = true;
	r4->instanced = r6;
	r6 = true;
	r0->instanced = r6;
	r7 = (String)$s_ipos;
	r8 = 2;
	kha_graphics4_VertexStructure_add(r4,r7,r8);
	r9 = 2;
	if( r2 == r9 ) goto label$b7ac406_3_13;
	r9 = 4;
	if( r2 != r9 ) goto label$b7ac406_3_16;
	label$b7ac406_3_13:
	r7 = (String)$s_irot;
	r8 = 2;
	kha_graphics4_VertexStructure_add(r4,r7,r8);
	label$b7ac406_3_16:
	r9 = 3;
	if( r2 == r9 ) goto label$b7ac406_3_20;
	r9 = 4;
	if( r2 != r9 ) goto label$b7ac406_3_23;
	label$b7ac406_3_20:
	r7 = (String)$s_iscl;
	r8 = 2;
	kha_graphics4_VertexStructure_add(r4,r7,r8);
	label$b7ac406_3_23:
	if( r1 == NULL ) hl_null_access();
	r8 = r1->length;
	r9 = kha_graphics4_VertexStructure_byteSize(r4);
	r11 = (double)r9;
	r12 = 4.;
	r11 = r11 / r12;
	r12 = (double)r8;
	r9 = (int)r11;
	r13 = (double)r9;
	r12 = r12 / r13;
	r9 = (int)r12;
	r0->instanceCount = r9;
	r14 = (kha__graphics4__VertexBuffer)hl_alloc_obj(&$t_kha_graphics4_VertexBuffer);
	r9 = r0->instanceCount;
	r16 = 1;
	r17 = &r16;
	r18 = NULL;
	kha_graphics4_VertexBuffer_new(r14,r9,r4,r3,r17,r18);
	r0->instancedVB = r14;
	r14 = r0->instancedVB;
	if( r14 == NULL ) hl_null_access();
	r19 = NULL;
	r20 = NULL;
	r10 = kha_graphics4_VertexBuffer_lock(r14,r19,r20);
	r9 = 0;
	if( r10 == NULL ) hl_null_access();
	r15 = r10->length;
	label$b7ac406_3_50:
	if( r9 >= r15 ) goto label$b7ac406_3_61;
	r21 = r9;
	++r9;
	if( r1 == NULL ) hl_null_access();
	r23 = r1->self;
	r22 = hl_kore_float32array_get(r23,r21);
	if( r10 == NULL ) hl_null_access();
	r23 = r10->self;
	hl_kore_float32array_set(r23,r21,r22);
	goto label$b7ac406_3_50;
	label$b7ac406_3_61:
	r14 = r0->instancedVB;
	if( r14 == NULL ) hl_null_access();
	r19 = NULL;
	kha_graphics4_VertexBuffer_unlock(r14,r19);
	return;
}

void iron_data_Geometry_buildVertices(kha__arrays__Int16ArrayPrivate r0,kha__arrays__Int16ArrayPrivate r1,kha__arrays__Int16ArrayPrivate r2,kha__arrays__Int16ArrayPrivate r3,kha__arrays__Int16ArrayPrivate r4,kha__arrays__Int16ArrayPrivate r5,kha__arrays__Int16ArrayPrivate r6,kha__arrays__Int16ArrayPrivate r7,kha__arrays__Int16ArrayPrivate r8,int* r9,bool* r10) {
	bool r12;
	double r13, r15;
	vbyte *r22;
	int r11, r14, r17, r18, r19, r20, r21, r23;
	if( r9 ) goto label$b7ac406_4_3;
	r11 = 0;
	goto label$b7ac406_4_4;
	label$b7ac406_4_3:
	r11 = *r9;
	label$b7ac406_4_4:
	if( r10 ) goto label$b7ac406_4_7;
	r12 = false;
	goto label$b7ac406_4_8;
	label$b7ac406_4_7:
	r12 = *r10;
	label$b7ac406_4_8:
	if( r1 == NULL ) hl_null_access();
	r14 = r1->length;
	r13 = (double)r14;
	r15 = 4.;
	r13 = r13 / r15;
	r14 = (int)r13;
	r17 = -1;
	r17 = r17 + r11;
	r18 = 0;
	r19 = r14;
	label$b7ac406_4_18:
	if( r18 >= r19 ) goto label$b7ac406_4_257;
	r20 = r18;
	++r18;
	if( r1 == NULL ) hl_null_access();
	r22 = r1->self;
	r23 = 4;
	r21 = r20 * r23;
	r21 = hl_kore_int16array_get(r22,r21);
	if( r0 == NULL ) hl_null_access();
	r22 = r0->self;
	++r17;
	hl_kore_int16array_set(r22,r17,r21);
	r22 = r1->self;
	r23 = 4;
	r21 = r20 * r23;
	r23 = 1;
	r21 = r21 + r23;
	r21 = hl_kore_int16array_get(r22,r21);
	r22 = r0->self;
	++r17;
	hl_kore_int16array_set(r22,r17,r21);
	r22 = r1->self;
	r23 = 4;
	r21 = r20 * r23;
	r23 = 2;
	r21 = r21 + r23;
	r21 = hl_kore_int16array_get(r22,r21);
	r22 = r0->self;
	++r17;
	hl_kore_int16array_set(r22,r17,r21);
	r22 = r1->self;
	r23 = 4;
	r21 = r20 * r23;
	r23 = 3;
	r21 = r21 + r23;
	r21 = hl_kore_int16array_get(r22,r21);
	r22 = r0->self;
	++r17;
	hl_kore_int16array_set(r22,r17,r21);
	if( !r2 ) goto label$b7ac406_4_76;
	if( r2 == NULL ) hl_null_access();
	r22 = r2->self;
	r23 = 2;
	r21 = r20 * r23;
	r21 = hl_kore_int16array_get(r22,r21);
	r22 = r0->self;
	++r17;
	hl_kore_int16array_set(r22,r17,r21);
	r22 = r2->self;
	r23 = 2;
	r21 = r20 * r23;
	r23 = 1;
	r21 = r21 + r23;
	r21 = hl_kore_int16array_get(r22,r21);
	r22 = r0->self;
	++r17;
	hl_kore_int16array_set(r22,r17,r21);
	label$b7ac406_4_76:
	if( !r3 ) goto label$b7ac406_4_95;
	if( r3 == NULL ) hl_null_access();
	r22 = r3->self;
	r23 = 2;
	r21 = r20 * r23;
	r21 = hl_kore_int16array_get(r22,r21);
	r22 = r0->self;
	++r17;
	hl_kore_int16array_set(r22,r17,r21);
	r22 = r3->self;
	r23 = 2;
	r21 = r20 * r23;
	r23 = 1;
	r21 = r21 + r23;
	r21 = hl_kore_int16array_get(r22,r21);
	r22 = r0->self;
	++r17;
	hl_kore_int16array_set(r22,r17,r21);
	goto label$b7ac406_4_104;
	label$b7ac406_4_95:
	if( !r12 ) goto label$b7ac406_4_104;
	r22 = r0->self;
	++r17;
	r21 = 0;
	hl_kore_int16array_set(r22,r17,r21);
	r22 = r0->self;
	++r17;
	r21 = 0;
	hl_kore_int16array_set(r22,r17,r21);
	label$b7ac406_4_104:
	if( !r4 ) goto label$b7ac406_4_122;
	if( r4 == NULL ) hl_null_access();
	r22 = r4->self;
	r23 = 2;
	r21 = r20 * r23;
	r21 = hl_kore_int16array_get(r22,r21);
	r22 = r0->self;
	++r17;
	hl_kore_int16array_set(r22,r17,r21);
	r22 = r4->self;
	r23 = 2;
	r21 = r20 * r23;
	r23 = 1;
	r21 = r21 + r23;
	r21 = hl_kore_int16array_get(r22,r21);
	r22 = r0->self;
	++r17;
	hl_kore_int16array_set(r22,r17,r21);
	label$b7ac406_4_122:
	if( !r5 ) goto label$b7ac406_4_153;
	if( r5 == NULL ) hl_null_access();
	r22 = r5->self;
	r23 = 3;
	r21 = r20 * r23;
	r21 = hl_kore_int16array_get(r22,r21);
	r22 = r0->self;
	++r17;
	hl_kore_int16array_set(r22,r17,r21);
	r22 = r5->self;
	r23 = 3;
	r21 = r20 * r23;
	r23 = 1;
	r21 = r21 + r23;
	r21 = hl_kore_int16array_get(r22,r21);
	r22 = r0->self;
	++r17;
	hl_kore_int16array_set(r22,r17,r21);
	r22 = r5->self;
	r23 = 3;
	r21 = r20 * r23;
	r23 = 2;
	r21 = r21 + r23;
	r21 = hl_kore_int16array_get(r22,r21);
	r22 = r0->self;
	++r17;
	hl_kore_int16array_set(r22,r17,r21);
	r22 = r0->self;
	++r17;
	r21 = 0;
	hl_kore_int16array_set(r22,r17,r21);
	label$b7ac406_4_153:
	if( !r6 ) goto label$b7ac406_4_184;
	if( r6 == NULL ) hl_null_access();
	r22 = r6->self;
	r23 = 3;
	r21 = r20 * r23;
	r21 = hl_kore_int16array_get(r22,r21);
	r22 = r0->self;
	++r17;
	hl_kore_int16array_set(r22,r17,r21);
	r22 = r6->self;
	r23 = 3;
	r21 = r20 * r23;
	r23 = 1;
	r21 = r21 + r23;
	r21 = hl_kore_int16array_get(r22,r21);
	r22 = r0->self;
	++r17;
	hl_kore_int16array_set(r22,r17,r21);
	r22 = r6->self;
	r23 = 3;
	r21 = r20 * r23;
	r23 = 2;
	r21 = r21 + r23;
	r21 = hl_kore_int16array_get(r22,r21);
	r22 = r0->self;
	++r17;
	hl_kore_int16array_set(r22,r17,r21);
	r22 = r0->self;
	++r17;
	r21 = 0;
	hl_kore_int16array_set(r22,r17,r21);
	label$b7ac406_4_184:
	if( !r7 ) goto label$b7ac406_4_220;
	if( r7 == NULL ) hl_null_access();
	r22 = r7->self;
	r23 = 4;
	r21 = r20 * r23;
	r21 = hl_kore_int16array_get(r22,r21);
	r22 = r0->self;
	++r17;
	hl_kore_int16array_set(r22,r17,r21);
	r22 = r7->self;
	r23 = 4;
	r21 = r20 * r23;
	r23 = 1;
	r21 = r21 + r23;
	r21 = hl_kore_int16array_get(r22,r21);
	r22 = r0->self;
	++r17;
	hl_kore_int16array_set(r22,r17,r21);
	r22 = r7->self;
	r23 = 4;
	r21 = r20 * r23;
	r23 = 2;
	r21 = r21 + r23;
	r21 = hl_kore_int16array_get(r22,r21);
	r22 = r0->self;
	++r17;
	hl_kore_int16array_set(r22,r17,r21);
	r22 = r7->self;
	r23 = 4;
	r21 = r20 * r23;
	r23 = 3;
	r21 = r21 + r23;
	r21 = hl_kore_int16array_get(r22,r21);
	r22 = r0->self;
	++r17;
	hl_kore_int16array_set(r22,r17,r21);
	label$b7ac406_4_220:
	if( !r8 ) goto label$b7ac406_4_256;
	if( r8 == NULL ) hl_null_access();
	r22 = r8->self;
	r23 = 4;
	r21 = r20 * r23;
	r21 = hl_kore_int16array_get(r22,r21);
	r22 = r0->self;
	++r17;
	hl_kore_int16array_set(r22,r17,r21);
	r22 = r8->self;
	r23 = 4;
	r21 = r20 * r23;
	r23 = 1;
	r21 = r21 + r23;
	r21 = hl_kore_int16array_get(r22,r21);
	r22 = r0->self;
	++r17;
	hl_kore_int16array_set(r22,r17,r21);
	r22 = r8->self;
	r23 = 4;
	r21 = r20 * r23;
	r23 = 2;
	r21 = r21 + r23;
	r21 = hl_kore_int16array_get(r22,r21);
	r22 = r0->self;
	++r17;
	hl_kore_int16array_set(r22,r17,r21);
	r22 = r8->self;
	r23 = 4;
	r21 = r20 * r23;
	r23 = 3;
	r21 = r21 + r23;
	r21 = hl_kore_int16array_get(r22,r21);
	r22 = r0->self;
	++r17;
	hl_kore_int16array_set(r22,r17,r21);
	label$b7ac406_4_256:
	goto label$b7ac406_4_18;
	label$b7ac406_4_257:
	return;
}

bool iron_data_Geometry_hasAttrib(iron__data__Geometry r0,String r1,hl__types__ArrayObj r2) {
	String r8;
	bool r9;
	iron__data__TVertexElement r5;
	vdynamic *r6;
	varray *r7;
	int r3, r4;
	r3 = 0;
	label$b7ac406_5_1:
	if( r2 == NULL ) hl_null_access();
	r4 = r2->length;
	if( r3 >= r4 ) goto label$b7ac406_5_19;
	r4 = r2->length;
	if( ((unsigned)r3) < ((unsigned)r4) ) goto label$b7ac406_5_9;
	r5 = NULL;
	goto label$b7ac406_5_12;
	label$b7ac406_5_9:
	r7 = r2->array;
	r6 = ((vdynamic**)(r7 + 1))[r3];
	r5 = (iron__data__TVertexElement)r6;
	label$b7ac406_5_12:
	++r3;
	if( r5 == NULL ) hl_null_access();
	r8 = r5->name;
	if( r8 != r1 && (!r8 || !r1 || String___compare(r8,(vdynamic*)r1) != 0) ) goto label$b7ac406_5_18;
	r9 = true;
	return r9;
	label$b7ac406_5_18:
	goto label$b7ac406_5_1;
	label$b7ac406_5_19:
	r9 = false;
	return r9;
}

kha__graphics4__VertexBuffer iron_data_Geometry_get(iron__data__Geometry r0,hl__types__ArrayObj r1) {
	bool *r25, *r27, *r29, *r31, *r33, *r35, *r37, *r39;
	String r2, r10, r11;
	kha__arrays__Int16ArrayPrivate r41, r46, r48, r49, r50, r51, r52, r53, r54, r55;
	vvirtual *r58, *r59;
	haxe__ds__StringMap r12;
	bool r15, r16, r17, r18, r19, r20, r21, r22, r24, r26, r28, r30, r32, r34, r36, r38, r47;
	haxe__$Log r57;
	kha__graphics4__VertexBuffer r13, r14;
	vclosure *r56;
	double r40, r42;
	iron__data__TVertexElement r7;
	int *r43;
	vdynamic *r8, *r44, *r45;
	kha__graphics4__VertexStructure r23;
	varray *r9;
	int r4, r5, r6;
	r2 = (String)$s_;
	r4 = 0;
	label$b7ac406_6_2:
	if( r1 == NULL ) hl_null_access();
	r6 = r1->length;
	if( r4 >= r6 ) goto label$b7ac406_6_19;
	r6 = r1->length;
	if( ((unsigned)r4) < ((unsigned)r6) ) goto label$b7ac406_6_10;
	r7 = NULL;
	goto label$b7ac406_6_13;
	label$b7ac406_6_10:
	r9 = r1->array;
	r8 = ((vdynamic**)(r9 + 1))[r4];
	r7 = (iron__data__TVertexElement)r8;
	label$b7ac406_6_13:
	++r4;
	if( r7 == NULL ) hl_null_access();
	r11 = r7->name;
	r10 = String___add__(r2,r11);
	r2 = r10;
	goto label$b7ac406_6_2;
	label$b7ac406_6_19:
	r12 = r0->vertexBufferMap;
	if( r12 == NULL ) hl_null_access();
	r8 = haxe_ds_StringMap_get(r12,r2);
	r13 = (kha__graphics4__VertexBuffer)r8;
	if( r13 ) goto label$b7ac406_6_166;
	r10 = (String)$s_pos;
	r15 = iron_data_Geometry_hasAttrib(r0,r10,r1);
	r10 = (String)$s_nor;
	r16 = iron_data_Geometry_hasAttrib(r0,r10,r1);
	r10 = (String)$s_tex;
	r17 = iron_data_Geometry_hasAttrib(r0,r10,r1);
	r10 = (String)$s_tex1;
	r18 = iron_data_Geometry_hasAttrib(r0,r10,r1);
	r10 = (String)$s_col;
	r19 = iron_data_Geometry_hasAttrib(r0,r10,r1);
	r10 = (String)$s_tang;
	r20 = iron_data_Geometry_hasAttrib(r0,r10,r1);
	r10 = (String)$s_bone;
	r21 = iron_data_Geometry_hasAttrib(r0,r10,r1);
	r10 = (String)$s_weight;
	r22 = iron_data_Geometry_hasAttrib(r0,r10,r1);
	r24 = r15;
	r25 = &r24;
	r26 = r16;
	r27 = &r26;
	r28 = r17;
	r29 = &r28;
	r30 = r18;
	r31 = &r30;
	r32 = r19;
	r33 = &r32;
	r34 = r20;
	r35 = &r34;
	r36 = r21;
	r37 = &r36;
	r38 = r22;
	r39 = &r38;
	r23 = iron_data_Geometry_getVertexStructure(r25,r27,r29,r31,r33,r35,r37,r39);
	r41 = r0->positions;
	if( r41 == NULL ) hl_null_access();
	r4 = r41->length;
	r40 = (double)r4;
	r42 = 4.;
	r40 = r40 / r42;
	r14 = (kha__graphics4__VertexBuffer)hl_alloc_obj(&$t_kha_graphics4_VertexBuffer);
	r4 = (int)r40;
	r5 = r0->usage;
	r43 = NULL;
	r25 = NULL;
	kha_graphics4_VertexBuffer_new(r14,r4,r23,r5,r43,r25);
	r13 = r14;
	r44 = NULL;
	r45 = NULL;
	r41 = kha_graphics4_VertexBuffer_lockInt16(r14,r44,r45);
	r0->vertices = r41;
	r41 = r0->vertices;
	if( !r15 ) goto label$b7ac406_6_78;
	r46 = r0->positions;
	goto label$b7ac406_6_79;
	label$b7ac406_6_78:
	r46 = NULL;
	label$b7ac406_6_79:
	if( !r16 ) goto label$b7ac406_6_82;
	r48 = r0->normals;
	goto label$b7ac406_6_83;
	label$b7ac406_6_82:
	r48 = NULL;
	label$b7ac406_6_83:
	if( !r17 ) goto label$b7ac406_6_86;
	r49 = r0->uvs;
	goto label$b7ac406_6_87;
	label$b7ac406_6_86:
	r49 = NULL;
	label$b7ac406_6_87:
	if( !r18 ) goto label$b7ac406_6_90;
	r50 = r0->uvs1;
	goto label$b7ac406_6_91;
	label$b7ac406_6_90:
	r50 = NULL;
	label$b7ac406_6_91:
	if( !r19 ) goto label$b7ac406_6_94;
	r51 = r0->cols;
	goto label$b7ac406_6_95;
	label$b7ac406_6_94:
	r51 = NULL;
	label$b7ac406_6_95:
	if( !r20 ) goto label$b7ac406_6_98;
	r52 = r0->tangents;
	goto label$b7ac406_6_99;
	label$b7ac406_6_98:
	r52 = NULL;
	label$b7ac406_6_99:
	if( !r21 ) goto label$b7ac406_6_102;
	r53 = r0->bones;
	goto label$b7ac406_6_103;
	label$b7ac406_6_102:
	r53 = NULL;
	label$b7ac406_6_103:
	if( !r22 ) goto label$b7ac406_6_106;
	r54 = r0->weights;
	goto label$b7ac406_6_107;
	label$b7ac406_6_106:
	r54 = NULL;
	label$b7ac406_6_107:
	r4 = 0;
	r43 = &r4;
	if( !r17 ) goto label$b7ac406_6_114;
	r55 = r0->uvs;
	if( r55 ) goto label$b7ac406_6_114;
	r47 = true;
	goto label$b7ac406_6_115;
	label$b7ac406_6_114:
	r47 = false;
	label$b7ac406_6_115:
	r25 = &r47;
	iron_data_Geometry_buildVertices(r41,r46,r48,r49,r50,r51,r52,r53,r54,r43,r25);
	r44 = NULL;
	kha_graphics4_VertexBuffer_unlock(r14,r44);
	r12 = r0->vertexBufferMap;
	if( r12 == NULL ) hl_null_access();
	haxe_ds_StringMap_set(r12,r2,((vdynamic*)r14));
	if( !r17 ) goto label$b7ac406_6_144;
	r41 = r0->uvs;
	if( r41 ) goto label$b7ac406_6_144;
	r57 = (haxe__$Log)$g__haxe_Log;
	r56 = r57->trace;
	if( r56 == NULL ) hl_null_access();
	r10 = (String)$s_Armory_Warning_Geometry_;
	r11 = r0->name;
	r10 = String___add__(r10,r11);
	r11 = (String)$s__is_missing_UV_map;
	r10 = String___add__(r10,r11);
	r58 = hl_alloc_virtual(&$t_vrt_329ffa8);
	r11 = (String)$s_Sources_iron_data_Geometry_hx;
	if( hl_vfields(r58)[1] ) *(String*)(hl_vfields(r58)[1]) = (String)r11; else hl_dyn_setp(r58->value,37969014/*fileName*/,&$t_String,r11);
	r5 = 271;
	if( hl_vfields(r58)[2] ) *(int*)(hl_vfields(r58)[2]) = (int)r5; else hl_dyn_seti(r58->value,371360620/*lineNumber*/,&$t_i32,r5);
	r11 = (String)$s_iron_data_Geometry;
	if( hl_vfields(r58)[0] ) *(String*)(hl_vfields(r58)[0]) = (String)r11; else hl_dyn_setp(r58->value,-63073762/*className*/,&$t_String,r11);
	r11 = (String)$s_get;
	if( hl_vfields(r58)[3] ) *(String*)(hl_vfields(r58)[3]) = (String)r11; else hl_dyn_setp(r58->value,302979532/*methodName*/,&$t_String,r11);
	r59 = hl_to_virtual(&$t_vrt_eaa6a3b,(vdynamic*)r58);
	r56->hasValue ? ((void (*)(vdynamic*,vdynamic*,vvirtual*))r56->fun)((vdynamic*)r56->value,((vdynamic*)r10),r59) : ((void (*)(vdynamic*,vvirtual*))r56->fun)(((vdynamic*)r10),r59);
	label$b7ac406_6_144:
	if( !r19 ) goto label$b7ac406_6_166;
	r41 = r0->cols;
	if( r41 ) goto label$b7ac406_6_166;
	r57 = (haxe__$Log)$g__haxe_Log;
	r56 = r57->trace;
	if( r56 == NULL ) hl_null_access();
	r10 = (String)$s_Armory_Warning_Geometry_;
	r11 = r0->name;
	r10 = String___add__(r10,r11);
	r11 = (String)$s__is_missing_vertex_colors;
	r10 = String___add__(r10,r11);
	r58 = hl_alloc_virtual(&$t_vrt_329ffa8);
	r11 = (String)$s_Sources_iron_data_Geometry_hx;
	if( hl_vfields(r58)[1] ) *(String*)(hl_vfields(r58)[1]) = (String)r11; else hl_dyn_setp(r58->value,37969014/*fileName*/,&$t_String,r11);
	r5 = 272;
	if( hl_vfields(r58)[2] ) *(int*)(hl_vfields(r58)[2]) = (int)r5; else hl_dyn_seti(r58->value,371360620/*lineNumber*/,&$t_i32,r5);
	r11 = (String)$s_iron_data_Geometry;
	if( hl_vfields(r58)[0] ) *(String*)(hl_vfields(r58)[0]) = (String)r11; else hl_dyn_setp(r58->value,-63073762/*className*/,&$t_String,r11);
	r11 = (String)$s_get;
	if( hl_vfields(r58)[3] ) *(String*)(hl_vfields(r58)[3]) = (String)r11; else hl_dyn_setp(r58->value,302979532/*methodName*/,&$t_String,r11);
	r59 = hl_to_virtual(&$t_vrt_eaa6a3b,(vdynamic*)r58);
	r56->hasValue ? ((void (*)(vdynamic*,vdynamic*,vvirtual*))r56->fun)((vdynamic*)r56->value,((vdynamic*)r10),r59) : ((void (*)(vdynamic*,vvirtual*))r56->fun)(((vdynamic*)r10),r59);
	label$b7ac406_6_166:
	return r13;
}

void iron_data_Geometry_build(iron__data__Geometry r0) {
	String r24;
	bool *r12;
	kha__arrays__Int16ArrayPrivate r6, r15, r16, r17, r18, r19, r20, r21, r22;
	hl__types__ArrayObj r25, r29;
	haxe__ds__StringMap r23;
	hl_type *r27;
	bool r2;
	kha__graphics4__VertexBuffer r8;
	kha__graphics4__IndexBuffer r32;
	iron__data__MeshData r39;
	kha__arrays__Float32ArrayPrivate r37;
	iron__data__TMeshData r38;
	kha__arrays__Uint32ArrayPrivate r30, r31;
	double r4, r7, r33;
	int *r11;
	vdynamic *r3, *r13, *r14;
	vbyte *r36;
	varray *r26;
	kha__graphics4__VertexStructure r9;
	int r5, r10, r28, r34, r35;
	r2 = r0->ready;
	if( !r2 ) goto label$b7ac406_7_3;
	return;
	label$b7ac406_7_3:
	r6 = r0->positions;
	if( r6 == NULL ) hl_null_access();
	r5 = r6->length;
	r4 = (double)r5;
	r7 = 4.;
	r4 = r4 / r7;
	r8 = (kha__graphics4__VertexBuffer)hl_alloc_obj(&$t_kha_graphics4_VertexBuffer);
	r5 = (int)r4;
	r9 = r0->_struct;
	r10 = r0->usage;
	r11 = NULL;
	r12 = NULL;
	kha_graphics4_VertexBuffer_new(r8,r5,r9,r10,r11,r12);
	r0->vertexBuffer = r8;
	r8 = r0->vertexBuffer;
	if( r8 == NULL ) hl_null_access();
	r13 = NULL;
	r14 = NULL;
	r6 = kha_graphics4_VertexBuffer_lockInt16(r8,r13,r14);
	r0->vertices = r6;
	r6 = r0->vertices;
	r15 = r0->positions;
	r16 = r0->normals;
	r17 = r0->uvs;
	r18 = r0->uvs1;
	r19 = r0->cols;
	r20 = r0->tangents;
	r21 = r0->bones;
	r22 = r0->weights;
	r11 = NULL;
	r12 = NULL;
	iron_data_Geometry_buildVertices(r6,r15,r16,r17,r18,r19,r20,r21,r22,r11,r12);
	r8 = r0->vertexBuffer;
	if( r8 == NULL ) hl_null_access();
	r13 = NULL;
	kha_graphics4_VertexBuffer_unlock(r8,r13);
	r23 = r0->vertexBufferMap;
	if( r23 == NULL ) hl_null_access();
	r24 = r0->structStr;
	r8 = r0->vertexBuffer;
	haxe_ds_StringMap_set(r23,r24,((vdynamic*)r8));
	r27 = &$t_kha_graphics4_IndexBuffer;
	r5 = 0;
	r26 = hl_alloc_array(r27,r5);
	r25 = hl_types_ArrayObj_alloc(r26);
	r0->indexBuffers = r25;
	r5 = 0;
	r25 = r0->indices;
	label$b7ac406_7_51:
	if( r25 == NULL ) hl_null_access();
	r28 = r25->length;
	if( r5 >= r28 ) goto label$b7ac406_7_102;
	r28 = r25->length;
	if( ((unsigned)r5) < ((unsigned)r28) ) goto label$b7ac406_7_59;
	r30 = NULL;
	goto label$b7ac406_7_62;
	label$b7ac406_7_59:
	r26 = r25->array;
	r3 = ((vdynamic**)(r26 + 1))[r5];
	r30 = (kha__arrays__Uint32ArrayPrivate)r3;
	label$b7ac406_7_62:
	++r5;
	if( r30 == NULL ) hl_null_access();
	r10 = r30->length;
	r28 = 0;
	if( r10 != r28 ) goto label$b7ac406_7_68;
	goto label$b7ac406_7_51;
	label$b7ac406_7_68:
	r32 = (kha__graphics4__IndexBuffer)hl_alloc_obj(&$t_kha_graphics4_IndexBuffer);
	r10 = r30->length;
	r28 = r0->usage;
	r12 = NULL;
	kha_graphics4_IndexBuffer_new(r32,r10,r28,r12);
	r10 = r30->length;
	r7 = (double)r10;
	r33 = 3.;
	r7 = r7 / r33;
	r10 = r0->numTris;
	r28 = (int)r7;
	r10 = r10 + r28;
	r0->numTris = r10;
	r31 = kha_graphics4_IndexBuffer_lock(r32);
	r10 = 0;
	if( r31 == NULL ) hl_null_access();
	r28 = r31->length;
	label$b7ac406_7_85:
	if( r10 >= r28 ) goto label$b7ac406_7_96;
	r34 = r10;
	++r10;
	if( r30 == NULL ) hl_null_access();
	r36 = r30->self;
	r35 = hl_kore_uint32array_get(r36,r34);
	if( r31 == NULL ) hl_null_access();
	r36 = r31->self;
	hl_kore_uint32array_set(r36,r34,r35);
	goto label$b7ac406_7_85;
	label$b7ac406_7_96:
	if( r32 == NULL ) hl_null_access();
	kha_graphics4_IndexBuffer_unlock(r32);
	r29 = r0->indexBuffers;
	if( r29 == NULL ) hl_null_access();
	r10 = hl_types_ArrayObj_push(r29,((vdynamic*)r32));
	goto label$b7ac406_7_51;
	label$b7ac406_7_102:
	r39 = r0->data;
	if( r39 == NULL ) hl_null_access();
	r38 = r39->raw;
	if( r38 == NULL ) hl_null_access();
	r37 = r38->instanced_data;
	if( !r37 ) goto label$b7ac406_7_121;
	r39 = r0->data;
	if( r39 == NULL ) hl_null_access();
	r38 = r39->raw;
	if( r38 == NULL ) hl_null_access();
	r37 = r38->instanced_data;
	r39 = r0->data;
	if( r39 == NULL ) hl_null_access();
	r38 = r39->raw;
	if( r38 == NULL ) hl_null_access();
	r13 = r38->instanced_type;
	r5 = r13 ? r13->v.i : 0;
	r10 = r0->usage;
	iron_data_Geometry_setupInstanced(r0,r37,r5,r10);
	label$b7ac406_7_121:
	r2 = true;
	r0->ready = r2;
	return;
}

void iron_data_Geometry_addArmature(iron__data__Geometry r0,iron__data__Armature r1) {
	String r10;
	vvirtual *r7;
	hl__types__ArrayObj r4, r6;
	vdynamic *r8;
	varray *r9;
	int r2, r5;
	r2 = 0;
	if( r1 == NULL ) hl_null_access();
	r4 = r1->actions;
	label$b7ac406_8_3:
	if( r4 == NULL ) hl_null_access();
	r5 = r4->length;
	if( r2 >= r5 ) goto label$b7ac406_8_20;
	r5 = r4->length;
	if( ((unsigned)r2) < ((unsigned)r5) ) goto label$b7ac406_8_11;
	r7 = NULL;
	goto label$b7ac406_8_14;
	label$b7ac406_8_11:
	r9 = r4->array;
	r8 = ((vdynamic**)(r9 + 1))[r2];
	r7 = hl_to_virtual(&$t_vrt_7235b40,(vdynamic*)r8);
	label$b7ac406_8_14:
	++r2;
	if( r7 == NULL ) hl_null_access();
	r6 = hl_vfields(r7)[0] ? (*(hl__types__ArrayObj*)(hl_vfields(r7)[0])) : (hl__types__ArrayObj)hl_dyn_getp(r7->value,-151562331/*bones*/,&$t_hl_types_ArrayObj);
	r10 = hl_vfields(r7)[2] ? (*(String*)(hl_vfields(r7)[2])) : (String)hl_dyn_getp(r7->value,150958933/*name*/,&$t_String);
	iron_data_Geometry_addAction(r0,r6,r10);
	goto label$b7ac406_8_3;
	label$b7ac406_8_20:
	return;
}

void iron_data_Geometry_addAction(iron__data__Geometry r0,hl__types__ArrayObj r1,String r2) {
	String r7, r16;
	haxe__ds__StringMap r6;
	hl__types__ArrayObj r4, r11;
	hl_type *r9;
	iron__data__TObj r15;
	iron__data__TTransform r18;
	float r20, r22, r23, r24, r25, r26, r27, r28, r29, r30, r31, r32, r33, r34, r35, r36;
	iron__math__Mat4 r19;
	kha__arrays__Float32ArrayPrivate r17;
	vdynamic *r5;
	vbyte *r21;
	int r10, r12, r13, r14;
	varray *r8;
	if( r1 ) goto label$b7ac406_9_2;
	return;
	label$b7ac406_9_2:
	r6 = r0->actions;
	if( r6 ) goto label$b7ac406_9_10;
	r6 = (haxe__ds__StringMap)hl_alloc_obj(&$t_haxe_ds_StringMap);
	haxe_ds_StringMap_new(r6);
	r0->actions = r6;
	r6 = (haxe__ds__StringMap)hl_alloc_obj(&$t_haxe_ds_StringMap);
	haxe_ds_StringMap_new(r6);
	r0->mats = r6;
	label$b7ac406_9_10:
	r6 = r0->actions;
	if( r6 == NULL ) hl_null_access();
	r5 = haxe_ds_StringMap_get(r6,r2);
	r4 = (hl__types__ArrayObj)hl_dyn_castp(&r5,&$t_dyn,&$t_hl_types_ArrayObj);
	if( !r4 ) goto label$b7ac406_9_16;
	return;
	label$b7ac406_9_16:
	r9 = &$t_iron_data_TObj;
	r10 = 0;
	r8 = hl_alloc_array(r9,r10);
	r4 = hl_types_ArrayObj_alloc(r8);
	r10 = 0;
	r11 = r0->skeletonBoneRefs;
	label$b7ac406_9_22:
	if( r11 == NULL ) hl_null_access();
	r13 = r11->length;
	if( r10 >= r13 ) goto label$b7ac406_9_54;
	r13 = r11->length;
	if( ((unsigned)r10) < ((unsigned)r13) ) goto label$b7ac406_9_30;
	r7 = NULL;
	goto label$b7ac406_9_33;
	label$b7ac406_9_30:
	r8 = r11->array;
	r5 = ((vdynamic**)(r8 + 1))[r10];
	r7 = (String)r5;
	label$b7ac406_9_33:
	++r10;
	r12 = 0;
	label$b7ac406_9_35:
	if( r1 == NULL ) hl_null_access();
	r14 = r1->length;
	if( r12 >= r14 ) goto label$b7ac406_9_53;
	r14 = r1->length;
	if( ((unsigned)r12) < ((unsigned)r14) ) goto label$b7ac406_9_43;
	r15 = NULL;
	goto label$b7ac406_9_46;
	label$b7ac406_9_43:
	r8 = r1->array;
	r5 = ((vdynamic**)(r8 + 1))[r12];
	r15 = (iron__data__TObj)r5;
	label$b7ac406_9_46:
	++r12;
	if( r15 == NULL ) hl_null_access();
	r16 = r15->name;
	if( r16 != r7 && (!r16 || !r7 || String___compare(r16,(vdynamic*)r7) != 0) ) goto label$b7ac406_9_52;
	if( r4 == NULL ) hl_null_access();
	r13 = hl_types_ArrayObj_push(r4,((vdynamic*)r15));
	label$b7ac406_9_52:
	goto label$b7ac406_9_35;
	label$b7ac406_9_53:
	goto label$b7ac406_9_22;
	label$b7ac406_9_54:
	r6 = r0->actions;
	if( r6 == NULL ) hl_null_access();
	haxe_ds_StringMap_set(r6,r2,((vdynamic*)r4));
	r9 = &$t_iron_math_Mat4;
	r10 = 0;
	r8 = hl_alloc_array(r9,r10);
	r11 = hl_types_ArrayObj_alloc(r8);
	r10 = 0;
	label$b7ac406_9_62:
	if( r4 == NULL ) hl_null_access();
	r13 = r4->length;
	if( r10 >= r13 ) goto label$b7ac406_9_147;
	r13 = r4->length;
	if( ((unsigned)r10) < ((unsigned)r13) ) goto label$b7ac406_9_70;
	r15 = NULL;
	goto label$b7ac406_9_73;
	label$b7ac406_9_70:
	r8 = r4->array;
	r5 = ((vdynamic**)(r8 + 1))[r10];
	r15 = (iron__data__TObj)r5;
	label$b7ac406_9_73:
	++r10;
	if( r15 == NULL ) hl_null_access();
	r18 = r15->transform;
	if( r18 == NULL ) hl_null_access();
	r17 = r18->values;
	r12 = 0;
	if( r11 == NULL ) hl_null_access();
	r19 = (iron__math__Mat4)hl_alloc_obj(&$t_iron_math_Mat4);
	if( r17 == NULL ) hl_null_access();
	r21 = r17->self;
	r20 = hl_kore_float32array_get(r21,r12);
	r21 = r17->self;
	r13 = 1;
	r13 = r13 + r12;
	r22 = hl_kore_float32array_get(r21,r13);
	r21 = r17->self;
	r13 = 2;
	r13 = r13 + r12;
	r23 = hl_kore_float32array_get(r21,r13);
	r21 = r17->self;
	r13 = 3;
	r13 = r13 + r12;
	r24 = hl_kore_float32array_get(r21,r13);
	r21 = r17->self;
	r13 = 4;
	r13 = r13 + r12;
	r25 = hl_kore_float32array_get(r21,r13);
	r21 = r17->self;
	r13 = 5;
	r13 = r13 + r12;
	r26 = hl_kore_float32array_get(r21,r13);
	r21 = r17->self;
	r13 = 6;
	r13 = r13 + r12;
	r27 = hl_kore_float32array_get(r21,r13);
	r21 = r17->self;
	r13 = 7;
	r13 = r13 + r12;
	r28 = hl_kore_float32array_get(r21,r13);
	r21 = r17->self;
	r13 = 8;
	r13 = r13 + r12;
	r29 = hl_kore_float32array_get(r21,r13);
	r21 = r17->self;
	r13 = 9;
	r13 = r13 + r12;
	r30 = hl_kore_float32array_get(r21,r13);
	r21 = r17->self;
	r13 = 10;
	r13 = r13 + r12;
	r31 = hl_kore_float32array_get(r21,r13);
	r21 = r17->self;
	r13 = 11;
	r13 = r13 + r12;
	r32 = hl_kore_float32array_get(r21,r13);
	r21 = r17->self;
	r13 = 12;
	r13 = r13 + r12;
	r33 = hl_kore_float32array_get(r21,r13);
	r21 = r17->self;
	r13 = 13;
	r13 = r13 + r12;
	r34 = hl_kore_float32array_get(r21,r13);
	r21 = r17->self;
	r13 = 14;
	r13 = r13 + r12;
	r35 = hl_kore_float32array_get(r21,r13);
	r21 = r17->self;
	r13 = 15;
	r13 = r13 + r12;
	r36 = hl_kore_float32array_get(r21,r13);
	iron_math_Mat4_new(r19,r20,r22,r23,r24,r25,r26,r27,r28,r29,r30,r31,r32,r33,r34,r35,r36);
	r13 = hl_types_ArrayObj_push(r11,((vdynamic*)r19));
	goto label$b7ac406_9_62;
	label$b7ac406_9_147:
	r6 = r0->mats;
	if( r6 == NULL ) hl_null_access();
	haxe_ds_StringMap_set(r6,r2,((vdynamic*)r11));
	return;
}

void iron_data_Geometry_initSkeletonTransforms(iron__data__Geometry r0,hl__types__ArrayObj r1) {
	hl__types__ArrayObj r2;
	hl_type *r4;
	float r12, r14, r15, r16, r17, r18, r19, r20, r21, r22, r23, r24, r25, r26, r27, r28;
	iron__math__Mat4 r11;
	kha__arrays__Float32ArrayPrivate r9;
	vdynamic *r10;
	vbyte *r13;
	int r5, r7, r8;
	varray *r3;
	r4 = &$t_iron_math_Mat4;
	r5 = 0;
	r3 = hl_alloc_array(r4,r5);
	r2 = hl_types_ArrayObj_alloc(r3);
	r0->skeletonTransformsI = r2;
	r5 = 0;
	label$b7ac406_10_6:
	if( r1 == NULL ) hl_null_access();
	r8 = r1->length;
	if( r5 >= r8 ) goto label$b7ac406_10_88;
	r8 = r1->length;
	if( ((unsigned)r5) < ((unsigned)r8) ) goto label$b7ac406_10_14;
	r9 = NULL;
	goto label$b7ac406_10_17;
	label$b7ac406_10_14:
	r3 = r1->array;
	r10 = ((vdynamic**)(r3 + 1))[r5];
	r9 = (kha__arrays__Float32ArrayPrivate)r10;
	label$b7ac406_10_17:
	++r5;
	r7 = 0;
	r11 = (iron__math__Mat4)hl_alloc_obj(&$t_iron_math_Mat4);
	if( r9 == NULL ) hl_null_access();
	r13 = r9->self;
	r12 = hl_kore_float32array_get(r13,r7);
	r13 = r9->self;
	r8 = 1;
	r8 = r8 + r7;
	r14 = hl_kore_float32array_get(r13,r8);
	r13 = r9->self;
	r8 = 2;
	r8 = r8 + r7;
	r15 = hl_kore_float32array_get(r13,r8);
	r13 = r9->self;
	r8 = 3;
	r8 = r8 + r7;
	r16 = hl_kore_float32array_get(r13,r8);
	r13 = r9->self;
	r8 = 4;
	r8 = r8 + r7;
	r17 = hl_kore_float32array_get(r13,r8);
	r13 = r9->self;
	r8 = 5;
	r8 = r8 + r7;
	r18 = hl_kore_float32array_get(r13,r8);
	r13 = r9->self;
	r8 = 6;
	r8 = r8 + r7;
	r19 = hl_kore_float32array_get(r13,r8);
	r13 = r9->self;
	r8 = 7;
	r8 = r8 + r7;
	r20 = hl_kore_float32array_get(r13,r8);
	r13 = r9->self;
	r8 = 8;
	r8 = r8 + r7;
	r21 = hl_kore_float32array_get(r13,r8);
	r13 = r9->self;
	r8 = 9;
	r8 = r8 + r7;
	r22 = hl_kore_float32array_get(r13,r8);
	r13 = r9->self;
	r8 = 10;
	r8 = r8 + r7;
	r23 = hl_kore_float32array_get(r13,r8);
	r13 = r9->self;
	r8 = 11;
	r8 = r8 + r7;
	r24 = hl_kore_float32array_get(r13,r8);
	r13 = r9->self;
	r8 = 12;
	r8 = r8 + r7;
	r25 = hl_kore_float32array_get(r13,r8);
	r13 = r9->self;
	r8 = 13;
	r8 = r8 + r7;
	r26 = hl_kore_float32array_get(r13,r8);
	r13 = r9->self;
	r8 = 14;
	r8 = r8 + r7;
	r27 = hl_kore_float32array_get(r13,r8);
	r13 = r9->self;
	r8 = 15;
	r8 = r8 + r7;
	r28 = hl_kore_float32array_get(r13,r8);
	iron_math_Mat4_new(r11,r12,r14,r15,r16,r17,r18,r19,r20,r21,r22,r23,r24,r25,r26,r27,r28);
	r2 = r0->skeletonTransformsI;
	if( r2 == NULL ) hl_null_access();
	r8 = hl_types_ArrayObj_push(r2,((vdynamic*)r11));
	goto label$b7ac406_10_6;
	label$b7ac406_10_88:
	return;
}

void iron_data_Geometry_new(iron__data__Geometry r0,iron__data__MeshData r1,hl__types__ArrayObj r2,hl__types__ArrayBytes_Int r3,kha__arrays__Int16ArrayPrivate r4,kha__arrays__Int16ArrayPrivate r5,kha__arrays__Int16ArrayPrivate r6,kha__arrays__Int16ArrayPrivate r7,kha__arrays__Int16ArrayPrivate r8,kha__arrays__Int16ArrayPrivate r9,kha__arrays__Int16ArrayPrivate r10,kha__arrays__Int16ArrayPrivate r11,vdynamic* r12) {
	bool *r25, *r27, *r29, *r31, *r33, *r35, *r37, *r39;
	String r20, r46;
	kha__arrays__Int16ArrayPrivate r16, r24;
	hl__types__ArrayObj r15;
	haxe__ds__StringMap r13;
	bool r18, r26, r28, r30, r32, r34, r36, r38;
	kha__graphics4__VertexElement r43;
	kha__graphics4__VertexBuffer r19;
	kha__arrays__Float32ArrayPrivate r14;
	double r40, r41;
	vdynamic *r22, *r44;
	varray *r45;
	kha__graphics4__VertexStructure r23;
	int r17, r42;
	r13 = NULL;
	r0->mats = r13;
	r13 = NULL;
	r0->actions = r13;
	r14 = NULL;
	r0->skeletonBoneLens = r14;
	r15 = NULL;
	r0->skeletonBoneRefs = r15;
	r15 = NULL;
	r0->skeletonTransformsI = r15;
	r16 = NULL;
	r0->skinBoneWeights = r16;
	r16 = NULL;
	r0->skinBoneIndices = r16;
	r16 = NULL;
	r0->skinBoneCounts = r16;
	r17 = 0;
	r0->instanceCount = r17;
	r18 = false;
	r0->instanced = r18;
	r19 = NULL;
	r0->instancedVB = r19;
	r17 = 0;
	r0->numTris = r17;
	r18 = false;
	r0->ready = r18;
	r20 = (String)$s_;
	r0->name = r20;
	r17 = -1;
	r0->count = r17;
	r17 = 0;
	r0->start = r17;
	r13 = (haxe__ds__StringMap)hl_alloc_obj(&$t_haxe_ds_StringMap);
	haxe_ds_StringMap_new(r13);
	r0->vertexBufferMap = r13;
	if( r12 ) goto label$b7ac406_11_39;
	r17 = 0;
	r22 = hl_alloc_dynamic(&$t_i32);
	r22->v.i = r17;
	r12 = r22;
	label$b7ac406_11_39:
	r0->indices = r2;
	r0->materialIndices = r3;
	r17 = r12 ? r12->v.i : 0;
	r0->usage = r17;
	r0->positions = r4;
	r0->normals = r5;
	r0->uvs = r6;
	r0->uvs1 = r7;
	r0->cols = r8;
	r0->tangents = r9;
	r0->bones = r10;
	r0->weights = r11;
	r0->data = r1;
	r24 = NULL;
	if( r4 != r24 ) goto label$b7ac406_11_56;
	r18 = false;
	goto label$b7ac406_11_57;
	label$b7ac406_11_56:
	r18 = true;
	label$b7ac406_11_57:
	r25 = &r18;
	r24 = NULL;
	if( r5 != r24 ) goto label$b7ac406_11_62;
	r26 = false;
	goto label$b7ac406_11_63;
	label$b7ac406_11_62:
	r26 = true;
	label$b7ac406_11_63:
	r27 = &r26;
	r24 = NULL;
	if( r6 != r24 ) goto label$b7ac406_11_68;
	r28 = false;
	goto label$b7ac406_11_69;
	label$b7ac406_11_68:
	r28 = true;
	label$b7ac406_11_69:
	r29 = &r28;
	r24 = NULL;
	if( r7 != r24 ) goto label$b7ac406_11_74;
	r30 = false;
	goto label$b7ac406_11_75;
	label$b7ac406_11_74:
	r30 = true;
	label$b7ac406_11_75:
	r31 = &r30;
	r24 = NULL;
	if( r8 != r24 ) goto label$b7ac406_11_80;
	r32 = false;
	goto label$b7ac406_11_81;
	label$b7ac406_11_80:
	r32 = true;
	label$b7ac406_11_81:
	r33 = &r32;
	r24 = NULL;
	if( r9 != r24 ) goto label$b7ac406_11_86;
	r34 = false;
	goto label$b7ac406_11_87;
	label$b7ac406_11_86:
	r34 = true;
	label$b7ac406_11_87:
	r35 = &r34;
	r24 = NULL;
	if( r10 != r24 ) goto label$b7ac406_11_92;
	r36 = false;
	goto label$b7ac406_11_93;
	label$b7ac406_11_92:
	r36 = true;
	label$b7ac406_11_93:
	r37 = &r36;
	r24 = NULL;
	if( r11 != r24 ) goto label$b7ac406_11_98;
	r38 = false;
	goto label$b7ac406_11_99;
	label$b7ac406_11_98:
	r38 = true;
	label$b7ac406_11_99:
	r39 = &r38;
	r23 = iron_data_Geometry_getVertexStructure(r25,r27,r29,r31,r33,r35,r37,r39);
	r0->_struct = r23;
	r23 = r0->_struct;
	if( r23 == NULL ) hl_null_access();
	r17 = kha_graphics4_VertexStructure_byteSize(r23);
	r40 = (double)r17;
	r41 = 2.;
	r40 = r40 / r41;
	r17 = (int)r40;
	r0->structLength = r17;
	r20 = (String)$s_;
	r0->structStr = r20;
	r17 = 0;
	r23 = r0->_struct;
	if( r23 == NULL ) hl_null_access();
	r15 = r23->elements;
	label$b7ac406_11_116:
	if( r15 == NULL ) hl_null_access();
	r42 = r15->length;
	if( r17 >= r42 ) goto label$b7ac406_11_134;
	r42 = r15->length;
	if( ((unsigned)r17) < ((unsigned)r42) ) goto label$b7ac406_11_124;
	r43 = NULL;
	goto label$b7ac406_11_127;
	label$b7ac406_11_124:
	r45 = r15->array;
	r44 = ((vdynamic**)(r45 + 1))[r17];
	r43 = (kha__graphics4__VertexElement)r44;
	label$b7ac406_11_127:
	++r17;
	r20 = r0->structStr;
	if( r43 == NULL ) hl_null_access();
	r46 = r43->name;
	r20 = String___add__(r20,r46);
	r0->structStr = r20;
	goto label$b7ac406_11_116;
	label$b7ac406_11_134:
	return;
}

