// Generated by HLC 4.0.0 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <iron/data/TObj.h>

void iron_data_TObj_new(iron__data__TObj r0,String r1,String r2,String r3,iron__data__TTransform r4,hl__types__ArrayObj r5,hl__types__ArrayObj r6,vdynamic* r7,hl__types__ArrayObj r8,String r9,hl__types__ArrayObj r10,vdynamic* r11,hl__types__ArrayObj r12,hl__types__ArrayObj r13,hl__types__ArrayObj r14,kha__arrays__Float32ArrayPrivate r15,hl__types__ArrayObj r16,hl__types__ArrayObj r17,iron__data__TAnimation r18,iron__data__TObj r19,String r20,kha__arrays__Float32ArrayPrivate r21,kha__arrays__Float32ArrayPrivate r22,vdynamic* r23,vdynamic* r24,vdynamic* r25,vdynamic* r26,vdynamic* r27,vdynamic* r28,vdynamic* r29,String r30,String r31,vdynamic* r32) {
	r0->type = r1;
	r0->name = r2;
	r0->data_ref = r3;
	r0->transform = r4;
	r0->material_refs = r5;
	r0->particle_refs = r6;
	r0->is_particle = r7;
	r0->children = r8;
	r0->group_ref = r9;
	r0->lods = r10;
	r0->lod_material = r11;
	r0->traits = r12;
	r0->properties = r13;
	r0->constraints = r14;
	r0->dimensions = r15;
	r0->object_actions = r16;
	r0->bone_actions = r17;
	r0->anim = r18;
	r0->parent = r19;
	r0->parent_bone = r20;
	r0->parent_bone_tail = r21;
	r0->parent_bone_tail_pose = r22;
	r0->parent_bone_connected = r23;
	r0->visible = r24;
	r0->visible_mesh = r25;
	r0->visible_shadow = r26;
	r0->mobile = r27;
	r0->spawn = r28;
	r0->local_only = r29;
	r0->tilesheet_ref = r30;
	r0->tilesheet_action_ref = r31;
	r0->sampled = r32;
	return;
}

