// Generated by HLC 4.0.0 (HL v4)
#ifndef INC_iron__data__TShaderConstant
#define INC_iron__data__TShaderConstant
typedef struct _iron__data__$TShaderConstant *iron__data__$TShaderConstant;
typedef struct _iron__data__TShaderConstant *iron__data__TShaderConstant;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <kha/arrays/Float32ArrayPrivate.h>


struct _iron__data__$TShaderConstant {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
};
struct _iron__data__TShaderConstant {
	hl_type *$type;
	String name;
	String type;
	String link;
	kha__arrays__Float32ArrayPrivate vec4;
	kha__arrays__Float32ArrayPrivate vec3;
	kha__arrays__Float32ArrayPrivate vec2;
	vdynamic* _float;
	vdynamic* bool;
	vdynamic* _int;
};
#endif

