// Generated by HLC 4.0.0 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <hl/types/ArrayDynIterator.h>

void hl_types_ArrayDynIterator_new(hl__types__ArrayDynIterator r0,hl__types__ArrayBase r1) {
	int r2;
	r0->a = r1;
	if( r1 == NULL ) hl_null_access();
	r2 = r1->length;
	r0->len = r2;
	r2 = 0;
	r0->pos = r2;
	return;
}

bool hl_types_ArrayDynIterator_hasNext(hl__types__ArrayDynIterator r0) {
	bool r1;
	int r2, r3;
	r2 = r0->pos;
	r3 = r0->len;
	if( r2 < r3 ) goto label$602cf05_2_5;
	r1 = false;
	goto label$602cf05_2_6;
	label$602cf05_2_5:
	r1 = true;
	label$602cf05_2_6:
	return r1;
}

vdynamic* hl_types_ArrayDynIterator_next(hl__types__ArrayDynIterator r0) {
	hl__types__ArrayBase r2;
	vdynamic *r1;
	int r3, r4;
	r2 = r0->a;
	if( r2 == NULL ) hl_null_access();
	r3 = r0->pos;
	r4 = r3;
	++r3;
	r0->pos = r3;
	r1 = ((vdynamic* (*)(hl__types__ArrayBase,int))r2->$type->vobj_proto[0])(r2,r4);
	return r1;
}

