// Generated by HLC 4.0.0 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <kha/graphics4/IndexBuffer.h>
#include <hl/natives.h>
#include <kha/arrays/Uint32ArrayPrivate.h>
extern hl_type $t_kha_arrays_Uint32ArrayPrivate;
void kha_arrays_Uint32ArrayPrivate_new(kha__arrays__Uint32ArrayPrivate);

void kha_graphics4_IndexBuffer_new(kha__graphics4__IndexBuffer r0,int r1,int r2,bool* r3) {
	bool r4;
	vbyte *r5;
	if( r3 ) goto label$9deed45_1_3;
	r4 = false;
	goto label$9deed45_1_4;
	label$9deed45_1_3:
	r4 = *r3;
	label$9deed45_1_4:
	r0->myCount = r1;
	r5 = hl_kore_create_indexbuffer(r1);
	r0->_buffer = r5;
	return;
}

kha__arrays__Uint32ArrayPrivate kha_graphics4_IndexBuffer_lock(kha__graphics4__IndexBuffer r0) {
	kha__arrays__Uint32ArrayPrivate r3;
	vbyte *r6;
	int r1, r4, r5;
	r1 = 0;
	r3 = (kha__arrays__Uint32ArrayPrivate)hl_alloc_obj(&$t_kha_arrays_Uint32ArrayPrivate);
	kha_arrays_Uint32ArrayPrivate_new(r3);
	r3->length = r1;
	r5 = 0;
	if( r5 >= r1 ) goto label$9deed45_2_8;
	r6 = hl_kore_uint32array_alloc(r1);
	r3->self = r6;
	label$9deed45_2_8:
	r6 = r0->_buffer;
	r6 = hl_kore_indexbuffer_lock(r6);
	r3->self = r6;
	r4 = r0->myCount;
	r3->length = r4;
	return r3;
}

void kha_graphics4_IndexBuffer_unlock(kha__graphics4__IndexBuffer r0) {
	vbyte *r2;
	r2 = r0->_buffer;
	hl_kore_indexbuffer_unlock(r2);
	return;
}

