// Generated by HLC 4.0.0 (HL v4)
#ifndef INC_kha__graphics4__PipelineCache
#define INC_kha__graphics4__PipelineCache
typedef struct _kha__graphics4__$PipelineCache *kha__graphics4__$PipelineCache;
typedef struct _kha__graphics4__PipelineCache *kha__graphics4__PipelineCache;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <kha/graphics4/PipelineState.h>


struct _kha__graphics4__$PipelineCache {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
};
struct _kha__graphics4__PipelineCache {
	hl_type *$type;
	kha__graphics4__PipelineState pipeline;
	vvirtual* projectionLocation;
	vvirtual* textureLocation;
};
#endif

