// Generated by HLC 4.0.0 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <kha/graphics4/PipelineCache.h>
extern String $s_projectionMatrix;
vvirtual* kha_graphics4_PipelineState_getConstantLocation(kha__graphics4__PipelineState,String);
extern String $s_tex;
vvirtual* kha_graphics4_PipelineState_getTextureUnit(kha__graphics4__PipelineState,String);

void kha_graphics4_PipelineCache_new(kha__graphics4__PipelineCache r0,kha__graphics4__PipelineState r1) {
	String r3;
	vvirtual *r2;
	r0->pipeline = r1;
	if( r1 == NULL ) hl_null_access();
	r3 = (String)$s_projectionMatrix;
	r2 = kha_graphics4_PipelineState_getConstantLocation(r1,r3);
	r0->projectionLocation = r2;
	r3 = (String)$s_tex;
	r2 = kha_graphics4_PipelineState_getTextureUnit(r1,r3);
	r0->textureLocation = r2;
	return;
}

