// Generated by HLC 4.0.0 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <iron/object/ObjectAnimation.h>
void iron_object_Animation_new(iron__object__Animation);
#include <iron/data/TSceneFormat.h>
int String___compare(String,vdynamic*);
extern String $s_;
void iron_object_Animation_play(iron__object__Animation,String,vclosure*,double*,double*,bool*);
void iron_object_Animation_update(iron__object__Animation,float);
void iron_object_ObjectAnimation_updateObjectAnim(iron__object__ObjectAnimation);
#include <iron/data/TAnimation.h>
#include <iron/object/Transform.h>
void iron_object_ObjectAnimation_updateTransformAnim(iron__object__ObjectAnimation,iron__data__TAnimation,iron__object__Transform);
void iron_object_Transform_buildMatrix(iron__object__Transform);
#include <iron/data/TTrack.h>
#include <kha/arrays/Uint32ArrayPrivate.h>
#include <iron/math/Vec4.h>
#include <iron/math/Quat.h>
#include <kha/arrays/Float32ArrayPrivate.h>
extern hl_type $t_iron_math_Vec4;
void iron_math_Vec4_new(iron__math__Vec4,float*,float*,float*,float*);
extern hl_type $t_iron_math_Quat;
void iron_math_Quat_new(iron__math__Quat,float*,float*,float*,float*);
void iron_object_Animation_rewind(iron__object__Animation,iron__data__TTrack);
#include <hl/natives.h>
void iron_object_Transform_setRotation(iron__object__Transform,float,float,float);

void iron_object_ObjectAnimation_new(iron__object__ObjectAnimation r0,iron__object__Object r1,hl__types__ArrayObj r2) {
	bool r3;
	r0->object = r1;
	r0->oactions = r2;
	r3 = false;
	r0->isSkinned = r3;
	iron_object_Animation_new(((iron__object__Animation)r0));
	return;
}

iron__data__TObj iron_object_ObjectAnimation_getAction(iron__object__ObjectAnimation r0,String r1) {
	String r10;
	hl__types__ArrayObj r3, r6;
	iron__data__TObj r11;
	iron__data__TSceneFormat r7;
	vdynamic *r8;
	varray *r9;
	int r2, r4, r5;
	r2 = 0;
	r3 = r0->oactions;
	label$cd1e1cd_2_2:
	if( r3 == NULL ) hl_null_access();
	r5 = r3->length;
	if( r2 >= r5 ) goto label$cd1e1cd_2_41;
	r5 = r3->length;
	if( ((unsigned)r2) < ((unsigned)r5) ) goto label$cd1e1cd_2_10;
	r7 = NULL;
	goto label$cd1e1cd_2_13;
	label$cd1e1cd_2_10:
	r9 = r3->array;
	r8 = ((vdynamic**)(r9 + 1))[r2];
	r7 = (iron__data__TSceneFormat)r8;
	label$cd1e1cd_2_13:
	++r2;
	if( !r7 ) goto label$cd1e1cd_2_40;
	if( r7 == NULL ) hl_null_access();
	r6 = r7->objects;
	if( r6 == NULL ) hl_null_access();
	r4 = 0;
	r5 = r6->length;
	if( ((unsigned)r4) < ((unsigned)r5) ) goto label$cd1e1cd_2_23;
	r11 = NULL;
	goto label$cd1e1cd_2_26;
	label$cd1e1cd_2_23:
	r9 = r6->array;
	r8 = ((vdynamic**)(r9 + 1))[r4];
	r11 = (iron__data__TObj)r8;
	label$cd1e1cd_2_26:
	if( r11 == NULL ) hl_null_access();
	r10 = r11->name;
	if( r10 != r1 && (!r10 || !r1 || String___compare(r10,(vdynamic*)r1) != 0) ) goto label$cd1e1cd_2_40;
	r6 = r7->objects;
	if( r6 == NULL ) hl_null_access();
	r4 = 0;
	r5 = r6->length;
	if( ((unsigned)r4) < ((unsigned)r5) ) goto label$cd1e1cd_2_36;
	r11 = NULL;
	goto label$cd1e1cd_2_39;
	label$cd1e1cd_2_36:
	r9 = r6->array;
	r8 = ((vdynamic**)(r9 + 1))[r4];
	r11 = (iron__data__TObj)r8;
	label$cd1e1cd_2_39:
	return r11;
	label$cd1e1cd_2_40:
	goto label$cd1e1cd_2_2;
	label$cd1e1cd_2_41:
	r11 = NULL;
	return r11;
}

void iron_object_ObjectAnimation_play(iron__object__ObjectAnimation r0,String r1,vclosure* r2,double* r3,double* r4,bool* r5) {
	String r6, r14;
	hl__types__ArrayObj r15;
	bool r9, r13, r22;
	iron__data__TObj r21;
	iron__data__TSceneFormat r18;
	double r7, r8, r11, r12;
	vdynamic *r19, *r23;
	varray *r20;
	int r16, r17;
	if( r1 ) goto label$cd1e1cd_3_3;
	r6 = (String)$s_;
	r1 = r6;
	label$cd1e1cd_3_3:
	if( r3 ) goto label$cd1e1cd_3_6;
	r7 = 0.;
	goto label$cd1e1cd_3_7;
	label$cd1e1cd_3_6:
	r7 = *r3;
	label$cd1e1cd_3_7:
	if( r4 ) goto label$cd1e1cd_3_10;
	r8 = 1.;
	goto label$cd1e1cd_3_11;
	label$cd1e1cd_3_10:
	r8 = *r4;
	label$cd1e1cd_3_11:
	if( r5 ) goto label$cd1e1cd_3_14;
	r9 = true;
	goto label$cd1e1cd_3_15;
	label$cd1e1cd_3_14:
	r9 = *r5;
	label$cd1e1cd_3_15:
	r11 = r7;
	r3 = &r11;
	r12 = r8;
	r4 = &r12;
	r13 = r9;
	r5 = &r13;
	iron_object_Animation_play(((iron__object__Animation)r0),r1,r2,r3,r4,r5);
	r6 = r0->action;
	r14 = (String)$s_;
	if( r6 != r14 && (!r6 || !r14 || String___compare(r6,(vdynamic*)r14) != 0) ) goto label$cd1e1cd_3_60;
	r15 = r0->oactions;
	if( r15 == NULL ) hl_null_access();
	r16 = 0;
	r17 = r15->length;
	if( ((unsigned)r16) < ((unsigned)r17) ) goto label$cd1e1cd_3_32;
	r18 = NULL;
	goto label$cd1e1cd_3_35;
	label$cd1e1cd_3_32:
	r20 = r15->array;
	r19 = ((vdynamic**)(r20 + 1))[r16];
	r18 = (iron__data__TSceneFormat)r19;
	label$cd1e1cd_3_35:
	if( !r18 ) goto label$cd1e1cd_3_60;
	r15 = r0->oactions;
	if( r15 == NULL ) hl_null_access();
	r16 = 0;
	r17 = r15->length;
	if( ((unsigned)r16) < ((unsigned)r17) ) goto label$cd1e1cd_3_43;
	r18 = NULL;
	goto label$cd1e1cd_3_46;
	label$cd1e1cd_3_43:
	r20 = r15->array;
	r19 = ((vdynamic**)(r20 + 1))[r16];
	r18 = (iron__data__TSceneFormat)r19;
	label$cd1e1cd_3_46:
	if( r18 == NULL ) hl_null_access();
	r15 = r18->objects;
	if( r15 == NULL ) hl_null_access();
	r16 = 0;
	r17 = r15->length;
	if( ((unsigned)r16) < ((unsigned)r17) ) goto label$cd1e1cd_3_54;
	r21 = NULL;
	goto label$cd1e1cd_3_57;
	label$cd1e1cd_3_54:
	r20 = r15->array;
	r19 = ((vdynamic**)(r20 + 1))[r16];
	r21 = (iron__data__TObj)r19;
	label$cd1e1cd_3_57:
	if( r21 == NULL ) hl_null_access();
	r6 = r21->name;
	r0->action = r6;
	label$cd1e1cd_3_60:
	r6 = r0->action;
	r21 = iron_object_ObjectAnimation_getAction(r0,r6);
	r0->oaction = r21;
	r21 = r0->oaction;
	if( !r21 ) goto label$cd1e1cd_3_78;
	r21 = r0->oaction;
	if( r21 == NULL ) hl_null_access();
	r23 = r21->sampled;
	if( !r23 ) goto label$cd1e1cd_3_76;
	r21 = r0->oaction;
	if( r21 == NULL ) hl_null_access();
	r23 = r21->sampled;
	r22 = r23 ? r23->v.b : 0;
	if( !r22 ) goto label$cd1e1cd_3_76;
	r22 = true;
	goto label$cd1e1cd_3_77;
	label$cd1e1cd_3_76:
	r22 = false;
	label$cd1e1cd_3_77:
	r0->isSampled = r22;
	label$cd1e1cd_3_78:
	return;
}

void iron_object_ObjectAnimation_update(iron__object__ObjectAnimation r0,float r1) {
	bool r3;
	iron__data__TObj r5;
	iron__object__Object r4;
	r4 = r0->object;
	if( r4 == NULL ) hl_null_access();
	r3 = r4->visible;
	if( !r3 ) goto label$cd1e1cd_4_10;
	r4 = r0->object;
	if( r4 == NULL ) hl_null_access();
	r3 = r4->culled;
	if( r3 ) goto label$cd1e1cd_4_10;
	r5 = r0->oaction;
	if( r5 ) goto label$cd1e1cd_4_11;
	label$cd1e1cd_4_10:
	return;
	label$cd1e1cd_4_11:
	iron_object_Animation_update(((iron__object__Animation)r0),r1);
	r3 = r0->paused;
	if( !r3 ) goto label$cd1e1cd_4_15;
	return;
	label$cd1e1cd_4_15:
	r3 = r0->isSkinned;
	if( r3 ) goto label$cd1e1cd_4_18;
	iron_object_ObjectAnimation_updateObjectAnim(r0);
	label$cd1e1cd_4_18:
	return;
}

void iron_object_ObjectAnimation_updateObjectAnim(iron__object__ObjectAnimation r0) {
	iron__data__TAnimation r2;
	iron__data__TObj r3;
	iron__object__Transform r4;
	iron__object__Object r5;
	r3 = r0->oaction;
	if( r3 == NULL ) hl_null_access();
	r2 = r3->anim;
	r5 = r0->object;
	if( r5 == NULL ) hl_null_access();
	r4 = r5->transform;
	iron_object_ObjectAnimation_updateTransformAnim(r0,r2,r4);
	r5 = r0->object;
	if( r5 == NULL ) hl_null_access();
	r4 = r5->transform;
	if( r4 == NULL ) hl_null_access();
	iron_object_Transform_buildMatrix(r4);
	return;
}

bool iron_object_ObjectAnimation_isTrackEnd(iron__object__ObjectAnimation r0,iron__data__TTrack r1) {
	bool r5;
	float r2, r4;
	kha__arrays__Uint32ArrayPrivate r7;
	int r3, r6, r8;
	r2 = r0->speed;
	r3 = 0;
	r4 = (float)r3;
	if( !(r4 < r2) ) goto label$cd1e1cd_6_16;
	r3 = r0->frameIndex;
	if( r1 == NULL ) hl_null_access();
	r7 = r1->frames;
	if( r7 == NULL ) hl_null_access();
	r6 = r7->length;
	r8 = 2;
	r6 = r6 - r8;
	if( r3 >= r6 ) goto label$cd1e1cd_6_14;
	r5 = false;
	goto label$cd1e1cd_6_15;
	label$cd1e1cd_6_14:
	r5 = true;
	label$cd1e1cd_6_15:
	return r5;
	label$cd1e1cd_6_16:
	r3 = r0->frameIndex;
	r6 = 0;
	if( r3 <= r6 ) goto label$cd1e1cd_6_21;
	r5 = false;
	goto label$cd1e1cd_6_22;
	label$cd1e1cd_6_21:
	r5 = true;
	label$cd1e1cd_6_22:
	return r5;
}

void iron_object_ObjectAnimation_updateTransformAnim(iron__object__ObjectAnimation r0,iron__data__TAnimation r1,iron__object__Transform r2) {
	String r38;
	hl__types__ArrayObj r19;
	iron__math__Quat r17;
	iron__data__TTrack r22;
	bool r11;
	iron__math__Vec4 r12;
	kha__arrays__Float32ArrayPrivate r31;
	float r5, r8, r9, r24, r29, r32, r33, r34, r40, r41;
	vclosure *r30;
	kha__arrays__Uint32ArrayPrivate r25;
	double r18, r35, r36, r37;
	vdynamic *r4, *r6, *r10;
	vbyte *r28, *r39;
	varray *r23;
	float *r13, *r14, *r15, *r16;
	int r7, r20, r21, r26, r27;
	if( r1 ) goto label$cd1e1cd_7_2;
	return;
	label$cd1e1cd_7_2:
	if( r1 == NULL ) hl_null_access();
	r6 = r1->end;
	r7 = r6 ? r6->v.i : 0;
	r5 = (float)r7;
	r8 = r0->frameTime;
	r5 = r5 * r8;
	r6 = r1->begin;
	r7 = r6 ? r6->v.i : 0;
	r8 = (float)r7;
	r9 = r0->frameTime;
	r8 = r8 * r9;
	r5 = r5 - r8;
	r10 = r1->has_delta;
	r11 = r10 ? r10->v.b : 0;
	if( !r11 ) goto label$cd1e1cd_7_74;
	if( r2 == NULL ) hl_null_access();
	r12 = r2->dloc;
	if( r12 ) goto label$cd1e1cd_7_41;
	r12 = (iron__math__Vec4)hl_alloc_obj(&$t_iron_math_Vec4);
	r13 = NULL;
	r14 = NULL;
	r15 = NULL;
	r16 = NULL;
	iron_math_Vec4_new(r12,r13,r14,r15,r16);
	r2->dloc = r12;
	r17 = (iron__math__Quat)hl_alloc_obj(&$t_iron_math_Quat);
	r13 = NULL;
	r14 = NULL;
	r15 = NULL;
	r16 = NULL;
	iron_math_Quat_new(r17,r13,r14,r15,r16);
	r2->drot = r17;
	r12 = (iron__math__Vec4)hl_alloc_obj(&$t_iron_math_Vec4);
	r13 = NULL;
	r14 = NULL;
	r15 = NULL;
	r16 = NULL;
	iron_math_Vec4_new(r12,r13,r14,r15,r16);
	r2->dscale = r12;
	label$cd1e1cd_7_41:
	r12 = r2->dloc;
	if( r12 == NULL ) hl_null_access();
	r7 = 0;
	r8 = (float)r7;
	r12->x = r8;
	r7 = 0;
	r8 = (float)r7;
	r12->y = r8;
	r7 = 0;
	r8 = (float)r7;
	r12->z = r8;
	r18 = 1.;
	r8 = (float)r18;
	r12->w = r8;
	r12 = r2->dscale;
	if( r12 == NULL ) hl_null_access();
	r7 = 0;
	r8 = (float)r7;
	r12->x = r8;
	r7 = 0;
	r8 = (float)r7;
	r12->y = r8;
	r7 = 0;
	r8 = (float)r7;
	r12->z = r8;
	r18 = 1.;
	r8 = (float)r18;
	r12->w = r8;
	r18 = 0.;
	r8 = (float)r18;
	r2->_deulerZ = r8;
	r2->_deulerY = r8;
	r2->_deulerX = r8;
	label$cd1e1cd_7_74:
	r7 = 0;
	r19 = r1->tracks;
	label$cd1e1cd_7_76:
	if( r19 == NULL ) hl_null_access();
	r21 = r19->length;
	if( r7 >= r21 ) goto label$cd1e1cd_7_579;
	r21 = r19->length;
	if( ((unsigned)r7) < ((unsigned)r21) ) goto label$cd1e1cd_7_84;
	r22 = NULL;
	goto label$cd1e1cd_7_87;
	label$cd1e1cd_7_84:
	r23 = r19->array;
	r4 = ((vdynamic**)(r23 + 1))[r7];
	r22 = (iron__data__TTrack)r4;
	label$cd1e1cd_7_87:
	++r7;
	r20 = r0->frameIndex;
	r21 = -1;
	if( r20 != r21 ) goto label$cd1e1cd_7_92;
	iron_object_Animation_rewind(((iron__object__Animation)r0),r22);
	label$cd1e1cd_7_92:
	r8 = r0->speed;
	r20 = 0;
	r9 = (float)r20;
	if( !(r9 < r8) ) goto label$cd1e1cd_7_98;
	r20 = 1;
	goto label$cd1e1cd_7_99;
	label$cd1e1cd_7_98:
	r20 = -1;
	label$cd1e1cd_7_99:
	r8 = r0->time;
	if( r1 == NULL ) hl_null_access();
	r6 = r1->begin;
	r21 = r6 ? r6->v.i : 0;
	r9 = (float)r21;
	r24 = r0->frameTime;
	r9 = r9 * r24;
	r8 = r8 + r9;
	label$cd1e1cd_7_107:
	r11 = true;
	if( !r11 ) goto label$cd1e1cd_7_157;
	if( r22 == NULL ) hl_null_access();
	r25 = r22->frames;
	r9 = r0->speed;
	r21 = 0;
	r24 = (float)r21;
	if( !(r24 < r9) ) goto label$cd1e1cd_7_135;
	r21 = r0->frameIndex;
	if( r25 == NULL ) hl_null_access();
	r26 = r25->length;
	r27 = 2;
	r26 = r26 - r27;
	if( r21 >= r26 ) goto label$cd1e1cd_7_133;
	r28 = r25->self;
	r21 = r0->frameIndex;
	r26 = 1;
	r21 = r21 + r26;
	r21 = hl_kore_uint32array_get(r28,r21);
	r24 = (float)r21;
	r29 = r0->frameTime;
	r24 = r24 * r29;
	if( !(r24 < r8) ) goto label$cd1e1cd_7_133;
	r11 = true;
	goto label$cd1e1cd_7_134;
	label$cd1e1cd_7_133:
	r11 = false;
	label$cd1e1cd_7_134:
	goto label$cd1e1cd_7_151;
	label$cd1e1cd_7_135:
	r21 = r0->frameIndex;
	r26 = 1;
	if( r26 >= r21 ) goto label$cd1e1cd_7_150;
	if( r25 == NULL ) hl_null_access();
	r28 = r25->self;
	r21 = r0->frameIndex;
	r26 = 1;
	r21 = r21 - r26;
	r21 = hl_kore_uint32array_get(r28,r21);
	r24 = (float)r21;
	r29 = r0->frameTime;
	r24 = r24 * r29;
	if( !(r24 < r8) ) goto label$cd1e1cd_7_150;
	r11 = true;
	goto label$cd1e1cd_7_151;
	label$cd1e1cd_7_150:
	r11 = false;
	label$cd1e1cd_7_151:
	if( r11 ) goto label$cd1e1cd_7_153;
	goto label$cd1e1cd_7_157;
	label$cd1e1cd_7_153:
	r21 = r0->frameIndex;
	r21 = r21 + r20;
	r0->frameIndex = r21;
	goto label$cd1e1cd_7_107;
	label$cd1e1cd_7_157:
	r21 = r0->frameIndex;
	if( r22 == NULL ) hl_null_access();
	r25 = r22->frames;
	if( r25 == NULL ) hl_null_access();
	r26 = r25->length;
	if( r21 < r26 ) goto label$cd1e1cd_7_164;
	goto label$cd1e1cd_7_76;
	label$cd1e1cd_7_164:
	r9 = r0->time;
	if( !(r5 < r9) ) goto label$cd1e1cd_7_181;
	r30 = r0->onComplete;
	if( !r30 ) goto label$cd1e1cd_7_171;
	r30 = r0->onComplete;
	if( r30 == NULL ) hl_null_access();
	r30->hasValue ? ((void (*)(vdynamic*))r30->fun)((vdynamic*)r30->value) : ((void (*)(void))r30->fun)();
	label$cd1e1cd_7_171:
	r11 = r0->loop;
	if( !r11 ) goto label$cd1e1cd_7_175;
	iron_object_Animation_rewind(((iron__object__Animation)r0),r22);
	goto label$cd1e1cd_7_180;
	label$cd1e1cd_7_175:
	r21 = r0->frameIndex;
	r21 = r21 - r20;
	r0->frameIndex = r21;
	r11 = true;
	r0->paused = r11;
	label$cd1e1cd_7_180:
	return;
	label$cd1e1cd_7_181:
	r21 = r0->frameIndex;
	r25 = r22->frames;
	if( r25 == NULL ) hl_null_access();
	r28 = r25->self;
	r26 = hl_kore_uint32array_get(r28,r21);
	r9 = (float)r26;
	r24 = r0->frameTime;
	r9 = r9 * r24;
	r25 = r22->frames;
	if( r25 == NULL ) hl_null_access();
	r28 = r25->self;
	r26 = r21 + r20;
	r26 = hl_kore_uint32array_get(r28,r26);
	r24 = (float)r26;
	r29 = r0->frameTime;
	r24 = r24 * r29;
	r31 = r22->values;
	if( r31 == NULL ) hl_null_access();
	r28 = r31->self;
	r29 = hl_kore_float32array_get(r28,r21);
	r31 = r22->values;
	if( r31 == NULL ) hl_null_access();
	r28 = r31->self;
	r26 = r21 + r20;
	r32 = hl_kore_float32array_get(r28,r26);
	r33 = r8 - r9;
	r18 = (double)r33;
	r33 = r24 - r9;
	r35 = (double)r33;
	r18 = r18 / r35;
	r35 = 1.;
	r35 = r35 - r18;
	r36 = (double)r29;
	r35 = r35 * r36;
	r37 = (double)r32;
	r36 = r18 * r37;
	r35 = r35 + r36;
	r33 = (float)r35;
	r38 = r22->target;
	if( !r38 ) goto label$cd1e1cd_7_229;
	r26 = r38->length;
	r27 = 6;
	if( r26 != r27 ) goto label$cd1e1cd_7_229;
	r28 = r38->bytes;
	r39 = (vbyte*)USTR("dqwrot");
	r26 = hl_string_compare(r28,r39,r26);
	r27 = 0;
	if( r26 == r27 ) goto label$cd1e1cd_7_455;
	label$cd1e1cd_7_229:
	if( !r38 ) goto label$cd1e1cd_7_238;
	r26 = r38->length;
	r27 = 6;
	if( r26 != r27 ) goto label$cd1e1cd_7_238;
	r28 = r38->bytes;
	r39 = (vbyte*)USTR("dqxrot");
	r26 = hl_string_compare(r28,r39,r26);
	r27 = 0;
	if( r26 == r27 ) goto label$cd1e1cd_7_460;
	label$cd1e1cd_7_238:
	if( !r38 ) goto label$cd1e1cd_7_247;
	r26 = r38->length;
	r27 = 6;
	if( r26 != r27 ) goto label$cd1e1cd_7_247;
	r28 = r38->bytes;
	r39 = (vbyte*)USTR("dqyrot");
	r26 = hl_string_compare(r28,r39,r26);
	r27 = 0;
	if( r26 == r27 ) goto label$cd1e1cd_7_465;
	label$cd1e1cd_7_247:
	if( !r38 ) goto label$cd1e1cd_7_256;
	r26 = r38->length;
	r27 = 6;
	if( r26 != r27 ) goto label$cd1e1cd_7_256;
	r28 = r38->bytes;
	r39 = (vbyte*)USTR("dqzrot");
	r26 = hl_string_compare(r28,r39,r26);
	r27 = 0;
	if( r26 == r27 ) goto label$cd1e1cd_7_470;
	label$cd1e1cd_7_256:
	if( !r38 ) goto label$cd1e1cd_7_265;
	r26 = r38->length;
	r27 = 5;
	if( r26 != r27 ) goto label$cd1e1cd_7_265;
	r28 = r38->bytes;
	r39 = (vbyte*)USTR("dxloc");
	r26 = hl_string_compare(r28,r39,r26);
	r27 = 0;
	if( r26 == r27 ) goto label$cd1e1cd_7_475;
	label$cd1e1cd_7_265:
	if( !r38 ) goto label$cd1e1cd_7_274;
	r26 = r38->length;
	r27 = 5;
	if( r26 != r27 ) goto label$cd1e1cd_7_274;
	r28 = r38->bytes;
	r39 = (vbyte*)USTR("dxrot");
	r26 = hl_string_compare(r28,r39,r26);
	r27 = 0;
	if( r26 == r27 ) goto label$cd1e1cd_7_480;
	label$cd1e1cd_7_274:
	if( !r38 ) goto label$cd1e1cd_7_283;
	r26 = r38->length;
	r27 = 5;
	if( r26 != r27 ) goto label$cd1e1cd_7_283;
	r28 = r38->bytes;
	r39 = (vbyte*)USTR("dxscl");
	r26 = hl_string_compare(r28,r39,r26);
	r27 = 0;
	if( r26 == r27 ) goto label$cd1e1cd_7_483;
	label$cd1e1cd_7_283:
	if( !r38 ) goto label$cd1e1cd_7_292;
	r26 = r38->length;
	r27 = 5;
	if( r26 != r27 ) goto label$cd1e1cd_7_292;
	r28 = r38->bytes;
	r39 = (vbyte*)USTR("dyloc");
	r26 = hl_string_compare(r28,r39,r26);
	r27 = 0;
	if( r26 == r27 ) goto label$cd1e1cd_7_488;
	label$cd1e1cd_7_292:
	if( !r38 ) goto label$cd1e1cd_7_301;
	r26 = r38->length;
	r27 = 5;
	if( r26 != r27 ) goto label$cd1e1cd_7_301;
	r28 = r38->bytes;
	r39 = (vbyte*)USTR("dyrot");
	r26 = hl_string_compare(r28,r39,r26);
	r27 = 0;
	if( r26 == r27 ) goto label$cd1e1cd_7_493;
	label$cd1e1cd_7_301:
	if( !r38 ) goto label$cd1e1cd_7_310;
	r26 = r38->length;
	r27 = 5;
	if( r26 != r27 ) goto label$cd1e1cd_7_310;
	r28 = r38->bytes;
	r39 = (vbyte*)USTR("dyscl");
	r26 = hl_string_compare(r28,r39,r26);
	r27 = 0;
	if( r26 == r27 ) goto label$cd1e1cd_7_496;
	label$cd1e1cd_7_310:
	if( !r38 ) goto label$cd1e1cd_7_319;
	r26 = r38->length;
	r27 = 5;
	if( r26 != r27 ) goto label$cd1e1cd_7_319;
	r28 = r38->bytes;
	r39 = (vbyte*)USTR("dzloc");
	r26 = hl_string_compare(r28,r39,r26);
	r27 = 0;
	if( r26 == r27 ) goto label$cd1e1cd_7_501;
	label$cd1e1cd_7_319:
	if( !r38 ) goto label$cd1e1cd_7_328;
	r26 = r38->length;
	r27 = 5;
	if( r26 != r27 ) goto label$cd1e1cd_7_328;
	r28 = r38->bytes;
	r39 = (vbyte*)USTR("dzrot");
	r26 = hl_string_compare(r28,r39,r26);
	r27 = 0;
	if( r26 == r27 ) goto label$cd1e1cd_7_506;
	label$cd1e1cd_7_328:
	if( !r38 ) goto label$cd1e1cd_7_337;
	r26 = r38->length;
	r27 = 5;
	if( r26 != r27 ) goto label$cd1e1cd_7_337;
	r28 = r38->bytes;
	r39 = (vbyte*)USTR("dzscl");
	r26 = hl_string_compare(r28,r39,r26);
	r27 = 0;
	if( r26 == r27 ) goto label$cd1e1cd_7_509;
	label$cd1e1cd_7_337:
	if( !r38 ) goto label$cd1e1cd_7_346;
	r26 = r38->length;
	r27 = 5;
	if( r26 != r27 ) goto label$cd1e1cd_7_346;
	r28 = r38->bytes;
	r39 = (vbyte*)USTR("qwrot");
	r26 = hl_string_compare(r28,r39,r26);
	r27 = 0;
	if( r26 == r27 ) goto label$cd1e1cd_7_514;
	label$cd1e1cd_7_346:
	if( !r38 ) goto label$cd1e1cd_7_355;
	r26 = r38->length;
	r27 = 5;
	if( r26 != r27 ) goto label$cd1e1cd_7_355;
	r28 = r38->bytes;
	r39 = (vbyte*)USTR("qxrot");
	r26 = hl_string_compare(r28,r39,r26);
	r27 = 0;
	if( r26 == r27 ) goto label$cd1e1cd_7_519;
	label$cd1e1cd_7_355:
	if( !r38 ) goto label$cd1e1cd_7_364;
	r26 = r38->length;
	r27 = 5;
	if( r26 != r27 ) goto label$cd1e1cd_7_364;
	r28 = r38->bytes;
	r39 = (vbyte*)USTR("qyrot");
	r26 = hl_string_compare(r28,r39,r26);
	r27 = 0;
	if( r26 == r27 ) goto label$cd1e1cd_7_524;
	label$cd1e1cd_7_364:
	if( !r38 ) goto label$cd1e1cd_7_373;
	r26 = r38->length;
	r27 = 5;
	if( r26 != r27 ) goto label$cd1e1cd_7_373;
	r28 = r38->bytes;
	r39 = (vbyte*)USTR("qzrot");
	r26 = hl_string_compare(r28,r39,r26);
	r27 = 0;
	if( r26 == r27 ) goto label$cd1e1cd_7_529;
	label$cd1e1cd_7_373:
	if( !r38 ) goto label$cd1e1cd_7_382;
	r26 = r38->length;
	r27 = 4;
	if( r26 != r27 ) goto label$cd1e1cd_7_382;
	r28 = r38->bytes;
	r39 = (vbyte*)USTR("xloc");
	r26 = hl_string_compare(r28,r39,r26);
	r27 = 0;
	if( r26 == r27 ) goto label$cd1e1cd_7_534;
	label$cd1e1cd_7_382:
	if( !r38 ) goto label$cd1e1cd_7_391;
	r26 = r38->length;
	r27 = 4;
	if( r26 != r27 ) goto label$cd1e1cd_7_391;
	r28 = r38->bytes;
	r39 = (vbyte*)USTR("xrot");
	r26 = hl_string_compare(r28,r39,r26);
	r27 = 0;
	if( r26 == r27 ) goto label$cd1e1cd_7_539;
	label$cd1e1cd_7_391:
	if( !r38 ) goto label$cd1e1cd_7_400;
	r26 = r38->length;
	r27 = 4;
	if( r26 != r27 ) goto label$cd1e1cd_7_400;
	r28 = r38->bytes;
	r39 = (vbyte*)USTR("xscl");
	r26 = hl_string_compare(r28,r39,r26);
	r27 = 0;
	if( r26 == r27 ) goto label$cd1e1cd_7_544;
	label$cd1e1cd_7_400:
	if( !r38 ) goto label$cd1e1cd_7_409;
	r26 = r38->length;
	r27 = 4;
	if( r26 != r27 ) goto label$cd1e1cd_7_409;
	r28 = r38->bytes;
	r39 = (vbyte*)USTR("yloc");
	r26 = hl_string_compare(r28,r39,r26);
	r27 = 0;
	if( r26 == r27 ) goto label$cd1e1cd_7_549;
	label$cd1e1cd_7_409:
	if( !r38 ) goto label$cd1e1cd_7_418;
	r26 = r38->length;
	r27 = 4;
	if( r26 != r27 ) goto label$cd1e1cd_7_418;
	r28 = r38->bytes;
	r39 = (vbyte*)USTR("yrot");
	r26 = hl_string_compare(r28,r39,r26);
	r27 = 0;
	if( r26 == r27 ) goto label$cd1e1cd_7_554;
	label$cd1e1cd_7_418:
	if( !r38 ) goto label$cd1e1cd_7_427;
	r26 = r38->length;
	r27 = 4;
	if( r26 != r27 ) goto label$cd1e1cd_7_427;
	r28 = r38->bytes;
	r39 = (vbyte*)USTR("yscl");
	r26 = hl_string_compare(r28,r39,r26);
	r27 = 0;
	if( r26 == r27 ) goto label$cd1e1cd_7_559;
	label$cd1e1cd_7_427:
	if( !r38 ) goto label$cd1e1cd_7_436;
	r26 = r38->length;
	r27 = 4;
	if( r26 != r27 ) goto label$cd1e1cd_7_436;
	r28 = r38->bytes;
	r39 = (vbyte*)USTR("zloc");
	r26 = hl_string_compare(r28,r39,r26);
	r27 = 0;
	if( r26 == r27 ) goto label$cd1e1cd_7_564;
	label$cd1e1cd_7_436:
	if( !r38 ) goto label$cd1e1cd_7_445;
	r26 = r38->length;
	r27 = 4;
	if( r26 != r27 ) goto label$cd1e1cd_7_445;
	r28 = r38->bytes;
	r39 = (vbyte*)USTR("zrot");
	r26 = hl_string_compare(r28,r39,r26);
	r27 = 0;
	if( r26 == r27 ) goto label$cd1e1cd_7_569;
	label$cd1e1cd_7_445:
	if( !r38 ) goto label$cd1e1cd_7_454;
	r26 = r38->length;
	r27 = 4;
	if( r26 != r27 ) goto label$cd1e1cd_7_454;
	r28 = r38->bytes;
	r39 = (vbyte*)USTR("zscl");
	r26 = hl_string_compare(r28,r39,r26);
	r27 = 0;
	if( r26 == r27 ) goto label$cd1e1cd_7_574;
	label$cd1e1cd_7_454:
	goto label$cd1e1cd_7_578;
	label$cd1e1cd_7_455:
	if( r2 == NULL ) hl_null_access();
	r17 = r2->drot;
	if( r17 == NULL ) hl_null_access();
	r17->w = r33;
	goto label$cd1e1cd_7_578;
	label$cd1e1cd_7_460:
	if( r2 == NULL ) hl_null_access();
	r17 = r2->drot;
	if( r17 == NULL ) hl_null_access();
	r17->x = r33;
	goto label$cd1e1cd_7_578;
	label$cd1e1cd_7_465:
	if( r2 == NULL ) hl_null_access();
	r17 = r2->drot;
	if( r17 == NULL ) hl_null_access();
	r17->y = r33;
	goto label$cd1e1cd_7_578;
	label$cd1e1cd_7_470:
	if( r2 == NULL ) hl_null_access();
	r17 = r2->drot;
	if( r17 == NULL ) hl_null_access();
	r17->z = r33;
	goto label$cd1e1cd_7_578;
	label$cd1e1cd_7_475:
	if( r2 == NULL ) hl_null_access();
	r12 = r2->dloc;
	if( r12 == NULL ) hl_null_access();
	r12->x = r33;
	goto label$cd1e1cd_7_578;
	label$cd1e1cd_7_480:
	if( r2 == NULL ) hl_null_access();
	r2->_deulerX = r33;
	goto label$cd1e1cd_7_578;
	label$cd1e1cd_7_483:
	if( r2 == NULL ) hl_null_access();
	r12 = r2->dscale;
	if( r12 == NULL ) hl_null_access();
	r12->x = r33;
	goto label$cd1e1cd_7_578;
	label$cd1e1cd_7_488:
	if( r2 == NULL ) hl_null_access();
	r12 = r2->dloc;
	if( r12 == NULL ) hl_null_access();
	r12->y = r33;
	goto label$cd1e1cd_7_578;
	label$cd1e1cd_7_493:
	if( r2 == NULL ) hl_null_access();
	r2->_deulerY = r33;
	goto label$cd1e1cd_7_578;
	label$cd1e1cd_7_496:
	if( r2 == NULL ) hl_null_access();
	r12 = r2->dscale;
	if( r12 == NULL ) hl_null_access();
	r12->y = r33;
	goto label$cd1e1cd_7_578;
	label$cd1e1cd_7_501:
	if( r2 == NULL ) hl_null_access();
	r12 = r2->dloc;
	if( r12 == NULL ) hl_null_access();
	r12->z = r33;
	goto label$cd1e1cd_7_578;
	label$cd1e1cd_7_506:
	if( r2 == NULL ) hl_null_access();
	r2->_deulerZ = r33;
	goto label$cd1e1cd_7_578;
	label$cd1e1cd_7_509:
	if( r2 == NULL ) hl_null_access();
	r12 = r2->dscale;
	if( r12 == NULL ) hl_null_access();
	r12->z = r33;
	goto label$cd1e1cd_7_578;
	label$cd1e1cd_7_514:
	if( r2 == NULL ) hl_null_access();
	r17 = r2->rot;
	if( r17 == NULL ) hl_null_access();
	r17->w = r33;
	goto label$cd1e1cd_7_578;
	label$cd1e1cd_7_519:
	if( r2 == NULL ) hl_null_access();
	r17 = r2->rot;
	if( r17 == NULL ) hl_null_access();
	r17->x = r33;
	goto label$cd1e1cd_7_578;
	label$cd1e1cd_7_524:
	if( r2 == NULL ) hl_null_access();
	r17 = r2->rot;
	if( r17 == NULL ) hl_null_access();
	r17->y = r33;
	goto label$cd1e1cd_7_578;
	label$cd1e1cd_7_529:
	if( r2 == NULL ) hl_null_access();
	r17 = r2->rot;
	if( r17 == NULL ) hl_null_access();
	r17->z = r33;
	goto label$cd1e1cd_7_578;
	label$cd1e1cd_7_534:
	if( r2 == NULL ) hl_null_access();
	r12 = r2->loc;
	if( r12 == NULL ) hl_null_access();
	r12->x = r33;
	goto label$cd1e1cd_7_578;
	label$cd1e1cd_7_539:
	if( r2 == NULL ) hl_null_access();
	r40 = r2->_eulerY;
	r41 = r2->_eulerZ;
	iron_object_Transform_setRotation(r2,r33,r40,r41);
	goto label$cd1e1cd_7_578;
	label$cd1e1cd_7_544:
	if( r2 == NULL ) hl_null_access();
	r12 = r2->scale;
	if( r12 == NULL ) hl_null_access();
	r12->x = r33;
	goto label$cd1e1cd_7_578;
	label$cd1e1cd_7_549:
	if( r2 == NULL ) hl_null_access();
	r12 = r2->loc;
	if( r12 == NULL ) hl_null_access();
	r12->y = r33;
	goto label$cd1e1cd_7_578;
	label$cd1e1cd_7_554:
	if( r2 == NULL ) hl_null_access();
	r34 = r2->_eulerX;
	r41 = r2->_eulerZ;
	iron_object_Transform_setRotation(r2,r34,r33,r41);
	goto label$cd1e1cd_7_578;
	label$cd1e1cd_7_559:
	if( r2 == NULL ) hl_null_access();
	r12 = r2->scale;
	if( r12 == NULL ) hl_null_access();
	r12->y = r33;
	goto label$cd1e1cd_7_578;
	label$cd1e1cd_7_564:
	if( r2 == NULL ) hl_null_access();
	r12 = r2->loc;
	if( r12 == NULL ) hl_null_access();
	r12->z = r33;
	goto label$cd1e1cd_7_578;
	label$cd1e1cd_7_569:
	if( r2 == NULL ) hl_null_access();
	r34 = r2->_eulerX;
	r40 = r2->_eulerY;
	iron_object_Transform_setRotation(r2,r34,r40,r33);
	goto label$cd1e1cd_7_578;
	label$cd1e1cd_7_574:
	if( r2 == NULL ) hl_null_access();
	r12 = r2->scale;
	if( r12 == NULL ) hl_null_access();
	r12->z = r33;
	label$cd1e1cd_7_578:
	goto label$cd1e1cd_7_76;
	label$cd1e1cd_7_579:
	return;
}

