// Generated by HLC 4.0.0 (HL v4)
#ifndef INC_kha__audio2__AudioChannel
#define INC_kha__audio2__AudioChannel
typedef struct _kha__audio2__$AudioChannel *kha__audio2__$AudioChannel;
typedef struct _kha__audio2__AudioChannel *kha__audio2__AudioChannel;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <kha/arrays/Float32ArrayPrivate.h>


struct _kha__audio2__$AudioChannel {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
};
struct _kha__audio2__AudioChannel {
	hl_type *$type;
	kha__arrays__Float32ArrayPrivate data;
	double myVolume;
	int myPosition;
	bool paused;
	bool stopped;
	bool looping;
	bool finished;
	vvirtual* $_f7;
};
#endif

