// Generated by HLC 4.0.0 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <iron/Trait.h>
void iron_object_Object_removeTrait(iron__object__Object,iron__Trait);

void iron_Trait_remove(iron__Trait r0) {
	iron__object__Object r2;
	r2 = r0->object;
	if( r2 == NULL ) hl_null_access();
	iron_object_Object_removeTrait(r2,r0);
	return;
}

void iron_Trait_new(iron__Trait r0) {
	hl__types__ArrayObj r1;
	r1 = NULL;
	r0->_render2D = r1;
	r1 = NULL;
	r0->_render = r1;
	r1 = NULL;
	r0->_lateUpdate = r1;
	r1 = NULL;
	r0->_update = r1;
	r1 = NULL;
	r0->_remove = r1;
	r1 = NULL;
	r0->_init = r1;
	r1 = NULL;
	r0->_add = r1;
	return;
}

