// Generated by HLC 4.0.0 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <zui/Ext.h>
#include <zui/Zui.h>
#include <kha/graphics2/Graphics.h>
extern String $s_;
extern hl_type $t_i32;
bool zui_Zui_isVisible(zui__Zui,double);
void zui_Zui_endElement(zui__Zui,vdynamic*);
bool zui_Zui_getHover(zui__Zui,double*);
extern zui__$Zui $g__zui_Zui;
extern hl_type $t_bool;
void zui_Zui_fadeColor(zui__Zui);
bool zui_Zui_getReleased(zui__Zui,double*);
void zui_Zui_startTextEdit(zui__Zui,zui__Handle);
void zui_Ext_listenToKey(zui__Zui,zui__Handle);
int String___compare(String,vdynamic*);
extern hl_type $t_f64;
void zui_Zui_drawString(zui__Zui,kha__graphics2__Graphics,String,vdynamic*,double*,int*);
String zui_Ext_keycodeToString(int);
#include <kha/input/Keyboard.h>
kha__input__Keyboard kha_input_Keyboard_get(int*);
void kha_input_Keyboard_hide(kha__input__Keyboard);
extern String $s_Press_a_key_;
extern String $s_None;
extern String $s_Unknown;
extern String $s_Back;
extern String $s_Cancel;
extern String $s_Help;
extern String $s_Backspace;
extern String $s_Tab;
extern String $s_Clear;
extern String $s_Return;
extern String $s_Shift;
extern String $s_Ctrl;
extern String $s_Alt;
extern String $s_Pause;
extern String $s_CapsLock;
extern String $s_Kana;
extern String $s_Eisu;
extern String $s_Junja;
extern String $s_Final;
extern String $s_Hanja;
extern String $s_Esc;
extern String $s_Convert;
extern String $s_NonConvert;
extern String $s_Accept;
extern String $s_ModeChange;
extern String $s_Space;
extern String $s_PageUp;
extern String $s_PageDown;
extern String $s_End;
extern String $s_Home;
extern String $s_Left;
extern String $s_Up;
extern String $s_Right;
extern String $s_Down;
extern String $s_Select;
extern String $s_Print;
extern String $s_Execute;
extern String $s_PrintScreen;
extern String $s_Insert;
extern String $s_Delete;
extern String $s_Colon;
extern String $s_Semicolon;
extern String $s_LessThan;
extern String $s_Equals;
extern String $s_GreaterThan;
extern String $s_QuestionMark;
extern String $s_At;
extern String $s_Win;
extern String $s_ContextMenu;
extern String $s_Sleep;
extern String $s_Numpad0;
extern String $s_Numpad1;
extern String $s_Numpad2;
extern String $s_Numpad3;
extern String $s_Numpad4;
extern String $s_Numpad5;
extern String $s_Numpad6;
extern String $s_Numpad7;
extern String $s_Numpad8;
extern String $s_Numpad9;
extern String $s_Multiply;
extern String $s_Add;
extern String $s_Separator;
extern String $s_Subtract;
extern String $s_Decimal;
extern String $s_Divide;
extern String $s_F1;
extern String $s_F2;
extern String $s_F3;
extern String $s_F4;
extern String $s_F5;
extern String $s_F6;
extern String $s_F7;
extern String $s_F8;
extern String $s_F9;
extern String $s_F10;
extern String $s_F11;
extern String $s_F12;
extern String $s_F13;
extern String $s_F14;
extern String $s_F15;
extern String $s_F16;
extern String $s_F17;
extern String $s_F18;
extern String $s_F19;
extern String $s_F20;
extern String $s_F21;
extern String $s_F22;
extern String $s_F23;
extern String $s_F24;
extern String $s_NumLock;
extern String $s_ScrollLock;
extern String $s_WinOemFjJisho;
extern String $s_WinOemFjMasshou;
extern String $s_WinOemFjTouroku;
extern String $s_WinOemFjLoya;
extern String $s_WinOemFjRoya;
extern String $s_Circumflex;
extern String $s_Exclamation;
extern String $s_DoubleQuote;
extern String $s_Hash;
extern String $s_Dollar;
extern String $s_Percent;
extern String $s_Ampersand;
extern String $s_Underscore;
extern String $s_OpenParen;
extern String $s_CloseParen;
extern String $s_Asterisk;
extern String $s_Plus;
extern String $s_Pipe;
extern String $s_HyphenMinus;
extern String $s_OpenCurlyBracket;
extern String $s_CloseCurlyBracket;
extern String $s_Tilde;
extern String $s_VolumeMute;
extern String $s_VolumeDown;
extern String $s_VolumeUp;
extern String $s_Comma;
extern String $s_Period;
extern String $s_Slash;
extern String $s_BackQuote;
extern String $s_OpenBracket;
extern String $s_BackSlash;
extern String $s_CloseBracket;
extern String $s_Quote;
extern String $s_Meta;
extern String $s_AltGr;
extern String $s_WinIcoHelp;
extern String $s_WinIco00;
extern String $s_WinIcoClear;
extern String $s_WinOemReset;
extern String $s_WinOemJump;
extern String $s_WinOemPA1;
extern String $s_WinOemPA2;
extern String $s_WinOemPA3;
extern String $s_WinOemWSCTRL;
extern String $s_WinOemCUSEL;
extern String $s_WinOemATTN;
extern String $s_WinOemFinish;
extern String $s_WinOemCopy;
extern String $s_WinOemAuto;
extern String $s_WinOemENLW;
extern String $s_WinOemBackTab;
extern String $s_ATTN;
extern String $s_CRSEL;
extern String $s_EXSEL;
extern String $s_EREOF;
extern String $s_Play;
extern String $s_Zoom;
extern String $s_PA1;
extern String $s_WinOemClear;
String String_fromCharCode(int);

int zui_Ext_keyInput(zui__Zui r0,zui__Handle r1,String r2,int* r3) {
	String r4, r26;
	vvirtual *r10;
	bool r7, r15, r24;
	kha__graphics2__Graphics r18;
	zui__$Zui r17;
	vclosure *r16;
	double r8, r11, r19, r20, r21, r22, r23, r25;
	double *r14;
	zui__Handle r13;
	vdynamic *r12;
	int r5, r9, r27, r28, r29;
	if( r2 ) goto label$b6ce9d2_1_3;
	r4 = (String)$s_;
	r2 = r4;
	label$b6ce9d2_1_3:
	if( r3 ) goto label$b6ce9d2_1_6;
	r5 = 0;
	goto label$b6ce9d2_1_7;
	label$b6ce9d2_1_6:
	r5 = *r3;
	label$b6ce9d2_1_7:
	if( r0 == NULL ) hl_null_access();
	r10 = r0->_t;
	if( r10 == NULL ) hl_null_access();
	r9 = hl_vfields(r10)[12] ? (*(int*)(hl_vfields(r10)[12])) : (int)hl_dyn_geti(r10->value,-482102240/*ELEMENT_H*/,&$t_i32);
	r8 = (double)r9;
	r11 = r0->SCALE;
	r8 = r8 * r11;
	r7 = zui_Zui_isVisible(r0,r8);
	if( r7 ) goto label$b6ce9d2_1_22;
	r12 = NULL;
	zui_Zui_endElement(r0,r12);
	if( r1 == NULL ) hl_null_access();
	r8 = r1->value;
	r9 = (int)r8;
	return r9;
	label$b6ce9d2_1_22:
	r14 = NULL;
	r7 = zui_Zui_getHover(r0,r14);
	if( !r7 ) goto label$b6ce9d2_1_32;
	r17 = (zui__$Zui)$g__zui_Zui;
	r16 = r17->onTextHover;
	if( !r16 ) goto label$b6ce9d2_1_32;
	r17 = (zui__$Zui)$g__zui_Zui;
	r16 = r17->onTextHover;
	if( r16 == NULL ) hl_null_access();
	r16->hasValue ? ((void (*)(vdynamic*))r16->fun)((vdynamic*)r16->value) : ((void (*)(void))r16->fun)();
	label$b6ce9d2_1_32:
	r18 = r0->g;
	if( r18 == NULL ) hl_null_access();
	if( !r7 ) goto label$b6ce9d2_1_39;
	r10 = r0->_t;
	if( r10 == NULL ) hl_null_access();
	r9 = hl_vfields(r10)[1] ? (*(int*)(hl_vfields(r10)[1])) : (int)hl_dyn_geti(r10->value,-43289016/*ACCENT_HOVER_COL*/,&$t_i32);
	goto label$b6ce9d2_1_42;
	label$b6ce9d2_1_39:
	r10 = r0->_t;
	if( r10 == NULL ) hl_null_access();
	r9 = hl_vfields(r10)[0] ? (*(int*)(hl_vfields(r10)[0])) : (int)hl_dyn_geti(r10->value,34671467/*ACCENT_COL*/,&$t_i32);
	label$b6ce9d2_1_42:
	r9 = ((int (*)(kha__graphics2__Graphics,int))r18->$type->vobj_proto[9])(r18,r9);
	r18 = r0->g;
	r10 = r0->_t;
	if( r10 == NULL ) hl_null_access();
	r15 = hl_vfields(r10)[15] ? (*(bool*)(hl_vfields(r10)[15])) : (bool)hl_dyn_geti(r10->value,51671661/*FILL_ACCENT_BG*/,&$t_bool);
	r8 = r0->_x;
	r11 = r0->buttonOffsetY;
	r8 = r8 + r11;
	r11 = r0->_y;
	r19 = r0->buttonOffsetY;
	r11 = r11 + r19;
	r9 = r0->_w;
	r19 = (double)r9;
	r20 = r0->buttonOffsetY;
	r21 = 2.;
	r20 = r20 * r21;
	r19 = r19 - r20;
	r10 = r0->_t;
	if( r10 == NULL ) hl_null_access();
	r9 = hl_vfields(r10)[6] ? (*(int*)(hl_vfields(r10)[6])) : (int)hl_dyn_geti(r10->value,-172474255/*BUTTON_H*/,&$t_i32);
	r20 = (double)r9;
	r21 = r0->SCALE;
	r20 = r20 * r21;
	r21 = 0.;
	r23 = 0.;
	if( r21 != r23 ) goto label$b6ce9d2_1_75;
	r10 = r0->_t;
	if( r10 == NULL ) hl_null_access();
	r9 = hl_vfields(r10)[21] ? (*(int*)(hl_vfields(r10)[21])) : (int)hl_dyn_geti(r10->value,-63120798/*LINE_STRENGTH*/,&$t_i32);
	r22 = (double)r9;
	r23 = r0->SCALE;
	r22 = r22 * r23;
	r21 = r22;
	label$b6ce9d2_1_75:
	r24 = r0->enabled;
	if( r24 ) goto label$b6ce9d2_1_78;
	zui_Zui_fadeColor(r0);
	label$b6ce9d2_1_78:
	if( !r15 ) goto label$b6ce9d2_1_82;
	if( r18 == NULL ) hl_null_access();
	((void (*)(kha__graphics2__Graphics,double,double,double,double))r18->$type->vobj_proto[4])(r18,r8,r11,r19,r20);
	goto label$b6ce9d2_1_86;
	label$b6ce9d2_1_82:
	if( r18 == NULL ) hl_null_access();
	r25 = r21;
	r14 = &r25;
	((void (*)(kha__graphics2__Graphics,double,double,double,double,double*))r18->$type->vobj_proto[3])(r18,r8,r11,r19,r20,r14);
	label$b6ce9d2_1_86:
	r14 = NULL;
	r15 = zui_Zui_getReleased(r0,r14);
	if( r15 ) goto label$b6ce9d2_1_93;
	r15 = r0->tabPressed;
	if( r15 ) goto label$b6ce9d2_1_93;
	r15 = false;
	goto label$b6ce9d2_1_94;
	label$b6ce9d2_1_93:
	r15 = true;
	label$b6ce9d2_1_94:
	r13 = r0->textSelectedHandle;
	if( r13 == r1 ) goto label$b6ce9d2_1_98;
	if( !r15 ) goto label$b6ce9d2_1_98;
	zui_Zui_startTextEdit(r0,r1);
	label$b6ce9d2_1_98:
	r13 = r0->textSelectedHandle;
	if( r13 != r1 ) goto label$b6ce9d2_1_102;
	zui_Ext_listenToKey(r0,r1);
	goto label$b6ce9d2_1_105;
	label$b6ce9d2_1_102:
	if( r1 == NULL ) hl_null_access();
	r24 = false;
	r1->changed = r24;
	label$b6ce9d2_1_105:
	r26 = (String)$s_;
	if( r2 == r26 || (r2 && r26 && String___compare(r2,(vdynamic*)r26) == 0) ) goto label$b6ce9d2_1_132;
	r18 = r0->g;
	if( r18 == NULL ) hl_null_access();
	r10 = r0->_t;
	if( r10 == NULL ) hl_null_access();
	r9 = hl_vfields(r10)[20] ? (*(int*)(hl_vfields(r10)[20])) : (int)hl_dyn_geti(r10->value,370483844/*LABEL_COL*/,&$t_i32);
	r9 = ((int (*)(kha__graphics2__Graphics,int))r18->$type->vobj_proto[9])(r18,r9);
	r27 = 2;
	if( r5 != r27 ) goto label$b6ce9d2_1_117;
	r9 = 0;
	goto label$b6ce9d2_1_118;
	label$b6ce9d2_1_117:
	r9 = 2;
	label$b6ce9d2_1_118:
	r28 = 0;
	if( r9 != r28 ) goto label$b6ce9d2_1_122;
	r27 = 7;
	goto label$b6ce9d2_1_123;
	label$b6ce9d2_1_122:
	r27 = 0;
	label$b6ce9d2_1_123:
	r18 = r0->g;
	r8 = (double)r27;
	r12 = hl_alloc_dynamic(&$t_f64);
	r12->v.d = r8;
	r28 = 0;
	r8 = (double)r28;
	r14 = &r8;
	r28 = r9;
	r3 = &r28;
	zui_Zui_drawString(r0,r18,r2,r12,r14,r3);
	label$b6ce9d2_1_132:
	if( r1 == NULL ) hl_null_access();
	r11 = r1->value;
	r9 = (int)r11;
	r4 = zui_Ext_keycodeToString(r9);
	r1->text = r4;
	r18 = r0->g;
	if( r18 == NULL ) hl_null_access();
	r10 = r0->_t;
	if( r10 == NULL ) hl_null_access();
	r9 = hl_vfields(r10)[27] ? (*(int*)(hl_vfields(r10)[27])) : (int)hl_dyn_geti(r10->value,-437956663/*TEXT_COL*/,&$t_i32);
	r9 = ((int (*)(kha__graphics2__Graphics,int))r18->$type->vobj_proto[9])(r18,r9);
	r13 = r0->textSelectedHandle;
	if( r13 == r1 ) goto label$b6ce9d2_1_155;
	r18 = r0->g;
	r4 = r1->text;
	r12 = NULL;
	r9 = 0;
	r19 = (double)r9;
	r14 = &r19;
	r9 = r5;
	r3 = &r9;
	zui_Zui_drawString(r0,r18,r4,r12,r14,r3);
	goto label$b6ce9d2_1_164;
	label$b6ce9d2_1_155:
	r18 = r0->g;
	r4 = r0->textSelectedCurrentText;
	r12 = NULL;
	r27 = 0;
	r20 = (double)r27;
	r14 = &r20;
	r27 = r5;
	r3 = &r27;
	zui_Zui_drawString(r0,r18,r4,r12,r14,r3);
	label$b6ce9d2_1_164:
	r12 = NULL;
	zui_Zui_endElement(r0,r12);
	r21 = r1->value;
	r29 = (int)r21;
	return r29;
}

void zui_Ext_listenToKey(zui__Zui r0,zui__Handle r1) {
	String r10;
	bool r3;
	double r7;
	int *r9;
	vdynamic *r5;
	zui__Handle r4;
	kha__input__Keyboard r8;
	int r6;
	if( r0 == NULL ) hl_null_access();
	r3 = r0->isKeyDown;
	if( !r3 ) goto label$b6ce9d2_2_23;
	if( r1 == NULL ) hl_null_access();
	r5 = r0->key;
	r6 = r5 ? r5->v.i : 0;
	r7 = (double)r6;
	r1->value = r7;
	r3 = true;
	r0->changed = r3;
	r1->changed = r3;
	r4 = NULL;
	r0->textSelectedHandle = r4;
	r3 = false;
	r0->isTyping = r3;
	r9 = NULL;
	r8 = kha_input_Keyboard_get(r9);
	if( !r8 ) goto label$b6ce9d2_2_22;
	r9 = NULL;
	r8 = kha_input_Keyboard_get(r9);
	if( r8 == NULL ) hl_null_access();
	kha_input_Keyboard_hide(r8);
	label$b6ce9d2_2_22:
	goto label$b6ce9d2_2_25;
	label$b6ce9d2_2_23:
	r10 = (String)$s_Press_a_key_;
	r0->textSelectedCurrentText = r10;
	label$b6ce9d2_2_25:
	return;
}

String zui_Ext_keycodeToString(int r0) {
	String r2;
	int r1;
	r1 = -1;
	if( r1 == r0 ) goto label$b6ce9d2_3_301;
	r1 = 0;
	if( r1 == r0 ) goto label$b6ce9d2_3_303;
	r1 = 1;
	if( r1 == r0 ) goto label$b6ce9d2_3_305;
	r1 = 3;
	if( r1 == r0 ) goto label$b6ce9d2_3_307;
	r1 = 6;
	if( r1 == r0 ) goto label$b6ce9d2_3_309;
	r1 = 8;
	if( r1 == r0 ) goto label$b6ce9d2_3_311;
	r1 = 9;
	if( r1 == r0 ) goto label$b6ce9d2_3_313;
	r1 = 12;
	if( r1 == r0 ) goto label$b6ce9d2_3_315;
	r1 = 13;
	if( r1 == r0 ) goto label$b6ce9d2_3_317;
	r1 = 16;
	if( r1 == r0 ) goto label$b6ce9d2_3_319;
	r1 = 17;
	if( r1 == r0 ) goto label$b6ce9d2_3_321;
	r1 = 18;
	if( r1 == r0 ) goto label$b6ce9d2_3_323;
	r1 = 19;
	if( r1 == r0 ) goto label$b6ce9d2_3_325;
	r1 = 20;
	if( r1 == r0 ) goto label$b6ce9d2_3_327;
	r1 = 21;
	if( r1 == r0 ) goto label$b6ce9d2_3_329;
	r1 = 22;
	if( r1 == r0 ) goto label$b6ce9d2_3_331;
	r1 = 23;
	if( r1 == r0 ) goto label$b6ce9d2_3_333;
	r1 = 24;
	if( r1 == r0 ) goto label$b6ce9d2_3_335;
	r1 = 25;
	if( r1 == r0 ) goto label$b6ce9d2_3_337;
	r1 = 27;
	if( r1 == r0 ) goto label$b6ce9d2_3_339;
	r1 = 28;
	if( r1 == r0 ) goto label$b6ce9d2_3_341;
	r1 = 29;
	if( r1 == r0 ) goto label$b6ce9d2_3_343;
	r1 = 30;
	if( r1 == r0 ) goto label$b6ce9d2_3_345;
	r1 = 31;
	if( r1 == r0 ) goto label$b6ce9d2_3_347;
	r1 = 32;
	if( r1 == r0 ) goto label$b6ce9d2_3_349;
	r1 = 33;
	if( r1 == r0 ) goto label$b6ce9d2_3_351;
	r1 = 34;
	if( r1 == r0 ) goto label$b6ce9d2_3_353;
	r1 = 35;
	if( r1 == r0 ) goto label$b6ce9d2_3_355;
	r1 = 36;
	if( r1 == r0 ) goto label$b6ce9d2_3_357;
	r1 = 37;
	if( r1 == r0 ) goto label$b6ce9d2_3_359;
	r1 = 38;
	if( r1 == r0 ) goto label$b6ce9d2_3_361;
	r1 = 39;
	if( r1 == r0 ) goto label$b6ce9d2_3_363;
	r1 = 40;
	if( r1 == r0 ) goto label$b6ce9d2_3_365;
	r1 = 41;
	if( r1 == r0 ) goto label$b6ce9d2_3_367;
	r1 = 42;
	if( r1 == r0 ) goto label$b6ce9d2_3_369;
	r1 = 43;
	if( r1 == r0 ) goto label$b6ce9d2_3_371;
	r1 = 44;
	if( r1 == r0 ) goto label$b6ce9d2_3_373;
	r1 = 45;
	if( r1 == r0 ) goto label$b6ce9d2_3_375;
	r1 = 46;
	if( r1 == r0 ) goto label$b6ce9d2_3_377;
	r1 = 58;
	if( r1 == r0 ) goto label$b6ce9d2_3_379;
	r1 = 59;
	if( r1 == r0 ) goto label$b6ce9d2_3_381;
	r1 = 60;
	if( r1 == r0 ) goto label$b6ce9d2_3_383;
	r1 = 61;
	if( r1 == r0 ) goto label$b6ce9d2_3_385;
	r1 = 62;
	if( r1 == r0 ) goto label$b6ce9d2_3_387;
	r1 = 63;
	if( r1 == r0 ) goto label$b6ce9d2_3_389;
	r1 = 64;
	if( r1 == r0 ) goto label$b6ce9d2_3_391;
	r1 = 91;
	if( r1 == r0 ) goto label$b6ce9d2_3_393;
	r1 = 93;
	if( r1 == r0 ) goto label$b6ce9d2_3_395;
	r1 = 95;
	if( r1 == r0 ) goto label$b6ce9d2_3_397;
	r1 = 96;
	if( r1 == r0 ) goto label$b6ce9d2_3_399;
	r1 = 97;
	if( r1 == r0 ) goto label$b6ce9d2_3_401;
	r1 = 98;
	if( r1 == r0 ) goto label$b6ce9d2_3_403;
	r1 = 99;
	if( r1 == r0 ) goto label$b6ce9d2_3_405;
	r1 = 100;
	if( r1 == r0 ) goto label$b6ce9d2_3_407;
	r1 = 101;
	if( r1 == r0 ) goto label$b6ce9d2_3_409;
	r1 = 102;
	if( r1 == r0 ) goto label$b6ce9d2_3_411;
	r1 = 103;
	if( r1 == r0 ) goto label$b6ce9d2_3_413;
	r1 = 104;
	if( r1 == r0 ) goto label$b6ce9d2_3_415;
	r1 = 105;
	if( r1 == r0 ) goto label$b6ce9d2_3_417;
	r1 = 106;
	if( r1 == r0 ) goto label$b6ce9d2_3_419;
	r1 = 107;
	if( r1 == r0 ) goto label$b6ce9d2_3_421;
	r1 = 108;
	if( r1 == r0 ) goto label$b6ce9d2_3_423;
	r1 = 109;
	if( r1 == r0 ) goto label$b6ce9d2_3_425;
	r1 = 110;
	if( r1 == r0 ) goto label$b6ce9d2_3_427;
	r1 = 111;
	if( r1 == r0 ) goto label$b6ce9d2_3_429;
	r1 = 112;
	if( r1 == r0 ) goto label$b6ce9d2_3_431;
	r1 = 113;
	if( r1 == r0 ) goto label$b6ce9d2_3_433;
	r1 = 114;
	if( r1 == r0 ) goto label$b6ce9d2_3_435;
	r1 = 115;
	if( r1 == r0 ) goto label$b6ce9d2_3_437;
	r1 = 116;
	if( r1 == r0 ) goto label$b6ce9d2_3_439;
	r1 = 117;
	if( r1 == r0 ) goto label$b6ce9d2_3_441;
	r1 = 118;
	if( r1 == r0 ) goto label$b6ce9d2_3_443;
	r1 = 119;
	if( r1 == r0 ) goto label$b6ce9d2_3_445;
	r1 = 120;
	if( r1 == r0 ) goto label$b6ce9d2_3_447;
	r1 = 121;
	if( r1 == r0 ) goto label$b6ce9d2_3_449;
	r1 = 122;
	if( r1 == r0 ) goto label$b6ce9d2_3_451;
	r1 = 123;
	if( r1 == r0 ) goto label$b6ce9d2_3_453;
	r1 = 124;
	if( r1 == r0 ) goto label$b6ce9d2_3_455;
	r1 = 125;
	if( r1 == r0 ) goto label$b6ce9d2_3_457;
	r1 = 126;
	if( r1 == r0 ) goto label$b6ce9d2_3_459;
	r1 = 127;
	if( r1 == r0 ) goto label$b6ce9d2_3_461;
	r1 = 128;
	if( r1 == r0 ) goto label$b6ce9d2_3_463;
	r1 = 129;
	if( r1 == r0 ) goto label$b6ce9d2_3_465;
	r1 = 130;
	if( r1 == r0 ) goto label$b6ce9d2_3_467;
	r1 = 131;
	if( r1 == r0 ) goto label$b6ce9d2_3_469;
	r1 = 132;
	if( r1 == r0 ) goto label$b6ce9d2_3_471;
	r1 = 133;
	if( r1 == r0 ) goto label$b6ce9d2_3_473;
	r1 = 134;
	if( r1 == r0 ) goto label$b6ce9d2_3_475;
	r1 = 135;
	if( r1 == r0 ) goto label$b6ce9d2_3_477;
	r1 = 144;
	if( r1 == r0 ) goto label$b6ce9d2_3_479;
	r1 = 145;
	if( r1 == r0 ) goto label$b6ce9d2_3_481;
	r1 = 146;
	if( r1 == r0 ) goto label$b6ce9d2_3_483;
	r1 = 147;
	if( r1 == r0 ) goto label$b6ce9d2_3_485;
	r1 = 148;
	if( r1 == r0 ) goto label$b6ce9d2_3_487;
	r1 = 149;
	if( r1 == r0 ) goto label$b6ce9d2_3_489;
	r1 = 150;
	if( r1 == r0 ) goto label$b6ce9d2_3_491;
	r1 = 160;
	if( r1 == r0 ) goto label$b6ce9d2_3_493;
	r1 = 161;
	if( r1 == r0 ) goto label$b6ce9d2_3_495;
	r1 = 162;
	if( r1 == r0 ) goto label$b6ce9d2_3_497;
	r1 = 163;
	if( r1 == r0 ) goto label$b6ce9d2_3_499;
	r1 = 164;
	if( r1 == r0 ) goto label$b6ce9d2_3_501;
	r1 = 165;
	if( r1 == r0 ) goto label$b6ce9d2_3_503;
	r1 = 166;
	if( r1 == r0 ) goto label$b6ce9d2_3_505;
	r1 = 167;
	if( r1 == r0 ) goto label$b6ce9d2_3_507;
	r1 = 168;
	if( r1 == r0 ) goto label$b6ce9d2_3_509;
	r1 = 169;
	if( r1 == r0 ) goto label$b6ce9d2_3_511;
	r1 = 170;
	if( r1 == r0 ) goto label$b6ce9d2_3_513;
	r1 = 171;
	if( r1 == r0 ) goto label$b6ce9d2_3_515;
	r1 = 172;
	if( r1 == r0 ) goto label$b6ce9d2_3_517;
	r1 = 173;
	if( r1 == r0 ) goto label$b6ce9d2_3_519;
	r1 = 174;
	if( r1 == r0 ) goto label$b6ce9d2_3_521;
	r1 = 175;
	if( r1 == r0 ) goto label$b6ce9d2_3_523;
	r1 = 176;
	if( r1 == r0 ) goto label$b6ce9d2_3_525;
	r1 = 181;
	if( r1 == r0 ) goto label$b6ce9d2_3_527;
	r1 = 182;
	if( r1 == r0 ) goto label$b6ce9d2_3_529;
	r1 = 183;
	if( r1 == r0 ) goto label$b6ce9d2_3_531;
	r1 = 188;
	if( r1 == r0 ) goto label$b6ce9d2_3_533;
	r1 = 190;
	if( r1 == r0 ) goto label$b6ce9d2_3_535;
	r1 = 191;
	if( r1 == r0 ) goto label$b6ce9d2_3_537;
	r1 = 192;
	if( r1 == r0 ) goto label$b6ce9d2_3_539;
	r1 = 219;
	if( r1 == r0 ) goto label$b6ce9d2_3_541;
	r1 = 220;
	if( r1 == r0 ) goto label$b6ce9d2_3_543;
	r1 = 221;
	if( r1 == r0 ) goto label$b6ce9d2_3_545;
	r1 = 222;
	if( r1 == r0 ) goto label$b6ce9d2_3_547;
	r1 = 224;
	if( r1 == r0 ) goto label$b6ce9d2_3_549;
	r1 = 225;
	if( r1 == r0 ) goto label$b6ce9d2_3_551;
	r1 = 227;
	if( r1 == r0 ) goto label$b6ce9d2_3_553;
	r1 = 228;
	if( r1 == r0 ) goto label$b6ce9d2_3_555;
	r1 = 230;
	if( r1 == r0 ) goto label$b6ce9d2_3_557;
	r1 = 233;
	if( r1 == r0 ) goto label$b6ce9d2_3_559;
	r1 = 234;
	if( r1 == r0 ) goto label$b6ce9d2_3_561;
	r1 = 235;
	if( r1 == r0 ) goto label$b6ce9d2_3_563;
	r1 = 236;
	if( r1 == r0 ) goto label$b6ce9d2_3_565;
	r1 = 237;
	if( r1 == r0 ) goto label$b6ce9d2_3_567;
	r1 = 238;
	if( r1 == r0 ) goto label$b6ce9d2_3_569;
	r1 = 239;
	if( r1 == r0 ) goto label$b6ce9d2_3_571;
	r1 = 240;
	if( r1 == r0 ) goto label$b6ce9d2_3_573;
	r1 = 241;
	if( r1 == r0 ) goto label$b6ce9d2_3_575;
	r1 = 242;
	if( r1 == r0 ) goto label$b6ce9d2_3_577;
	r1 = 243;
	if( r1 == r0 ) goto label$b6ce9d2_3_579;
	r1 = 244;
	if( r1 == r0 ) goto label$b6ce9d2_3_581;
	r1 = 245;
	if( r1 == r0 ) goto label$b6ce9d2_3_583;
	r1 = 246;
	if( r1 == r0 ) goto label$b6ce9d2_3_585;
	r1 = 247;
	if( r1 == r0 ) goto label$b6ce9d2_3_587;
	r1 = 248;
	if( r1 == r0 ) goto label$b6ce9d2_3_589;
	r1 = 249;
	if( r1 == r0 ) goto label$b6ce9d2_3_591;
	r1 = 250;
	if( r1 == r0 ) goto label$b6ce9d2_3_593;
	r1 = 251;
	if( r1 == r0 ) goto label$b6ce9d2_3_595;
	r1 = 253;
	if( r1 == r0 ) goto label$b6ce9d2_3_597;
	r1 = 254;
	if( r1 == r0 ) goto label$b6ce9d2_3_599;
	goto label$b6ce9d2_3_601;
	label$b6ce9d2_3_301:
	r2 = (String)$s_None;
	return r2;
	label$b6ce9d2_3_303:
	r2 = (String)$s_Unknown;
	return r2;
	label$b6ce9d2_3_305:
	r2 = (String)$s_Back;
	return r2;
	label$b6ce9d2_3_307:
	r2 = (String)$s_Cancel;
	return r2;
	label$b6ce9d2_3_309:
	r2 = (String)$s_Help;
	return r2;
	label$b6ce9d2_3_311:
	r2 = (String)$s_Backspace;
	return r2;
	label$b6ce9d2_3_313:
	r2 = (String)$s_Tab;
	return r2;
	label$b6ce9d2_3_315:
	r2 = (String)$s_Clear;
	return r2;
	label$b6ce9d2_3_317:
	r2 = (String)$s_Return;
	return r2;
	label$b6ce9d2_3_319:
	r2 = (String)$s_Shift;
	return r2;
	label$b6ce9d2_3_321:
	r2 = (String)$s_Ctrl;
	return r2;
	label$b6ce9d2_3_323:
	r2 = (String)$s_Alt;
	return r2;
	label$b6ce9d2_3_325:
	r2 = (String)$s_Pause;
	return r2;
	label$b6ce9d2_3_327:
	r2 = (String)$s_CapsLock;
	return r2;
	label$b6ce9d2_3_329:
	r2 = (String)$s_Kana;
	return r2;
	label$b6ce9d2_3_331:
	r2 = (String)$s_Eisu;
	return r2;
	label$b6ce9d2_3_333:
	r2 = (String)$s_Junja;
	return r2;
	label$b6ce9d2_3_335:
	r2 = (String)$s_Final;
	return r2;
	label$b6ce9d2_3_337:
	r2 = (String)$s_Hanja;
	return r2;
	label$b6ce9d2_3_339:
	r2 = (String)$s_Esc;
	return r2;
	label$b6ce9d2_3_341:
	r2 = (String)$s_Convert;
	return r2;
	label$b6ce9d2_3_343:
	r2 = (String)$s_NonConvert;
	return r2;
	label$b6ce9d2_3_345:
	r2 = (String)$s_Accept;
	return r2;
	label$b6ce9d2_3_347:
	r2 = (String)$s_ModeChange;
	return r2;
	label$b6ce9d2_3_349:
	r2 = (String)$s_Space;
	return r2;
	label$b6ce9d2_3_351:
	r2 = (String)$s_PageUp;
	return r2;
	label$b6ce9d2_3_353:
	r2 = (String)$s_PageDown;
	return r2;
	label$b6ce9d2_3_355:
	r2 = (String)$s_End;
	return r2;
	label$b6ce9d2_3_357:
	r2 = (String)$s_Home;
	return r2;
	label$b6ce9d2_3_359:
	r2 = (String)$s_Left;
	return r2;
	label$b6ce9d2_3_361:
	r2 = (String)$s_Up;
	return r2;
	label$b6ce9d2_3_363:
	r2 = (String)$s_Right;
	return r2;
	label$b6ce9d2_3_365:
	r2 = (String)$s_Down;
	return r2;
	label$b6ce9d2_3_367:
	r2 = (String)$s_Select;
	return r2;
	label$b6ce9d2_3_369:
	r2 = (String)$s_Print;
	return r2;
	label$b6ce9d2_3_371:
	r2 = (String)$s_Execute;
	return r2;
	label$b6ce9d2_3_373:
	r2 = (String)$s_PrintScreen;
	return r2;
	label$b6ce9d2_3_375:
	r2 = (String)$s_Insert;
	return r2;
	label$b6ce9d2_3_377:
	r2 = (String)$s_Delete;
	return r2;
	label$b6ce9d2_3_379:
	r2 = (String)$s_Colon;
	return r2;
	label$b6ce9d2_3_381:
	r2 = (String)$s_Semicolon;
	return r2;
	label$b6ce9d2_3_383:
	r2 = (String)$s_LessThan;
	return r2;
	label$b6ce9d2_3_385:
	r2 = (String)$s_Equals;
	return r2;
	label$b6ce9d2_3_387:
	r2 = (String)$s_GreaterThan;
	return r2;
	label$b6ce9d2_3_389:
	r2 = (String)$s_QuestionMark;
	return r2;
	label$b6ce9d2_3_391:
	r2 = (String)$s_At;
	return r2;
	label$b6ce9d2_3_393:
	r2 = (String)$s_Win;
	return r2;
	label$b6ce9d2_3_395:
	r2 = (String)$s_ContextMenu;
	return r2;
	label$b6ce9d2_3_397:
	r2 = (String)$s_Sleep;
	return r2;
	label$b6ce9d2_3_399:
	r2 = (String)$s_Numpad0;
	return r2;
	label$b6ce9d2_3_401:
	r2 = (String)$s_Numpad1;
	return r2;
	label$b6ce9d2_3_403:
	r2 = (String)$s_Numpad2;
	return r2;
	label$b6ce9d2_3_405:
	r2 = (String)$s_Numpad3;
	return r2;
	label$b6ce9d2_3_407:
	r2 = (String)$s_Numpad4;
	return r2;
	label$b6ce9d2_3_409:
	r2 = (String)$s_Numpad5;
	return r2;
	label$b6ce9d2_3_411:
	r2 = (String)$s_Numpad6;
	return r2;
	label$b6ce9d2_3_413:
	r2 = (String)$s_Numpad7;
	return r2;
	label$b6ce9d2_3_415:
	r2 = (String)$s_Numpad8;
	return r2;
	label$b6ce9d2_3_417:
	r2 = (String)$s_Numpad9;
	return r2;
	label$b6ce9d2_3_419:
	r2 = (String)$s_Multiply;
	return r2;
	label$b6ce9d2_3_421:
	r2 = (String)$s_Add;
	return r2;
	label$b6ce9d2_3_423:
	r2 = (String)$s_Separator;
	return r2;
	label$b6ce9d2_3_425:
	r2 = (String)$s_Subtract;
	return r2;
	label$b6ce9d2_3_427:
	r2 = (String)$s_Decimal;
	return r2;
	label$b6ce9d2_3_429:
	r2 = (String)$s_Divide;
	return r2;
	label$b6ce9d2_3_431:
	r2 = (String)$s_F1;
	return r2;
	label$b6ce9d2_3_433:
	r2 = (String)$s_F2;
	return r2;
	label$b6ce9d2_3_435:
	r2 = (String)$s_F3;
	return r2;
	label$b6ce9d2_3_437:
	r2 = (String)$s_F4;
	return r2;
	label$b6ce9d2_3_439:
	r2 = (String)$s_F5;
	return r2;
	label$b6ce9d2_3_441:
	r2 = (String)$s_F6;
	return r2;
	label$b6ce9d2_3_443:
	r2 = (String)$s_F7;
	return r2;
	label$b6ce9d2_3_445:
	r2 = (String)$s_F8;
	return r2;
	label$b6ce9d2_3_447:
	r2 = (String)$s_F9;
	return r2;
	label$b6ce9d2_3_449:
	r2 = (String)$s_F10;
	return r2;
	label$b6ce9d2_3_451:
	r2 = (String)$s_F11;
	return r2;
	label$b6ce9d2_3_453:
	r2 = (String)$s_F12;
	return r2;
	label$b6ce9d2_3_455:
	r2 = (String)$s_F13;
	return r2;
	label$b6ce9d2_3_457:
	r2 = (String)$s_F14;
	return r2;
	label$b6ce9d2_3_459:
	r2 = (String)$s_F15;
	return r2;
	label$b6ce9d2_3_461:
	r2 = (String)$s_F16;
	return r2;
	label$b6ce9d2_3_463:
	r2 = (String)$s_F17;
	return r2;
	label$b6ce9d2_3_465:
	r2 = (String)$s_F18;
	return r2;
	label$b6ce9d2_3_467:
	r2 = (String)$s_F19;
	return r2;
	label$b6ce9d2_3_469:
	r2 = (String)$s_F20;
	return r2;
	label$b6ce9d2_3_471:
	r2 = (String)$s_F21;
	return r2;
	label$b6ce9d2_3_473:
	r2 = (String)$s_F22;
	return r2;
	label$b6ce9d2_3_475:
	r2 = (String)$s_F23;
	return r2;
	label$b6ce9d2_3_477:
	r2 = (String)$s_F24;
	return r2;
	label$b6ce9d2_3_479:
	r2 = (String)$s_NumLock;
	return r2;
	label$b6ce9d2_3_481:
	r2 = (String)$s_ScrollLock;
	return r2;
	label$b6ce9d2_3_483:
	r2 = (String)$s_WinOemFjJisho;
	return r2;
	label$b6ce9d2_3_485:
	r2 = (String)$s_WinOemFjMasshou;
	return r2;
	label$b6ce9d2_3_487:
	r2 = (String)$s_WinOemFjTouroku;
	return r2;
	label$b6ce9d2_3_489:
	r2 = (String)$s_WinOemFjLoya;
	return r2;
	label$b6ce9d2_3_491:
	r2 = (String)$s_WinOemFjRoya;
	return r2;
	label$b6ce9d2_3_493:
	r2 = (String)$s_Circumflex;
	return r2;
	label$b6ce9d2_3_495:
	r2 = (String)$s_Exclamation;
	return r2;
	label$b6ce9d2_3_497:
	r2 = (String)$s_DoubleQuote;
	return r2;
	label$b6ce9d2_3_499:
	r2 = (String)$s_Hash;
	return r2;
	label$b6ce9d2_3_501:
	r2 = (String)$s_Dollar;
	return r2;
	label$b6ce9d2_3_503:
	r2 = (String)$s_Percent;
	return r2;
	label$b6ce9d2_3_505:
	r2 = (String)$s_Ampersand;
	return r2;
	label$b6ce9d2_3_507:
	r2 = (String)$s_Underscore;
	return r2;
	label$b6ce9d2_3_509:
	r2 = (String)$s_OpenParen;
	return r2;
	label$b6ce9d2_3_511:
	r2 = (String)$s_CloseParen;
	return r2;
	label$b6ce9d2_3_513:
	r2 = (String)$s_Asterisk;
	return r2;
	label$b6ce9d2_3_515:
	r2 = (String)$s_Plus;
	return r2;
	label$b6ce9d2_3_517:
	r2 = (String)$s_Pipe;
	return r2;
	label$b6ce9d2_3_519:
	r2 = (String)$s_HyphenMinus;
	return r2;
	label$b6ce9d2_3_521:
	r2 = (String)$s_OpenCurlyBracket;
	return r2;
	label$b6ce9d2_3_523:
	r2 = (String)$s_CloseCurlyBracket;
	return r2;
	label$b6ce9d2_3_525:
	r2 = (String)$s_Tilde;
	return r2;
	label$b6ce9d2_3_527:
	r2 = (String)$s_VolumeMute;
	return r2;
	label$b6ce9d2_3_529:
	r2 = (String)$s_VolumeDown;
	return r2;
	label$b6ce9d2_3_531:
	r2 = (String)$s_VolumeUp;
	return r2;
	label$b6ce9d2_3_533:
	r2 = (String)$s_Comma;
	return r2;
	label$b6ce9d2_3_535:
	r2 = (String)$s_Period;
	return r2;
	label$b6ce9d2_3_537:
	r2 = (String)$s_Slash;
	return r2;
	label$b6ce9d2_3_539:
	r2 = (String)$s_BackQuote;
	return r2;
	label$b6ce9d2_3_541:
	r2 = (String)$s_OpenBracket;
	return r2;
	label$b6ce9d2_3_543:
	r2 = (String)$s_BackSlash;
	return r2;
	label$b6ce9d2_3_545:
	r2 = (String)$s_CloseBracket;
	return r2;
	label$b6ce9d2_3_547:
	r2 = (String)$s_Quote;
	return r2;
	label$b6ce9d2_3_549:
	r2 = (String)$s_Meta;
	return r2;
	label$b6ce9d2_3_551:
	r2 = (String)$s_AltGr;
	return r2;
	label$b6ce9d2_3_553:
	r2 = (String)$s_WinIcoHelp;
	return r2;
	label$b6ce9d2_3_555:
	r2 = (String)$s_WinIco00;
	return r2;
	label$b6ce9d2_3_557:
	r2 = (String)$s_WinIcoClear;
	return r2;
	label$b6ce9d2_3_559:
	r2 = (String)$s_WinOemReset;
	return r2;
	label$b6ce9d2_3_561:
	r2 = (String)$s_WinOemJump;
	return r2;
	label$b6ce9d2_3_563:
	r2 = (String)$s_WinOemPA1;
	return r2;
	label$b6ce9d2_3_565:
	r2 = (String)$s_WinOemPA2;
	return r2;
	label$b6ce9d2_3_567:
	r2 = (String)$s_WinOemPA3;
	return r2;
	label$b6ce9d2_3_569:
	r2 = (String)$s_WinOemWSCTRL;
	return r2;
	label$b6ce9d2_3_571:
	r2 = (String)$s_WinOemCUSEL;
	return r2;
	label$b6ce9d2_3_573:
	r2 = (String)$s_WinOemATTN;
	return r2;
	label$b6ce9d2_3_575:
	r2 = (String)$s_WinOemFinish;
	return r2;
	label$b6ce9d2_3_577:
	r2 = (String)$s_WinOemCopy;
	return r2;
	label$b6ce9d2_3_579:
	r2 = (String)$s_WinOemAuto;
	return r2;
	label$b6ce9d2_3_581:
	r2 = (String)$s_WinOemENLW;
	return r2;
	label$b6ce9d2_3_583:
	r2 = (String)$s_WinOemBackTab;
	return r2;
	label$b6ce9d2_3_585:
	r2 = (String)$s_ATTN;
	return r2;
	label$b6ce9d2_3_587:
	r2 = (String)$s_CRSEL;
	return r2;
	label$b6ce9d2_3_589:
	r2 = (String)$s_EXSEL;
	return r2;
	label$b6ce9d2_3_591:
	r2 = (String)$s_EREOF;
	return r2;
	label$b6ce9d2_3_593:
	r2 = (String)$s_Play;
	return r2;
	label$b6ce9d2_3_595:
	r2 = (String)$s_Zoom;
	return r2;
	label$b6ce9d2_3_597:
	r2 = (String)$s_PA1;
	return r2;
	label$b6ce9d2_3_599:
	r2 = (String)$s_WinOemClear;
	return r2;
	label$b6ce9d2_3_601:
	r2 = String_fromCharCode(r0);
	return r2;
}

