// Generated by HLC 4.0.0 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <armory/renderpath/Inc.h>
extern armory__renderpath__$Inc $g__armory_renderpath_Inc;
#include <hl/types/ArrayObj.h>
#include <iron/Scene.h>
#include <iron/data/TLightData.h>
#include <iron/data/LightData.h>
extern iron__$Scene $g__iron_Scene;
extern String $s_sun;
int String___compare(String,vdynamic*);
extern String $s_shadowMap;
void iron_RenderPath_bindTarget(iron__RenderPath,String,String);
extern String $s_shadowMapPoint_;
#include <hl/natives.h>
String String___alloc__(vbyte*,int);
String String___add__(String,String);
extern String $s_0fbd177;
extern String $s_shadowMapSpot_;
extern String $s_point;
#include <haxe/ds/StringMap.h>
#include <iron/RenderTarget.h>
#include <iron/RenderTargetRaw.h>
#include <iron/object/LightObject.h>
vdynamic* haxe_ds_StringMap_get(haxe__ds__StringMap,String);
extern hl_type $t_iron_RenderTargetRaw;
void iron_RenderTargetRaw_new(iron__RenderTargetRaw);
extern String $s_DEPTH16;
iron__RenderTarget iron_RenderPath_createRenderTarget(iron__RenderPath,iron__RenderTargetRaw);
extern iron__object__$LightObject $g__iron_object_LightObject;
extern hl_type $t_i32;
void iron_RenderPath_setTarget(iron__RenderPath,String,hl__types__ArrayObj,double*);
extern hl_type $t_f64;
void iron_RenderPath_clearTarget(iron__RenderPath,vdynamic*,vdynamic*);
extern String $s_shadowmap;
void iron_RenderPath_drawMeshes(iron__RenderPath,String);
extern String $s_spot;
extern String $s_area;

void armory_renderpath_Inc_init(iron__RenderPath r0) {
	armory__renderpath__$Inc r1;
	r1 = (armory__renderpath__$Inc)$g__armory_renderpath_Inc;
	r1->path = r0;
	return;
}

void armory_renderpath_Inc_bindShadowMap() {
	String r14, r15;
	iron__data__TLightData r12;
	hl__types__ArrayObj r2;
	bool r10;
	iron__$Scene r4;
	iron__Scene r3;
	iron__data__LightData r13;
	iron__object__LightObject r7;
	int *r19;
	vdynamic *r8, *r11;
	vbyte *r20;
	armory__renderpath__$Inc r17;
	iron__RenderPath r16;
	varray *r9;
	int r0, r5, r6, r18;
	r0 = 0;
	r4 = (iron__$Scene)$g__iron_Scene;
	r3 = r4->active;
	if( r3 == NULL ) hl_null_access();
	r2 = r3->lights;
	label$d589772_2_5:
	if( r2 == NULL ) hl_null_access();
	r6 = r2->length;
	if( r0 >= r6 ) goto label$d589772_2_40;
	r6 = r2->length;
	if( ((unsigned)r0) < ((unsigned)r6) ) goto label$d589772_2_13;
	r7 = NULL;
	goto label$d589772_2_16;
	label$d589772_2_13:
	r9 = r2->array;
	r8 = ((vdynamic**)(r9 + 1))[r0];
	r7 = (iron__object__LightObject)r8;
	label$d589772_2_16:
	++r0;
	if( r7 == NULL ) hl_null_access();
	r10 = r7->visible;
	if( !r10 ) goto label$d589772_2_34;
	r13 = r7->data;
	if( r13 == NULL ) hl_null_access();
	r12 = r13->raw;
	if( r12 == NULL ) hl_null_access();
	r11 = r12->cast_shadow;
	r10 = r11 ? r11->v.b : 0;
	if( !r10 ) goto label$d589772_2_34;
	r13 = r7->data;
	if( r13 == NULL ) hl_null_access();
	r12 = r13->raw;
	if( r12 == NULL ) hl_null_access();
	r14 = r12->type;
	r15 = (String)$s_sun;
	if( r14 == r15 || (r14 && r15 && String___compare(r14,(vdynamic*)r15) == 0) ) goto label$d589772_2_35;
	label$d589772_2_34:
	goto label$d589772_2_5;
	label$d589772_2_35:
	r14 = (String)$s_shadowMap;
	r17 = (armory__renderpath__$Inc)$g__armory_renderpath_Inc;
	r16 = r17->path;
	if( r16 == NULL ) hl_null_access();
	iron_RenderPath_bindTarget(r16,r14,r14);
	label$d589772_2_40:
	r0 = 0;
	r17 = (armory__renderpath__$Inc)$g__armory_renderpath_Inc;
	r5 = r17->pointIndex;
	label$d589772_2_43:
	if( r0 >= r5 ) goto label$d589772_2_60;
	r6 = r0;
	++r0;
	r14 = (String)$s_shadowMapPoint_;
	r18 = r6;
	r19 = &r18;
	r20 = hl_itos(r18,r19);
	r15 = String___alloc__(r20,r18);
	r14 = String___add__(r14,r15);
	r15 = (String)$s_0fbd177;
	r14 = String___add__(r14,r15);
	r17 = (armory__renderpath__$Inc)$g__armory_renderpath_Inc;
	r16 = r17->path;
	if( r16 == NULL ) hl_null_access();
	iron_RenderPath_bindTarget(r16,r14,r14);
	goto label$d589772_2_43;
	label$d589772_2_60:
	r0 = 0;
	r17 = (armory__renderpath__$Inc)$g__armory_renderpath_Inc;
	r5 = r17->spotIndex;
	label$d589772_2_63:
	if( r0 >= r5 ) goto label$d589772_2_80;
	r6 = r0;
	++r0;
	r14 = (String)$s_shadowMapSpot_;
	r18 = r6;
	r19 = &r18;
	r20 = hl_itos(r18,r19);
	r15 = String___alloc__(r20,r18);
	r14 = String___add__(r14,r15);
	r15 = (String)$s_0fbd177;
	r14 = String___add__(r14,r15);
	r17 = (armory__renderpath__$Inc)$g__armory_renderpath_Inc;
	r16 = r17->path;
	if( r16 == NULL ) hl_null_access();
	iron_RenderPath_bindTarget(r16,r14,r14);
	goto label$d589772_2_63;
	label$d589772_2_80:
	return;
}

String armory_renderpath_Inc_shadowMapName(iron__object__LightObject r0) {
	String r1, r4;
	iron__data__TLightData r2;
	iron__data__LightData r3;
	int *r7;
	vbyte *r8;
	armory__renderpath__$Inc r6;
	int r5;
	if( r0 == NULL ) hl_null_access();
	r3 = r0->data;
	if( r3 == NULL ) hl_null_access();
	r2 = r3->raw;
	if( r2 == NULL ) hl_null_access();
	r1 = r2->type;
	r4 = (String)$s_sun;
	if( r1 != r4 && (!r1 || !r4 || String___compare(r1,(vdynamic*)r4) != 0) ) goto label$d589772_3_10;
	r1 = (String)$s_shadowMap;
	return r1;
	label$d589772_3_10:
	r3 = r0->data;
	if( r3 == NULL ) hl_null_access();
	r2 = r3->raw;
	if( r2 == NULL ) hl_null_access();
	r1 = r2->type;
	r4 = (String)$s_point;
	if( r1 != r4 && (!r1 || !r4 || String___compare(r1,(vdynamic*)r4) != 0) ) goto label$d589772_3_27;
	r1 = (String)$s_shadowMapPoint_;
	r6 = (armory__renderpath__$Inc)$g__armory_renderpath_Inc;
	r5 = r6->pointIndex;
	r7 = &r5;
	r8 = hl_itos(r5,r7);
	r4 = String___alloc__(r8,r5);
	r1 = String___add__(r1,r4);
	r4 = (String)$s_0fbd177;
	r1 = String___add__(r1,r4);
	return r1;
	label$d589772_3_27:
	r1 = (String)$s_shadowMapSpot_;
	r6 = (armory__renderpath__$Inc)$g__armory_renderpath_Inc;
	r5 = r6->spotIndex;
	r7 = &r5;
	r8 = hl_itos(r5,r7);
	r4 = String___alloc__(r8,r5);
	r1 = String___add__(r1,r4);
	r4 = (String)$s_0fbd177;
	r1 = String___add__(r1,r4);
	return r1;
}

String armory_renderpath_Inc_getShadowMap(iron__object__LightObject r0) {
	String r1, r8, r19;
	iron__data__TLightData r12;
	haxe__ds__StringMap r5;
	iron__RenderTargetRaw r16;
	bool r14;
	iron__data__LightData r13;
	iron__RenderTarget r9, r10;
	iron__object__LightObject r2;
	vdynamic *r4, *r11, *r15, *r17, *r20;
	iron__object__$LightObject r22;
	int r18, r21;
	armory__renderpath__$Inc r7;
	iron__RenderPath r6;
	r1 = armory_renderpath_Inc_shadowMapName(r0);
	r7 = (armory__renderpath__$Inc)$g__armory_renderpath_Inc;
	r6 = r7->path;
	if( r6 == NULL ) hl_null_access();
	r5 = r6->renderTargets;
	if( r5 == NULL ) hl_null_access();
	r4 = haxe_ds_StringMap_get(r5,r1);
	r9 = (iron__RenderTarget)r4;
	if( r9 ) goto label$d589772_4_86;
	r7 = (armory__renderpath__$Inc)$g__armory_renderpath_Inc;
	r6 = r7->path;
	if( r6 == NULL ) hl_null_access();
	r2 = r6->light;
	if( r2 == NULL ) hl_null_access();
	r13 = r2->data;
	if( r13 == NULL ) hl_null_access();
	r12 = r13->raw;
	if( r12 == NULL ) hl_null_access();
	r11 = r12->shadowmap_cube;
	r14 = r11 ? r11->v.b : 0;
	if( !r14 ) goto label$d589772_4_48;
	r7 = (armory__renderpath__$Inc)$g__armory_renderpath_Inc;
	r6 = r7->path;
	if( r6 == NULL ) hl_null_access();
	r2 = r6->light;
	if( r2 == NULL ) hl_null_access();
	r13 = r2->data;
	if( r13 == NULL ) hl_null_access();
	r12 = r13->raw;
	if( r12 == NULL ) hl_null_access();
	r15 = r12->shadowmap_size;
	r16 = (iron__RenderTargetRaw)hl_alloc_obj(&$t_iron_RenderTargetRaw);
	iron_RenderTargetRaw_new(r16);
	r16->name = r1;
	r18 = r15 ? r15->v.i : 0;
	r16->width = r18;
	r18 = r15 ? r15->v.i : 0;
	r16->height = r18;
	r8 = (String)$s_DEPTH16;
	r16->format = r8;
	r14 = true;
	r11 = hl_alloc_dynbool(r14);
	r16->is_cubemap = r11;
	r7 = (armory__renderpath__$Inc)$g__armory_renderpath_Inc;
	r6 = r7->path;
	if( r6 == NULL ) hl_null_access();
	r10 = iron_RenderPath_createRenderTarget(r6,r16);
	goto label$d589772_4_86;
	label$d589772_4_48:
	r7 = (armory__renderpath__$Inc)$g__armory_renderpath_Inc;
	r6 = r7->path;
	if( r6 == NULL ) hl_null_access();
	r2 = r6->light;
	if( r2 == NULL ) hl_null_access();
	r13 = r2->data;
	if( r13 == NULL ) hl_null_access();
	r12 = r13->raw;
	if( r12 == NULL ) hl_null_access();
	r15 = r12->shadowmap_size;
	r17 = r15;
	if( r0 == NULL ) hl_null_access();
	r13 = r0->data;
	if( r13 == NULL ) hl_null_access();
	r12 = r13->raw;
	if( r12 == NULL ) hl_null_access();
	r8 = r12->type;
	r19 = (String)$s_sun;
	if( r8 != r19 && (!r8 || !r19 || String___compare(r8,(vdynamic*)r19) != 0) ) goto label$d589772_4_73;
	r18 = r15 ? r15->v.i : 0;
	r22 = (iron__object__$LightObject)$g__iron_object_LightObject;
	r21 = r22->cascadeCount;
	r18 = r18 * r21;
	r20 = hl_alloc_dynamic(&$t_i32);
	r20->v.i = r18;
	r15 = r20;
	label$d589772_4_73:
	r16 = (iron__RenderTargetRaw)hl_alloc_obj(&$t_iron_RenderTargetRaw);
	iron_RenderTargetRaw_new(r16);
	r16->name = r1;
	r18 = r15 ? r15->v.i : 0;
	r16->width = r18;
	r18 = r17 ? r17->v.i : 0;
	r16->height = r18;
	r8 = (String)$s_DEPTH16;
	r16->format = r8;
	r7 = (armory__renderpath__$Inc)$g__armory_renderpath_Inc;
	r6 = r7->path;
	if( r6 == NULL ) hl_null_access();
	r10 = iron_RenderPath_createRenderTarget(r6,r16);
	label$d589772_4_86:
	return r1;
}

void armory_renderpath_Inc_drawShadowMap() {
	String r17, r21, r26;
	iron__data__TLightData r14;
	hl__types__ArrayObj r3, r8;
	bool r12;
	iron__$Scene r5;
	iron__Scene r4;
	iron__data__LightData r15;
	iron__object__LightObject r9;
	double r24;
	double *r22;
	vdynamic *r10, *r13, *r23, *r25;
	iron__RenderPath r16;
	varray *r11;
	armory__renderpath__$Inc r1;
	int r0, r6, r7, r18, r19, r20;
	r0 = 0;
	r1 = (armory__renderpath__$Inc)$g__armory_renderpath_Inc;
	r1->pointIndex = r0;
	r0 = 0;
	r1 = (armory__renderpath__$Inc)$g__armory_renderpath_Inc;
	r1->spotIndex = r0;
	r0 = 0;
	r5 = (iron__$Scene)$g__iron_Scene;
	r4 = r5->active;
	if( r4 == NULL ) hl_null_access();
	r3 = r4->lights;
	label$d589772_5_11:
	if( r3 == NULL ) hl_null_access();
	r7 = r3->length;
	if( r0 >= r7 ) goto label$d589772_5_117;
	r7 = r3->length;
	if( ((unsigned)r0) < ((unsigned)r7) ) goto label$d589772_5_19;
	r9 = NULL;
	goto label$d589772_5_22;
	label$d589772_5_19:
	r11 = r3->array;
	r10 = ((vdynamic**)(r11 + 1))[r0];
	r9 = (iron__object__LightObject)r10;
	label$d589772_5_22:
	++r0;
	if( r9 == NULL ) hl_null_access();
	r12 = r9->visible;
	if( !r12 ) goto label$d589772_5_33;
	r15 = r9->data;
	if( r15 == NULL ) hl_null_access();
	r14 = r15->raw;
	if( r14 == NULL ) hl_null_access();
	r13 = r14->cast_shadow;
	r12 = r13 ? r13->v.b : 0;
	if( r12 ) goto label$d589772_5_34;
	label$d589772_5_33:
	goto label$d589772_5_11;
	label$d589772_5_34:
	r1 = (armory__renderpath__$Inc)$g__armory_renderpath_Inc;
	r16 = r1->path;
	if( r16 == NULL ) hl_null_access();
	r16->light = r9;
	r17 = armory_renderpath_Inc_getShadowMap(r9);
	r15 = r9->data;
	if( r15 == NULL ) hl_null_access();
	r14 = r15->raw;
	if( r14 == NULL ) hl_null_access();
	r13 = r14->shadowmap_cube;
	r12 = r13 ? r13->v.b : 0;
	if( !r12 ) goto label$d589772_5_48;
	r6 = 6;
	goto label$d589772_5_49;
	label$d589772_5_48:
	r6 = 1;
	label$d589772_5_49:
	r7 = 0;
	r18 = r6;
	label$d589772_5_51:
	if( r7 >= r18 ) goto label$d589772_5_80;
	r19 = r7;
	++r7;
	r20 = 1;
	if( r20 >= r6 ) goto label$d589772_5_61;
	r1 = (armory__renderpath__$Inc)$g__armory_renderpath_Inc;
	r16 = r1->path;
	if( r16 == NULL ) hl_null_access();
	r16->currentFace = r19;
	label$d589772_5_61:
	r1 = (armory__renderpath__$Inc)$g__armory_renderpath_Inc;
	r16 = r1->path;
	if( r16 == NULL ) hl_null_access();
	r8 = NULL;
	r22 = NULL;
	iron_RenderPath_setTarget(r16,r17,r8,r22);
	r1 = (armory__renderpath__$Inc)$g__armory_renderpath_Inc;
	r16 = r1->path;
	if( r16 == NULL ) hl_null_access();
	r23 = NULL;
	r24 = 1.;
	r25 = hl_alloc_dynamic(&$t_f64);
	r25->v.d = r24;
	iron_RenderPath_clearTarget(r16,r23,r25);
	r1 = (armory__renderpath__$Inc)$g__armory_renderpath_Inc;
	r16 = r1->path;
	if( r16 == NULL ) hl_null_access();
	r21 = (String)$s_shadowmap;
	iron_RenderPath_drawMeshes(r16,r21);
	goto label$d589772_5_51;
	label$d589772_5_80:
	r1 = (armory__renderpath__$Inc)$g__armory_renderpath_Inc;
	r16 = r1->path;
	if( r16 == NULL ) hl_null_access();
	r7 = -1;
	r16->currentFace = r7;
	if( r9 == NULL ) hl_null_access();
	r15 = r9->data;
	if( r15 == NULL ) hl_null_access();
	r14 = r15->raw;
	if( r14 == NULL ) hl_null_access();
	r21 = r14->type;
	r26 = (String)$s_point;
	if( r21 != r26 && (!r21 || !r26 || String___compare(r21,(vdynamic*)r26) != 0) ) goto label$d589772_5_98;
	r1 = (armory__renderpath__$Inc)$g__armory_renderpath_Inc;
	r7 = r1->pointIndex;
	++r7;
	r1->pointIndex = r7;
	goto label$d589772_5_116;
	label$d589772_5_98:
	r15 = r9->data;
	if( r15 == NULL ) hl_null_access();
	r14 = r15->raw;
	if( r14 == NULL ) hl_null_access();
	r21 = r14->type;
	r26 = (String)$s_spot;
	if( r21 == r26 || (r21 && r26 && String___compare(r21,(vdynamic*)r26) == 0) ) goto label$d589772_5_112;
	r15 = r9->data;
	if( r15 == NULL ) hl_null_access();
	r14 = r15->raw;
	if( r14 == NULL ) hl_null_access();
	r21 = r14->type;
	r26 = (String)$s_area;
	if( r21 != r26 && (!r21 || !r26 || String___compare(r21,(vdynamic*)r26) != 0) ) goto label$d589772_5_116;
	label$d589772_5_112:
	r1 = (armory__renderpath__$Inc)$g__armory_renderpath_Inc;
	r7 = r1->spotIndex;
	++r7;
	r1->spotIndex = r7;
	label$d589772_5_116:
	goto label$d589772_5_11;
	label$d589772_5_117:
	return;
}

