// Generated by HLC 4.0.0 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <armory/renderpath/RenderPathCreator.h>
void armory_renderpath_RenderPathDeferred_commands(void);
extern hl_type $t_fun_7b48b4f;
extern hl_type $t_iron_RenderPath;
void iron_RenderPath_new(iron__RenderPath);
extern armory__renderpath__$RenderPathCreator $g_b7ec311;
void armory_renderpath_Inc_init(iron__RenderPath);
void armory_renderpath_RenderPathDeferred_init(iron__RenderPath);

iron__RenderPath armory_renderpath_RenderPathCreator_get() {
	armory__renderpath__$RenderPathCreator r2;
	vclosure *r3;
	iron__RenderPath r0;
	static vclosure cl$0 = { &$t_fun_7b48b4f, armory_renderpath_RenderPathDeferred_commands, 0 };
	r0 = (iron__RenderPath)hl_alloc_obj(&$t_iron_RenderPath);
	iron_RenderPath_new(r0);
	r2 = (armory__renderpath__$RenderPathCreator)$g_b7ec311;
	r2->path = r0;
	r2 = (armory__renderpath__$RenderPathCreator)$g_b7ec311;
	r0 = r2->path;
	armory_renderpath_Inc_init(r0);
	r2 = (armory__renderpath__$RenderPathCreator)$g_b7ec311;
	r0 = r2->path;
	armory_renderpath_RenderPathDeferred_init(r0);
	r2 = (armory__renderpath__$RenderPathCreator)$g_b7ec311;
	r0 = r2->path;
	if( r0 == NULL ) hl_null_access();
	r3 = &cl$0;
	r0->commands = r3;
	r2 = (armory__renderpath__$RenderPathCreator)$g_b7ec311;
	r0 = r2->path;
	return r0;
}

