// Generated by HLC 4.0.0 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <iron/Trait.h>
void iron_object_Object_removeTrait(iron__object__Object,iron__Trait);
extern hl_type t$fun_7b48b4f;
#include <hl/natives.h>
hl__types__ArrayObj hl_types_ArrayObj_alloc(varray*);
int hl_types_ArrayObj_push(hl__types__ArrayObj,vdynamic*);
void iron_App_notifyOnUpdate(vclosure*);
#include <kha/graphics2/Graphics.h>
extern hl_type t$fun_0e31624;
void iron_App_notifyOnRender2D(vclosure*);

void iron_Trait_remove(iron__Trait r0) {
	iron__object__Object r2;
	r2 = r0->object;
	if( r2 == NULL ) hl_null_access();
	iron_object_Object_removeTrait(r2,r0);
	return;
}

void iron_Trait_notifyOnUpdate(iron__Trait r0,vclosure* r1) {
	hl__types__ArrayObj r3;
	hl_type *r5;
	int r6;
	varray *r4;
	r3 = r0->_update;
	if( r3 ) goto label$bf1c181_2_7;
	r5 = &t$fun_7b48b4f;
	r6 = 0;
	r4 = hl_alloc_array(r5,r6);
	r3 = hl_types_ArrayObj_alloc(r4);
	r0->_update = r3;
	label$bf1c181_2_7:
	r3 = r0->_update;
	if( r3 == NULL ) hl_null_access();
	r6 = hl_types_ArrayObj_push(r3,((vdynamic*)r1));
	iron_App_notifyOnUpdate(r1);
	return;
}

void iron_Trait_notifyOnRender2D(iron__Trait r0,vclosure* r1) {
	hl__types__ArrayObj r3;
	hl_type *r5;
	int r6;
	varray *r4;
	r3 = r0->_render2D;
	if( r3 ) goto label$bf1c181_3_7;
	r5 = &t$fun_0e31624;
	r6 = 0;
	r4 = hl_alloc_array(r5,r6);
	r3 = hl_types_ArrayObj_alloc(r4);
	r0->_render2D = r3;
	label$bf1c181_3_7:
	r3 = r0->_render2D;
	if( r3 == NULL ) hl_null_access();
	r6 = hl_types_ArrayObj_push(r3,((vdynamic*)r1));
	iron_App_notifyOnRender2D(r1);
	return;
}

void iron_Trait_new(iron__Trait r0) {
	hl__types__ArrayObj r1;
	r1 = NULL;
	r0->_render2D = r1;
	r1 = NULL;
	r0->_render = r1;
	r1 = NULL;
	r0->_lateUpdate = r1;
	r1 = NULL;
	r0->_update = r1;
	r1 = NULL;
	r0->_remove = r1;
	r1 = NULL;
	r0->_init = r1;
	r1 = NULL;
	r0->_add = r1;
	return;
}

