// Generated by HLC 4.0.0 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <iron/system/Input.h>
extern iron__system__$Input $g__iron_system_Input;
void iron_system_Mouse_reset(iron__system__Mouse);
void iron_system_Pen_reset(iron__system__Pen);
void iron_system_Keyboard_reset(iron__system__Keyboard);
void iron_system_Gamepad_reset(iron__system__Gamepad);
#include <iron/system/VirtualButton.h>
void iron_system_Mouse_endFrame(iron__system__Mouse);
void iron_system_Pen_endFrame(iron__system__Pen);
void iron_system_Keyboard_endFrame(iron__system__Keyboard);
void iron_system_Gamepad_endFrame(iron__system__Gamepad);
vvirtual* haxe_ds_StringMap_iterator(haxe__ds__StringMap);
extern hl_type $t_vrt_feadf90;
extern hl_type $t_fun_bf7849e;
extern hl_type $t_fun_c51a9c7;
extern hl_type $t_fun_7b48b4f;
void iron_App_notifyOnEndFrame(vclosure*);
void iron_App_notifyOnReset(vclosure*);
extern hl_type $t_iron_system_Gamepad;
void iron_system_Gamepad_new(iron__system__Gamepad,int,bool*);
int hl_types_ArrayObj_push(hl__types__ArrayObj,vdynamic*);

void iron_system_Input_reset() {
	hl__types__ArrayObj r7;
	iron__system__Gamepad r9;
	bool r0;
	iron__system__Mouse r3;
	iron__system__Keyboard r5;
	iron__system__Pen r4;
	vdynamic *r10;
	iron__system__$Input r1;
	varray *r11;
	int r6, r8;
	r0 = false;
	r1 = (iron__system__$Input)$g__iron_system_Input;
	r1->occupied = r0;
	r1 = (iron__system__$Input)$g__iron_system_Input;
	r3 = r1->mouse;
	if( !r3 ) goto label$bf59d00_1_10;
	r1 = (iron__system__$Input)$g__iron_system_Input;
	r3 = r1->mouse;
	if( r3 == NULL ) hl_null_access();
	iron_system_Mouse_reset(r3);
	label$bf59d00_1_10:
	r1 = (iron__system__$Input)$g__iron_system_Input;
	r4 = r1->pen;
	if( !r4 ) goto label$bf59d00_1_17;
	r1 = (iron__system__$Input)$g__iron_system_Input;
	r4 = r1->pen;
	if( r4 == NULL ) hl_null_access();
	iron_system_Pen_reset(r4);
	label$bf59d00_1_17:
	r1 = (iron__system__$Input)$g__iron_system_Input;
	r5 = r1->keyboard;
	if( !r5 ) goto label$bf59d00_1_24;
	r1 = (iron__system__$Input)$g__iron_system_Input;
	r5 = r1->keyboard;
	if( r5 == NULL ) hl_null_access();
	iron_system_Keyboard_reset(r5);
	label$bf59d00_1_24:
	r6 = 0;
	r1 = (iron__system__$Input)$g__iron_system_Input;
	r7 = r1->gamepads;
	label$bf59d00_1_27:
	if( r7 == NULL ) hl_null_access();
	r8 = r7->length;
	if( r6 >= r8 ) goto label$bf59d00_1_42;
	r8 = r7->length;
	if( ((unsigned)r6) < ((unsigned)r8) ) goto label$bf59d00_1_35;
	r9 = NULL;
	goto label$bf59d00_1_38;
	label$bf59d00_1_35:
	r11 = r7->array;
	r10 = ((vdynamic**)(r11 + 1))[r6];
	r9 = (iron__system__Gamepad)r10;
	label$bf59d00_1_38:
	++r6;
	if( r9 == NULL ) hl_null_access();
	iron_system_Gamepad_reset(r9);
	goto label$bf59d00_1_27;
	label$bf59d00_1_42:
	return;
}

void iron_system_Input_endFrame() {
	vvirtual *r12, *r13;
	haxe__ds__StringMap r11;
	hl__types__ArrayObj r6;
	bool r14;
	iron__system__Gamepad r8;
	iron__system__VirtualButton r15;
	iron__system__Mouse r1;
	iron__system__Keyboard r4;
	iron__system__Pen r3;
	vdynamic *r9;
	iron__system__$Input r2;
	varray *r10;
	int r5, r7;
	r2 = (iron__system__$Input)$g__iron_system_Input;
	r1 = r2->mouse;
	if( !r1 ) goto label$bf59d00_2_7;
	r2 = (iron__system__$Input)$g__iron_system_Input;
	r1 = r2->mouse;
	if( r1 == NULL ) hl_null_access();
	iron_system_Mouse_endFrame(r1);
	label$bf59d00_2_7:
	r2 = (iron__system__$Input)$g__iron_system_Input;
	r3 = r2->pen;
	if( !r3 ) goto label$bf59d00_2_14;
	r2 = (iron__system__$Input)$g__iron_system_Input;
	r3 = r2->pen;
	if( r3 == NULL ) hl_null_access();
	iron_system_Pen_endFrame(r3);
	label$bf59d00_2_14:
	r2 = (iron__system__$Input)$g__iron_system_Input;
	r4 = r2->keyboard;
	if( !r4 ) goto label$bf59d00_2_21;
	r2 = (iron__system__$Input)$g__iron_system_Input;
	r4 = r2->keyboard;
	if( r4 == NULL ) hl_null_access();
	iron_system_Keyboard_endFrame(r4);
	label$bf59d00_2_21:
	r5 = 0;
	r2 = (iron__system__$Input)$g__iron_system_Input;
	r6 = r2->gamepads;
	label$bf59d00_2_24:
	if( r6 == NULL ) hl_null_access();
	r7 = r6->length;
	if( r5 >= r7 ) goto label$bf59d00_2_39;
	r7 = r6->length;
	if( ((unsigned)r5) < ((unsigned)r7) ) goto label$bf59d00_2_32;
	r8 = NULL;
	goto label$bf59d00_2_35;
	label$bf59d00_2_32:
	r10 = r6->array;
	r9 = ((vdynamic**)(r10 + 1))[r5];
	r8 = (iron__system__Gamepad)r9;
	label$bf59d00_2_35:
	++r5;
	if( r8 == NULL ) hl_null_access();
	iron_system_Gamepad_endFrame(r8);
	goto label$bf59d00_2_24;
	label$bf59d00_2_39:
	r2 = (iron__system__$Input)$g__iron_system_Input;
	r11 = r2->virtualButtons;
	if( !r11 ) goto label$bf59d00_2_57;
	r2 = (iron__system__$Input)$g__iron_system_Input;
	r11 = r2->virtualButtons;
	if( r11 == NULL ) hl_null_access();
	r12 = haxe_ds_StringMap_iterator(r11);
	r13 = hl_to_virtual(&$t_vrt_feadf90,(vdynamic*)r12);
	label$bf59d00_2_47:
	if( r13 == NULL ) hl_null_access();
	if( hl_vfields(r13)[0] ) r14 = ((bool (*)(vdynamic*))hl_vfields(r13)[0])(r13->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r13->value,&$t_fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r14 = (bool)ret.v.i;
	}
	if( !r14 ) goto label$bf59d00_2_57;
	if( hl_vfields(r13)[1] ) r15 = ((iron__system__VirtualButton (*)(vdynamic*))hl_vfields(r13)[1])(r13->value); else {
		r15 = (iron__system__VirtualButton)hl_dyn_call_obj(r13->value,&$t_fun_c51a9c7,151160317/*next*/,NULL,NULL);
	}
	if( r15 == NULL ) hl_null_access();
	r14 = false;
	r15->released = r14;
	r15->started = r14;
	goto label$bf59d00_2_47;
	label$bf59d00_2_57:
	return;
}

iron__system__Gamepad iron_system_Input_getGamepad(int* r0) {
	bool *r12;
	hl__types__ArrayObj r10, r11;
	bool r7;
	iron__system__Gamepad r5;
	vclosure *r9;
	iron__system__$Input r8;
	vdynamic *r6;
	varray *r13;
	int r1, r3, r4;
	static vclosure cl$0 = { &$t_fun_7b48b4f, iron_system_Input_endFrame, 0 };
	static vclosure cl$1 = { &$t_fun_7b48b4f, iron_system_Input_reset, 0 };
	if( r0 ) goto label$bf59d00_3_3;
	r1 = 0;
	goto label$bf59d00_3_4;
	label$bf59d00_3_3:
	r1 = *r0;
	label$bf59d00_3_4:
	r4 = 4;
	if( r1 < r4 ) goto label$bf59d00_3_8;
	r5 = NULL;
	return r5;
	label$bf59d00_3_8:
	r8 = (iron__system__$Input)$g__iron_system_Input;
	r7 = r8->registered;
	if( r7 ) goto label$bf59d00_3_18;
	r7 = true;
	r8 = (iron__system__$Input)$g__iron_system_Input;
	r8->registered = r7;
	r9 = &cl$0;
	iron_App_notifyOnEndFrame(r9);
	r9 = &cl$1;
	iron_App_notifyOnReset(r9);
	label$bf59d00_3_18:
	r8 = (iron__system__$Input)$g__iron_system_Input;
	r10 = r8->gamepads;
	if( r10 == NULL ) hl_null_access();
	r3 = r10->length;
	if( r1 < r3 ) goto label$bf59d00_3_36;
	r8 = (iron__system__$Input)$g__iron_system_Input;
	r10 = r8->gamepads;
	if( r10 == NULL ) hl_null_access();
	r5 = (iron__system__Gamepad)hl_alloc_obj(&$t_iron_system_Gamepad);
	r8 = (iron__system__$Input)$g__iron_system_Input;
	r11 = r8->gamepads;
	if( r11 == NULL ) hl_null_access();
	r3 = r11->length;
	r12 = NULL;
	iron_system_Gamepad_new(r5,r3,r12);
	r3 = hl_types_ArrayObj_push(r10,((vdynamic*)r5));
	goto label$bf59d00_3_18;
	label$bf59d00_3_36:
	r8 = (iron__system__$Input)$g__iron_system_Input;
	r10 = r8->gamepads;
	if( r10 == NULL ) hl_null_access();
	r4 = r10->length;
	if( ((unsigned)r1) < ((unsigned)r4) ) goto label$bf59d00_3_43;
	r5 = NULL;
	goto label$bf59d00_3_46;
	label$bf59d00_3_43:
	r13 = r10->array;
	r6 = ((vdynamic**)(r13 + 1))[r1];
	r5 = (iron__system__Gamepad)r6;
	label$bf59d00_3_46:
	if( r5 == NULL ) hl_null_access();
	r7 = r5->connected;
	if( !r7 ) goto label$bf59d00_3_60;
	r8 = (iron__system__$Input)$g__iron_system_Input;
	r10 = r8->gamepads;
	if( r10 == NULL ) hl_null_access();
	r4 = r10->length;
	if( ((unsigned)r1) < ((unsigned)r4) ) goto label$bf59d00_3_56;
	r5 = NULL;
	goto label$bf59d00_3_59;
	label$bf59d00_3_56:
	r13 = r10->array;
	r6 = ((vdynamic**)(r13 + 1))[r1];
	r5 = (iron__system__Gamepad)r6;
	label$bf59d00_3_59:
	return r5;
	label$bf59d00_3_60:
	r5 = NULL;
	return r5;
}

