// Generated by HLC 4.0.0 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <zui/Handle.h>
extern hl_type t$haxe_ds_IntMap;
void haxe_ds_IntMap_new(haxe__ds__IntMap);
vdynamic* haxe_ds_IntMap_get(haxe__ds__IntMap,int);
extern hl_type t$vrt_b840ca7;
extern hl_type t$zui_Handle;
void zui_Handle_new(zui__Handle,vvirtual*);
void haxe_ds_IntMap_set(haxe__ds__IntMap,int,vdynamic*);
extern String s$;
extern hl_type t$nul_bool;
extern hl_type t$nul_i32;
extern hl_type t$nul_f64;
extern hl_type t$String;

zui__Handle zui_Handle_nest(zui__Handle r0,int r1,vvirtual* r2) {
	vvirtual *r8;
	haxe__ds__IntMap r4;
	zui__Handle r6, r7;
	vdynamic *r5;
	r4 = r0->children;
	if( r4 ) goto label$7b42a9f_1_5;
	r4 = (haxe__ds__IntMap)hl_alloc_obj(&t$haxe_ds_IntMap);
	haxe_ds_IntMap_new(r4);
	r0->children = r4;
	label$7b42a9f_1_5:
	r4 = r0->children;
	if( r4 == NULL ) hl_null_access();
	r5 = haxe_ds_IntMap_get(r4,r1);
	r6 = (zui__Handle)r5;
	if( r6 ) goto label$7b42a9f_1_24;
	r4 = r0->children;
	if( r4 ) goto label$7b42a9f_1_14;
	r8 = NULL;
	goto label$7b42a9f_1_18;
	label$7b42a9f_1_14:
	r8 = r4->f$1;
	if( r8 ) goto label$7b42a9f_1_18;
	r8 = hl_to_virtual(&t$vrt_b840ca7,(vdynamic*)r4);
	r4->f$1 = r8;
	label$7b42a9f_1_18:
	r7 = (zui__Handle)hl_alloc_obj(&t$zui_Handle);
	zui_Handle_new(r7,r2);
	r6 = r7;
	r4 = (haxe__ds__IntMap)hl_dyn_castp(&r8,&t$vrt_b840ca7,&t$haxe_ds_IntMap);
	if( r4 == NULL ) hl_null_access();
	haxe_ds_IntMap_set(r4,r1,((vdynamic*)r7));
	label$7b42a9f_1_24:
	return r6;
}

void zui_Handle_new(zui__Handle r0,vvirtual* r1) {
	String r6;
	kha__Image r5;
	bool r2;
	double r4;
	vdynamic *r8, *r9, *r10;
	int r3;
	r2 = false;
	r0->changed = r2;
	r3 = 0;
	r0->dragY = r3;
	r3 = 0;
	r0->dragX = r3;
	r2 = false;
	r0->dragEnabled = r2;
	r4 = 0.;
	r0->lastMaxY = r4;
	r4 = 0.;
	r0->lastMaxX = r4;
	r3 = 0;
	r0->layout = r3;
	r2 = false;
	r0->scrollEnabled = r2;
	r4 = 0.;
	r0->scrollOffset = r4;
	r3 = 2;
	r0->redraws = r3;
	r5 = NULL;
	r0->texture = r5;
	r6 = (String)s$;
	r0->text = r6;
	r4 = 0.;
	r0->value = r4;
	r3 = -1;
	r0->color = r3;
	r3 = 0;
	r0->position = r3;
	r2 = false;
	r0->selected = r2;
	if( !r1 ) goto label$7b42a9f_2_63;
	if( r1 == NULL ) hl_null_access();
	r8 = hl_vfields(r1)[3] ? (*(vdynamic**)(hl_vfields(r1)[3])) : (vdynamic*)hl_dyn_getp(r1->value,-244504239/*selected*/,&t$nul_bool);
	if( !r8 ) goto label$7b42a9f_2_39;
	r8 = hl_vfields(r1)[3] ? (*(vdynamic**)(hl_vfields(r1)[3])) : (vdynamic*)hl_dyn_getp(r1->value,-244504239/*selected*/,&t$nul_bool);
	r2 = r8 ? r8->v.b : 0;
	r0->selected = r2;
	label$7b42a9f_2_39:
	r9 = hl_vfields(r1)[2] ? (*(vdynamic**)(hl_vfields(r1)[2])) : (vdynamic*)hl_dyn_getp(r1->value,-352673756/*position*/,&t$nul_i32);
	if( !r9 ) goto label$7b42a9f_2_44;
	r9 = hl_vfields(r1)[2] ? (*(vdynamic**)(hl_vfields(r1)[2])) : (vdynamic*)hl_dyn_getp(r1->value,-352673756/*position*/,&t$nul_i32);
	r3 = r9 ? r9->v.i : 0;
	r0->position = r3;
	label$7b42a9f_2_44:
	r10 = hl_vfields(r1)[5] ? (*(vdynamic**)(hl_vfields(r1)[5])) : (vdynamic*)hl_dyn_getp(r1->value,297304054/*value*/,&t$nul_f64);
	if( !r10 ) goto label$7b42a9f_2_49;
	r10 = hl_vfields(r1)[5] ? (*(vdynamic**)(hl_vfields(r1)[5])) : (vdynamic*)hl_dyn_getp(r1->value,297304054/*value*/,&t$nul_f64);
	r4 = r10 ? r10->v.d : 0;
	r0->value = r4;
	label$7b42a9f_2_49:
	r6 = hl_vfields(r1)[4] ? (*(String*)(hl_vfields(r1)[4])) : (String)hl_dyn_getp(r1->value,217697719/*text*/,&t$String);
	if( !r6 ) goto label$7b42a9f_2_53;
	r6 = hl_vfields(r1)[4] ? (*(String*)(hl_vfields(r1)[4])) : (String)hl_dyn_getp(r1->value,217697719/*text*/,&t$String);
	r0->text = r6;
	label$7b42a9f_2_53:
	r9 = hl_vfields(r1)[0] ? (*(vdynamic**)(hl_vfields(r1)[0])) : (vdynamic*)hl_dyn_getp(r1->value,173830765/*color*/,&t$nul_i32);
	if( !r9 ) goto label$7b42a9f_2_58;
	r9 = hl_vfields(r1)[0] ? (*(vdynamic**)(hl_vfields(r1)[0])) : (vdynamic*)hl_dyn_getp(r1->value,173830765/*color*/,&t$nul_i32);
	r3 = r9 ? r9->v.i : 0;
	r0->color = r3;
	label$7b42a9f_2_58:
	r9 = hl_vfields(r1)[1] ? (*(vdynamic**)(hl_vfields(r1)[1])) : (vdynamic*)hl_dyn_getp(r1->value,414756788/*layout*/,&t$nul_i32);
	if( !r9 ) goto label$7b42a9f_2_63;
	r9 = hl_vfields(r1)[1] ? (*(vdynamic**)(hl_vfields(r1)[1])) : (vdynamic*)hl_dyn_getp(r1->value,414756788/*layout*/,&t$nul_i32);
	r3 = r9 ? r9->v.i : 0;
	r0->layout = r3;
	label$7b42a9f_2_63:
	return;
}

