// Generated by HLC 4.0.0 (HL v4)
#ifndef INC_iron__data__TGroup
#define INC_iron__data__TGroup
typedef struct _iron__data__$TGroup *iron__data__$TGroup;
typedef struct _iron__data__TGroup *iron__data__TGroup;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <hl/types/ArrayObj.h>


struct _iron__data__$TGroup {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
};
struct _iron__data__TGroup {
	hl_type *$type;
	String name;
	hl__types__ArrayObj object_refs;
};
#endif

