// Generated by HLC 4.0.0 (HL v4)
#ifndef INC_iron__data__TLightData
#define INC_iron__data__TLightData
typedef struct _iron__data__$TLightData *iron__data__$TLightData;
typedef struct _iron__data__TLightData *iron__data__TLightData;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <kha/arrays/Float32ArrayPrivate.h>


struct _iron__data__$TLightData {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
};
struct _iron__data__TLightData {
	hl_type *$type;
	String name;
	String type;
	kha__arrays__Float32ArrayPrivate color;
	float strength;
	vdynamic* cast_shadow;
	vdynamic* near_plane;
	vdynamic* far_plane;
	vdynamic* fov;
	vdynamic* shadows_bias;
	vdynamic* shadowmap_size;
	vdynamic* shadowmap_cube;
	vdynamic* spot_size;
	vdynamic* spot_blend;
	vdynamic* light_size;
	vdynamic* size;
	vdynamic* size_y;
};
#endif

