// Generated by HLC 4.0.0 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <iron/data/TVertexArray.h>

void iron_data_TVertexArray_new(iron__data__TVertexArray r0,String r1,kha__arrays__Int16ArrayPrivate r2) {
	r0->attrib = r1;
	r0->values = r2;
	return;
}

