// Generated by HLC 4.0.0 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <iron/object/Tilesheet.h>
#include <iron/data/TSceneFormat.h>
#include <hl/types/ArrayObj.h>
int String___compare(String,vdynamic*);
void iron_object_Tilesheet_play(iron__object__Tilesheet,String,vclosure*);
void iron_object_Tilesheet_setFrame(iron__object__Tilesheet,int);
#include <iron/system/Time.h>
extern iron__system__$Time g$_iron_system_Time;
extern hl_type t$ctx_18cedd0;
extern hl_type t$fun_493cad1;
void iron_data_Data_getSceneRaw(String,vclosure*);

void iron_object_Tilesheet_new__$1(venum* r0,iron__data__TSceneFormat r1) {
	String r9, r10;
	iron__data__TTilesheetData r6;
	hl__types__ArrayObj r4;
	bool r13;
	iron__object__Tilesheet r11;
	vclosure *r12;
	vdynamic *r7;
	varray *r8;
	int r2, r5;
	r2 = 0;
	if( r1 == NULL ) hl_null_access();
	r4 = r1->tilesheet_datas;
	label$cb9e570_1_3:
	if( r4 == NULL ) hl_null_access();
	r5 = r4->length;
	if( r2 >= r5 ) goto label$cb9e570_1_33;
	r5 = r4->length;
	if( ((unsigned)r2) < ((unsigned)r5) ) goto label$cb9e570_1_11;
	r6 = NULL;
	goto label$cb9e570_1_14;
	label$cb9e570_1_11:
	r8 = r4->array;
	r7 = ((vdynamic**)(r8 + 1))[r2];
	r6 = (iron__data__TTilesheetData)r7;
	label$cb9e570_1_14:
	++r2;
	if( r6 == NULL ) hl_null_access();
	r9 = r6->name;
	r10 = ((Enumt$ctx_18cedd0*)r0)->p0;
	if( r9 != r10 && (!r9 || !r10 || String___compare(r9,(vdynamic*)r10) != 0) ) goto label$cb9e570_1_32;
	r11 = ((Enumt$ctx_18cedd0*)r0)->p2;
	if( r11 == NULL ) hl_null_access();
	r11->raw = r6;
	r11 = ((Enumt$ctx_18cedd0*)r0)->p2;
	if( r11 == NULL ) hl_null_access();
	r9 = ((Enumt$ctx_18cedd0*)r0)->p1;
	r12 = NULL;
	iron_object_Tilesheet_play(r11,r9,r12);
	r11 = ((Enumt$ctx_18cedd0*)r0)->p2;
	if( r11 == NULL ) hl_null_access();
	r13 = true;
	r11->ready = r13;
	goto label$cb9e570_1_33;
	label$cb9e570_1_32:
	goto label$cb9e570_1_3;
	label$cb9e570_1_33:
	return;
}

void iron_object_Tilesheet_play(iron__object__Tilesheet r0,String r1,vclosure* r2) {
	String r11;
	iron__data__TTilesheetData r6;
	hl__types__ArrayObj r5;
	bool r12;
	iron__data__TTilesheetAction r8;
	vdynamic *r9;
	varray *r10;
	int r3, r7;
	r0->onActionComplete = r2;
	r3 = 0;
	r6 = r0->raw;
	if( r6 == NULL ) hl_null_access();
	r5 = r6->actions;
	label$cb9e570_2_5:
	if( r5 == NULL ) hl_null_access();
	r7 = r5->length;
	if( r3 >= r7 ) goto label$cb9e570_2_23;
	r7 = r5->length;
	if( ((unsigned)r3) < ((unsigned)r7) ) goto label$cb9e570_2_13;
	r8 = NULL;
	goto label$cb9e570_2_16;
	label$cb9e570_2_13:
	r10 = r5->array;
	r9 = ((vdynamic**)(r10 + 1))[r3];
	r8 = (iron__data__TTilesheetAction)r9;
	label$cb9e570_2_16:
	++r3;
	if( r8 == NULL ) hl_null_access();
	r11 = r8->name;
	if( r11 != r1 && (!r11 || !r1 || String___compare(r11,(vdynamic*)r1) != 0) ) goto label$cb9e570_2_22;
	r0->action = r8;
	goto label$cb9e570_2_23;
	label$cb9e570_2_22:
	goto label$cb9e570_2_5;
	label$cb9e570_2_23:
	r8 = r0->action;
	if( r8 == NULL ) hl_null_access();
	r3 = r8->start;
	iron_object_Tilesheet_setFrame(r0,r3);
	r12 = false;
	r0->paused = r12;
	return;
}

void iron_object_Tilesheet_remove(iron__object__Tilesheet r0) {
	return;
}

void iron_object_Tilesheet_update(iron__object__Tilesheet r0) {
	iron__data__TTilesheetData r10;
	bool r2;
	iron__data__TTilesheetAction r4;
	double r6, r7, r8;
	iron__system__$Time r9;
	int r3, r5;
	r2 = r0->ready;
	if( !r2 ) goto label$cb9e570_4_11;
	r2 = r0->paused;
	if( r2 ) goto label$cb9e570_4_11;
	r4 = r0->action;
	if( r4 == NULL ) hl_null_access();
	r3 = r4->start;
	r4 = r0->action;
	if( r4 == NULL ) hl_null_access();
	r5 = r4->end;
	if( r3 < r5 ) goto label$cb9e570_4_12;
	label$cb9e570_4_11:
	return;
	label$cb9e570_4_12:
	r6 = r0->time;
	r7 = 0.016666666666666666;
	r9 = (iron__system__$Time)g$_iron_system_Time;
	r8 = r9->scale;
	r7 = r7 * r8;
	r6 = r6 + r7;
	r0->time = r6;
	r6 = r0->time;
	r7 = 1.;
	r10 = r0->raw;
	if( r10 == NULL ) hl_null_access();
	r3 = r10->framerate;
	r8 = (double)r3;
	r7 = r7 / r8;
	if( !(r6 >= r7) ) goto label$cb9e570_4_31;
	r3 = r0->frame;
	r5 = 1;
	r3 = r3 + r5;
	iron_object_Tilesheet_setFrame(r0,r3);
	label$cb9e570_4_31:
	return;
}

void iron_object_Tilesheet_setFrame(iron__object__Tilesheet r0,int r1) {
	iron__data__TTilesheetData r5;
	bool r14;
	iron__data__TTilesheetAction r12;
	vclosure *r13;
	double r3, r7, r9, r10;
	int r2, r4, r8, r11;
	r0->frame = r1;
	r3 = 0.;
	r0->time = r3;
	r2 = r0->frame;
	r5 = r0->raw;
	if( r5 == NULL ) hl_null_access();
	r4 = r5->tilesx;
	r2 = r4 == 0 ? 0 : r2 % r4;
	r4 = r0->frame;
	r3 = (double)r4;
	r5 = r0->raw;
	if( r5 == NULL ) hl_null_access();
	r4 = r5->tilesx;
	r7 = (double)r4;
	r3 = r3 / r7;
	r4 = (int)r3;
	r7 = (double)r2;
	r9 = 1.;
	r5 = r0->raw;
	if( r5 == NULL ) hl_null_access();
	r8 = r5->tilesx;
	r10 = (double)r8;
	r9 = r9 / r10;
	r7 = r7 * r9;
	r0->tileX = r7;
	r7 = (double)r4;
	r9 = 1.;
	r5 = r0->raw;
	if( r5 == NULL ) hl_null_access();
	r8 = r5->tilesy;
	r10 = (double)r8;
	r9 = r9 / r10;
	r7 = r7 * r9;
	r0->tileY = r7;
	r8 = r0->frame;
	r12 = r0->action;
	if( r12 == NULL ) hl_null_access();
	r11 = r12->end;
	if( r8 < r11 ) goto label$cb9e570_5_62;
	r12 = r0->action;
	if( r12 == NULL ) hl_null_access();
	r8 = r12->start;
	r12 = r0->action;
	if( r12 == NULL ) hl_null_access();
	r11 = r12->end;
	if( r8 >= r11 ) goto label$cb9e570_5_62;
	r13 = r0->onActionComplete;
	if( !r13 ) goto label$cb9e570_5_51;
	r13 = r0->onActionComplete;
	if( r13 == NULL ) hl_null_access();
	r13->hasValue ? ((void (*)(vdynamic*))r13->fun)((vdynamic*)r13->value) : ((void (*)(void))r13->fun)();
	label$cb9e570_5_51:
	r12 = r0->action;
	if( r12 == NULL ) hl_null_access();
	r14 = r12->loop;
	if( !r14 ) goto label$cb9e570_5_60;
	r12 = r0->action;
	if( r12 == NULL ) hl_null_access();
	r8 = r12->start;
	iron_object_Tilesheet_setFrame(r0,r8);
	goto label$cb9e570_5_62;
	label$cb9e570_5_60:
	r14 = true;
	r0->paused = r14;
	label$cb9e570_5_62:
	return;
}

void iron_object_Tilesheet_new(iron__object__Tilesheet r0,String r1,String r2,String r3) {
	venum *r11;
	bool r7;
	iron__data__TTilesheetAction r8;
	double r5;
	vclosure *r4, *r10;
	int r6;
	r4 = NULL;
	r0->onActionComplete = r4;
	r5 = 0.;
	r0->time = r5;
	r6 = 0;
	r0->frame = r6;
	r7 = false;
	r0->paused = r7;
	r8 = NULL;
	r0->action = r8;
	r5 = 0.;
	r0->tileY = r5;
	r5 = 0.;
	r0->tileX = r5;
	r7 = false;
	r0->ready = r7;
	r11 = hl_alloc_enum(&t$ctx_18cedd0,0);
	((Enumt$ctx_18cedd0*)r11)->p0 = (String)r2;
	((Enumt$ctx_18cedd0*)r11)->p1 = (String)r3;
	((Enumt$ctx_18cedd0*)r11)->p2 = (iron__object__Tilesheet)r0;
	r10 = hl_alloc_closure_ptr(&t$fun_493cad1,iron_object_Tilesheet_new__$1,r11);
	iron_data_Data_getSceneRaw(r1,r10);
	return;
}

