// Generated by HLC 4.0.0 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <kha/arrays/Float32ArrayPrivate.h>

void kha_arrays_Float32ArrayPrivate_new(kha__arrays__Float32ArrayPrivate r0) {
	return;
}

