// Generated by HLC 4.0.0 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <kha/audio2/ogg/vorbis/data/Mode.h>
#include <kha/audio2/ogg/vorbis/data/ReaderError.h>
#include <kha/audio2/ogg/vorbis/data/ReaderErrorType.h>
#include <hl/types/ArrayDyn.h>
extern hl_type $t_kha_audio2_ogg_vorbis_data_Mode;
int kha_audio2_ogg_vorbis_VorbisDecodeState_readBits(kha__audio2__ogg__vorbis__VorbisDecodeState,int);
extern hl_type $t_kha_audio2_ogg_vorbis_data_ReaderError;
extern venum* $g_b94286b;
extern hl_type $t_vrt_329ffa8;
extern String $s_1b4ef39;
extern hl_type $t_String;
extern hl_type $t_i32;
extern String $s_kha_audio2_ogg_vorbis_data_Mode;
extern String $s_read;
extern hl_type $t_vrt_eaa6a3b;
void kha_audio2_ogg_vorbis_data_ReaderError_new(kha__audio2__ogg__vorbis__data__ReaderError,venum*,String,vvirtual*);

void kha_audio2_ogg_vorbis_data_Mode_new(kha__audio2__ogg__vorbis__data__Mode r0) {
	return;
}

kha__audio2__ogg__vorbis__data__Mode kha_audio2_ogg_vorbis_data_Mode_read(kha__audio2__ogg__vorbis__VorbisDecodeState r0) {
	String r8, r10;
	vvirtual *r9, *r11;
	venum *r7;
	bool r3;
	kha__audio2__ogg__vorbis__data__Mode r1;
	kha__audio2__ogg__vorbis__data__ReaderError r6;
	int r4, r5;
	r1 = (kha__audio2__ogg__vorbis__data__Mode)hl_alloc_obj(&$t_kha_audio2_ogg_vorbis_data_Mode);
	kha_audio2_ogg_vorbis_data_Mode_new(r1);
	if( r0 == NULL ) hl_null_access();
	r4 = 1;
	r4 = kha_audio2_ogg_vorbis_VorbisDecodeState_readBits(r0,r4);
	r5 = 0;
	if( r4 != r5 ) goto label$f509af1_2_9;
	r3 = false;
	goto label$f509af1_2_10;
	label$f509af1_2_9:
	r3 = true;
	label$f509af1_2_10:
	r1->blockflag = r3;
	r4 = 16;
	r4 = kha_audio2_ogg_vorbis_VorbisDecodeState_readBits(r0,r4);
	r1->windowtype = r4;
	r4 = 16;
	r4 = kha_audio2_ogg_vorbis_VorbisDecodeState_readBits(r0,r4);
	r1->transformtype = r4;
	r4 = 8;
	r4 = kha_audio2_ogg_vorbis_VorbisDecodeState_readBits(r0,r4);
	r1->mapping = r4;
	r4 = r1->windowtype;
	r5 = 0;
	if( r4 == r5 ) goto label$f509af1_2_38;
	r6 = (kha__audio2__ogg__vorbis__data__ReaderError)hl_alloc_obj(&$t_kha_audio2_ogg_vorbis_data_ReaderError);
	r7 = (venum*)$g_b94286b;
	r8 = NULL;
	r9 = hl_alloc_virtual(&$t_vrt_329ffa8);
	r10 = (String)$s_1b4ef39;
	if( hl_vfields(r9)[1] ) *(String*)(hl_vfields(r9)[1]) = (String)r10; else hl_dyn_setp(r9->value,37969014/*fileName*/,&$t_String,r10);
	r4 = 22;
	if( hl_vfields(r9)[2] ) *(int*)(hl_vfields(r9)[2]) = (int)r4; else hl_dyn_seti(r9->value,371360620/*lineNumber*/,&$t_i32,r4);
	r10 = (String)$s_kha_audio2_ogg_vorbis_data_Mode;
	if( hl_vfields(r9)[0] ) *(String*)(hl_vfields(r9)[0]) = (String)r10; else hl_dyn_setp(r9->value,-63073762/*className*/,&$t_String,r10);
	r10 = (String)$s_read;
	if( hl_vfields(r9)[3] ) *(String*)(hl_vfields(r9)[3]) = (String)r10; else hl_dyn_setp(r9->value,302979532/*methodName*/,&$t_String,r10);
	r11 = hl_to_virtual(&$t_vrt_eaa6a3b,(vdynamic*)r9);
	kha_audio2_ogg_vorbis_data_ReaderError_new(r6,r7,r8,r11);
	hl_throw((vdynamic*)r6);
	label$f509af1_2_38:
	r4 = r1->transformtype;
	r5 = 0;
	if( r4 == r5 ) goto label$f509af1_2_56;
	r6 = (kha__audio2__ogg__vorbis__data__ReaderError)hl_alloc_obj(&$t_kha_audio2_ogg_vorbis_data_ReaderError);
	r7 = (venum*)$g_b94286b;
	r8 = NULL;
	r9 = hl_alloc_virtual(&$t_vrt_329ffa8);
	r10 = (String)$s_1b4ef39;
	if( hl_vfields(r9)[1] ) *(String*)(hl_vfields(r9)[1]) = (String)r10; else hl_dyn_setp(r9->value,37969014/*fileName*/,&$t_String,r10);
	r4 = 25;
	if( hl_vfields(r9)[2] ) *(int*)(hl_vfields(r9)[2]) = (int)r4; else hl_dyn_seti(r9->value,371360620/*lineNumber*/,&$t_i32,r4);
	r10 = (String)$s_kha_audio2_ogg_vorbis_data_Mode;
	if( hl_vfields(r9)[0] ) *(String*)(hl_vfields(r9)[0]) = (String)r10; else hl_dyn_setp(r9->value,-63073762/*className*/,&$t_String,r10);
	r10 = (String)$s_read;
	if( hl_vfields(r9)[3] ) *(String*)(hl_vfields(r9)[3]) = (String)r10; else hl_dyn_setp(r9->value,302979532/*methodName*/,&$t_String,r10);
	r11 = hl_to_virtual(&$t_vrt_eaa6a3b,(vdynamic*)r9);
	kha_audio2_ogg_vorbis_data_ReaderError_new(r6,r7,r8,r11);
	hl_throw((vdynamic*)r6);
	label$f509af1_2_56:
	return r1;
}

