// Generated by HLC 4.0.0 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <kha/audio2/ogg/vorbis/data/Residue.h>
#include <kha/audio2/ogg/vorbis/data/ReaderError.h>
#include <kha/audio2/ogg/vorbis/data/ReaderErrorType.h>
#include <hl/types/ArrayDyn.h>
#include <hl/types/ArrayBytes_Int.h>
#include <kha/audio2/ogg/vorbis/data/Codebook.h>
extern hl_type $t_kha_audio2_ogg_vorbis_data_Residue;
int kha_audio2_ogg_vorbis_VorbisDecodeState_readBits(kha__audio2__ogg__vorbis__VorbisDecodeState,int);
extern hl_type $t_kha_audio2_ogg_vorbis_data_ReaderError;
extern venum* $g_b94286b;
extern hl_type $t_vrt_329ffa8;
extern String $s_665fdd3;
extern hl_type $t_String;
extern hl_type $t_i32;
extern String $s_c64aefd;
extern String $s_read;
extern hl_type $t_vrt_eaa6a3b;
void kha_audio2_ogg_vorbis_data_ReaderError_new(kha__audio2__ogg__vorbis__data__ReaderError,venum*,String,vvirtual*);
#include <hl/natives.h>
hl__types__ArrayBytes_Int hl_types_ArrayBase_allocI32(vbyte*,int);
extern hl_type $t_dyn;
void hl_types_ArrayBytes_Int___expand(hl__types__ArrayBytes_Int,int);
extern hl_type $t_hl_types_ArrayBytes_Int;
hl__types__ArrayObj hl_types_ArrayObj_alloc(varray*);
void hl_types_ArrayObj___expand(hl__types__ArrayObj,int);
#include <kha/audio2/ogg/vorbis/data/Header.h>
#include <hl/types/ArrayBytes_Float.h>
extern hl_type $t_bool;
extern hl_type $t_hl_types_ArrayBytes_Float;
void hl_types_ArrayBytes_Float___expand(hl__types__ArrayBytes_Float,int);
void kha_audio2_ogg_vorbis_VorbisDecodeState_prepHuffman(kha__audio2__ogg__vorbis__VorbisDecodeState);
int kha_audio2_ogg_vorbis_VorbisDecodeState_decodeScalarRaw(kha__audio2__ogg__vorbis__VorbisDecodeState,kha__audio2__ogg__vorbis__data__Codebook);
vvirtual* kha_audio2_ogg_vorbis_data_Codebook_decodeDeinterleaveRepeat(kha__audio2__ogg__vorbis__data__Codebook,kha__audio2__ogg__vorbis__VorbisDecodeState,hl__types__ArrayObj,int,int,int,int,int);
bool kha_audio2_ogg_vorbis_data_Codebook_residueDecode(kha__audio2__ogg__vorbis__data__Codebook,kha__audio2__ogg__vorbis__VorbisDecodeState,hl__types__ArrayBytes_Float,int,int,int);

void kha_audio2_ogg_vorbis_data_Residue_new(kha__audio2__ogg__vorbis__data__Residue r0) {
	return;
}

kha__audio2__ogg__vorbis__data__Residue kha_audio2_ogg_vorbis_data_Residue_read(kha__audio2__ogg__vorbis__VorbisDecodeState r0,hl__types__ArrayObj r1) {
	String r8, r10;
	kha__audio2__ogg__vorbis__data__Codebook r30;
	hl__types__ArrayObj r24, r27, r31;
	vvirtual *r9, *r12;
	hl_type *r26;
	venum *r7;
	hl__types__ArrayBytes_Int r13, r15, r22, r28;
	kha__audio2__ogg__vorbis__data__Residue r2;
	kha__audio2__ogg__vorbis__data__ReaderError r6;
	vdynamic *r11;
	varray *r25;
	vbyte *r14;
	int r4, r5, r16, r17, r18, r19, r20, r21, r23, r29, r32, r33;
	r2 = (kha__audio2__ogg__vorbis__data__Residue)hl_alloc_obj(&$t_kha_audio2_ogg_vorbis_data_Residue);
	kha_audio2_ogg_vorbis_data_Residue_new(r2);
	if( r0 == NULL ) hl_null_access();
	r4 = 16;
	r4 = kha_audio2_ogg_vorbis_VorbisDecodeState_readBits(r0,r4);
	r2->type = r4;
	r4 = r2->type;
	r5 = 2;
	if( r5 >= r4 ) goto label$cbd4d3d_2_24;
	r6 = (kha__audio2__ogg__vorbis__data__ReaderError)hl_alloc_obj(&$t_kha_audio2_ogg_vorbis_data_ReaderError);
	r7 = (venum*)$g_b94286b;
	r8 = NULL;
	r9 = hl_alloc_virtual(&$t_vrt_329ffa8);
	r10 = (String)$s_665fdd3;
	if( hl_vfields(r9)[1] ) *(String*)(hl_vfields(r9)[1]) = (String)r10; else hl_dyn_setp(r9->value,37969014/*fileName*/,&$t_String,r10);
	r4 = 29;
	if( hl_vfields(r9)[2] ) *(int*)(hl_vfields(r9)[2]) = (int)r4; else hl_dyn_seti(r9->value,371360620/*lineNumber*/,&$t_i32,r4);
	r10 = (String)$s_c64aefd;
	if( hl_vfields(r9)[0] ) *(String*)(hl_vfields(r9)[0]) = (String)r10; else hl_dyn_setp(r9->value,-63073762/*className*/,&$t_String,r10);
	r10 = (String)$s_read;
	if( hl_vfields(r9)[3] ) *(String*)(hl_vfields(r9)[3]) = (String)r10; else hl_dyn_setp(r9->value,302979532/*methodName*/,&$t_String,r10);
	r12 = hl_to_virtual(&$t_vrt_eaa6a3b,(vdynamic*)r9);
	kha_audio2_ogg_vorbis_data_ReaderError_new(r6,r7,r8,r12);
	hl_throw((vdynamic*)r6);
	label$cbd4d3d_2_24:
	r4 = 0;
	r14 = hl_alloc_bytes(r4);
	r4 = 0;
	r4 = 0;
	r13 = hl_types_ArrayBase_allocI32(r14,r4);
	if( r13 == NULL ) hl_null_access();
	r4 = 63;
	r11 = NULL;
	r5 = (int)hl_dyn_casti(&r11,&$t_dyn,&$t_i32);
	r16 = r13->length;
	if( ((unsigned)r4) < ((unsigned)r16) ) goto label$cbd4d3d_2_36;
	hl_types_ArrayBytes_Int___expand(r13,r4);
	label$cbd4d3d_2_36:
	r14 = r13->bytes;
	r16 = 2;
	r16 = r4 << r16;
	*(int*)(r14 + r16) = r5;
	r15 = r13;
	r4 = 24;
	r4 = kha_audio2_ogg_vorbis_VorbisDecodeState_readBits(r0,r4);
	r2->begin = r4;
	r4 = 24;
	r4 = kha_audio2_ogg_vorbis_VorbisDecodeState_readBits(r0,r4);
	r2->end = r4;
	r4 = 24;
	r4 = kha_audio2_ogg_vorbis_VorbisDecodeState_readBits(r0,r4);
	r5 = 1;
	r4 = r4 + r5;
	r2->partSize = r4;
	r4 = 6;
	r4 = kha_audio2_ogg_vorbis_VorbisDecodeState_readBits(r0,r4);
	r5 = 1;
	r4 = r4 + r5;
	r2->classifications = r4;
	r5 = 8;
	r5 = kha_audio2_ogg_vorbis_VorbisDecodeState_readBits(r0,r5);
	r2->classbook = r5;
	r5 = 0;
	r16 = r2->classifications;
	label$cbd4d3d_2_62:
	if( r5 >= r16 ) goto label$cbd4d3d_2_89;
	r17 = r5;
	++r5;
	r18 = 0;
	if( r0 == NULL ) hl_null_access();
	r19 = 3;
	r19 = kha_audio2_ogg_vorbis_VorbisDecodeState_readBits(r0,r19);
	r20 = 1;
	r20 = kha_audio2_ogg_vorbis_VorbisDecodeState_readBits(r0,r20);
	r21 = 0;
	if( r20 == r21 ) goto label$cbd4d3d_2_77;
	r20 = 5;
	r20 = kha_audio2_ogg_vorbis_VorbisDecodeState_readBits(r0,r20);
	r18 = r20;
	label$cbd4d3d_2_77:
	if( r15 == NULL ) hl_null_access();
	r23 = 8;
	r21 = r18 * r23;
	r21 = r21 + r19;
	r23 = r15->length;
	if( ((unsigned)r17) < ((unsigned)r23) ) goto label$cbd4d3d_2_84;
	hl_types_ArrayBytes_Int___expand(r15,r17);
	label$cbd4d3d_2_84:
	r14 = r15->bytes;
	r23 = 2;
	r23 = r17 << r23;
	*(int*)(r14 + r23) = r21;
	goto label$cbd4d3d_2_62;
	label$cbd4d3d_2_89:
	if( r2 == NULL ) hl_null_access();
	r5 = r2->classifications;
	r26 = &$t_hl_types_ArrayBytes_Int;
	r16 = 0;
	r25 = hl_alloc_array(r26,r16);
	r24 = hl_types_ArrayObj_alloc(r25);
	r17 = 0;
	if( r17 >= r5 ) goto label$cbd4d3d_2_107;
	if( r24 == NULL ) hl_null_access();
	r17 = 1;
	r16 = r5 - r17;
	r11 = NULL;
	r22 = (hl__types__ArrayBytes_Int)hl_dyn_castp(&r11,&$t_dyn,&$t_hl_types_ArrayBytes_Int);
	r17 = r24->length;
	if( ((unsigned)r16) < ((unsigned)r17) ) goto label$cbd4d3d_2_105;
	hl_types_ArrayObj___expand(r24,r16);
	label$cbd4d3d_2_105:
	r25 = r24->array;
	((hl__types__ArrayBytes_Int*)(r25 + 1))[r16] = r22;
	label$cbd4d3d_2_107:
	r2->residueBooks = r24;
	r16 = 0;
	r17 = r2->classifications;
	label$cbd4d3d_2_110:
	if( r16 >= r17 ) goto label$cbd4d3d_2_237;
	r18 = r16;
	++r16;
	r19 = 0;
	r14 = hl_alloc_bytes(r19);
	r19 = 0;
	r19 = 0;
	r22 = hl_types_ArrayBase_allocI32(r14,r19);
	if( r22 == NULL ) hl_null_access();
	r19 = 7;
	r11 = NULL;
	r20 = (int)hl_dyn_casti(&r11,&$t_dyn,&$t_i32);
	r21 = r22->length;
	if( ((unsigned)r19) < ((unsigned)r21) ) goto label$cbd4d3d_2_126;
	hl_types_ArrayBytes_Int___expand(r22,r19);
	label$cbd4d3d_2_126:
	r14 = r22->bytes;
	r21 = 2;
	r21 = r19 << r21;
	*(int*)(r14 + r21) = r20;
	if( r2 == NULL ) hl_null_access();
	r27 = r2->residueBooks;
	if( r27 == NULL ) hl_null_access();
	r20 = r27->length;
	if( ((unsigned)r18) < ((unsigned)r20) ) goto label$cbd4d3d_2_136;
	hl_types_ArrayObj___expand(r27,r18);
	label$cbd4d3d_2_136:
	r25 = r27->array;
	((hl__types__ArrayBytes_Int*)(r25 + 1))[r18] = r22;
	r19 = 0;
	label$cbd4d3d_2_139:
	r21 = 8;
	if( r19 >= r21 ) goto label$cbd4d3d_2_236;
	r20 = r19;
	++r19;
	if( r15 == NULL ) hl_null_access();
	r23 = r15->length;
	if( ((unsigned)r18) < ((unsigned)r23) ) goto label$cbd4d3d_2_149;
	r21 = 0;
	goto label$cbd4d3d_2_153;
	label$cbd4d3d_2_149:
	r14 = r15->bytes;
	r23 = 2;
	r23 = r18 << r23;
	r21 = *(int*)(r14 + r23);
	label$cbd4d3d_2_153:
	r23 = 1;
	r23 = r23 << r20;
	r21 = r21 & r23;
	r23 = 0;
	if( r21 == r23 ) goto label$cbd4d3d_2_216;
	if( r2 == NULL ) hl_null_access();
	r27 = r2->residueBooks;
	if( r27 == NULL ) hl_null_access();
	r23 = r27->length;
	if( ((unsigned)r18) < ((unsigned)r23) ) goto label$cbd4d3d_2_165;
	r22 = NULL;
	goto label$cbd4d3d_2_168;
	label$cbd4d3d_2_165:
	r25 = r27->array;
	r11 = ((vdynamic**)(r25 + 1))[r18];
	r22 = (hl__types__ArrayBytes_Int)hl_dyn_castp(&r11,&$t_dyn,&$t_hl_types_ArrayBytes_Int);
	label$cbd4d3d_2_168:
	if( r22 == NULL ) hl_null_access();
	if( r0 == NULL ) hl_null_access();
	r23 = 8;
	r23 = kha_audio2_ogg_vorbis_VorbisDecodeState_readBits(r0,r23);
	r29 = r22->length;
	if( ((unsigned)r20) < ((unsigned)r29) ) goto label$cbd4d3d_2_175;
	hl_types_ArrayBytes_Int___expand(r22,r20);
	label$cbd4d3d_2_175:
	r14 = r22->bytes;
	r29 = 2;
	r29 = r20 << r29;
	*(int*)(r14 + r29) = r23;
	r27 = r2->residueBooks;
	if( r27 == NULL ) hl_null_access();
	r23 = r27->length;
	if( ((unsigned)r18) < ((unsigned)r23) ) goto label$cbd4d3d_2_185;
	r22 = NULL;
	goto label$cbd4d3d_2_188;
	label$cbd4d3d_2_185:
	r25 = r27->array;
	r11 = ((vdynamic**)(r25 + 1))[r18];
	r22 = (hl__types__ArrayBytes_Int)hl_dyn_castp(&r11,&$t_dyn,&$t_hl_types_ArrayBytes_Int);
	label$cbd4d3d_2_188:
	if( r22 == NULL ) hl_null_access();
	r23 = r22->length;
	if( ((unsigned)r20) < ((unsigned)r23) ) goto label$cbd4d3d_2_193;
	r21 = 0;
	goto label$cbd4d3d_2_197;
	label$cbd4d3d_2_193:
	r14 = r22->bytes;
	r23 = 2;
	r23 = r20 << r23;
	r21 = *(int*)(r14 + r23);
	label$cbd4d3d_2_197:
	if( r1 == NULL ) hl_null_access();
	r23 = r1->length;
	if( r21 < r23 ) goto label$cbd4d3d_2_215;
	r6 = (kha__audio2__ogg__vorbis__data__ReaderError)hl_alloc_obj(&$t_kha_audio2_ogg_vorbis_data_ReaderError);
	r7 = (venum*)$g_b94286b;
	r8 = NULL;
	r9 = hl_alloc_virtual(&$t_vrt_329ffa8);
	r10 = (String)$s_665fdd3;
	if( hl_vfields(r9)[1] ) *(String*)(hl_vfields(r9)[1]) = (String)r10; else hl_dyn_setp(r9->value,37969014/*fileName*/,&$t_String,r10);
	r21 = 55;
	if( hl_vfields(r9)[2] ) *(int*)(hl_vfields(r9)[2]) = (int)r21; else hl_dyn_seti(r9->value,371360620/*lineNumber*/,&$t_i32,r21);
	r10 = (String)$s_c64aefd;
	if( hl_vfields(r9)[0] ) *(String*)(hl_vfields(r9)[0]) = (String)r10; else hl_dyn_setp(r9->value,-63073762/*className*/,&$t_String,r10);
	r10 = (String)$s_read;
	if( hl_vfields(r9)[3] ) *(String*)(hl_vfields(r9)[3]) = (String)r10; else hl_dyn_setp(r9->value,302979532/*methodName*/,&$t_String,r10);
	r12 = hl_to_virtual(&$t_vrt_eaa6a3b,(vdynamic*)r9);
	kha_audio2_ogg_vorbis_data_ReaderError_new(r6,r7,r8,r12);
	hl_throw((vdynamic*)r6);
	label$cbd4d3d_2_215:
	goto label$cbd4d3d_2_235;
	label$cbd4d3d_2_216:
	if( r2 == NULL ) hl_null_access();
	r27 = r2->residueBooks;
	if( r27 == NULL ) hl_null_access();
	r23 = r27->length;
	if( ((unsigned)r18) < ((unsigned)r23) ) goto label$cbd4d3d_2_223;
	r22 = NULL;
	goto label$cbd4d3d_2_226;
	label$cbd4d3d_2_223:
	r25 = r27->array;
	r11 = ((vdynamic**)(r25 + 1))[r18];
	r22 = (hl__types__ArrayBytes_Int)hl_dyn_castp(&r11,&$t_dyn,&$t_hl_types_ArrayBytes_Int);
	label$cbd4d3d_2_226:
	if( r22 == NULL ) hl_null_access();
	r23 = -1;
	r29 = r22->length;
	if( ((unsigned)r20) < ((unsigned)r29) ) goto label$cbd4d3d_2_231;
	hl_types_ArrayBytes_Int___expand(r22,r20);
	label$cbd4d3d_2_231:
	r14 = r22->bytes;
	r29 = 2;
	r29 = r20 << r29;
	*(int*)(r14 + r29) = r23;
	label$cbd4d3d_2_235:
	goto label$cbd4d3d_2_139;
	label$cbd4d3d_2_236:
	goto label$cbd4d3d_2_110;
	label$cbd4d3d_2_237:
	if( r1 == NULL ) hl_null_access();
	if( r2 == NULL ) hl_null_access();
	r16 = r2->classbook;
	r17 = r1->length;
	if( ((unsigned)r16) < ((unsigned)r17) ) goto label$cbd4d3d_2_244;
	r30 = NULL;
	goto label$cbd4d3d_2_247;
	label$cbd4d3d_2_244:
	r25 = r1->array;
	r11 = ((vdynamic**)(r25 + 1))[r16];
	r30 = (kha__audio2__ogg__vorbis__data__Codebook)r11;
	label$cbd4d3d_2_247:
	if( r30 == NULL ) hl_null_access();
	r16 = r30->entries;
	r17 = r2->classbook;
	r18 = r1->length;
	if( ((unsigned)r17) < ((unsigned)r18) ) goto label$cbd4d3d_2_254;
	r30 = NULL;
	goto label$cbd4d3d_2_257;
	label$cbd4d3d_2_254:
	r25 = r1->array;
	r11 = ((vdynamic**)(r25 + 1))[r17];
	r30 = (kha__audio2__ogg__vorbis__data__Codebook)r11;
	label$cbd4d3d_2_257:
	if( r30 == NULL ) hl_null_access();
	r17 = r30->dimensions;
	r26 = &$t_hl_types_ArrayBytes_Int;
	r18 = 0;
	r25 = hl_alloc_array(r26,r18);
	r27 = hl_types_ArrayObj_alloc(r25);
	r19 = 0;
	if( r19 >= r16 ) goto label$cbd4d3d_2_275;
	if( r27 == NULL ) hl_null_access();
	r19 = 1;
	r18 = r16 - r19;
	r11 = NULL;
	r22 = (hl__types__ArrayBytes_Int)hl_dyn_castp(&r11,&$t_dyn,&$t_hl_types_ArrayBytes_Int);
	r19 = r27->length;
	if( ((unsigned)r18) < ((unsigned)r19) ) goto label$cbd4d3d_2_273;
	hl_types_ArrayObj___expand(r27,r18);
	label$cbd4d3d_2_273:
	r25 = r27->array;
	((hl__types__ArrayBytes_Int*)(r25 + 1))[r18] = r22;
	label$cbd4d3d_2_275:
	r2->classdata = r27;
	r18 = 0;
	r19 = r16;
	label$cbd4d3d_2_278:
	if( r18 >= r19 ) goto label$cbd4d3d_2_329;
	r20 = r18;
	++r18;
	r21 = r20;
	r23 = r17;
	r29 = 0;
	r14 = hl_alloc_bytes(r29);
	r29 = 0;
	r29 = 0;
	r22 = hl_types_ArrayBase_allocI32(r14,r29);
	r32 = 0;
	if( r32 >= r17 ) goto label$cbd4d3d_2_303;
	if( r22 == NULL ) hl_null_access();
	r32 = 1;
	r29 = r17 - r32;
	r11 = NULL;
	r32 = (int)hl_dyn_casti(&r11,&$t_dyn,&$t_i32);
	r33 = r22->length;
	if( ((unsigned)r29) < ((unsigned)r33) ) goto label$cbd4d3d_2_299;
	hl_types_ArrayBytes_Int___expand(r22,r29);
	label$cbd4d3d_2_299:
	r14 = r22->bytes;
	r33 = 2;
	r33 = r29 << r33;
	*(int*)(r14 + r33) = r32;
	label$cbd4d3d_2_303:
	if( r2 == NULL ) hl_null_access();
	r31 = r2->classdata;
	if( r31 == NULL ) hl_null_access();
	r32 = r31->length;
	if( ((unsigned)r20) < ((unsigned)r32) ) goto label$cbd4d3d_2_309;
	hl_types_ArrayObj___expand(r31,r20);
	label$cbd4d3d_2_309:
	r25 = r31->array;
	((hl__types__ArrayBytes_Int*)(r25 + 1))[r20] = r22;
	r28 = r22;
	label$cbd4d3d_2_312:
	--r23;
	r29 = 0;
	if( r23 < r29 ) goto label$cbd4d3d_2_328;
	if( r28 == NULL ) hl_null_access();
	r32 = r4 == 0 ? 0 : r21 % r4;
	r33 = r28->length;
	if( ((unsigned)r23) < ((unsigned)r33) ) goto label$cbd4d3d_2_321;
	hl_types_ArrayBytes_Int___expand(r28,r23);
	label$cbd4d3d_2_321:
	r14 = r28->bytes;
	r33 = 2;
	r33 = r23 << r33;
	*(int*)(r14 + r33) = r32;
	r29 = r4 == 0 ? 0 : r21 / r4;
	r21 = r29;
	goto label$cbd4d3d_2_312;
	label$cbd4d3d_2_328:
	goto label$cbd4d3d_2_278;
	label$cbd4d3d_2_329:
	return r2;
}

void kha_audio2_ogg_vorbis_data_Residue_decode(kha__audio2__ogg__vorbis__data__Residue r0,kha__audio2__ogg__vorbis__VorbisDecodeState r1,kha__audio2__ogg__vorbis__data__Header r2,hl__types__ArrayObj r3,int r4,int r5,hl__types__ArrayObj r6,hl__types__ArrayObj r7) {
	vvirtual *r42;
	kha__audio2__ogg__vorbis__data__Codebook r13;
	hl__types__ArrayObj r8, r11;
	bool r29;
	hl__types__ArrayBytes_Int r22, r25, r35;
	hl__types__ArrayBytes_Float r30;
	double r18, r19;
	vdynamic *r14;
	vbyte *r23;
	varray *r15;
	int r10, r12, r16, r17, r20, r21, r24, r26, r27, r28, r31, r32, r33, r34, r36, r37, r38, r39, r40, r41, r43, r44;
	if( r2 == NULL ) hl_null_access();
	r8 = r2->codebooks;
	if( r8 == NULL ) hl_null_access();
	r10 = r0->classbook;
	r12 = r8->length;
	if( ((unsigned)r10) < ((unsigned)r12) ) goto label$cbd4d3d_3_8;
	r13 = NULL;
	goto label$cbd4d3d_3_11;
	label$cbd4d3d_3_8:
	r15 = r8->array;
	r14 = ((vdynamic**)(r15 + 1))[r10];
	r13 = (kha__audio2__ogg__vorbis__data__Codebook)r14;
	label$cbd4d3d_3_11:
	if( r13 == NULL ) hl_null_access();
	r10 = r13->dimensions;
	r12 = r0->end;
	r16 = r0->begin;
	r12 = r12 - r16;
	r16 = r0->partSize;
	r18 = (double)(unsigned)r12;
	r19 = (double)(unsigned)r16;
	r18 = r18 / r19;
	r17 = (int)r18;
	r20 = r2->channel;
	r20 = r20 * r17;
	r21 = 1;
	r20 = r20 + r21;
	r21 = 0;
	r23 = hl_alloc_bytes(r21);
	r21 = 0;
	r21 = 0;
	r22 = hl_types_ArrayBase_allocI32(r23,r21);
	r24 = 0;
	if( r24 >= r20 ) goto label$cbd4d3d_3_44;
	if( r22 == NULL ) hl_null_access();
	r24 = 1;
	r21 = r20 - r24;
	r14 = NULL;
	r24 = (int)hl_dyn_casti(&r14,&$t_dyn,&$t_i32);
	r26 = r22->length;
	if( ((unsigned)r21) < ((unsigned)r26) ) goto label$cbd4d3d_3_40;
	hl_types_ArrayBytes_Int___expand(r22,r21);
	label$cbd4d3d_3_40:
	r23 = r22->bytes;
	r26 = 2;
	r26 = r21 << r26;
	*(int*)(r23 + r26) = r24;
	label$cbd4d3d_3_44:
	r25 = r22;
	r21 = 0;
	r24 = r4;
	label$cbd4d3d_3_47:
	if( r21 >= r24 ) goto label$cbd4d3d_3_86;
	r26 = r21;
	++r21;
	if( r6 == NULL ) hl_null_access();
	r28 = r6->length;
	if( ((unsigned)r26) < ((unsigned)r28) ) goto label$cbd4d3d_3_56;
	r29 = false;
	goto label$cbd4d3d_3_59;
	label$cbd4d3d_3_56:
	r15 = r6->array;
	r14 = ((vdynamic**)(r15 + 1))[r26];
	r29 = (bool)hl_dyn_casti(&r14,&$t_dyn,&$t_bool);
	label$cbd4d3d_3_59:
	if( r29 ) goto label$cbd4d3d_3_85;
	if( r3 == NULL ) hl_null_access();
	r28 = r3->length;
	if( ((unsigned)r26) < ((unsigned)r28) ) goto label$cbd4d3d_3_65;
	r30 = NULL;
	goto label$cbd4d3d_3_68;
	label$cbd4d3d_3_65:
	r15 = r3->array;
	r14 = ((vdynamic**)(r15 + 1))[r26];
	r30 = (hl__types__ArrayBytes_Float)hl_dyn_castp(&r14,&$t_dyn,&$t_hl_types_ArrayBytes_Float);
	label$cbd4d3d_3_68:
	r27 = 0;
	if( r30 == NULL ) hl_null_access();
	r28 = r30->length;
	label$cbd4d3d_3_71:
	if( r27 >= r28 ) goto label$cbd4d3d_3_85;
	r31 = r27;
	++r27;
	if( r30 == NULL ) hl_null_access();
	r18 = 0.;
	r33 = r30->length;
	if( ((unsigned)r31) < ((unsigned)r33) ) goto label$cbd4d3d_3_80;
	hl_types_ArrayBytes_Float___expand(r30,r31);
	label$cbd4d3d_3_80:
	r23 = r30->bytes;
	r33 = 3;
	r33 = r31 << r33;
	*(double*)(r23 + r33) = r18;
	goto label$cbd4d3d_3_71;
	label$cbd4d3d_3_85:
	goto label$cbd4d3d_3_47;
	label$cbd4d3d_3_86:
	r21 = r0->type;
	r24 = 2;
	if( r21 != r24 ) goto label$cbd4d3d_3_656;
	r24 = 1;
	if( r4 == r24 ) goto label$cbd4d3d_3_656;
	r21 = 0;
	r24 = r4;
	label$cbd4d3d_3_93:
	if( r21 >= r24 ) goto label$cbd4d3d_3_112;
	r26 = r21;
	++r21;
	if( r6 == NULL ) hl_null_access();
	r28 = r6->length;
	if( ((unsigned)r26) < ((unsigned)r28) ) goto label$cbd4d3d_3_102;
	r29 = false;
	goto label$cbd4d3d_3_105;
	label$cbd4d3d_3_102:
	r15 = r6->array;
	r14 = ((vdynamic**)(r15 + 1))[r26];
	r29 = (bool)hl_dyn_casti(&r14,&$t_dyn,&$t_bool);
	label$cbd4d3d_3_105:
	if( r29 ) goto label$cbd4d3d_3_107;
	goto label$cbd4d3d_3_112;
	label$cbd4d3d_3_107:
	r31 = 1;
	r28 = r4 - r31;
	if( r26 != r28 ) goto label$cbd4d3d_3_111;
	return;
	label$cbd4d3d_3_111:
	goto label$cbd4d3d_3_93;
	label$cbd4d3d_3_112:
	r21 = 0;
	label$cbd4d3d_3_113:
	r26 = 8;
	if( r21 >= r26 ) goto label$cbd4d3d_3_655;
	r24 = r21;
	++r21;
	r26 = 0;
	r27 = 0;
	r31 = 2;
	if( r4 != r31 ) goto label$cbd4d3d_3_300;
	label$cbd4d3d_3_122:
	if( r26 >= r17 ) goto label$cbd4d3d_3_299;
	r28 = r0->begin;
	r31 = r26 * r16;
	r28 = r28 + r31;
	r32 = 1;
	r31 = r28 & r32;
	r33 = 1;
	r32 = ((unsigned)r28) >> r33;
	r34 = 0;
	if( r24 != r34 ) goto label$cbd4d3d_3_231;
	if( r8 == NULL ) hl_null_access();
	r33 = r0->classbook;
	r34 = r8->length;
	if( ((unsigned)r33) < ((unsigned)r34) ) goto label$cbd4d3d_3_139;
	r13 = NULL;
	goto label$cbd4d3d_3_142;
	label$cbd4d3d_3_139:
	r15 = r8->array;
	r14 = ((vdynamic**)(r15 + 1))[r33];
	r13 = (kha__audio2__ogg__vorbis__data__Codebook)r14;
	label$cbd4d3d_3_142:
	if( r1 == NULL ) hl_null_access();
	r33 = r1->validBits;
	r34 = 10;
	if( r33 >= r34 ) goto label$cbd4d3d_3_147;
	kha_audio2_ogg_vorbis_VorbisDecodeState_prepHuffman(r1);
	label$cbd4d3d_3_147:
	if( r13 == NULL ) hl_null_access();
	r35 = r13->fastHuffman;
	if( r35 == NULL ) hl_null_access();
	r33 = r1->acc;
	r34 = 1023;
	r33 = r33 & r34;
	r34 = r35->length;
	if( ((unsigned)r33) < ((unsigned)r34) ) goto label$cbd4d3d_3_157;
	r33 = 0;
	goto label$cbd4d3d_3_161;
	label$cbd4d3d_3_157:
	r23 = r35->bytes;
	r34 = 2;
	r34 = r33 << r34;
	r33 = *(int*)(r23 + r34);
	label$cbd4d3d_3_161:
	r36 = 0;
	if( r33 < r36 ) goto label$cbd4d3d_3_189;
	r35 = r13->codewordLengths;
	if( r35 == NULL ) hl_null_access();
	r36 = r35->length;
	if( ((unsigned)r33) < ((unsigned)r36) ) goto label$cbd4d3d_3_169;
	r34 = 0;
	goto label$cbd4d3d_3_173;
	label$cbd4d3d_3_169:
	r23 = r35->bytes;
	r36 = 2;
	r36 = r33 << r36;
	r34 = *(int*)(r23 + r36);
	label$cbd4d3d_3_173:
	r36 = r1->acc;
	r36 = ((unsigned)r36) >> r34;
	r1->acc = r36;
	r36 = r1->validBits;
	r36 = r36 - r34;
	r1->validBits = r36;
	r36 = r1->validBits;
	r37 = 0;
	if( r36 >= r37 ) goto label$cbd4d3d_3_187;
	r36 = 0;
	r1->validBits = r36;
	r37 = -1;
	r36 = r37;
	goto label$cbd4d3d_3_188;
	label$cbd4d3d_3_187:
	r36 = r33;
	label$cbd4d3d_3_188:
	goto label$cbd4d3d_3_191;
	label$cbd4d3d_3_189:
	r34 = kha_audio2_ogg_vorbis_VorbisDecodeState_decodeScalarRaw(r1,r13);
	r36 = r34;
	label$cbd4d3d_3_191:
	r29 = r13->sparse;
	if( !r29 ) goto label$cbd4d3d_3_204;
	r35 = r13->sortedValues;
	if( r35 == NULL ) hl_null_access();
	r37 = r35->length;
	if( ((unsigned)r36) < ((unsigned)r37) ) goto label$cbd4d3d_3_199;
	r34 = 0;
	goto label$cbd4d3d_3_203;
	label$cbd4d3d_3_199:
	r23 = r35->bytes;
	r37 = 2;
	r37 = r36 << r37;
	r34 = *(int*)(r23 + r37);
	label$cbd4d3d_3_203:
	r36 = r34;
	label$cbd4d3d_3_204:
	r34 = r36;
	r38 = -1;
	if( r36 != r38 ) goto label$cbd4d3d_3_208;
	return;
	label$cbd4d3d_3_208:
	r37 = r10;
	label$cbd4d3d_3_209:
	--r37;
	r38 = 0;
	if( r37 < r38 ) goto label$cbd4d3d_3_231;
	if( r25 == NULL ) hl_null_access();
	r38 = r37 + r26;
	r40 = r0->classifications;
	r39 = r40 == 0 ? 0 : r34 % r40;
	r40 = r25->length;
	if( ((unsigned)r38) < ((unsigned)r40) ) goto label$cbd4d3d_3_220;
	hl_types_ArrayBytes_Int___expand(r25,r38);
	label$cbd4d3d_3_220:
	r23 = r25->bytes;
	r40 = 2;
	r40 = r38 << r40;
	*(int*)(r23 + r40) = r39;
	r18 = (double)r34;
	r38 = r0->classifications;
	r19 = (double)r38;
	r18 = r18 / r19;
	r38 = (int)r18;
	r34 = r38;
	goto label$cbd4d3d_3_209;
	label$cbd4d3d_3_231:
	r33 = 0;
	r34 = r10;
	label$cbd4d3d_3_233:
	if( r33 >= r34 ) goto label$cbd4d3d_3_298;
	++r33;
	if( r26 < r17 ) goto label$cbd4d3d_3_238;
	goto label$cbd4d3d_3_298;
	label$cbd4d3d_3_238:
	r37 = r0->begin;
	r38 = r26 * r16;
	r37 = r37 + r38;
	if( r25 == NULL ) hl_null_access();
	r39 = r25->length;
	if( ((unsigned)r26) < ((unsigned)r39) ) goto label$cbd4d3d_3_246;
	r38 = 0;
	goto label$cbd4d3d_3_250;
	label$cbd4d3d_3_246:
	r23 = r25->bytes;
	r39 = 2;
	r39 = r26 << r39;
	r38 = *(int*)(r23 + r39);
	label$cbd4d3d_3_250:
	r11 = r0->residueBooks;
	if( r11 == NULL ) hl_null_access();
	r40 = r11->length;
	if( ((unsigned)r38) < ((unsigned)r40) ) goto label$cbd4d3d_3_256;
	r35 = NULL;
	goto label$cbd4d3d_3_259;
	label$cbd4d3d_3_256:
	r15 = r11->array;
	r14 = ((vdynamic**)(r15 + 1))[r38];
	r35 = (hl__types__ArrayBytes_Int)hl_dyn_castp(&r14,&$t_dyn,&$t_hl_types_ArrayBytes_Int);
	label$cbd4d3d_3_259:
	if( r35 == NULL ) hl_null_access();
	r40 = r35->length;
	if( ((unsigned)r24) < ((unsigned)r40) ) goto label$cbd4d3d_3_264;
	r39 = 0;
	goto label$cbd4d3d_3_268;
	label$cbd4d3d_3_264:
	r23 = r35->bytes;
	r40 = 2;
	r40 = r24 << r40;
	r39 = *(int*)(r23 + r40);
	label$cbd4d3d_3_268:
	r41 = 0;
	if( r39 < r41 ) goto label$cbd4d3d_3_288;
	if( r8 == NULL ) hl_null_access();
	r41 = r8->length;
	if( ((unsigned)r39) < ((unsigned)r41) ) goto label$cbd4d3d_3_275;
	r13 = NULL;
	goto label$cbd4d3d_3_278;
	label$cbd4d3d_3_275:
	r15 = r8->array;
	r14 = ((vdynamic**)(r15 + 1))[r39];
	r13 = (kha__audio2__ogg__vorbis__data__Codebook)r14;
	label$cbd4d3d_3_278:
	if( r13 == NULL ) hl_null_access();
	r42 = kha_audio2_ogg_vorbis_data_Codebook_decodeDeinterleaveRepeat(r13,r1,r3,r4,r31,r32,r5,r16);
	if( r42 ) goto label$cbd4d3d_3_282;
	return;
	label$cbd4d3d_3_282:
	if( r42 == NULL ) hl_null_access();
	r40 = hl_vfields(r42)[0] ? (*(int*)(hl_vfields(r42)[0])) : (int)hl_dyn_geti(r42->value,-425531463/*cInter*/,&$t_i32);
	r31 = r40;
	r40 = hl_vfields(r42)[1] ? (*(int*)(hl_vfields(r42)[1])) : (int)hl_dyn_geti(r42->value,424056972/*pInter*/,&$t_i32);
	r32 = r40;
	goto label$cbd4d3d_3_296;
	label$cbd4d3d_3_288:
	r40 = r37 + r16;
	r37 = r40;
	r41 = 1;
	r40 = r40 & r41;
	r31 = r40;
	r41 = 1;
	r40 = ((unsigned)r37) >> r41;
	r32 = r40;
	label$cbd4d3d_3_296:
	++r26;
	goto label$cbd4d3d_3_233;
	label$cbd4d3d_3_298:
	goto label$cbd4d3d_3_122;
	label$cbd4d3d_3_299:
	goto label$cbd4d3d_3_654;
	label$cbd4d3d_3_300:
	r31 = 1;
	if( r4 != r31 ) goto label$cbd4d3d_3_475;
	label$cbd4d3d_3_302:
	if( r26 >= r17 ) goto label$cbd4d3d_3_474;
	r28 = r0->begin;
	r31 = r26 * r16;
	r28 = r28 + r31;
	r31 = 0;
	r32 = r28;
	r34 = 0;
	if( r24 != r34 ) goto label$cbd4d3d_3_409;
	if( r8 == NULL ) hl_null_access();
	r33 = r0->classbook;
	r34 = r8->length;
	if( ((unsigned)r33) < ((unsigned)r34) ) goto label$cbd4d3d_3_317;
	r13 = NULL;
	goto label$cbd4d3d_3_320;
	label$cbd4d3d_3_317:
	r15 = r8->array;
	r14 = ((vdynamic**)(r15 + 1))[r33];
	r13 = (kha__audio2__ogg__vorbis__data__Codebook)r14;
	label$cbd4d3d_3_320:
	if( r1 == NULL ) hl_null_access();
	r33 = r1->validBits;
	r34 = 10;
	if( r33 >= r34 ) goto label$cbd4d3d_3_325;
	kha_audio2_ogg_vorbis_VorbisDecodeState_prepHuffman(r1);
	label$cbd4d3d_3_325:
	if( r13 == NULL ) hl_null_access();
	r35 = r13->fastHuffman;
	if( r35 == NULL ) hl_null_access();
	r33 = r1->acc;
	r34 = 1023;
	r33 = r33 & r34;
	r34 = r35->length;
	if( ((unsigned)r33) < ((unsigned)r34) ) goto label$cbd4d3d_3_335;
	r33 = 0;
	goto label$cbd4d3d_3_339;
	label$cbd4d3d_3_335:
	r23 = r35->bytes;
	r34 = 2;
	r34 = r33 << r34;
	r33 = *(int*)(r23 + r34);
	label$cbd4d3d_3_339:
	r36 = 0;
	if( r33 < r36 ) goto label$cbd4d3d_3_367;
	r35 = r13->codewordLengths;
	if( r35 == NULL ) hl_null_access();
	r36 = r35->length;
	if( ((unsigned)r33) < ((unsigned)r36) ) goto label$cbd4d3d_3_347;
	r34 = 0;
	goto label$cbd4d3d_3_351;
	label$cbd4d3d_3_347:
	r23 = r35->bytes;
	r36 = 2;
	r36 = r33 << r36;
	r34 = *(int*)(r23 + r36);
	label$cbd4d3d_3_351:
	r36 = r1->acc;
	r36 = ((unsigned)r36) >> r34;
	r1->acc = r36;
	r36 = r1->validBits;
	r36 = r36 - r34;
	r1->validBits = r36;
	r36 = r1->validBits;
	r37 = 0;
	if( r36 >= r37 ) goto label$cbd4d3d_3_365;
	r36 = 0;
	r1->validBits = r36;
	r37 = -1;
	r36 = r37;
	goto label$cbd4d3d_3_366;
	label$cbd4d3d_3_365:
	r36 = r33;
	label$cbd4d3d_3_366:
	goto label$cbd4d3d_3_369;
	label$cbd4d3d_3_367:
	r34 = kha_audio2_ogg_vorbis_VorbisDecodeState_decodeScalarRaw(r1,r13);
	r36 = r34;
	label$cbd4d3d_3_369:
	r29 = r13->sparse;
	if( !r29 ) goto label$cbd4d3d_3_382;
	r35 = r13->sortedValues;
	if( r35 == NULL ) hl_null_access();
	r37 = r35->length;
	if( ((unsigned)r36) < ((unsigned)r37) ) goto label$cbd4d3d_3_377;
	r34 = 0;
	goto label$cbd4d3d_3_381;
	label$cbd4d3d_3_377:
	r23 = r35->bytes;
	r37 = 2;
	r37 = r36 << r37;
	r34 = *(int*)(r23 + r37);
	label$cbd4d3d_3_381:
	r36 = r34;
	label$cbd4d3d_3_382:
	r34 = r36;
	r38 = -1;
	if( r36 != r38 ) goto label$cbd4d3d_3_386;
	return;
	label$cbd4d3d_3_386:
	r37 = r10;
	label$cbd4d3d_3_387:
	--r37;
	r38 = 0;
	if( r37 < r38 ) goto label$cbd4d3d_3_409;
	if( r25 == NULL ) hl_null_access();
	r38 = r37 + r26;
	r40 = r0->classifications;
	r39 = r40 == 0 ? 0 : r34 % r40;
	r40 = r25->length;
	if( ((unsigned)r38) < ((unsigned)r40) ) goto label$cbd4d3d_3_398;
	hl_types_ArrayBytes_Int___expand(r25,r38);
	label$cbd4d3d_3_398:
	r23 = r25->bytes;
	r40 = 2;
	r40 = r38 << r40;
	*(int*)(r23 + r40) = r39;
	r18 = (double)r34;
	r38 = r0->classifications;
	r19 = (double)r38;
	r18 = r18 / r19;
	r38 = (int)r18;
	r34 = r38;
	goto label$cbd4d3d_3_387;
	label$cbd4d3d_3_409:
	r33 = 0;
	r34 = r10;
	label$cbd4d3d_3_411:
	if( r33 >= r34 ) goto label$cbd4d3d_3_473;
	++r33;
	if( r26 < r17 ) goto label$cbd4d3d_3_416;
	goto label$cbd4d3d_3_473;
	label$cbd4d3d_3_416:
	r37 = r0->begin;
	r38 = r26 * r16;
	r37 = r37 + r38;
	r11 = r0->residueBooks;
	if( r11 == NULL ) hl_null_access();
	if( r25 == NULL ) hl_null_access();
	r39 = r25->length;
	if( ((unsigned)r26) < ((unsigned)r39) ) goto label$cbd4d3d_3_426;
	r38 = 0;
	goto label$cbd4d3d_3_430;
	label$cbd4d3d_3_426:
	r23 = r25->bytes;
	r39 = 2;
	r39 = r26 << r39;
	r38 = *(int*)(r23 + r39);
	label$cbd4d3d_3_430:
	r39 = r11->length;
	if( ((unsigned)r38) < ((unsigned)r39) ) goto label$cbd4d3d_3_434;
	r35 = NULL;
	goto label$cbd4d3d_3_437;
	label$cbd4d3d_3_434:
	r15 = r11->array;
	r14 = ((vdynamic**)(r15 + 1))[r38];
	r35 = (hl__types__ArrayBytes_Int)hl_dyn_castp(&r14,&$t_dyn,&$t_hl_types_ArrayBytes_Int);
	label$cbd4d3d_3_437:
	if( r35 == NULL ) hl_null_access();
	r39 = r35->length;
	if( ((unsigned)r24) < ((unsigned)r39) ) goto label$cbd4d3d_3_442;
	r38 = 0;
	goto label$cbd4d3d_3_446;
	label$cbd4d3d_3_442:
	r23 = r35->bytes;
	r39 = 2;
	r39 = r24 << r39;
	r38 = *(int*)(r23 + r39);
	label$cbd4d3d_3_446:
	r40 = 0;
	if( r38 < r40 ) goto label$cbd4d3d_3_466;
	if( r8 == NULL ) hl_null_access();
	r40 = r8->length;
	if( ((unsigned)r38) < ((unsigned)r40) ) goto label$cbd4d3d_3_453;
	r13 = NULL;
	goto label$cbd4d3d_3_456;
	label$cbd4d3d_3_453:
	r15 = r8->array;
	r14 = ((vdynamic**)(r15 + 1))[r38];
	r13 = (kha__audio2__ogg__vorbis__data__Codebook)r14;
	label$cbd4d3d_3_456:
	if( r13 == NULL ) hl_null_access();
	r42 = kha_audio2_ogg_vorbis_data_Codebook_decodeDeinterleaveRepeat(r13,r1,r3,r4,r31,r32,r5,r16);
	if( r42 ) goto label$cbd4d3d_3_460;
	return;
	label$cbd4d3d_3_460:
	if( r42 == NULL ) hl_null_access();
	r39 = hl_vfields(r42)[0] ? (*(int*)(hl_vfields(r42)[0])) : (int)hl_dyn_geti(r42->value,-425531463/*cInter*/,&$t_i32);
	r31 = r39;
	r39 = hl_vfields(r42)[1] ? (*(int*)(hl_vfields(r42)[1])) : (int)hl_dyn_geti(r42->value,424056972/*pInter*/,&$t_i32);
	r32 = r39;
	goto label$cbd4d3d_3_471;
	label$cbd4d3d_3_466:
	r39 = r37 + r16;
	r37 = r39;
	r39 = 0;
	r31 = r39;
	r32 = r37;
	label$cbd4d3d_3_471:
	++r26;
	goto label$cbd4d3d_3_411;
	label$cbd4d3d_3_473:
	goto label$cbd4d3d_3_302;
	label$cbd4d3d_3_474:
	goto label$cbd4d3d_3_654;
	label$cbd4d3d_3_475:
	if( r26 >= r17 ) goto label$cbd4d3d_3_654;
	r28 = r0->begin;
	r31 = r26 * r16;
	r28 = r28 + r31;
	r31 = r4 == 0 ? 0 : ((unsigned)r28) % ((unsigned)r4);
	r18 = (double)(unsigned)r28;
	r19 = (double)(unsigned)r4;
	r18 = r18 / r19;
	r32 = (int)r18;
	r34 = 0;
	if( r24 != r34 ) goto label$cbd4d3d_3_585;
	if( r8 == NULL ) hl_null_access();
	r33 = r0->classbook;
	r34 = r8->length;
	if( ((unsigned)r33) < ((unsigned)r34) ) goto label$cbd4d3d_3_493;
	r13 = NULL;
	goto label$cbd4d3d_3_496;
	label$cbd4d3d_3_493:
	r15 = r8->array;
	r14 = ((vdynamic**)(r15 + 1))[r33];
	r13 = (kha__audio2__ogg__vorbis__data__Codebook)r14;
	label$cbd4d3d_3_496:
	if( r1 == NULL ) hl_null_access();
	r33 = r1->validBits;
	r34 = 10;
	if( r33 >= r34 ) goto label$cbd4d3d_3_501;
	kha_audio2_ogg_vorbis_VorbisDecodeState_prepHuffman(r1);
	label$cbd4d3d_3_501:
	if( r13 == NULL ) hl_null_access();
	r35 = r13->fastHuffman;
	if( r35 == NULL ) hl_null_access();
	r33 = r1->acc;
	r34 = 1023;
	r33 = r33 & r34;
	r34 = r35->length;
	if( ((unsigned)r33) < ((unsigned)r34) ) goto label$cbd4d3d_3_511;
	r33 = 0;
	goto label$cbd4d3d_3_515;
	label$cbd4d3d_3_511:
	r23 = r35->bytes;
	r34 = 2;
	r34 = r33 << r34;
	r33 = *(int*)(r23 + r34);
	label$cbd4d3d_3_515:
	r36 = 0;
	if( r33 < r36 ) goto label$cbd4d3d_3_543;
	r35 = r13->codewordLengths;
	if( r35 == NULL ) hl_null_access();
	r36 = r35->length;
	if( ((unsigned)r33) < ((unsigned)r36) ) goto label$cbd4d3d_3_523;
	r34 = 0;
	goto label$cbd4d3d_3_527;
	label$cbd4d3d_3_523:
	r23 = r35->bytes;
	r36 = 2;
	r36 = r33 << r36;
	r34 = *(int*)(r23 + r36);
	label$cbd4d3d_3_527:
	r36 = r1->acc;
	r36 = ((unsigned)r36) >> r34;
	r1->acc = r36;
	r36 = r1->validBits;
	r36 = r36 - r34;
	r1->validBits = r36;
	r36 = r1->validBits;
	r37 = 0;
	if( r36 >= r37 ) goto label$cbd4d3d_3_541;
	r36 = 0;
	r1->validBits = r36;
	r37 = -1;
	r36 = r37;
	goto label$cbd4d3d_3_542;
	label$cbd4d3d_3_541:
	r36 = r33;
	label$cbd4d3d_3_542:
	goto label$cbd4d3d_3_545;
	label$cbd4d3d_3_543:
	r34 = kha_audio2_ogg_vorbis_VorbisDecodeState_decodeScalarRaw(r1,r13);
	r36 = r34;
	label$cbd4d3d_3_545:
	r29 = r13->sparse;
	if( !r29 ) goto label$cbd4d3d_3_558;
	r35 = r13->sortedValues;
	if( r35 == NULL ) hl_null_access();
	r37 = r35->length;
	if( ((unsigned)r36) < ((unsigned)r37) ) goto label$cbd4d3d_3_553;
	r34 = 0;
	goto label$cbd4d3d_3_557;
	label$cbd4d3d_3_553:
	r23 = r35->bytes;
	r37 = 2;
	r37 = r36 << r37;
	r34 = *(int*)(r23 + r37);
	label$cbd4d3d_3_557:
	r36 = r34;
	label$cbd4d3d_3_558:
	r34 = r36;
	r38 = -1;
	if( r36 != r38 ) goto label$cbd4d3d_3_562;
	return;
	label$cbd4d3d_3_562:
	r37 = r10;
	label$cbd4d3d_3_563:
	--r37;
	r38 = 0;
	if( r37 < r38 ) goto label$cbd4d3d_3_585;
	if( r25 == NULL ) hl_null_access();
	r38 = r37 + r26;
	r40 = r0->classifications;
	r39 = r40 == 0 ? 0 : r34 % r40;
	r40 = r25->length;
	if( ((unsigned)r38) < ((unsigned)r40) ) goto label$cbd4d3d_3_574;
	hl_types_ArrayBytes_Int___expand(r25,r38);
	label$cbd4d3d_3_574:
	r23 = r25->bytes;
	r40 = 2;
	r40 = r38 << r40;
	*(int*)(r23 + r40) = r39;
	r18 = (double)r34;
	r38 = r0->classifications;
	r19 = (double)r38;
	r18 = r18 / r19;
	r38 = (int)r18;
	r34 = r38;
	goto label$cbd4d3d_3_563;
	label$cbd4d3d_3_585:
	r33 = 0;
	r34 = r10;
	label$cbd4d3d_3_587:
	if( r33 >= r34 ) goto label$cbd4d3d_3_653;
	++r33;
	if( r26 < r17 ) goto label$cbd4d3d_3_592;
	goto label$cbd4d3d_3_653;
	label$cbd4d3d_3_592:
	r37 = r0->begin;
	r38 = r26 * r16;
	r37 = r37 + r38;
	r11 = r0->residueBooks;
	if( r11 == NULL ) hl_null_access();
	if( r25 == NULL ) hl_null_access();
	r39 = r25->length;
	if( ((unsigned)r26) < ((unsigned)r39) ) goto label$cbd4d3d_3_602;
	r38 = 0;
	goto label$cbd4d3d_3_606;
	label$cbd4d3d_3_602:
	r23 = r25->bytes;
	r39 = 2;
	r39 = r26 << r39;
	r38 = *(int*)(r23 + r39);
	label$cbd4d3d_3_606:
	r39 = r11->length;
	if( ((unsigned)r38) < ((unsigned)r39) ) goto label$cbd4d3d_3_610;
	r35 = NULL;
	goto label$cbd4d3d_3_613;
	label$cbd4d3d_3_610:
	r15 = r11->array;
	r14 = ((vdynamic**)(r15 + 1))[r38];
	r35 = (hl__types__ArrayBytes_Int)hl_dyn_castp(&r14,&$t_dyn,&$t_hl_types_ArrayBytes_Int);
	label$cbd4d3d_3_613:
	if( r35 == NULL ) hl_null_access();
	r39 = r35->length;
	if( ((unsigned)r24) < ((unsigned)r39) ) goto label$cbd4d3d_3_618;
	r38 = 0;
	goto label$cbd4d3d_3_622;
	label$cbd4d3d_3_618:
	r23 = r35->bytes;
	r39 = 2;
	r39 = r24 << r39;
	r38 = *(int*)(r23 + r39);
	label$cbd4d3d_3_622:
	r40 = 0;
	if( r38 < r40 ) goto label$cbd4d3d_3_642;
	if( r8 == NULL ) hl_null_access();
	r40 = r8->length;
	if( ((unsigned)r38) < ((unsigned)r40) ) goto label$cbd4d3d_3_629;
	r13 = NULL;
	goto label$cbd4d3d_3_632;
	label$cbd4d3d_3_629:
	r15 = r8->array;
	r14 = ((vdynamic**)(r15 + 1))[r38];
	r13 = (kha__audio2__ogg__vorbis__data__Codebook)r14;
	label$cbd4d3d_3_632:
	if( r13 == NULL ) hl_null_access();
	r42 = kha_audio2_ogg_vorbis_data_Codebook_decodeDeinterleaveRepeat(r13,r1,r3,r4,r31,r32,r5,r16);
	if( r42 ) goto label$cbd4d3d_3_636;
	return;
	label$cbd4d3d_3_636:
	if( r42 == NULL ) hl_null_access();
	r39 = hl_vfields(r42)[0] ? (*(int*)(hl_vfields(r42)[0])) : (int)hl_dyn_geti(r42->value,-425531463/*cInter*/,&$t_i32);
	r31 = r39;
	r39 = hl_vfields(r42)[1] ? (*(int*)(hl_vfields(r42)[1])) : (int)hl_dyn_geti(r42->value,424056972/*pInter*/,&$t_i32);
	r32 = r39;
	goto label$cbd4d3d_3_651;
	label$cbd4d3d_3_642:
	r39 = r37 + r16;
	r37 = r39;
	r39 = r4 == 0 ? 0 : ((unsigned)r39) % ((unsigned)r4);
	r31 = r39;
	r18 = (double)(unsigned)r37;
	r19 = (double)(unsigned)r4;
	r18 = r18 / r19;
	r39 = (int)r18;
	r32 = r39;
	label$cbd4d3d_3_651:
	++r26;
	goto label$cbd4d3d_3_587;
	label$cbd4d3d_3_653:
	goto label$cbd4d3d_3_475;
	label$cbd4d3d_3_654:
	goto label$cbd4d3d_3_113;
	label$cbd4d3d_3_655:
	return;
	label$cbd4d3d_3_656:
	r21 = 0;
	label$cbd4d3d_3_657:
	r26 = 8;
	if( r21 >= r26 ) goto label$cbd4d3d_3_866;
	r24 = r21;
	++r21;
	r26 = 0;
	r27 = 0;
	label$cbd4d3d_3_664:
	if( r26 >= r17 ) goto label$cbd4d3d_3_865;
	r31 = 0;
	if( r24 != r31 ) goto label$cbd4d3d_3_784;
	r28 = 0;
	r31 = r4;
	label$cbd4d3d_3_670:
	if( r28 >= r31 ) goto label$cbd4d3d_3_784;
	r32 = r28;
	++r28;
	if( r6 == NULL ) hl_null_access();
	r34 = r6->length;
	if( ((unsigned)r32) < ((unsigned)r34) ) goto label$cbd4d3d_3_679;
	r29 = false;
	goto label$cbd4d3d_3_682;
	label$cbd4d3d_3_679:
	r15 = r6->array;
	r14 = ((vdynamic**)(r15 + 1))[r32];
	r29 = (bool)hl_dyn_casti(&r14,&$t_dyn,&$t_bool);
	label$cbd4d3d_3_682:
	if( r29 ) goto label$cbd4d3d_3_783;
	if( r8 == NULL ) hl_null_access();
	r33 = r0->classbook;
	r34 = r8->length;
	if( ((unsigned)r33) < ((unsigned)r34) ) goto label$cbd4d3d_3_689;
	r13 = NULL;
	goto label$cbd4d3d_3_692;
	label$cbd4d3d_3_689:
	r15 = r8->array;
	r14 = ((vdynamic**)(r15 + 1))[r33];
	r13 = (kha__audio2__ogg__vorbis__data__Codebook)r14;
	label$cbd4d3d_3_692:
	if( r1 == NULL ) hl_null_access();
	r33 = r1->validBits;
	r34 = 10;
	if( r33 >= r34 ) goto label$cbd4d3d_3_697;
	kha_audio2_ogg_vorbis_VorbisDecodeState_prepHuffman(r1);
	label$cbd4d3d_3_697:
	if( r13 == NULL ) hl_null_access();
	r35 = r13->fastHuffman;
	if( r35 == NULL ) hl_null_access();
	r33 = r1->acc;
	r34 = 1023;
	r33 = r33 & r34;
	r34 = r35->length;
	if( ((unsigned)r33) < ((unsigned)r34) ) goto label$cbd4d3d_3_707;
	r33 = 0;
	goto label$cbd4d3d_3_711;
	label$cbd4d3d_3_707:
	r23 = r35->bytes;
	r34 = 2;
	r34 = r33 << r34;
	r33 = *(int*)(r23 + r34);
	label$cbd4d3d_3_711:
	r36 = 0;
	if( r33 < r36 ) goto label$cbd4d3d_3_739;
	r35 = r13->codewordLengths;
	if( r35 == NULL ) hl_null_access();
	r36 = r35->length;
	if( ((unsigned)r33) < ((unsigned)r36) ) goto label$cbd4d3d_3_719;
	r34 = 0;
	goto label$cbd4d3d_3_723;
	label$cbd4d3d_3_719:
	r23 = r35->bytes;
	r36 = 2;
	r36 = r33 << r36;
	r34 = *(int*)(r23 + r36);
	label$cbd4d3d_3_723:
	r36 = r1->acc;
	r36 = ((unsigned)r36) >> r34;
	r1->acc = r36;
	r36 = r1->validBits;
	r36 = r36 - r34;
	r1->validBits = r36;
	r36 = r1->validBits;
	r37 = 0;
	if( r36 >= r37 ) goto label$cbd4d3d_3_737;
	r36 = 0;
	r1->validBits = r36;
	r37 = -1;
	r36 = r37;
	goto label$cbd4d3d_3_738;
	label$cbd4d3d_3_737:
	r36 = r33;
	label$cbd4d3d_3_738:
	goto label$cbd4d3d_3_741;
	label$cbd4d3d_3_739:
	r34 = kha_audio2_ogg_vorbis_VorbisDecodeState_decodeScalarRaw(r1,r13);
	r36 = r34;
	label$cbd4d3d_3_741:
	r29 = r13->sparse;
	if( !r29 ) goto label$cbd4d3d_3_754;
	r35 = r13->sortedValues;
	if( r35 == NULL ) hl_null_access();
	r37 = r35->length;
	if( ((unsigned)r36) < ((unsigned)r37) ) goto label$cbd4d3d_3_749;
	r34 = 0;
	goto label$cbd4d3d_3_753;
	label$cbd4d3d_3_749:
	r23 = r35->bytes;
	r37 = 2;
	r37 = r36 << r37;
	r34 = *(int*)(r23 + r37);
	label$cbd4d3d_3_753:
	r36 = r34;
	label$cbd4d3d_3_754:
	r34 = r36;
	r38 = -1;
	if( r36 != r38 ) goto label$cbd4d3d_3_758;
	return;
	label$cbd4d3d_3_758:
	r37 = r10;
	label$cbd4d3d_3_759:
	--r37;
	r38 = 0;
	if( r37 < r38 ) goto label$cbd4d3d_3_783;
	if( r25 == NULL ) hl_null_access();
	r38 = r32 * r17;
	r38 = r38 + r37;
	r38 = r38 + r26;
	r40 = r0->classifications;
	r39 = r40 == 0 ? 0 : r34 % r40;
	r40 = r25->length;
	if( ((unsigned)r38) < ((unsigned)r40) ) goto label$cbd4d3d_3_772;
	hl_types_ArrayBytes_Int___expand(r25,r38);
	label$cbd4d3d_3_772:
	r23 = r25->bytes;
	r40 = 2;
	r40 = r38 << r40;
	*(int*)(r23 + r40) = r39;
	r18 = (double)r34;
	r38 = r0->classifications;
	r19 = (double)r38;
	r18 = r18 / r19;
	r38 = (int)r18;
	r34 = r38;
	goto label$cbd4d3d_3_759;
	label$cbd4d3d_3_783:
	goto label$cbd4d3d_3_670;
	label$cbd4d3d_3_784:
	r28 = 0;
	r31 = r10;
	label$cbd4d3d_3_786:
	if( r28 >= r31 ) goto label$cbd4d3d_3_864;
	++r28;
	if( r26 < r17 ) goto label$cbd4d3d_3_791;
	goto label$cbd4d3d_3_864;
	label$cbd4d3d_3_791:
	r33 = 0;
	r34 = r4;
	label$cbd4d3d_3_793:
	if( r33 >= r34 ) goto label$cbd4d3d_3_862;
	r36 = r33;
	++r33;
	if( r6 == NULL ) hl_null_access();
	r38 = r6->length;
	if( ((unsigned)r36) < ((unsigned)r38) ) goto label$cbd4d3d_3_802;
	r29 = false;
	goto label$cbd4d3d_3_805;
	label$cbd4d3d_3_802:
	r15 = r6->array;
	r14 = ((vdynamic**)(r15 + 1))[r36];
	r29 = (bool)hl_dyn_casti(&r14,&$t_dyn,&$t_bool);
	label$cbd4d3d_3_805:
	if( r29 ) goto label$cbd4d3d_3_861;
	if( r25 == NULL ) hl_null_access();
	r37 = r36 * r17;
	r37 = r37 + r26;
	r38 = r25->length;
	if( ((unsigned)r37) < ((unsigned)r38) ) goto label$cbd4d3d_3_813;
	r37 = 0;
	goto label$cbd4d3d_3_817;
	label$cbd4d3d_3_813:
	r23 = r25->bytes;
	r38 = 2;
	r38 = r37 << r38;
	r37 = *(int*)(r23 + r38);
	label$cbd4d3d_3_817:
	r11 = r0->residueBooks;
	if( r11 == NULL ) hl_null_access();
	r39 = r11->length;
	if( ((unsigned)r37) < ((unsigned)r39) ) goto label$cbd4d3d_3_823;
	r35 = NULL;
	goto label$cbd4d3d_3_826;
	label$cbd4d3d_3_823:
	r15 = r11->array;
	r14 = ((vdynamic**)(r15 + 1))[r37];
	r35 = (hl__types__ArrayBytes_Int)hl_dyn_castp(&r14,&$t_dyn,&$t_hl_types_ArrayBytes_Int);
	label$cbd4d3d_3_826:
	if( r35 == NULL ) hl_null_access();
	r39 = r35->length;
	if( ((unsigned)r24) < ((unsigned)r39) ) goto label$cbd4d3d_3_831;
	r38 = 0;
	goto label$cbd4d3d_3_835;
	label$cbd4d3d_3_831:
	r23 = r35->bytes;
	r39 = 2;
	r39 = r24 << r39;
	r38 = *(int*)(r23 + r39);
	label$cbd4d3d_3_835:
	r40 = 0;
	if( r38 < r40 ) goto label$cbd4d3d_3_861;
	if( r3 == NULL ) hl_null_access();
	r40 = r3->length;
	if( ((unsigned)r36) < ((unsigned)r40) ) goto label$cbd4d3d_3_842;
	r30 = NULL;
	goto label$cbd4d3d_3_845;
	label$cbd4d3d_3_842:
	r15 = r3->array;
	r14 = ((vdynamic**)(r15 + 1))[r36];
	r30 = (hl__types__ArrayBytes_Float)hl_dyn_castp(&r14,&$t_dyn,&$t_hl_types_ArrayBytes_Float);
	label$cbd4d3d_3_845:
	r39 = r0->begin;
	r40 = r26 * r16;
	r39 = r39 + r40;
	if( r8 == NULL ) hl_null_access();
	r43 = r8->length;
	if( ((unsigned)r38) < ((unsigned)r43) ) goto label$cbd4d3d_3_853;
	r13 = NULL;
	goto label$cbd4d3d_3_856;
	label$cbd4d3d_3_853:
	r15 = r8->array;
	r14 = ((vdynamic**)(r15 + 1))[r38];
	r13 = (kha__audio2__ogg__vorbis__data__Codebook)r14;
	label$cbd4d3d_3_856:
	if( r13 == NULL ) hl_null_access();
	r44 = r0->type;
	r29 = kha_audio2_ogg_vorbis_data_Codebook_residueDecode(r13,r1,r30,r39,r16,r44);
	if( r29 ) goto label$cbd4d3d_3_861;
	return;
	label$cbd4d3d_3_861:
	goto label$cbd4d3d_3_793;
	label$cbd4d3d_3_862:
	++r26;
	goto label$cbd4d3d_3_786;
	label$cbd4d3d_3_864:
	goto label$cbd4d3d_3_664;
	label$cbd4d3d_3_865:
	goto label$cbd4d3d_3_657;
	label$cbd4d3d_3_866:
	return;
}

