// Generated by HLC 4.0.0 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <kha/korehl/Sound.h>
extern hl_type $t_kha_arrays_Float32ArrayPrivate;
void kha_arrays_Float32ArrayPrivate_new(kha__arrays__Float32ArrayPrivate);
#include <hl/natives.h>
void kha_Sound_new(kha__Sound);

void kha_korehl_Sound_initSound(kha__korehl__Sound r0,String r1) {
	kha__arrays__Float32ArrayPrivate r4, r5;
	double r13;
	double *r14;
	int *r10;
	vbyte *r8, *r9, *r11, *r15;
	int r2, r6, r7, r12;
	r2 = 0;
	r4 = (kha__arrays__Float32ArrayPrivate)hl_alloc_obj(&$t_kha_arrays_Float32ArrayPrivate);
	kha_arrays_Float32ArrayPrivate_new(r4);
	r4->length = r2;
	r7 = 0;
	if( r7 >= r2 ) goto label$0b8cc7c_1_8;
	r8 = hl_kore_float32array_alloc(r2);
	r4->self = r8;
	label$0b8cc7c_1_8:
	r0->uncompressedData = r4;
	r6 = 1;
	r7 = 1;
	r8 = hl_kore_uint32array_alloc(r7);
	r7 = 0;
	if( r1 == NULL ) hl_null_access();
	r9 = r1->bytes;
	r10 = &r7;
	r12 = 0;
	r11 = hl_utf16_to_utf8(r9,r12,r10);
	r13 = r0->length;
	r14 = &r13;
	r15 = hl_kore_sound_init_wav(r11,r8,r14);
	r5 = r0->uncompressedData;
	r12 = 0;
	r12 = hl_kore_uint32array_get(r8,r12);
	if( r5 == NULL ) hl_null_access();
	r5->self = r15;
	r5->length = r12;
	hl_kore_uint32array_free(r8);
	return;
}

void kha_korehl_Sound_new(kha__korehl__Sound r0,String r1,haxe__io__Bytes r2) {
	kha_Sound_new(((kha__Sound)r0));
	kha_korehl_Sound_initSound(r0,r1);
	return;
}

