// Generated by HLC 4.0.0 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <armory/system/Event.h>
extern armory__system__$Event $g__armory_system_Event;
vdynamic* haxe_ds_StringMap_get(haxe__ds__StringMap,String);
extern hl_type $t_hl_types_ArrayObj;
extern hl_type $t_dyn;

hl__types__ArrayObj armory_system_Event_get(String r0) {
	hl__types__ArrayObj r4;
	haxe__ds__StringMap r2;
	armory__system__$Event r3;
	vdynamic *r1;
	r3 = (armory__system__$Event)$g__armory_system_Event;
	r2 = r3->events;
	if( r2 == NULL ) hl_null_access();
	r1 = haxe_ds_StringMap_get(r2,r0);
	r4 = (hl__types__ArrayObj)hl_dyn_castp(&r1,&$t_dyn,&$t_hl_types_ArrayObj);
	return r4;
}

