// Generated by HLC 4.0.0 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <armory/system/Starter.h>
#include <hl/types/ArrayObj.h>
#include <iron/Scene.h>
#include <iron/data/Data.h>
extern iron__$Scene $g__iron_Scene;
void iron_App_removeRender2D(vclosure*);
extern armory__system__$Starter $g__armory_system_Starter;
extern iron__data__$Data $g__iron_data_Data;
#include <iron/object/Object.h>
void iron_RenderPath_setActive(iron__RenderPath);
extern hl_type $t_fun_0e31624;
#include <hl/natives.h>
hl__types__ArrayObj hl_types_ArrayObj_alloc(varray*);
extern hl_type $t_fun_a2f9e9e;
void hl_types_ArrayObj___expand(hl__types__ArrayObj,int);
void iron_App_notifyOnRender2D(vclosure*);
extern hl_type $t_fun_eeac1a0;
void iron_Scene_setActive(String,vclosure*);
#include <kha/Window.h>
extern hl_type $t_fun_8a7a13f;
void iron_App_init(vclosure*);
#include <armory/data/Config.h>
#include <kha/SystemOptions.h>
#include <kha/WindowOptions.h>
#include <kha/FramebufferOptions.h>
extern armory__data__$Config $g__armory_data_Config;
extern hl_type $t_vrt_9442311;
extern hl_type $t_nul_i32;
extern hl_type $t_i32;
extern hl_type $t_nul_bool;
extern hl_type $t_nul_f64;
extern hl_type $t_f64;
void armory_object_Uniforms_register(void);
extern hl_type $t_kha_SystemOptions;
extern String $s_gamepad_tester;
extern hl_type $t_kha_WindowOptions;
void kha_WindowOptions_new(kha__WindowOptions,String,vdynamic*,vdynamic*,vdynamic*,vdynamic*,vdynamic*,vdynamic*,vdynamic*,vdynamic*);
extern hl_type $t_kha_FramebufferOptions;
void kha_FramebufferOptions_new(kha__FramebufferOptions,vdynamic*,vdynamic*,vdynamic*,vdynamic*,vdynamic*,vdynamic*);
void kha_SystemOptions_new(kha__SystemOptions,String,vdynamic*,vdynamic*,kha__WindowOptions,kha__FramebufferOptions);
extern hl_type $t_fun_9b04443;
void kha_System_start(kha__SystemOptions,vclosure*);
extern hl_type $t_ctx_7680ad9;

void armory_system_Starter_main__$4(hl__types__ArrayObj r0,kha__graphics2__Graphics r1) {
	bool r5;
	iron__$Scene r4;
	iron__Scene r3;
	armory__system__$Starter r12;
	vclosure *r8, *r11;
	vdynamic *r9;
	iron__data__$Data r13;
	varray *r10;
	int r6, r7;
	r4 = (iron__$Scene)$g__iron_Scene;
	r3 = r4->active;
	if( !r3 ) goto label$fb84227_1_19;
	r4 = (iron__$Scene)$g__iron_Scene;
	r3 = r4->active;
	if( r3 == NULL ) hl_null_access();
	r5 = r3->ready;
	if( !r5 ) goto label$fb84227_1_19;
	if( r0 == NULL ) hl_null_access();
	r6 = 0;
	r7 = r0->length;
	if( ((unsigned)r6) < ((unsigned)r7) ) goto label$fb84227_1_14;
	r8 = NULL;
	goto label$fb84227_1_17;
	label$fb84227_1_14:
	r10 = r0->array;
	r9 = ((vdynamic**)(r10 + 1))[r6];
	r8 = (vclosure*)r9;
	label$fb84227_1_17:
	iron_App_removeRender2D(r8);
	goto label$fb84227_1_27;
	label$fb84227_1_19:
	r12 = (armory__system__$Starter)$g__armory_system_Starter;
	r11 = r12->drawLoading;
	if( r11 == NULL ) hl_null_access();
	r13 = (iron__data__$Data)$g__iron_data_Data;
	r6 = r13->assetsLoaded;
	r12 = (armory__system__$Starter)$g__armory_system_Starter;
	r7 = r12->numAssets;
	r11->hasValue ? ((void (*)(vdynamic*,kha__graphics2__Graphics,int,int))r11->fun)((vdynamic*)r11->value,r1,r6,r7) : ((void (*)(kha__graphics2__Graphics,int,int))r11->fun)(r1,r6,r7);
	label$fb84227_1_27:
	return;
}

void armory_system_Starter_main__$5(venum* r0,iron__object__Object r1) {
	vclosure *r4;
	iron__RenderPath r3;
	r4 = ((Enum$t_ctx_7680ad9*)r0)->p9;
	if( r4 == NULL ) hl_null_access();
	r3 = r4->hasValue ? ((iron__RenderPath (*)(vdynamic*))r4->fun)((vdynamic*)r4->value) : ((iron__RenderPath (*)(void))r4->fun)();
	iron_RenderPath_setActive(r3);
	return;
}

void armory_system_Starter_main__$3(venum* r0) {
	String r9;
	hl__types__ArrayObj r1;
	hl_type *r3;
	vclosure *r5, *r10;
	vdynamic *r8;
	int r4, r7;
	varray *r2;
	r3 = &$t_fun_0e31624;
	r4 = 1;
	r2 = hl_alloc_array(r3,r4);
	r5 = NULL;
	r4 = 0;
	((vclosure**)(r2 + 1))[r4] = r5;
	r1 = hl_types_ArrayObj_alloc(r2);
	if( r1 == NULL ) hl_null_access();
	r4 = 0;
	r5 = hl_alloc_closure_ptr(&$t_fun_a2f9e9e,armory_system_Starter_main__$4,r1);
	r7 = r1->length;
	if( ((unsigned)r4) < ((unsigned)r7) ) goto label$fb84227_3_13;
	hl_types_ArrayObj___expand(r1,r4);
	label$fb84227_3_13:
	r2 = r1->array;
	((vclosure**)(r2 + 1))[r4] = r5;
	r4 = 0;
	r7 = r1->length;
	if( ((unsigned)r4) < ((unsigned)r7) ) goto label$fb84227_3_20;
	r5 = NULL;
	goto label$fb84227_3_23;
	label$fb84227_3_20:
	r2 = r1->array;
	r8 = ((vdynamic**)(r2 + 1))[r4];
	r5 = (vclosure*)r8;
	label$fb84227_3_23:
	iron_App_notifyOnRender2D(r5);
	r9 = ((Enum$t_ctx_7680ad9*)r0)->p0;
	r10 = hl_alloc_closure_ptr(&$t_fun_eeac1a0,armory_system_Starter_main__$5,r0);
	iron_Scene_setActive(r9,r10);
	return;
}

void armory_system_Starter_main__$2(venum* r0,kha__Window r1) {
	vclosure *r3;
	r3 = hl_alloc_closure_ptr(&$t_fun_8a7a13f,armory_system_Starter_main__$3,r0);
	iron_App_init(r3);
	return;
}

void armory_system_Starter_main__$1(venum* r0) {
	String r17, r19;
	vdynobj *r7;
	vvirtual *r5;
	bool r10;
	kha__FramebufferOptions r27;
	kha__SystemOptions r16;
	armory__system__$Starter r3;
	vclosure *r28;
	double r12;
	armory__data__$Config r6;
	vdynamic *r8, *r9, *r11, *r13, *r20, *r21, *r22, *r23, *r24, *r25, *r26;
	kha__WindowOptions r18;
	int r2, r4, r14, r15;
	r3 = (armory__system__$Starter)$g__armory_system_Starter;
	r2 = r3->tasks;
	r4 = 0;
	if( r4 >= r2 ) goto label$fb84227_5_5;
	return;
	label$fb84227_5_5:
	r6 = (armory__data__$Config)$g__armory_data_Config;
	r5 = r6->raw;
	if( r5 ) goto label$fb84227_5_12;
	r7 = hl_alloc_dynobj();
	r5 = hl_to_virtual(&$t_vrt_9442311,(vdynamic*)r7);
	r6 = (armory__data__$Config)$g__armory_data_Config;
	r6->raw = r5;
	label$fb84227_5_12:
	r6 = (armory__data__$Config)$g__armory_data_Config;
	r5 = r6->raw;
	if( r5 == NULL ) hl_null_access();
	r8 = hl_vfields(r5)[13] ? (*(vdynamic**)(hl_vfields(r5)[13])) : (vdynamic*)hl_dyn_getp(r5->value,420943452/*window_mode*/,&$t_nul_i32);
	if( r8 ) goto label$fb84227_5_20;
	r2 = ((Enum$t_ctx_7680ad9*)r0)->p1;
	r8 = hl_alloc_dynamic(&$t_i32);
	r8->v.i = r2;
	if( hl_vfields(r5)[13] ) *(vdynamic**)(hl_vfields(r5)[13]) = (vdynamic*)r8; else hl_dyn_setp(r5->value,420943452/*window_mode*/,&$t_nul_i32,r8);
	label$fb84227_5_20:
	r9 = hl_vfields(r5)[15] ? (*(vdynamic**)(hl_vfields(r5)[15])) : (vdynamic*)hl_dyn_getp(r5->value,110727964/*window_resizable*/,&$t_nul_bool);
	if( r9 ) goto label$fb84227_5_25;
	r10 = ((Enum$t_ctx_7680ad9*)r0)->p2;
	r9 = hl_alloc_dynbool(r10);
	if( hl_vfields(r5)[15] ) *(vdynamic**)(hl_vfields(r5)[15]) = (vdynamic*)r9; else hl_dyn_setp(r5->value,110727964/*window_resizable*/,&$t_nul_bool,r9);
	label$fb84227_5_25:
	r9 = hl_vfields(r5)[12] ? (*(vdynamic**)(hl_vfields(r5)[12])) : (vdynamic*)hl_dyn_getp(r5->value,221172604/*window_minimizable*/,&$t_nul_bool);
	if( r9 ) goto label$fb84227_5_30;
	r10 = ((Enum$t_ctx_7680ad9*)r0)->p3;
	r9 = hl_alloc_dynbool(r10);
	if( hl_vfields(r5)[12] ) *(vdynamic**)(hl_vfields(r5)[12]) = (vdynamic*)r9; else hl_dyn_setp(r5->value,221172604/*window_minimizable*/,&$t_nul_bool,r9);
	label$fb84227_5_30:
	r9 = hl_vfields(r5)[11] ? (*(vdynamic**)(hl_vfields(r5)[11])) : (vdynamic*)hl_dyn_getp(r5->value,-397857803/*window_maximizable*/,&$t_nul_bool);
	if( r9 ) goto label$fb84227_5_35;
	r10 = ((Enum$t_ctx_7680ad9*)r0)->p4;
	r9 = hl_alloc_dynbool(r10);
	if( hl_vfields(r5)[11] ) *(vdynamic**)(hl_vfields(r5)[11]) = (vdynamic*)r9; else hl_dyn_setp(r5->value,-397857803/*window_maximizable*/,&$t_nul_bool,r9);
	label$fb84227_5_35:
	r8 = hl_vfields(r5)[18] ? (*(vdynamic**)(hl_vfields(r5)[18])) : (vdynamic*)hl_dyn_getp(r5->value,500024503/*window_w*/,&$t_nul_i32);
	if( r8 ) goto label$fb84227_5_40;
	r2 = ((Enum$t_ctx_7680ad9*)r0)->p5;
	r8 = hl_alloc_dynamic(&$t_i32);
	r8->v.i = r2;
	if( hl_vfields(r5)[18] ) *(vdynamic**)(hl_vfields(r5)[18]) = (vdynamic*)r8; else hl_dyn_setp(r5->value,500024503/*window_w*/,&$t_nul_i32,r8);
	label$fb84227_5_40:
	r8 = hl_vfields(r5)[10] ? (*(vdynamic**)(hl_vfields(r5)[10])) : (vdynamic*)hl_dyn_getp(r5->value,500024488/*window_h*/,&$t_nul_i32);
	if( r8 ) goto label$fb84227_5_45;
	r2 = ((Enum$t_ctx_7680ad9*)r0)->p6;
	r8 = hl_alloc_dynamic(&$t_i32);
	r8->v.i = r2;
	if( hl_vfields(r5)[10] ) *(vdynamic**)(hl_vfields(r5)[10]) = (vdynamic*)r8; else hl_dyn_setp(r5->value,500024488/*window_h*/,&$t_nul_i32,r8);
	label$fb84227_5_45:
	r11 = hl_vfields(r5)[16] ? (*(vdynamic**)(hl_vfields(r5)[16])) : (vdynamic*)hl_dyn_getp(r5->value,127024571/*window_scale*/,&$t_nul_f64);
	if( r11 ) goto label$fb84227_5_50;
	r12 = 1.;
	r11 = hl_alloc_dynamic(&$t_f64);
	r11->v.d = r12;
	if( hl_vfields(r5)[16] ) *(vdynamic**)(hl_vfields(r5)[16]) = (vdynamic*)r11; else hl_dyn_setp(r5->value,127024571/*window_scale*/,&$t_nul_f64,r11);
	label$fb84227_5_50:
	r8 = hl_vfields(r5)[14] ? (*(vdynamic**)(hl_vfields(r5)[14])) : (vdynamic*)hl_dyn_getp(r5->value,421141695/*window_msaa*/,&$t_nul_i32);
	if( r8 ) goto label$fb84227_5_55;
	r2 = ((Enum$t_ctx_7680ad9*)r0)->p7;
	r8 = hl_alloc_dynamic(&$t_i32);
	r8->v.i = r2;
	if( hl_vfields(r5)[14] ) *(vdynamic**)(hl_vfields(r5)[14]) = (vdynamic*)r8; else hl_dyn_setp(r5->value,421141695/*window_msaa*/,&$t_nul_i32,r8);
	label$fb84227_5_55:
	r9 = hl_vfields(r5)[17] ? (*(vdynamic**)(hl_vfields(r5)[17])) : (vdynamic*)hl_dyn_getp(r5->value,-328491907/*window_vsync*/,&$t_nul_bool);
	if( r9 ) goto label$fb84227_5_60;
	r10 = ((Enum$t_ctx_7680ad9*)r0)->p8;
	r9 = hl_alloc_dynbool(r10);
	if( hl_vfields(r5)[17] ) *(vdynamic**)(hl_vfields(r5)[17]) = (vdynamic*)r9; else hl_dyn_setp(r5->value,-328491907/*window_vsync*/,&$t_nul_bool,r9);
	label$fb84227_5_60:
	armory_object_Uniforms_register();
	r8 = hl_vfields(r5)[13] ? (*(vdynamic**)(hl_vfields(r5)[13])) : (vdynamic*)hl_dyn_getp(r5->value,420943452/*window_mode*/,&$t_nul_i32);
	r2 = 0;
	r13 = hl_alloc_dynamic(&$t_i32);
	r13->v.i = r2;
	if( r8 != r13 && (!r8 || !r13 || (r8->v.i != r13->v.i)) ) goto label$fb84227_5_67;
	r2 = 0;
	goto label$fb84227_5_68;
	label$fb84227_5_67:
	r2 = 1;
	label$fb84227_5_68:
	r4 = 0;
	r9 = hl_vfields(r5)[15] ? (*(vdynamic**)(hl_vfields(r5)[15])) : (vdynamic*)hl_dyn_getp(r5->value,110727964/*window_resizable*/,&$t_nul_bool);
	r10 = r9 ? r9->v.b : 0;
	if( !r10 ) goto label$fb84227_5_75;
	r15 = 1;
	r14 = r4 | r15;
	r4 = r14;
	label$fb84227_5_75:
	r9 = hl_vfields(r5)[11] ? (*(vdynamic**)(hl_vfields(r5)[11])) : (vdynamic*)hl_dyn_getp(r5->value,-397857803/*window_maximizable*/,&$t_nul_bool);
	r10 = r9 ? r9->v.b : 0;
	if( !r10 ) goto label$fb84227_5_81;
	r15 = 4;
	r14 = r4 | r15;
	r4 = r14;
	label$fb84227_5_81:
	r9 = hl_vfields(r5)[12] ? (*(vdynamic**)(hl_vfields(r5)[12])) : (vdynamic*)hl_dyn_getp(r5->value,221172604/*window_minimizable*/,&$t_nul_bool);
	r10 = r9 ? r9->v.b : 0;
	if( !r10 ) goto label$fb84227_5_87;
	r15 = 2;
	r14 = r4 | r15;
	r4 = r14;
	label$fb84227_5_87:
	r16 = (kha__SystemOptions)hl_alloc_obj(&$t_kha_SystemOptions);
	r17 = (String)$s_gamepad_tester;
	r8 = hl_vfields(r5)[18] ? (*(vdynamic**)(hl_vfields(r5)[18])) : (vdynamic*)hl_dyn_getp(r5->value,500024503/*window_w*/,&$t_nul_i32);
	r13 = hl_vfields(r5)[10] ? (*(vdynamic**)(hl_vfields(r5)[10])) : (vdynamic*)hl_dyn_getp(r5->value,500024488/*window_h*/,&$t_nul_i32);
	r18 = (kha__WindowOptions)hl_alloc_obj(&$t_kha_WindowOptions);
	r19 = NULL;
	r20 = NULL;
	r21 = NULL;
	r22 = NULL;
	r23 = NULL;
	r24 = NULL;
	r9 = NULL;
	r25 = hl_alloc_dynamic(&$t_i32);
	r25->v.i = r4;
	r26 = hl_alloc_dynamic(&$t_i32);
	r26->v.i = r2;
	kha_WindowOptions_new(r18,r19,r20,r21,r22,r23,r24,r9,r25,r26);
	r27 = (kha__FramebufferOptions)hl_alloc_obj(&$t_kha_FramebufferOptions);
	r20 = NULL;
	r9 = hl_vfields(r5)[17] ? (*(vdynamic**)(hl_vfields(r5)[17])) : (vdynamic*)hl_dyn_getp(r5->value,-328491907/*window_vsync*/,&$t_nul_bool);
	r21 = NULL;
	r22 = NULL;
	r23 = NULL;
	r24 = hl_vfields(r5)[14] ? (*(vdynamic**)(hl_vfields(r5)[14])) : (vdynamic*)hl_dyn_getp(r5->value,421141695/*window_msaa*/,&$t_nul_i32);
	kha_FramebufferOptions_new(r27,r20,r9,r21,r22,r23,r24);
	kha_SystemOptions_new(r16,r17,r8,r13,r18,r27);
	r28 = hl_alloc_closure_ptr(&$t_fun_9b04443,armory_system_Starter_main__$2,r0);
	kha_System_start(r16,r28);
	return;
}

void armory_system_Starter_main(String r0,int r1,bool r2,bool r3,bool r4,int r5,int r6,int r7,bool r8,vclosure* r9) {
	venum *r11;
	armory__system__$Starter r14;
	vclosure *r10;
	int r13;
	r11 = hl_alloc_enum(&$t_ctx_7680ad9,0);
	((Enum$t_ctx_7680ad9*)r11)->p0 = (String)r0;
	((Enum$t_ctx_7680ad9*)r11)->p1 = (int)r1;
	((Enum$t_ctx_7680ad9*)r11)->p2 = (bool)r2;
	((Enum$t_ctx_7680ad9*)r11)->p3 = (bool)r3;
	((Enum$t_ctx_7680ad9*)r11)->p4 = (bool)r4;
	((Enum$t_ctx_7680ad9*)r11)->p5 = (int)r5;
	((Enum$t_ctx_7680ad9*)r11)->p6 = (int)r6;
	((Enum$t_ctx_7680ad9*)r11)->p7 = (int)r7;
	((Enum$t_ctx_7680ad9*)r11)->p8 = (bool)r8;
	((Enum$t_ctx_7680ad9*)r11)->p9 = (vclosure*)r9;
	r10 = hl_alloc_closure_ptr(&$t_fun_8a7a13f,armory_system_Starter_main__$1,r11);
	r13 = 1;
	r14 = (armory__system__$Starter)$g__armory_system_Starter;
	r14->tasks = r13;
	r14 = (armory__system__$Starter)$g__armory_system_Starter;
	r13 = r14->tasks;
	--r13;
	r14->tasks = r13;
	if( r10 == NULL ) hl_null_access();
	r10->hasValue ? ((void (*)(vdynamic*))r10->fun)((vdynamic*)r10->value) : ((void (*)(void))r10->fun)();
	return;
}

