// Generated by HLC 4.0.0 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <iron/App.h>
extern hl_type $t_iron_App;
void iron_App_new(iron__App,vclosure*);
#include <iron/system/Time.h>
void iron_App_render(hl__types__ArrayObj);
extern hl_type $t_fun_715d8bf;
void iron_App_update(void);
extern hl_type $t_fun_7b48b4f;
void kha_System_notifyOnFrames(vclosure*);
extern iron__system__$Time $g__iron_system_Time;
int kha_Scheduler_addTimeTask(vclosure*,double,double*,double*);
#include <iron/Scene.h>
#include <hl/types/ArrayBase.h>
extern iron__$Scene $g__iron_Scene;
extern iron__$App $g__iron_App;
void iron_Scene_updateFrame(iron__Scene);
hl__types__ArrayBase hl_types_ArrayObj_splice(hl__types__ArrayObj,int,int);
extern hl_type $t_hl_types_ArrayObj;
extern hl_type $t_hl_types_ArrayBase;
void iron_system_Time_update(void);
void iron_App_render2D(kha__Framebuffer);
vvirtual* kha_Framebuffer_get_g4(kha__Framebuffer);
void iron_Scene_renderFrame(iron__Scene,vvirtual*);
kha__graphics2__Graphics kha_Framebuffer_get_g2(kha__Framebuffer);
int hl_types_ArrayObj_push(hl__types__ArrayObj,vdynamic*);
bool hl_types_ArrayObj_remove(hl__types__ArrayObj,vdynamic*);
#include <hl/natives.h>
hl__types__ArrayObj hl_types_ArrayObj_alloc(varray*);

void iron_App_init(vclosure* r0) {
	iron__App r1;
	r1 = (iron__App)hl_alloc_obj(&$t_iron_App);
	iron_App_new(r1,r0);
	return;
}

void iron_App_new(iron__App r0,vclosure* r1) {
	double r6, r7, r8;
	vclosure *r3, *r4;
	double *r10, *r11;
	iron__system__$Time r9;
	int r5;
	static vclosure cl$0 = { &$t_fun_715d8bf, iron_App_render, 0 };
	static vclosure cl$1 = { &$t_fun_7b48b4f, iron_App_update, 0 };
	if( r1 == NULL ) hl_null_access();
	r1->hasValue ? ((void (*)(vdynamic*))r1->fun)((vdynamic*)r1->value) : ((void (*)(void))r1->fun)();
	r4 = &cl$0;
	kha_System_notifyOnFrames(r4);
	r3 = &cl$1;
	r6 = 0.;
	r7 = 0.016666666666666666;
	r9 = (iron__system__$Time)$g__iron_system_Time;
	r8 = r9->scale;
	r7 = r7 * r8;
	r10 = &r7;
	r11 = NULL;
	r5 = kha_Scheduler_addTimeTask(r3,r6,r10,r11);
	return;
}

void iron_App_update() {
	hl__types__ArrayObj r8, r12;
	iron__$App r5;
	bool r3;
	iron__$Scene r2;
	iron__Scene r1;
	hl__types__ArrayBase r15;
	vclosure *r13;
	vdynamic *r4;
	varray *r14;
	int r6, r7, r9, r10, r11;
	r2 = (iron__$Scene)$g__iron_Scene;
	r1 = r2->active;
	if( !r1 ) goto label$8db8d29_3_8;
	r2 = (iron__$Scene)$g__iron_Scene;
	r1 = r2->active;
	if( r1 == NULL ) hl_null_access();
	r3 = r1->ready;
	if( r3 ) goto label$8db8d29_3_9;
	label$8db8d29_3_8:
	return;
	label$8db8d29_3_9:
	r5 = (iron__$App)$g__iron_App;
	r3 = r5->pauseUpdates;
	if( !r3 ) goto label$8db8d29_3_13;
	return;
	label$8db8d29_3_13:
	r2 = (iron__$Scene)$g__iron_Scene;
	r1 = r2->active;
	if( r1 == NULL ) hl_null_access();
	iron_Scene_updateFrame(r1);
	r6 = 0;
	r5 = (iron__$App)$g__iron_App;
	r8 = r5->traitUpdates;
	if( r8 == NULL ) hl_null_access();
	r7 = r8->length;
	label$8db8d29_3_22:
	if( r6 >= r7 ) goto label$8db8d29_3_91;
	r5 = (iron__$App)$g__iron_App;
	r8 = r5->traitInits;
	if( r8 == NULL ) hl_null_access();
	r9 = r8->length;
	r10 = 0;
	if( r10 >= r9 ) goto label$8db8d29_3_66;
	r9 = 0;
	r5 = (iron__$App)$g__iron_App;
	r8 = r5->traitInits;
	label$8db8d29_3_33:
	if( r8 == NULL ) hl_null_access();
	r11 = r8->length;
	if( r9 >= r11 ) goto label$8db8d29_3_56;
	r11 = r8->length;
	if( ((unsigned)r9) < ((unsigned)r11) ) goto label$8db8d29_3_41;
	r13 = NULL;
	goto label$8db8d29_3_44;
	label$8db8d29_3_41:
	r14 = r8->array;
	r4 = ((vdynamic**)(r14 + 1))[r9];
	r13 = (vclosure*)r4;
	label$8db8d29_3_44:
	++r9;
	r5 = (iron__$App)$g__iron_App;
	r12 = r5->traitInits;
	if( r12 == NULL ) hl_null_access();
	r10 = r12->length;
	r11 = 0;
	if( r11 >= r10 ) goto label$8db8d29_3_54;
	if( r13 == NULL ) hl_null_access();
	r13->hasValue ? ((void (*)(vdynamic*))r13->fun)((vdynamic*)r13->value) : ((void (*)(void))r13->fun)();
	goto label$8db8d29_3_55;
	label$8db8d29_3_54:
	goto label$8db8d29_3_56;
	label$8db8d29_3_55:
	goto label$8db8d29_3_33;
	label$8db8d29_3_56:
	r5 = (iron__$App)$g__iron_App;
	r8 = r5->traitInits;
	if( r8 == NULL ) hl_null_access();
	r9 = 0;
	r5 = (iron__$App)$g__iron_App;
	r12 = r5->traitInits;
	if( r12 == NULL ) hl_null_access();
	r10 = r12->length;
	r15 = hl_types_ArrayObj_splice(r8,r9,r10);
	r8 = (hl__types__ArrayObj)hl_dyn_castp(&r15,&$t_hl_types_ArrayBase,&$t_hl_types_ArrayObj);
	label$8db8d29_3_66:
	r5 = (iron__$App)$g__iron_App;
	r8 = r5->traitUpdates;
	if( r8 == NULL ) hl_null_access();
	r10 = r8->length;
	if( ((unsigned)r6) < ((unsigned)r10) ) goto label$8db8d29_3_73;
	r13 = NULL;
	goto label$8db8d29_3_76;
	label$8db8d29_3_73:
	r14 = r8->array;
	r4 = ((vdynamic**)(r14 + 1))[r6];
	r13 = (vclosure*)r4;
	label$8db8d29_3_76:
	if( r13 == NULL ) hl_null_access();
	r13->hasValue ? ((void (*)(vdynamic*))r13->fun)((vdynamic*)r13->value) : ((void (*)(void))r13->fun)();
	r5 = (iron__$App)$g__iron_App;
	r8 = r5->traitUpdates;
	if( r8 == NULL ) hl_null_access();
	r10 = r8->length;
	if( r10 < r7 ) goto label$8db8d29_3_85;
	++r6;
	goto label$8db8d29_3_90;
	label$8db8d29_3_85:
	r5 = (iron__$App)$g__iron_App;
	r8 = r5->traitUpdates;
	if( r8 == NULL ) hl_null_access();
	r9 = r8->length;
	r7 = r9;
	label$8db8d29_3_90:
	goto label$8db8d29_3_22;
	label$8db8d29_3_91:
	r9 = 0;
	r6 = r9;
	r5 = (iron__$App)$g__iron_App;
	r8 = r5->traitLateUpdates;
	if( r8 == NULL ) hl_null_access();
	r9 = r8->length;
	r7 = r9;
	label$8db8d29_3_98:
	if( r6 >= r7 ) goto label$8db8d29_3_125;
	r5 = (iron__$App)$g__iron_App;
	r8 = r5->traitLateUpdates;
	if( r8 == NULL ) hl_null_access();
	r10 = r8->length;
	if( ((unsigned)r6) < ((unsigned)r10) ) goto label$8db8d29_3_107;
	r13 = NULL;
	goto label$8db8d29_3_110;
	label$8db8d29_3_107:
	r14 = r8->array;
	r4 = ((vdynamic**)(r14 + 1))[r6];
	r13 = (vclosure*)r4;
	label$8db8d29_3_110:
	if( r13 == NULL ) hl_null_access();
	r13->hasValue ? ((void (*)(vdynamic*))r13->fun)((vdynamic*)r13->value) : ((void (*)(void))r13->fun)();
	r5 = (iron__$App)$g__iron_App;
	r8 = r5->traitLateUpdates;
	if( r8 == NULL ) hl_null_access();
	r10 = r8->length;
	if( r10 < r7 ) goto label$8db8d29_3_119;
	++r6;
	goto label$8db8d29_3_124;
	label$8db8d29_3_119:
	r5 = (iron__$App)$g__iron_App;
	r8 = r5->traitLateUpdates;
	if( r8 == NULL ) hl_null_access();
	r9 = r8->length;
	r7 = r9;
	label$8db8d29_3_124:
	goto label$8db8d29_3_98;
	label$8db8d29_3_125:
	r5 = (iron__$App)$g__iron_App;
	r8 = r5->onEndFrames;
	if( !r8 ) goto label$8db8d29_3_146;
	r9 = 0;
	r5 = (iron__$App)$g__iron_App;
	r8 = r5->onEndFrames;
	label$8db8d29_3_131:
	if( r8 == NULL ) hl_null_access();
	r11 = r8->length;
	if( r9 >= r11 ) goto label$8db8d29_3_146;
	r11 = r8->length;
	if( ((unsigned)r9) < ((unsigned)r11) ) goto label$8db8d29_3_139;
	r13 = NULL;
	goto label$8db8d29_3_142;
	label$8db8d29_3_139:
	r14 = r8->array;
	r4 = ((vdynamic**)(r14 + 1))[r9];
	r13 = (vclosure*)r4;
	label$8db8d29_3_142:
	++r9;
	if( r13 == NULL ) hl_null_access();
	r13->hasValue ? ((void (*)(vdynamic*))r13->fun)((vdynamic*)r13->value) : ((void (*)(void))r13->fun)();
	goto label$8db8d29_3_131;
	label$8db8d29_3_146:
	return;
}

void iron_App_render(hl__types__ArrayObj r0) {
	kha__Framebuffer r4;
	vvirtual *r16;
	hl__types__ArrayObj r1, r13;
	iron__$App r8;
	bool r11;
	iron__$Scene r10;
	iron__Scene r9;
	hl__types__ArrayBase r15;
	vclosure *r14, *r17;
	vdynamic *r5;
	varray *r6;
	int r2, r3, r12;
	if( r0 == NULL ) hl_null_access();
	r2 = 0;
	r3 = r0->length;
	if( ((unsigned)r2) < ((unsigned)r3) ) goto label$8db8d29_4_6;
	r4 = NULL;
	goto label$8db8d29_4_9;
	label$8db8d29_4_6:
	r6 = r0->array;
	r5 = ((vdynamic**)(r6 + 1))[r2];
	r4 = (kha__Framebuffer)r5;
	label$8db8d29_4_9:
	r8 = (iron__$App)$g__iron_App;
	r8->framebuffer = r4;
	iron_system_Time_update();
	r10 = (iron__$Scene)$g__iron_Scene;
	r9 = r10->active;
	if( !r9 ) goto label$8db8d29_4_20;
	r10 = (iron__$Scene)$g__iron_Scene;
	r9 = r10->active;
	if( r9 == NULL ) hl_null_access();
	r11 = r9->ready;
	if( r11 ) goto label$8db8d29_4_22;
	label$8db8d29_4_20:
	iron_App_render2D(r4);
	return;
	label$8db8d29_4_22:
	r8 = (iron__$App)$g__iron_App;
	r1 = r8->traitInits;
	if( r1 == NULL ) hl_null_access();
	r2 = r1->length;
	r3 = 0;
	if( r3 >= r2 ) goto label$8db8d29_4_64;
	r2 = 0;
	r8 = (iron__$App)$g__iron_App;
	r1 = r8->traitInits;
	label$8db8d29_4_31:
	if( r1 == NULL ) hl_null_access();
	r12 = r1->length;
	if( r2 >= r12 ) goto label$8db8d29_4_54;
	r12 = r1->length;
	if( ((unsigned)r2) < ((unsigned)r12) ) goto label$8db8d29_4_39;
	r14 = NULL;
	goto label$8db8d29_4_42;
	label$8db8d29_4_39:
	r6 = r1->array;
	r5 = ((vdynamic**)(r6 + 1))[r2];
	r14 = (vclosure*)r5;
	label$8db8d29_4_42:
	++r2;
	r8 = (iron__$App)$g__iron_App;
	r13 = r8->traitInits;
	if( r13 == NULL ) hl_null_access();
	r3 = r13->length;
	r12 = 0;
	if( r12 >= r3 ) goto label$8db8d29_4_52;
	if( r14 == NULL ) hl_null_access();
	r14->hasValue ? ((void (*)(vdynamic*))r14->fun)((vdynamic*)r14->value) : ((void (*)(void))r14->fun)();
	goto label$8db8d29_4_53;
	label$8db8d29_4_52:
	goto label$8db8d29_4_54;
	label$8db8d29_4_53:
	goto label$8db8d29_4_31;
	label$8db8d29_4_54:
	r8 = (iron__$App)$g__iron_App;
	r1 = r8->traitInits;
	if( r1 == NULL ) hl_null_access();
	r2 = 0;
	r8 = (iron__$App)$g__iron_App;
	r13 = r8->traitInits;
	if( r13 == NULL ) hl_null_access();
	r3 = r13->length;
	r15 = hl_types_ArrayObj_splice(r1,r2,r3);
	r1 = (hl__types__ArrayObj)hl_dyn_castp(&r15,&$t_hl_types_ArrayBase,&$t_hl_types_ArrayObj);
	label$8db8d29_4_64:
	r10 = (iron__$Scene)$g__iron_Scene;
	r9 = r10->active;
	if( r9 == NULL ) hl_null_access();
	if( r4 == NULL ) hl_null_access();
	r16 = kha_Framebuffer_get_g4(r4);
	iron_Scene_renderFrame(r9,r16);
	r2 = 0;
	r8 = (iron__$App)$g__iron_App;
	r1 = r8->traitRenders;
	label$8db8d29_4_73:
	if( r1 == NULL ) hl_null_access();
	r12 = r1->length;
	if( r2 >= r12 ) goto label$8db8d29_4_98;
	r12 = r1->length;
	if( ((unsigned)r2) < ((unsigned)r12) ) goto label$8db8d29_4_81;
	r17 = NULL;
	goto label$8db8d29_4_84;
	label$8db8d29_4_81:
	r6 = r1->array;
	r5 = ((vdynamic**)(r6 + 1))[r2];
	r17 = (vclosure*)r5;
	label$8db8d29_4_84:
	++r2;
	r8 = (iron__$App)$g__iron_App;
	r13 = r8->traitRenders;
	if( r13 == NULL ) hl_null_access();
	r3 = r13->length;
	r12 = 0;
	if( r12 >= r3 ) goto label$8db8d29_4_96;
	if( r17 == NULL ) hl_null_access();
	if( r4 == NULL ) hl_null_access();
	r16 = kha_Framebuffer_get_g4(r4);
	r17->hasValue ? ((void (*)(vdynamic*,vvirtual*))r17->fun)((vdynamic*)r17->value,r16) : ((void (*)(vvirtual*))r17->fun)(r16);
	goto label$8db8d29_4_97;
	label$8db8d29_4_96:
	goto label$8db8d29_4_98;
	label$8db8d29_4_97:
	goto label$8db8d29_4_73;
	label$8db8d29_4_98:
	iron_App_render2D(r4);
	return;
}

void iron_App_render2D(kha__Framebuffer r0) {
	bool *r8;
	hl__types__ArrayObj r3, r11;
	iron__$App r4;
	bool r7;
	kha__graphics2__Graphics r6;
	vclosure *r12;
	vdynamic *r9, *r13;
	varray *r14;
	int r2, r5, r10;
	r4 = (iron__$App)$g__iron_App;
	r3 = r4->traitRenders2D;
	if( r3 == NULL ) hl_null_access();
	r2 = r3->length;
	r5 = 0;
	if( r5 >= r2 ) goto label$8db8d29_5_45;
	if( r0 == NULL ) hl_null_access();
	r6 = kha_Framebuffer_get_g2(r0);
	if( r6 == NULL ) hl_null_access();
	r7 = false;
	r8 = &r7;
	r9 = NULL;
	((void (*)(kha__graphics2__Graphics,bool*,vdynamic*))r6->$type->vobj_proto[0])(r6,r8,r9);
	r2 = 0;
	r4 = (iron__$App)$g__iron_App;
	r3 = r4->traitRenders2D;
	label$8db8d29_5_16:
	if( r3 == NULL ) hl_null_access();
	r10 = r3->length;
	if( r2 >= r10 ) goto label$8db8d29_5_41;
	r10 = r3->length;
	if( ((unsigned)r2) < ((unsigned)r10) ) goto label$8db8d29_5_24;
	r12 = NULL;
	goto label$8db8d29_5_27;
	label$8db8d29_5_24:
	r14 = r3->array;
	r13 = ((vdynamic**)(r14 + 1))[r2];
	r12 = (vclosure*)r13;
	label$8db8d29_5_27:
	++r2;
	r4 = (iron__$App)$g__iron_App;
	r11 = r4->traitRenders2D;
	if( r11 == NULL ) hl_null_access();
	r5 = r11->length;
	r10 = 0;
	if( r10 >= r5 ) goto label$8db8d29_5_39;
	if( r12 == NULL ) hl_null_access();
	if( r0 == NULL ) hl_null_access();
	r6 = kha_Framebuffer_get_g2(r0);
	r12->hasValue ? ((void (*)(vdynamic*,kha__graphics2__Graphics))r12->fun)((vdynamic*)r12->value,r6) : ((void (*)(kha__graphics2__Graphics))r12->fun)(r6);
	goto label$8db8d29_5_40;
	label$8db8d29_5_39:
	goto label$8db8d29_5_41;
	label$8db8d29_5_40:
	goto label$8db8d29_5_16;
	label$8db8d29_5_41:
	if( r0 == NULL ) hl_null_access();
	r6 = kha_Framebuffer_get_g2(r0);
	if( r6 == NULL ) hl_null_access();
	((void (*)(kha__graphics2__Graphics))r6->$type->vobj_proto[1])(r6);
	label$8db8d29_5_45:
	return;
}

void iron_App_notifyOnInit(vclosure* r0) {
	hl__types__ArrayObj r2;
	iron__$App r3;
	int r1;
	r3 = (iron__$App)$g__iron_App;
	r2 = r3->traitInits;
	if( r2 == NULL ) hl_null_access();
	r1 = hl_types_ArrayObj_push(r2,((vdynamic*)r0));
	return;
}

void iron_App_removeInit(vclosure* r0) {
	hl__types__ArrayObj r2;
	iron__$App r3;
	bool r1;
	r3 = (iron__$App)$g__iron_App;
	r2 = r3->traitInits;
	if( r2 == NULL ) hl_null_access();
	r1 = hl_types_ArrayObj_remove(r2,((vdynamic*)r0));
	return;
}

void iron_App_notifyOnUpdate(vclosure* r0) {
	hl__types__ArrayObj r2;
	iron__$App r3;
	int r1;
	r3 = (iron__$App)$g__iron_App;
	r2 = r3->traitUpdates;
	if( r2 == NULL ) hl_null_access();
	r1 = hl_types_ArrayObj_push(r2,((vdynamic*)r0));
	return;
}

void iron_App_removeUpdate(vclosure* r0) {
	hl__types__ArrayObj r2;
	iron__$App r3;
	bool r1;
	r3 = (iron__$App)$g__iron_App;
	r2 = r3->traitUpdates;
	if( r2 == NULL ) hl_null_access();
	r1 = hl_types_ArrayObj_remove(r2,((vdynamic*)r0));
	return;
}

void iron_App_removeLateUpdate(vclosure* r0) {
	hl__types__ArrayObj r2;
	iron__$App r3;
	bool r1;
	r3 = (iron__$App)$g__iron_App;
	r2 = r3->traitLateUpdates;
	if( r2 == NULL ) hl_null_access();
	r1 = hl_types_ArrayObj_remove(r2,((vdynamic*)r0));
	return;
}

void iron_App_removeRender(vclosure* r0) {
	hl__types__ArrayObj r2;
	iron__$App r3;
	bool r1;
	r3 = (iron__$App)$g__iron_App;
	r2 = r3->traitRenders;
	if( r2 == NULL ) hl_null_access();
	r1 = hl_types_ArrayObj_remove(r2,((vdynamic*)r0));
	return;
}

void iron_App_notifyOnRender2D(vclosure* r0) {
	hl__types__ArrayObj r2;
	iron__$App r3;
	int r1;
	r3 = (iron__$App)$g__iron_App;
	r2 = r3->traitRenders2D;
	if( r2 == NULL ) hl_null_access();
	r1 = hl_types_ArrayObj_push(r2,((vdynamic*)r0));
	return;
}

void iron_App_removeRender2D(vclosure* r0) {
	hl__types__ArrayObj r2;
	iron__$App r3;
	bool r1;
	r3 = (iron__$App)$g__iron_App;
	r2 = r3->traitRenders2D;
	if( r2 == NULL ) hl_null_access();
	r1 = hl_types_ArrayObj_remove(r2,((vdynamic*)r0));
	return;
}

void iron_App_notifyOnReset(vclosure* r0) {
	hl__types__ArrayObj r2;
	hl_type *r5;
	iron__$App r3;
	int r6;
	varray *r4;
	r3 = (iron__$App)$g__iron_App;
	r2 = r3->onResets;
	if( r2 ) goto label$8db8d29_14_9;
	r5 = &$t_fun_7b48b4f;
	r6 = 0;
	r4 = hl_alloc_array(r5,r6);
	r2 = hl_types_ArrayObj_alloc(r4);
	r3 = (iron__$App)$g__iron_App;
	r3->onResets = r2;
	label$8db8d29_14_9:
	r3 = (iron__$App)$g__iron_App;
	r2 = r3->onResets;
	if( r2 == NULL ) hl_null_access();
	r6 = hl_types_ArrayObj_push(r2,((vdynamic*)r0));
	return;
}

void iron_App_notifyOnEndFrame(vclosure* r0) {
	hl__types__ArrayObj r2;
	hl_type *r5;
	iron__$App r3;
	int r6;
	varray *r4;
	r3 = (iron__$App)$g__iron_App;
	r2 = r3->onEndFrames;
	if( r2 ) goto label$8db8d29_15_9;
	r5 = &$t_fun_7b48b4f;
	r6 = 0;
	r4 = hl_alloc_array(r5,r6);
	r2 = hl_types_ArrayObj_alloc(r4);
	r3 = (iron__$App)$g__iron_App;
	r3->onEndFrames = r2;
	label$8db8d29_15_9:
	r3 = (iron__$App)$g__iron_App;
	r2 = r3->onEndFrames;
	if( r2 == NULL ) hl_null_access();
	r6 = hl_types_ArrayObj_push(r2,((vdynamic*)r0));
	return;
}

