// Generated by HLC 4.0.0 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <iron/RenderPath.h>
extern iron__$RenderPath $g__iron_RenderPath;
#include <iron/object/CameraObject.h>
#include <iron/Scene.h>
#include <iron/data/TLightData.h>
#include <iron/data/LightData.h>
int kha_System_windowWidth(int*);
int kha_System_windowHeight(int*);
double kha_Scheduler_time(void);
extern iron__$Scene $g__iron_Scene;
vvirtual* kha_Image_get_g4(kha__Image);
vvirtual* kha_graphics4_CubeMap_get_g4(kha__graphics4__CubeMap);
void iron_object_LightObject_buildMatrix(iron__object__LightObject,iron__object__CameraObject);
extern String $s_sun;
int String___compare(String,vdynamic*);
extern String $s_;
int kha_graphics4_CubeMap_get_width(kha__graphics4__CubeMap);
int kha_graphics4_CubeMap_get_height(kha__graphics4__CubeMap);
extern hl_type $t_fun_4c7a70a;
extern hl_type $t_fun_dc4017d;
extern hl_type $t_fun_58e3acc;
void iron_RenderPath_setFrameScissor(iron__RenderPath);
vdynamic* haxe_ds_StringMap_get(haxe__ds__StringMap,String);
extern hl_type $t_vrt_8a7100d;
#include <hl/natives.h>
hl__types__ArrayObj hl_types_ArrayObj_alloc(varray*);
int hl_types_ArrayObj_push(hl__types__ArrayObj,vdynamic*);
int kha_Image_get_width(kha__Image);
int kha_Image_get_height(kha__Image);
int kha_Image_get_depth(kha__Image);
extern hl_type $t_fun_5ac3579;
void iron_RenderPath_setCurrentViewport(iron__RenderPath,int,int);
void iron_RenderPath_setCurrentScissor(iron__RenderPath,int,int);
#include <iron/data/WorldData.h>
#include <iron/data/TWorldData.h>
#include <iron/data/TCameraData.h>
#include <iron/data/CameraData.h>
extern hl_type $t_i32;
int kha__Color_Color_Impl__fromFloats(float,float,float,float*);
extern hl_type $t_fun_5967954;
#include <iron/object/MeshObject.h>
extern hl_type $t_fun_01f8d35;
int wrap$t_fun_2237bde(vclosure*,vdynamic*,vdynamic*);
extern hl_type $t_fun_2237bde;
void hl_types_ArrayObj_sort(hl__types__ArrayObj,vclosure*);
#include <iron/data/MaterialData.h>
#include <iron/object/LightObject.h>
extern String $s_shadowmap;
void iron_object_LightObject_setCubeFace(iron__object__LightObject,int,iron__object__CameraObject);
extern iron__object__$LightObject $g__iron_object_LightObject;
void iron_object_LightObject_setCascade(iron__object__LightObject,iron__object__CameraObject,int);
void iron_RenderPath_submitDraw(iron__RenderPath,String);
#include <iron/math/Mat4.h>
#include <iron/object/Transform.h>
extern iron__object__$MeshObject $g__iron_object_MeshObject;
void iron_object_MeshObject_render(iron__object__MeshObject,vvirtual*,String,hl__types__ArrayObj);
#include <iron/data/ConstData.h>
#include <iron/data/ShaderContext.h>
#include <iron/object/Object.h>
extern iron__data__$ConstData $g__iron_data_ConstData;
void iron_data_ConstData_createSkydomeData(void);
extern hl_type $t_fun_c80ec77;
void iron_object_Uniforms_setContextConstants(vvirtual*,iron__data__ShaderContext,hl__types__ArrayObj);
void iron_object_Uniforms_setObjectConstants(vvirtual*,iron__data__ShaderContext,iron__object__Object);
extern hl_type $t_fun_a561c62;
extern hl_type $t_fun_46c6b6e;
extern hl_type $t_fun_8305be0;
extern hl_type $t_String;
void iron_data_ConstData_createScreenAlignedData(void);
#include <iron/data/ShaderData.h>
iron__data__ShaderContext iron_data_ShaderData_getContext(iron__data__ShaderData,String);
#include <iron/data/TShaderOverride.h>
extern hl_type $t_iron_CachedShaderContext;
void iron_CachedShaderContext_new(iron__CachedShaderContext);
void haxe_ds_StringMap_set(haxe__ds__StringMap,String,vdynamic*);
extern String $s_6666cd7;
hl__types__ArrayObj String_split(String,String);
extern hl_type $t_ctx_a363d40;
extern hl_type $t_fun_0f246dc;
void iron_data_Data_getShader(String,String,vclosure*,iron__data__TShaderOverride);
#include <iron/RenderTargetRaw.h>
iron__RenderTarget iron_RenderPath_createTarget(iron__RenderPath,iron__RenderTargetRaw);
extern hl_type $t_vrt_ee58142;
extern hl_type $t_iron_RenderTarget;
void iron_RenderTarget_new(iron__RenderTarget,iron__RenderTargetRaw);
kha__Image iron_RenderPath_createImage(iron__RenderPath,iron__RenderTargetRaw,int);
void kha_Image_setDepthStencilFrom(kha__Image,kha__Image);
kha__graphics4__CubeMap iron_RenderPath_createCubeMap(iron__RenderPath,iron__RenderTargetRaw,int);
kha__Image kha_Image_create3D(int,int,int,vdynamic*,vdynamic*);
void kha_Image_generateMipmaps(kha__Image,int);
kha__Image kha_Image_create(int,int,vdynamic*,vdynamic*);
kha__Image kha_Image_createRenderTarget(int,int,vdynamic*,int*,int*,int*);
kha__graphics4__CubeMap kha_graphics4_CubeMap_createRenderTarget(int,vdynamic*,vdynamic*,int*);
extern hl_type $t_haxe_ds_StringMap;
void haxe_ds_StringMap_new(haxe__ds__StringMap);

bool iron_RenderPath_get_ready(iron__RenderPath r0) {
	bool r1;
	int r2, r3;
	r2 = r0->loading;
	r3 = 0;
	if( r2 == r3 ) goto label$80733c3_1_5;
	r1 = false;
	goto label$80733c3_1_6;
	label$80733c3_1_5:
	r1 = true;
	label$80733c3_1_6:
	return r1;
}

void iron_RenderPath_setActive(iron__RenderPath r0) {
	iron__$RenderPath r1;
	r1 = (iron__$RenderPath)$g__iron_RenderPath;
	r1->active = r0;
	return;
}

void iron_RenderPath_renderFrame(iron__RenderPath r0,vvirtual* r1) {
	String r21, r24;
	kha__graphics4__CubeMap r15;
	kha__Image r14;
	iron__data__TLightData r22;
	hl__types__ArrayObj r17;
	vvirtual *r16;
	iron__$Scene r12;
	iron__Scene r11;
	bool r3;
	iron__data__LightData r23;
	iron__object__LightObject r19;
	vclosure *r25;
	iron__object__CameraObject r10, r13;
	double r8, r9;
	vdynamic *r7;
	int *r5;
	varray *r20;
	int r4, r6, r18;
	r3 = iron_RenderPath_get_ready(r0);
	if( !r3 ) goto label$80733c3_3_12;
	r3 = r0->paused;
	if( r3 ) goto label$80733c3_3_12;
	r5 = NULL;
	r4 = kha_System_windowWidth(r5);
	r6 = 0;
	if( r4 == r6 ) goto label$80733c3_3_12;
	r5 = NULL;
	r4 = kha_System_windowHeight(r5);
	r6 = 0;
	if( r4 != r6 ) goto label$80733c3_3_13;
	label$80733c3_3_12:
	return;
	label$80733c3_3_13:
	r8 = kha_Scheduler_time();
	r9 = r0->lastFrameTime;
	r8 = r8 - r9;
	r0->frameTime = r8;
	r8 = kha_Scheduler_time();
	r0->lastFrameTime = r8;
	r12 = (iron__$Scene)$g__iron_Scene;
	r11 = r12->active;
	if( r11 == NULL ) hl_null_access();
	r10 = r11->camera;
	if( !r10 ) goto label$80733c3_3_29;
	if( r10 == NULL ) hl_null_access();
	r14 = r10->renderTarget;
	if( !r14 ) goto label$80733c3_3_29;
	r3 = true;
	goto label$80733c3_3_30;
	label$80733c3_3_29:
	r3 = false;
	label$80733c3_3_30:
	r0->isProbePlanar = r3;
	if( !r10 ) goto label$80733c3_3_37;
	if( r10 == NULL ) hl_null_access();
	r15 = r10->renderTargetCube;
	if( !r15 ) goto label$80733c3_3_37;
	r3 = true;
	goto label$80733c3_3_38;
	label$80733c3_3_37:
	r3 = false;
	label$80733c3_3_38:
	r0->isProbeCube = r3;
	r3 = r0->isProbePlanar;
	if( r3 ) goto label$80733c3_3_45;
	r3 = r0->isProbeCube;
	if( r3 ) goto label$80733c3_3_45;
	r3 = false;
	goto label$80733c3_3_46;
	label$80733c3_3_45:
	r3 = true;
	label$80733c3_3_46:
	r0->isProbe = r3;
	r3 = r0->isProbePlanar;
	if( !r3 ) goto label$80733c3_3_55;
	if( r10 == NULL ) hl_null_access();
	r14 = r10->renderTarget;
	if( r14 == NULL ) hl_null_access();
	r16 = kha_Image_get_g4(r14);
	r0->frameG = r16;
	goto label$80733c3_3_64;
	label$80733c3_3_55:
	r3 = r0->isProbeCube;
	if( !r3 ) goto label$80733c3_3_63;
	if( r10 == NULL ) hl_null_access();
	r15 = r10->renderTargetCube;
	if( r15 == NULL ) hl_null_access();
	r16 = kha_graphics4_CubeMap_get_g4(r15);
	r0->frameG = r16;
	goto label$80733c3_3_64;
	label$80733c3_3_63:
	r0->frameG = r1;
	label$80733c3_3_64:
	r5 = NULL;
	r4 = kha_System_windowWidth(r5);
	r0->currentW = r4;
	r5 = NULL;
	r4 = kha_System_windowHeight(r5);
	r0->currentH = r4;
	r4 = 1;
	r0->currentD = r4;
	r4 = -1;
	r0->currentFace = r4;
	r3 = false;
	r0->meshesSorted = r3;
	r4 = 0;
	r12 = (iron__$Scene)$g__iron_Scene;
	r11 = r12->active;
	if( r11 == NULL ) hl_null_access();
	r17 = r11->lights;
	label$80733c3_3_81:
	if( r17 == NULL ) hl_null_access();
	r18 = r17->length;
	if( r4 >= r18 ) goto label$80733c3_3_112;
	r18 = r17->length;
	if( ((unsigned)r4) < ((unsigned)r18) ) goto label$80733c3_3_89;
	r19 = NULL;
	goto label$80733c3_3_92;
	label$80733c3_3_89:
	r20 = r17->array;
	r7 = ((vdynamic**)(r20 + 1))[r4];
	r19 = (iron__object__LightObject)r7;
	label$80733c3_3_92:
	++r4;
	if( r19 == NULL ) hl_null_access();
	r3 = r19->visible;
	if( !r3 ) goto label$80733c3_3_101;
	r12 = (iron__$Scene)$g__iron_Scene;
	r11 = r12->active;
	if( r11 == NULL ) hl_null_access();
	r13 = r11->camera;
	iron_object_LightObject_buildMatrix(r19,r13);
	label$80733c3_3_101:
	r23 = r19->data;
	if( r23 == NULL ) hl_null_access();
	r22 = r23->raw;
	if( r22 == NULL ) hl_null_access();
	r21 = r22->type;
	r24 = (String)$s_sun;
	if( r21 != r24 && (!r21 || !r24 || String___compare(r21,(vdynamic*)r24) != 0) ) goto label$80733c3_3_110;
	r0->sun = r19;
	goto label$80733c3_3_111;
	label$80733c3_3_110:
	r0->point = r19;
	label$80733c3_3_111:
	goto label$80733c3_3_81;
	label$80733c3_3_112:
	r12 = (iron__$Scene)$g__iron_Scene;
	r11 = r12->active;
	if( r11 == NULL ) hl_null_access();
	r17 = r11->lights;
	if( r17 == NULL ) hl_null_access();
	r4 = 0;
	r6 = r17->length;
	if( ((unsigned)r4) < ((unsigned)r6) ) goto label$80733c3_3_122;
	r19 = NULL;
	goto label$80733c3_3_125;
	label$80733c3_3_122:
	r20 = r17->array;
	r7 = ((vdynamic**)(r20 + 1))[r4];
	r19 = (iron__object__LightObject)r7;
	label$80733c3_3_125:
	r0->light = r19;
	r25 = r0->commands;
	if( r25 == NULL ) hl_null_access();
	r25->hasValue ? ((void (*)(vdynamic*))r25->fun)((vdynamic*)r25->value) : ((void (*)(void))r25->fun)();
	r3 = r0->isProbe;
	if( r3 ) goto label$80733c3_3_134;
	r4 = r0->frame;
	++r4;
	r0->frame = r4;
	label$80733c3_3_134:
	return;
}

void iron_RenderPath_setTarget(iron__RenderPath r0,String r1,hl__types__ArrayObj r2,double* r3) {
	kha__graphics4__CubeMap r11;
	String r6, r7;
	kha__Image r27;
	haxe__ds__StringMap r22;
	hl__types__ArrayObj r17, r24;
	vvirtual *r15, *r16;
	hl_type *r26;
	iron__$Scene r14;
	iron__Scene r13;
	bool r10;
	iron__RenderTarget r9, r23;
	iron__object__CameraObject r12;
	double r4, r28, r29;
	vdynamic *r21;
	int *r20;
	varray *r25;
	int r8, r18, r19;
	if( r3 ) goto label$80733c3_4_3;
	r4 = 1.;
	goto label$80733c3_4_4;
	label$80733c3_4_3:
	r4 = *r3;
	label$80733c3_4_4:
	r7 = (String)$s_;
	if( r1 != r7 && (!r1 || !r7 || String___compare(r1,(vdynamic*)r7) != 0) ) goto label$80733c3_4_102;
	r8 = 1;
	r0->currentD = r8;
	r9 = NULL;
	r0->currentTarget = r9;
	r8 = -1;
	r0->currentFace = r8;
	r10 = r0->isProbeCube;
	if( !r10 ) goto label$80733c3_4_65;
	r14 = (iron__$Scene)$g__iron_Scene;
	r13 = r14->active;
	if( r13 == NULL ) hl_null_access();
	r12 = r13->camera;
	if( r12 == NULL ) hl_null_access();
	r11 = r12->renderTargetCube;
	if( r11 == NULL ) hl_null_access();
	r8 = kha_graphics4_CubeMap_get_width(r11);
	r0->currentW = r8;
	r14 = (iron__$Scene)$g__iron_Scene;
	r13 = r14->active;
	if( r13 == NULL ) hl_null_access();
	r12 = r13->camera;
	if( r12 == NULL ) hl_null_access();
	r11 = r12->renderTargetCube;
	if( r11 == NULL ) hl_null_access();
	r8 = kha_graphics4_CubeMap_get_height(r11);
	r0->currentH = r8;
	r15 = r0->frameG;
	r14 = (iron__$Scene)$g__iron_Scene;
	r13 = r14->active;
	if( r13 == NULL ) hl_null_access();
	r12 = r13->camera;
	if( r12 == NULL ) hl_null_access();
	r8 = r12->currentFace;
	r16 = r0->currentG;
	if( !r16 ) goto label$80733c3_4_55;
	r10 = r0->scissorSet;
	if( !r10 ) goto label$80733c3_4_48;
	r16 = r0->currentG;
	if( r16 == NULL ) hl_null_access();
	if( hl_vfields(r16)[28] ) ((void (*)(vdynamic*))hl_vfields(r16)[28])(r16->value); else {
		hl_dyn_call_obj(r16->value,&$t_fun_4c7a70a,40268564/*disableScissor*/,NULL,NULL);
	}
	r10 = false;
	r0->scissorSet = r10;
	label$80733c3_4_48:
	r16 = r0->currentG;
	if( r16 == NULL ) hl_null_access();
	if( hl_vfields(r16)[25] ) ((void (*)(vdynamic*))hl_vfields(r16)[25])(r16->value); else {
		hl_dyn_call_obj(r16->value,&$t_fun_4c7a70a,5047259/*end*/,NULL,NULL);
	}
	r16 = NULL;
	r0->currentG = r16;
	r17 = NULL;
	r0->bindParams = r17;
	label$80733c3_4_55:
	r0->currentG = r15;
	r19 = 0;
	if( r8 < r19 ) goto label$80733c3_4_61;
	if( r15 == NULL ) hl_null_access();
	if( hl_vfields(r15)[30] ) ((void (*)(vdynamic*,int))hl_vfields(r15)[30])(r15->value,r8); else {
		void *args[] = {&r8};
		hl_dyn_call_obj(r15->value,&$t_fun_dc4017d,-326135337/*beginFace*/,args,NULL);
	}
	goto label$80733c3_4_64;
	label$80733c3_4_61:
	if( r15 == NULL ) hl_null_access();
	r17 = NULL;
	if( hl_vfields(r15)[31] ) ((void (*)(vdynamic*,hl__types__ArrayObj))hl_vfields(r15)[31])(r15->value,r17); else {
		void *args[] = {r17};
		hl_dyn_call_obj(r15->value,&$t_fun_58e3acc,-262805217/*begin*/,args,NULL);
	}
	label$80733c3_4_64:
	goto label$80733c3_4_101;
	label$80733c3_4_65:
	r20 = NULL;
	r8 = kha_System_windowWidth(r20);
	r0->currentW = r8;
	r20 = NULL;
	r8 = kha_System_windowHeight(r20);
	r0->currentH = r8;
	r10 = r0->frameScissor;
	if( !r10 ) goto label$80733c3_4_74;
	iron_RenderPath_setFrameScissor(r0);
	label$80733c3_4_74:
	r15 = r0->frameG;
	r8 = -1;
	r16 = r0->currentG;
	if( !r16 ) goto label$80733c3_4_92;
	r10 = r0->scissorSet;
	if( !r10 ) goto label$80733c3_4_85;
	r16 = r0->currentG;
	if( r16 == NULL ) hl_null_access();
	if( hl_vfields(r16)[28] ) ((void (*)(vdynamic*))hl_vfields(r16)[28])(r16->value); else {
		hl_dyn_call_obj(r16->value,&$t_fun_4c7a70a,40268564/*disableScissor*/,NULL,NULL);
	}
	r10 = false;
	r0->scissorSet = r10;
	label$80733c3_4_85:
	r16 = r0->currentG;
	if( r16 == NULL ) hl_null_access();
	if( hl_vfields(r16)[25] ) ((void (*)(vdynamic*))hl_vfields(r16)[25])(r16->value); else {
		hl_dyn_call_obj(r16->value,&$t_fun_4c7a70a,5047259/*end*/,NULL,NULL);
	}
	r16 = NULL;
	r0->currentG = r16;
	r17 = NULL;
	r0->bindParams = r17;
	label$80733c3_4_92:
	r0->currentG = r15;
	r19 = 0;
	if( r8 < r19 ) goto label$80733c3_4_98;
	if( r15 == NULL ) hl_null_access();
	if( hl_vfields(r15)[30] ) ((void (*)(vdynamic*,int))hl_vfields(r15)[30])(r15->value,r8); else {
		void *args[] = {&r8};
		hl_dyn_call_obj(r15->value,&$t_fun_dc4017d,-326135337/*beginFace*/,args,NULL);
	}
	goto label$80733c3_4_101;
	label$80733c3_4_98:
	if( r15 == NULL ) hl_null_access();
	r17 = NULL;
	if( hl_vfields(r15)[31] ) ((void (*)(vdynamic*,hl__types__ArrayObj))hl_vfields(r15)[31])(r15->value,r17); else {
		void *args[] = {r17};
		hl_dyn_call_obj(r15->value,&$t_fun_58e3acc,-262805217/*begin*/,args,NULL);
	}
	label$80733c3_4_101:
	goto label$80733c3_4_197;
	label$80733c3_4_102:
	r22 = r0->renderTargets;
	if( r22 == NULL ) hl_null_access();
	r21 = haxe_ds_StringMap_get(r22,r1);
	r9 = (iron__RenderTarget)r21;
	r0->currentTarget = r9;
	r17 = NULL;
	if( !r2 ) goto label$80733c3_4_136;
	r26 = &$t_vrt_8a7100d;
	r8 = 0;
	r25 = hl_alloc_array(r26,r8);
	r24 = hl_types_ArrayObj_alloc(r25);
	r17 = r24;
	r8 = 0;
	label$80733c3_4_115:
	if( r2 == NULL ) hl_null_access();
	r19 = r2->length;
	if( r8 >= r19 ) goto label$80733c3_4_136;
	r19 = r2->length;
	if( ((unsigned)r8) < ((unsigned)r19) ) goto label$80733c3_4_123;
	r6 = NULL;
	goto label$80733c3_4_126;
	label$80733c3_4_123:
	r25 = r2->array;
	r21 = ((vdynamic**)(r25 + 1))[r8];
	r6 = (String)r21;
	label$80733c3_4_126:
	++r8;
	r22 = r0->renderTargets;
	if( r22 == NULL ) hl_null_access();
	r21 = haxe_ds_StringMap_get(r22,r6);
	r23 = (iron__RenderTarget)r21;
	if( r17 == NULL ) hl_null_access();
	if( r23 == NULL ) hl_null_access();
	r27 = r23->image;
	r18 = hl_types_ArrayObj_push(r17,((vdynamic*)r27));
	goto label$80733c3_4_115;
	label$80733c3_4_136:
	if( r9 == NULL ) hl_null_access();
	r10 = r9->isCubeMap;
	if( !r10 ) goto label$80733c3_4_143;
	r11 = r9->cubeMap;
	if( r11 == NULL ) hl_null_access();
	r15 = kha_graphics4_CubeMap_get_g4(r11);
	goto label$80733c3_4_146;
	label$80733c3_4_143:
	r27 = r9->image;
	if( r27 == NULL ) hl_null_access();
	r15 = kha_Image_get_g4(r27);
	label$80733c3_4_146:
	r10 = r9->isCubeMap;
	if( !r10 ) goto label$80733c3_4_152;
	r11 = r9->cubeMap;
	if( r11 == NULL ) hl_null_access();
	r8 = kha_graphics4_CubeMap_get_width(r11);
	goto label$80733c3_4_155;
	label$80733c3_4_152:
	r27 = r9->image;
	if( r27 == NULL ) hl_null_access();
	r8 = kha_Image_get_width(r27);
	label$80733c3_4_155:
	r0->currentW = r8;
	r10 = r9->isCubeMap;
	if( !r10 ) goto label$80733c3_4_162;
	r11 = r9->cubeMap;
	if( r11 == NULL ) hl_null_access();
	r8 = kha_graphics4_CubeMap_get_height(r11);
	goto label$80733c3_4_165;
	label$80733c3_4_162:
	r27 = r9->image;
	if( r27 == NULL ) hl_null_access();
	r8 = kha_Image_get_height(r27);
	label$80733c3_4_165:
	r0->currentH = r8;
	r10 = r9->is3D;
	if( !r10 ) goto label$80733c3_4_172;
	r27 = r9->image;
	if( r27 == NULL ) hl_null_access();
	r8 = kha_Image_get_depth(r27);
	r0->currentD = r8;
	label$80733c3_4_172:
	r8 = r0->currentFace;
	r16 = r0->currentG;
	if( !r16 ) goto label$80733c3_4_189;
	r10 = r0->scissorSet;
	if( !r10 ) goto label$80733c3_4_182;
	r16 = r0->currentG;
	if( r16 == NULL ) hl_null_access();
	if( hl_vfields(r16)[28] ) ((void (*)(vdynamic*))hl_vfields(r16)[28])(r16->value); else {
		hl_dyn_call_obj(r16->value,&$t_fun_4c7a70a,40268564/*disableScissor*/,NULL,NULL);
	}
	r10 = false;
	r0->scissorSet = r10;
	label$80733c3_4_182:
	r16 = r0->currentG;
	if( r16 == NULL ) hl_null_access();
	if( hl_vfields(r16)[25] ) ((void (*)(vdynamic*))hl_vfields(r16)[25])(r16->value); else {
		hl_dyn_call_obj(r16->value,&$t_fun_4c7a70a,5047259/*end*/,NULL,NULL);
	}
	r16 = NULL;
	r0->currentG = r16;
	r24 = NULL;
	r0->bindParams = r24;
	label$80733c3_4_189:
	r0->currentG = r15;
	r19 = 0;
	if( r8 < r19 ) goto label$80733c3_4_195;
	if( r15 == NULL ) hl_null_access();
	if( hl_vfields(r15)[30] ) ((void (*)(vdynamic*,int))hl_vfields(r15)[30])(r15->value,r8); else {
		void *args[] = {&r8};
		hl_dyn_call_obj(r15->value,&$t_fun_dc4017d,-326135337/*beginFace*/,args,NULL);
	}
	goto label$80733c3_4_197;
	label$80733c3_4_195:
	if( r15 == NULL ) hl_null_access();
	if( hl_vfields(r15)[31] ) ((void (*)(vdynamic*,hl__types__ArrayObj))hl_vfields(r15)[31])(r15->value,r17); else {
		void *args[] = {r17};
		hl_dyn_call_obj(r15->value,&$t_fun_58e3acc,-262805217/*begin*/,args,NULL);
	}
	label$80733c3_4_197:
	r29 = 1.;
	if( r4 == r29 ) goto label$80733c3_4_218;
	r10 = true;
	r0->viewportScaled = r10;
	r8 = r0->currentW;
	r28 = (double)r8;
	r28 = r28 * r4;
	r8 = (int)r28;
	r18 = r0->currentH;
	r29 = (double)r18;
	r29 = r29 * r4;
	r18 = (int)r29;
	r15 = r0->currentG;
	if( r15 == NULL ) hl_null_access();
	r19 = 0;
	if( hl_vfields(r15)[0] ) ((void (*)(vdynamic*,int,int,int,int))hl_vfields(r15)[0])(r15->value,r19,r18,r8,r18); else {
		void *args[] = {&r19,&r18,&r8,&r18};
		hl_dyn_call_obj(r15->value,&$t_fun_5ac3579,-56276265/*viewport*/,args,NULL);
	}
	r15 = r0->currentG;
	if( r15 == NULL ) hl_null_access();
	r19 = 0;
	if( hl_vfields(r15)[23] ) ((void (*)(vdynamic*,int,int,int,int))hl_vfields(r15)[23])(r15->value,r19,r18,r8,r18); else {
		void *args[] = {&r19,&r18,&r8,&r18};
		hl_dyn_call_obj(r15->value,&$t_fun_5ac3579,82257948/*scissor*/,args,NULL);
	}
	goto label$80733c3_4_228;
	label$80733c3_4_218:
	r10 = r0->viewportScaled;
	if( !r10 ) goto label$80733c3_4_228;
	r10 = false;
	r0->viewportScaled = r10;
	r8 = r0->currentW;
	r18 = r0->currentH;
	iron_RenderPath_setCurrentViewport(r0,r8,r18);
	r8 = r0->currentW;
	r18 = r0->currentH;
	iron_RenderPath_setCurrentScissor(r0,r8,r18);
	label$80733c3_4_228:
	r17 = NULL;
	r0->bindParams = r17;
	return;
}

void iron_RenderPath_setCurrentViewport(iron__RenderPath r0,int r1,int r2) {
	vvirtual *r4;
	int r5, r6;
	r4 = r0->currentG;
	if( r4 == NULL ) hl_null_access();
	r5 = 0;
	r6 = r0->currentH;
	r6 = r6 - r2;
	if( hl_vfields(r4)[0] ) ((void (*)(vdynamic*,int,int,int,int))hl_vfields(r4)[0])(r4->value,r5,r6,r1,r2); else {
		void *args[] = {&r5,&r6,&r1,&r2};
		hl_dyn_call_obj(r4->value,&$t_fun_5ac3579,-56276265/*viewport*/,args,NULL);
	}
	return;
}

void iron_RenderPath_setCurrentScissor(iron__RenderPath r0,int r1,int r2) {
	vvirtual *r4;
	bool r7;
	int r5, r6;
	r4 = r0->currentG;
	if( r4 == NULL ) hl_null_access();
	r5 = 0;
	r6 = r0->currentH;
	r6 = r6 - r2;
	if( hl_vfields(r4)[23] ) ((void (*)(vdynamic*,int,int,int,int))hl_vfields(r4)[23])(r4->value,r5,r6,r1,r2); else {
		void *args[] = {&r5,&r6,&r1,&r2};
		hl_dyn_call_obj(r4->value,&$t_fun_5ac3579,82257948/*scissor*/,args,NULL);
	}
	r7 = true;
	r0->scissorSet = r7;
	return;
}

void iron_RenderPath_setFrameScissor(iron__RenderPath r0) {
	vvirtual *r2;
	int r3, r4, r5, r6;
	r2 = r0->frameG;
	if( r2 == NULL ) hl_null_access();
	r3 = r0->frameScissorX;
	r4 = r0->currentH;
	r5 = r0->frameScissorH;
	r6 = r0->frameScissorY;
	r5 = r5 - r6;
	r4 = r4 - r5;
	r5 = r0->frameScissorW;
	r6 = r0->frameScissorH;
	if( hl_vfields(r2)[23] ) ((void (*)(vdynamic*,int,int,int,int))hl_vfields(r2)[23])(r2->value,r3,r4,r5,r6); else {
		void *args[] = {&r3,&r4,&r5,&r6};
		hl_dyn_call_obj(r2->value,&$t_fun_5ac3579,82257948/*scissor*/,args,NULL);
	}
	return;
}

void iron_RenderPath_clearTarget(iron__RenderPath r0,vdynamic* r1,vdynamic* r2) {
	vvirtual *r20;
	iron__$Scene r9;
	iron__Scene r8;
	iron__data__TCameraData r13;
	iron__data__CameraData r14;
	iron__data__TWorldData r10;
	float r15, r17, r18;
	kha__arrays__Float32ArrayPrivate r12;
	iron__data__WorldData r7;
	iron__object__CameraObject r11;
	vdynamic *r4, *r6;
	float *r19;
	vbyte *r16;
	int r5;
	r5 = -1;
	r6 = hl_alloc_dynamic(&$t_i32);
	r6->v.i = r5;
	if( r1 != r6 && (!r1 || !r6 || (r1->v.i != r6->v.i)) ) goto label$80733c3_8_49;
	r9 = (iron__$Scene)$g__iron_Scene;
	r8 = r9->active;
	if( r8 == NULL ) hl_null_access();
	r7 = r8->world;
	if( !r7 ) goto label$80733c3_8_19;
	r9 = (iron__$Scene)$g__iron_Scene;
	r8 = r9->active;
	if( r8 == NULL ) hl_null_access();
	r7 = r8->world;
	if( r7 == NULL ) hl_null_access();
	r10 = r7->raw;
	if( r10 == NULL ) hl_null_access();
	r5 = r10->background_color;
	r4 = hl_alloc_dynamic(&$t_i32);
	r4->v.i = r5;
	r1 = r4;
	goto label$80733c3_8_49;
	label$80733c3_8_19:
	r9 = (iron__$Scene)$g__iron_Scene;
	r8 = r9->active;
	if( r8 == NULL ) hl_null_access();
	r11 = r8->camera;
	if( !r11 ) goto label$80733c3_8_49;
	r9 = (iron__$Scene)$g__iron_Scene;
	r8 = r9->active;
	if( r8 == NULL ) hl_null_access();
	r11 = r8->camera;
	if( r11 == NULL ) hl_null_access();
	r14 = r11->data;
	if( r14 == NULL ) hl_null_access();
	r13 = r14->raw;
	if( r13 == NULL ) hl_null_access();
	r12 = r13->clear_color;
	if( !r12 ) goto label$80733c3_8_49;
	if( r12 == NULL ) hl_null_access();
	r16 = r12->self;
	r5 = 0;
	r15 = hl_kore_float32array_get(r16,r5);
	r16 = r12->self;
	r5 = 1;
	r17 = hl_kore_float32array_get(r16,r5);
	r16 = r12->self;
	r5 = 2;
	r18 = hl_kore_float32array_get(r16,r5);
	r19 = NULL;
	r5 = kha__Color_Color_Impl__fromFloats(r15,r17,r18,r19);
	r4 = hl_alloc_dynamic(&$t_i32);
	r4->v.i = r5;
	r1 = r4;
	label$80733c3_8_49:
	r20 = r0->currentG;
	if( r20 == NULL ) hl_null_access();
	r6 = NULL;
	if( hl_vfields(r20)[29] ) ((void (*)(vdynamic*,vdynamic*,vdynamic*,vdynamic*))hl_vfields(r20)[29])(r20->value,r1,r2,r6); else {
		void *args[] = {r1,r2,r6};
		hl_dyn_call_obj(r20->value,&$t_fun_5967954,140210839/*clear*/,args,NULL);
	}
	return;
}

int iron_RenderPath_sortMeshesDistance__$1(iron__object__MeshObject r0,iron__object__MeshObject r1) {
	double r2, r3;
	int r4;
	if( r0 == NULL ) hl_null_access();
	r2 = r0->cameraDistance;
	if( r1 == NULL ) hl_null_access();
	r3 = r1->cameraDistance;
	if( !(r2 >= r3) ) goto label$80733c3_9_7;
	r4 = 1;
	return r4;
	label$80733c3_9_7:
	r4 = -1;
	return r4;
}

void iron_RenderPath_sortMeshesDistance(hl__types__ArrayObj r0) {
	vclosure *r2, *r3;
	static vclosure cl$0 = { &$t_fun_01f8d35, iron_RenderPath_sortMeshesDistance__$1, 0 };
	if( r0 == NULL ) hl_null_access();
	r2 = &cl$0;
	if( r2 ) goto label$80733c3_10_5;
	r3 = NULL;
	goto label$80733c3_10_6;
	label$80733c3_10_5:
	r3 = hl_alloc_closure_ptr(&$t_fun_2237bde,wrap$t_fun_2237bde,r2);
	label$80733c3_10_6:
	hl_types_ArrayObj_sort(r0,r3);
	return;
}

int iron_RenderPath_sortMeshesShader__$1(iron__object__MeshObject r0,iron__object__MeshObject r1) {
	String r2, r9;
	hl__types__ArrayObj r3;
	iron__data__MaterialData r6;
	vdynamic *r7;
	varray *r8;
	int r4, r5;
	if( r0 == NULL ) hl_null_access();
	r3 = r0->materials;
	if( r3 == NULL ) hl_null_access();
	r4 = 0;
	r5 = r3->length;
	if( ((unsigned)r4) < ((unsigned)r5) ) goto label$80733c3_11_8;
	r6 = NULL;
	goto label$80733c3_11_11;
	label$80733c3_11_8:
	r8 = r3->array;
	r7 = ((vdynamic**)(r8 + 1))[r4];
	r6 = (iron__data__MaterialData)r7;
	label$80733c3_11_11:
	if( r6 == NULL ) hl_null_access();
	r2 = r6->name;
	if( r1 == NULL ) hl_null_access();
	r3 = r1->materials;
	if( r3 == NULL ) hl_null_access();
	r4 = 0;
	r5 = r3->length;
	if( ((unsigned)r4) < ((unsigned)r5) ) goto label$80733c3_11_21;
	r6 = NULL;
	goto label$80733c3_11_24;
	label$80733c3_11_21:
	r8 = r3->array;
	r7 = ((vdynamic**)(r8 + 1))[r4];
	r6 = (iron__data__MaterialData)r7;
	label$80733c3_11_24:
	if( r6 == NULL ) hl_null_access();
	r9 = r6->name;
	if( r2 && r9 && String___compare(r2,(vdynamic*)r9) < 0 ) goto label$80733c3_11_29;
	r4 = 1;
	return r4;
	label$80733c3_11_29:
	r4 = -1;
	return r4;
}

void iron_RenderPath_sortMeshesShader(hl__types__ArrayObj r0) {
	vclosure *r2, *r3;
	static vclosure cl$0 = { &$t_fun_01f8d35, iron_RenderPath_sortMeshesShader__$1, 0 };
	if( r0 == NULL ) hl_null_access();
	r2 = &cl$0;
	if( r2 ) goto label$80733c3_12_5;
	r3 = NULL;
	goto label$80733c3_12_6;
	label$80733c3_12_5:
	r3 = hl_alloc_closure_ptr(&$t_fun_2237bde,wrap$t_fun_2237bde,r2);
	label$80733c3_12_6:
	hl_types_ArrayObj_sort(r0,r3);
	return;
}

void iron_RenderPath_drawMeshes(iron__RenderPath r0,String r1) {
	String r3, r4;
	hl__types__ArrayObj r25;
	vvirtual *r23;
	iron__data__TLightData r9;
	iron__$Scene r17;
	iron__Scene r16;
	bool r2, r6, r18;
	iron__data__LightData r10;
	iron__object__LightObject r7;
	float r11, r13;
	iron__object__CameraObject r15;
	vdynamic *r8;
	iron__object__$LightObject r20;
	int r12, r14, r19, r21, r22, r24;
	r4 = (String)$s_shadowmap;
	if( r1 == r4 || (r1 && r4 && String___compare(r1,(vdynamic*)r4) == 0) ) goto label$80733c3_13_4;
	r2 = false;
	goto label$80733c3_13_5;
	label$80733c3_13_4:
	r2 = true;
	label$80733c3_13_5:
	if( !r2 ) goto label$80733c3_13_32;
	r7 = r0->light;
	if( !r7 ) goto label$80733c3_13_31;
	r7 = r0->light;
	if( r7 == NULL ) hl_null_access();
	r10 = r7->data;
	if( r10 == NULL ) hl_null_access();
	r9 = r10->raw;
	if( r9 == NULL ) hl_null_access();
	r8 = r9->cast_shadow;
	r6 = r8 ? r8->v.b : 0;
	if( !r6 ) goto label$80733c3_13_31;
	r7 = r0->light;
	if( r7 == NULL ) hl_null_access();
	r6 = r7->visible;
	if( !r6 ) goto label$80733c3_13_31;
	r7 = r0->light;
	if( r7 == NULL ) hl_null_access();
	r10 = r7->data;
	if( r10 == NULL ) hl_null_access();
	r9 = r10->raw;
	if( r9 == NULL ) hl_null_access();
	r11 = r9->strength;
	r12 = 0;
	r13 = (float)r12;
	if( r11 != r13 ) goto label$80733c3_13_32;
	label$80733c3_13_31:
	return;
	label$80733c3_13_32:
	r12 = r0->currentFace;
	r14 = 0;
	if( r12 < r14 ) goto label$80733c3_13_45;
	r7 = r0->light;
	if( !r7 ) goto label$80733c3_13_45;
	r7 = r0->light;
	if( r7 == NULL ) hl_null_access();
	r12 = r0->currentFace;
	r17 = (iron__$Scene)$g__iron_Scene;
	r16 = r17->active;
	if( r16 == NULL ) hl_null_access();
	r15 = r16->camera;
	iron_object_LightObject_setCubeFace(r7,r12,r15);
	label$80733c3_13_45:
	r6 = false;
	if( !r2 ) goto label$80733c3_13_80;
	r7 = r0->light;
	if( r7 == NULL ) hl_null_access();
	r10 = r7->data;
	if( r10 == NULL ) hl_null_access();
	r9 = r10->raw;
	if( r9 == NULL ) hl_null_access();
	r3 = r9->type;
	r4 = (String)$s_sun;
	if( r3 != r4 && (!r3 || !r4 || String___compare(r3,(vdynamic*)r4) != 0) ) goto label$80733c3_13_80;
	r12 = r0->currentH;
	r14 = 0;
	r20 = (iron__object__$LightObject)$g__iron_object_LightObject;
	r19 = r20->cascadeCount;
	label$80733c3_13_60:
	if( r14 >= r19 ) goto label$80733c3_13_78;
	r21 = r14;
	++r14;
	r7 = r0->light;
	if( r7 == NULL ) hl_null_access();
	r17 = (iron__$Scene)$g__iron_Scene;
	r16 = r17->active;
	if( r16 == NULL ) hl_null_access();
	r15 = r16->camera;
	iron_object_LightObject_setCascade(r7,r15,r21);
	r23 = r0->currentG;
	if( r23 == NULL ) hl_null_access();
	r22 = r21 * r12;
	r24 = 0;
	if( hl_vfields(r23)[0] ) ((void (*)(vdynamic*,int,int,int,int))hl_vfields(r23)[0])(r23->value,r22,r24,r12,r12); else {
		void *args[] = {&r22,&r24,&r12,&r12};
		hl_dyn_call_obj(r23->value,&$t_fun_5ac3579,-56276265/*viewport*/,args,NULL);
	}
	iron_RenderPath_submitDraw(r0,r1);
	goto label$80733c3_13_60;
	label$80733c3_13_78:
	r18 = true;
	r6 = r18;
	label$80733c3_13_80:
	if( r6 ) goto label$80733c3_13_82;
	iron_RenderPath_submitDraw(r0,r1);
	label$80733c3_13_82:
	r18 = r0->scissorSet;
	if( !r18 ) goto label$80733c3_13_89;
	r23 = r0->currentG;
	if( r23 == NULL ) hl_null_access();
	if( hl_vfields(r23)[28] ) ((void (*)(vdynamic*))hl_vfields(r23)[28])(r23->value); else {
		hl_dyn_call_obj(r23->value,&$t_fun_4c7a70a,40268564/*disableScissor*/,NULL,NULL);
	}
	r18 = false;
	r0->scissorSet = r18;
	label$80733c3_13_89:
	r23 = r0->currentG;
	if( r23 == NULL ) hl_null_access();
	if( hl_vfields(r23)[25] ) ((void (*)(vdynamic*))hl_vfields(r23)[25])(r23->value); else {
		hl_dyn_call_obj(r23->value,&$t_fun_4c7a70a,5047259/*end*/,NULL,NULL);
	}
	r23 = NULL;
	r0->currentG = r23;
	r25 = NULL;
	r0->bindParams = r25;
	return;
}

void iron_RenderPath_submitDraw(iron__RenderPath r0,String r1) {
	iron__object__$MeshObject r8;
	iron__object__MeshObject r20;
	kha__graphics4__PipelineState r7;
	vvirtual *r29;
	hl__types__ArrayObj r6, r19;
	kha__math__FastMatrix4 r11;
	bool r9;
	iron__$Scene r4;
	iron__Scene r3;
	iron__object__Transform r13;
	iron__math__Mat4 r12;
	float r10, r14, r15, r23, r24, r25, r26, r28;
	double r27;
	iron__object__CameraObject r2;
	vdynamic *r21;
	varray *r22;
	int r16, r17, r18;
	r4 = (iron__$Scene)$g__iron_Scene;
	r3 = r4->active;
	if( r3 == NULL ) hl_null_access();
	r2 = r3->camera;
	r4 = (iron__$Scene)$g__iron_Scene;
	r3 = r4->active;
	if( r3 == NULL ) hl_null_access();
	r6 = r3->meshes;
	r7 = NULL;
	r8 = (iron__object__$MeshObject)$g__iron_object_MeshObject;
	r8->lastPipeline = r7;
	r9 = r0->meshesSorted;
	if( r9 ) goto label$80733c3_14_93;
	if( !r2 ) goto label$80733c3_14_93;
	if( r2 == NULL ) hl_null_access();
	r13 = r2->transform;
	if( r13 == NULL ) hl_null_access();
	r12 = r13->world;
	if( r12 == NULL ) hl_null_access();
	r11 = r12->self;
	if( r11 == NULL ) hl_null_access();
	r10 = r11->_30;
	r13 = r2->transform;
	if( r13 == NULL ) hl_null_access();
	r12 = r13->world;
	if( r12 == NULL ) hl_null_access();
	r11 = r12->self;
	if( r11 == NULL ) hl_null_access();
	r14 = r11->_31;
	r13 = r2->transform;
	if( r13 == NULL ) hl_null_access();
	r12 = r13->world;
	if( r12 == NULL ) hl_null_access();
	r11 = r12->self;
	if( r11 == NULL ) hl_null_access();
	r15 = r11->_32;
	r16 = 0;
	label$80733c3_14_37:
	if( r6 == NULL ) hl_null_access();
	r18 = r6->length;
	if( r16 >= r18 ) goto label$80733c3_14_85;
	r18 = r6->length;
	if( ((unsigned)r16) < ((unsigned)r18) ) goto label$80733c3_14_45;
	r20 = NULL;
	goto label$80733c3_14_48;
	label$80733c3_14_45:
	r22 = r6->array;
	r21 = ((vdynamic**)(r22 + 1))[r16];
	r20 = (iron__object__MeshObject)r21;
	label$80733c3_14_48:
	++r16;
	if( r20 == NULL ) hl_null_access();
	r13 = r20->transform;
	if( r13 == NULL ) hl_null_access();
	r12 = r13->world;
	if( r12 == NULL ) hl_null_access();
	r11 = r12->self;
	if( r11 == NULL ) hl_null_access();
	r24 = r11->_30;
	r23 = r10 - r24;
	r13 = r20->transform;
	if( r13 == NULL ) hl_null_access();
	r12 = r13->world;
	if( r12 == NULL ) hl_null_access();
	r11 = r12->self;
	if( r11 == NULL ) hl_null_access();
	r25 = r11->_31;
	r24 = r14 - r25;
	r13 = r20->transform;
	if( r13 == NULL ) hl_null_access();
	r12 = r13->world;
	if( r12 == NULL ) hl_null_access();
	r11 = r12->self;
	if( r11 == NULL ) hl_null_access();
	r26 = r11->_32;
	r25 = r15 - r26;
	r26 = r23 * r23;
	r28 = r24 * r24;
	r26 = r26 + r28;
	r28 = r25 * r25;
	r26 = r26 + r28;
	r27 = (double)r26;
	r27 = hl_math_sqrt(r27);
	r26 = (float)r27;
	r27 = (double)r26;
	r20->cameraDistance = r27;
	goto label$80733c3_14_37;
	label$80733c3_14_85:
	r16 = r0->drawOrder;
	r17 = 1;
	if( r16 != r17 ) goto label$80733c3_14_90;
	iron_RenderPath_sortMeshesShader(r6);
	goto label$80733c3_14_91;
	label$80733c3_14_90:
	iron_RenderPath_sortMeshesDistance(r6);
	label$80733c3_14_91:
	r9 = true;
	r0->meshesSorted = r9;
	label$80733c3_14_93:
	r16 = 0;
	label$80733c3_14_94:
	if( r6 == NULL ) hl_null_access();
	r18 = r6->length;
	if( r16 >= r18 ) goto label$80733c3_14_111;
	r18 = r6->length;
	if( ((unsigned)r16) < ((unsigned)r18) ) goto label$80733c3_14_102;
	r20 = NULL;
	goto label$80733c3_14_105;
	label$80733c3_14_102:
	r22 = r6->array;
	r21 = ((vdynamic**)(r22 + 1))[r16];
	r20 = (iron__object__MeshObject)r21;
	label$80733c3_14_105:
	++r16;
	if( r20 == NULL ) hl_null_access();
	r29 = r0->currentG;
	r19 = r0->bindParams;
	iron_object_MeshObject_render(r20,r29,r1,r19);
	goto label$80733c3_14_94;
	label$80733c3_14_111:
	return;
}

void iron_RenderPath_drawSkydome(iron__RenderPath r0,String r1) {
	kha__graphics4__PipelineState r10;
	iron__data__$ConstData r4;
	hl__types__ArrayObj r11;
	vvirtual *r9;
	iron__data__ShaderContext r8;
	haxe__ds__StringMap r6;
	bool r16;
	kha__graphics4__VertexBuffer r3;
	kha__graphics4__IndexBuffer r13;
	iron__CachedShaderContext r7;
	int *r14, *r15;
	iron__object__Object r12;
	vdynamic *r5;
	r4 = (iron__data__$ConstData)$g__iron_data_ConstData;
	r3 = r4->skydomeVB;
	if( r3 ) goto label$80733c3_15_4;
	iron_data_ConstData_createSkydomeData();
	label$80733c3_15_4:
	r6 = r0->cachedShaderContexts;
	if( r6 == NULL ) hl_null_access();
	r5 = haxe_ds_StringMap_get(r6,r1);
	r7 = (iron__CachedShaderContext)r5;
	if( r7 == NULL ) hl_null_access();
	r8 = r7->context;
	if( r8 ) goto label$80733c3_15_12;
	return;
	label$80733c3_15_12:
	r9 = r0->currentG;
	if( r9 == NULL ) hl_null_access();
	r8 = r7->context;
	if( r8 == NULL ) hl_null_access();
	r10 = r8->pipeState;
	if( hl_vfields(r9)[8] ) ((void (*)(vdynamic*,kha__graphics4__PipelineState))hl_vfields(r9)[8])(r9->value,r10); else {
		void *args[] = {r10};
		hl_dyn_call_obj(r9->value,&$t_fun_c80ec77,467961459/*setPipeline*/,args,NULL);
	}
	r9 = r0->currentG;
	r8 = r7->context;
	r11 = r0->bindParams;
	iron_object_Uniforms_setContextConstants(r9,r8,r11);
	r9 = r0->currentG;
	r8 = r7->context;
	r12 = NULL;
	iron_object_Uniforms_setObjectConstants(r9,r8,r12);
	r9 = r0->currentG;
	if( r9 == NULL ) hl_null_access();
	r4 = (iron__data__$ConstData)$g__iron_data_ConstData;
	r3 = r4->skydomeVB;
	if( hl_vfields(r9)[2] ) ((void (*)(vdynamic*,kha__graphics4__VertexBuffer))hl_vfields(r9)[2])(r9->value,r3); else {
		void *args[] = {r3};
		hl_dyn_call_obj(r9->value,&$t_fun_a561c62,-278953801/*setVertexBuffer*/,args,NULL);
	}
	r9 = r0->currentG;
	if( r9 == NULL ) hl_null_access();
	r4 = (iron__data__$ConstData)$g__iron_data_ConstData;
	r13 = r4->skydomeIB;
	if( hl_vfields(r9)[12] ) ((void (*)(vdynamic*,kha__graphics4__IndexBuffer))hl_vfields(r9)[12])(r9->value,r13); else {
		void *args[] = {r13};
		hl_dyn_call_obj(r9->value,&$t_fun_46c6b6e,-43737183/*setIndexBuffer*/,args,NULL);
	}
	r9 = r0->currentG;
	if( r9 == NULL ) hl_null_access();
	r14 = NULL;
	r15 = NULL;
	if( hl_vfields(r9)[27] ) ((void (*)(vdynamic*,int*,int*))hl_vfields(r9)[27])(r9->value,r14,r15); else {
		void *args[] = {r14,r15};
		hl_dyn_call_obj(r9->value,&$t_fun_8305be0,-519327652/*drawIndexedVertices*/,args,NULL);
	}
	r16 = r0->scissorSet;
	if( !r16 ) goto label$80733c3_15_48;
	r9 = r0->currentG;
	if( r9 == NULL ) hl_null_access();
	if( hl_vfields(r9)[28] ) ((void (*)(vdynamic*))hl_vfields(r9)[28])(r9->value); else {
		hl_dyn_call_obj(r9->value,&$t_fun_4c7a70a,40268564/*disableScissor*/,NULL,NULL);
	}
	r16 = false;
	r0->scissorSet = r16;
	label$80733c3_15_48:
	r9 = r0->currentG;
	if( r9 == NULL ) hl_null_access();
	if( hl_vfields(r9)[25] ) ((void (*)(vdynamic*))hl_vfields(r9)[25])(r9->value); else {
		hl_dyn_call_obj(r9->value,&$t_fun_4c7a70a,5047259/*end*/,NULL,NULL);
	}
	r9 = NULL;
	r0->currentG = r9;
	r11 = NULL;
	r0->bindParams = r11;
	return;
}

void iron_RenderPath_bindTarget(iron__RenderPath r0,String r1,String r2) {
	hl__types__ArrayObj r4;
	hl_type *r7;
	varray *r6;
	int r5;
	r4 = r0->bindParams;
	if( !r4 ) goto label$80733c3_16_9;
	r4 = r0->bindParams;
	if( r4 == NULL ) hl_null_access();
	r5 = hl_types_ArrayObj_push(r4,((vdynamic*)r1));
	r4 = r0->bindParams;
	if( r4 == NULL ) hl_null_access();
	r5 = hl_types_ArrayObj_push(r4,((vdynamic*)r2));
	goto label$80733c3_16_18;
	label$80733c3_16_9:
	r7 = &$t_String;
	r5 = 2;
	r6 = hl_alloc_array(r7,r5);
	r5 = 0;
	((String*)(r6 + 1))[r5] = r1;
	r5 = 1;
	((String*)(r6 + 1))[r5] = r2;
	r4 = hl_types_ArrayObj_alloc(r6);
	r0->bindParams = r4;
	label$80733c3_16_18:
	return;
}

void iron_RenderPath_drawShader(iron__RenderPath r0,String r1) {
	kha__graphics4__PipelineState r9;
	iron__data__$ConstData r7;
	hl__types__ArrayObj r11;
	iron__data__ShaderContext r10;
	vvirtual *r8;
	haxe__ds__StringMap r3;
	bool r16;
	kha__graphics4__VertexBuffer r6;
	kha__graphics4__IndexBuffer r13;
	iron__CachedShaderContext r4;
	int *r14, *r15;
	iron__object__Object r12;
	vdynamic *r2;
	r3 = r0->cachedShaderContexts;
	if( r3 == NULL ) hl_null_access();
	r2 = haxe_ds_StringMap_get(r3,r1);
	r4 = (iron__CachedShaderContext)r2;
	r7 = (iron__data__$ConstData)$g__iron_data_ConstData;
	r6 = r7->screenAlignedVB;
	if( r6 ) goto label$80733c3_17_8;
	iron_data_ConstData_createScreenAlignedData();
	label$80733c3_17_8:
	r8 = r0->currentG;
	if( r8 == NULL ) hl_null_access();
	if( r4 == NULL ) hl_null_access();
	r10 = r4->context;
	if( r10 == NULL ) hl_null_access();
	r9 = r10->pipeState;
	if( hl_vfields(r8)[8] ) ((void (*)(vdynamic*,kha__graphics4__PipelineState))hl_vfields(r8)[8])(r8->value,r9); else {
		void *args[] = {r9};
		hl_dyn_call_obj(r8->value,&$t_fun_c80ec77,467961459/*setPipeline*/,args,NULL);
	}
	r8 = r0->currentG;
	r10 = r4->context;
	r11 = r0->bindParams;
	iron_object_Uniforms_setContextConstants(r8,r10,r11);
	r8 = r0->currentG;
	r10 = r4->context;
	r12 = NULL;
	iron_object_Uniforms_setObjectConstants(r8,r10,r12);
	r8 = r0->currentG;
	if( r8 == NULL ) hl_null_access();
	r7 = (iron__data__$ConstData)$g__iron_data_ConstData;
	r6 = r7->screenAlignedVB;
	if( hl_vfields(r8)[2] ) ((void (*)(vdynamic*,kha__graphics4__VertexBuffer))hl_vfields(r8)[2])(r8->value,r6); else {
		void *args[] = {r6};
		hl_dyn_call_obj(r8->value,&$t_fun_a561c62,-278953801/*setVertexBuffer*/,args,NULL);
	}
	r8 = r0->currentG;
	if( r8 == NULL ) hl_null_access();
	r7 = (iron__data__$ConstData)$g__iron_data_ConstData;
	r13 = r7->screenAlignedIB;
	if( hl_vfields(r8)[12] ) ((void (*)(vdynamic*,kha__graphics4__IndexBuffer))hl_vfields(r8)[12])(r8->value,r13); else {
		void *args[] = {r13};
		hl_dyn_call_obj(r8->value,&$t_fun_46c6b6e,-43737183/*setIndexBuffer*/,args,NULL);
	}
	r8 = r0->currentG;
	if( r8 == NULL ) hl_null_access();
	r14 = NULL;
	r15 = NULL;
	if( hl_vfields(r8)[27] ) ((void (*)(vdynamic*,int*,int*))hl_vfields(r8)[27])(r8->value,r14,r15); else {
		void *args[] = {r14,r15};
		hl_dyn_call_obj(r8->value,&$t_fun_8305be0,-519327652/*drawIndexedVertices*/,args,NULL);
	}
	r16 = r0->scissorSet;
	if( !r16 ) goto label$80733c3_17_45;
	r8 = r0->currentG;
	if( r8 == NULL ) hl_null_access();
	if( hl_vfields(r8)[28] ) ((void (*)(vdynamic*))hl_vfields(r8)[28])(r8->value); else {
		hl_dyn_call_obj(r8->value,&$t_fun_4c7a70a,40268564/*disableScissor*/,NULL,NULL);
	}
	r16 = false;
	r0->scissorSet = r16;
	label$80733c3_17_45:
	r8 = r0->currentG;
	if( r8 == NULL ) hl_null_access();
	if( hl_vfields(r8)[25] ) ((void (*)(vdynamic*))hl_vfields(r8)[25])(r8->value); else {
		hl_dyn_call_obj(r8->value,&$t_fun_4c7a70a,5047259/*end*/,NULL,NULL);
	}
	r8 = NULL;
	r0->currentG = r8;
	r11 = NULL;
	r0->bindParams = r11;
	return;
}

void iron_RenderPath_loadShader__$1(venum* r0,iron__data__ShaderData r1) {
	String r7;
	hl__types__ArrayObj r4;
	iron__data__ShaderContext r3;
	iron__CachedShaderContext r2;
	vdynamic *r8;
	iron__RenderPath r10;
	varray *r9;
	int r5, r6;
	r2 = ((Enum$t_ctx_a363d40*)r0)->p0;
	if( r2 == NULL ) hl_null_access();
	if( r1 == NULL ) hl_null_access();
	r4 = ((Enum$t_ctx_a363d40*)r0)->p1;
	if( r4 == NULL ) hl_null_access();
	r5 = 2;
	r6 = r4->length;
	if( ((unsigned)r5) < ((unsigned)r6) ) goto label$80733c3_18_10;
	r7 = NULL;
	goto label$80733c3_18_13;
	label$80733c3_18_10:
	r9 = r4->array;
	r8 = ((vdynamic**)(r9 + 1))[r5];
	r7 = (String)r8;
	label$80733c3_18_13:
	r3 = iron_data_ShaderData_getContext(r1,r7);
	r2->context = r3;
	r10 = ((Enum$t_ctx_a363d40*)r0)->p2;
	if( r10 == NULL ) hl_null_access();
	r5 = r10->loading;
	--r5;
	r10->loading = r5;
	return;
}

void iron_RenderPath_loadShader(iron__RenderPath r0,String r1) {
	String r7, r11;
	hl__types__ArrayObj r10;
	haxe__ds__StringMap r6;
	venum *r14;
	vclosure *r13;
	iron__CachedShaderContext r8, r9;
	vdynamic *r5;
	iron__data__TShaderOverride r15;
	varray *r12;
	int r3, r4;
	r3 = r0->loading;
	++r3;
	r0->loading = r3;
	r6 = r0->cachedShaderContexts;
	if( r6 == NULL ) hl_null_access();
	r5 = haxe_ds_StringMap_get(r6,r1);
	r8 = (iron__CachedShaderContext)r5;
	if( !r8 ) goto label$80733c3_19_12;
	r3 = r0->loading;
	--r3;
	r0->loading = r3;
	return;
	label$80733c3_19_12:
	r9 = (iron__CachedShaderContext)hl_alloc_obj(&$t_iron_CachedShaderContext);
	iron_CachedShaderContext_new(r9);
	r6 = r0->cachedShaderContexts;
	if( r6 == NULL ) hl_null_access();
	haxe_ds_StringMap_set(r6,r1,((vdynamic*)r9));
	if( r1 == NULL ) hl_null_access();
	r11 = (String)$s_6666cd7;
	r10 = String_split(r1,r11);
	if( r10 == NULL ) hl_null_access();
	r3 = 0;
	r4 = r10->length;
	if( ((unsigned)r3) < ((unsigned)r4) ) goto label$80733c3_19_26;
	r7 = NULL;
	goto label$80733c3_19_29;
	label$80733c3_19_26:
	r12 = r10->array;
	r5 = ((vdynamic**)(r12 + 1))[r3];
	r7 = (String)r5;
	label$80733c3_19_29:
	r3 = 1;
	r4 = r10->length;
	if( ((unsigned)r3) < ((unsigned)r4) ) goto label$80733c3_19_34;
	r11 = NULL;
	goto label$80733c3_19_37;
	label$80733c3_19_34:
	r12 = r10->array;
	r5 = ((vdynamic**)(r12 + 1))[r3];
	r11 = (String)r5;
	label$80733c3_19_37:
	r14 = hl_alloc_enum(&$t_ctx_a363d40,0);
	((Enum$t_ctx_a363d40*)r14)->p0 = (iron__CachedShaderContext)r9;
	((Enum$t_ctx_a363d40*)r14)->p1 = (hl__types__ArrayObj)r10;
	((Enum$t_ctx_a363d40*)r14)->p2 = (iron__RenderPath)r0;
	r13 = hl_alloc_closure_ptr(&$t_fun_0f246dc,iron_RenderPath_loadShader__$1,r14);
	r15 = NULL;
	iron_data_Data_getShader(r7,r11,r13,r15);
	return;
}

iron__RenderTarget iron_RenderPath_createRenderTarget(iron__RenderPath r0,iron__RenderTargetRaw r1) {
	String r5;
	haxe__ds__StringMap r4;
	iron__RenderTarget r2;
	r2 = iron_RenderPath_createTarget(r0,r1);
	r4 = r0->renderTargets;
	if( r4 == NULL ) hl_null_access();
	if( r1 == NULL ) hl_null_access();
	r5 = r1->name;
	haxe_ds_StringMap_set(r4,r5,((vdynamic*)r2));
	return r2;
}

void iron_RenderPath_createDepthBuffer(iron__RenderPath r0,String r1,String r2) {
	vvirtual *r5;
	hl__types__ArrayObj r4;
	int r3;
	r4 = r0->depthBuffers;
	if( r4 == NULL ) hl_null_access();
	r5 = hl_alloc_virtual(&$t_vrt_ee58142);
	if( hl_vfields(r5)[1] ) *(String*)(hl_vfields(r5)[1]) = (String)r1; else hl_dyn_setp(r5->value,150958933/*name*/,&$t_String,r1);
	if( hl_vfields(r5)[0] ) *(String*)(hl_vfields(r5)[0]) = (String)r2; else hl_dyn_setp(r5->value,-40988873/*format*/,&$t_String,r2);
	r3 = hl_types_ArrayObj_push(r4,((vdynamic*)r5));
	return;
}

iron__RenderTarget iron_RenderPath_createTarget(iron__RenderPath r0,iron__RenderTargetRaw r1) {
	kha__graphics4__CubeMap r24;
	String r4, r15, r16;
	kha__Image r20, r21;
	vvirtual *r13;
	hl__types__ArrayObj r10;
	haxe__ds__StringMap r8;
	bool r6;
	iron__RenderTarget r2, r5;
	vdynamic *r7, *r22, *r23;
	vbyte *r18, *r19;
	varray *r14;
	int r9, r11, r12, r17;
	r2 = (iron__RenderTarget)hl_alloc_obj(&$t_iron_RenderTarget);
	iron_RenderTarget_new(r2,r1);
	if( r1 == NULL ) hl_null_access();
	r4 = r1->depth_buffer;
	if( !r4 ) goto label$80733c3_22_86;
	r6 = true;
	r2->hasDepth = r6;
	r8 = r0->depthToRenderTarget;
	if( r8 == NULL ) hl_null_access();
	r4 = r1->depth_buffer;
	r7 = haxe_ds_StringMap_get(r8,r4);
	r5 = (iron__RenderTarget)r7;
	if( r5 ) goto label$80733c3_22_73;
	r9 = 0;
	r10 = r0->depthBuffers;
	label$80733c3_22_15:
	if( r10 == NULL ) hl_null_access();
	r12 = r10->length;
	if( r9 >= r12 ) goto label$80733c3_22_72;
	r12 = r10->length;
	if( ((unsigned)r9) < ((unsigned)r12) ) goto label$80733c3_22_23;
	r13 = NULL;
	goto label$80733c3_22_26;
	label$80733c3_22_23:
	r14 = r10->array;
	r7 = ((vdynamic**)(r14 + 1))[r9];
	r13 = hl_to_virtual(&$t_vrt_ee58142,(vdynamic*)r7);
	label$80733c3_22_26:
	++r9;
	if( r13 == NULL ) hl_null_access();
	r4 = hl_vfields(r13)[1] ? (*(String*)(hl_vfields(r13)[1])) : (String)hl_dyn_getp(r13->value,150958933/*name*/,&$t_String);
	if( r1 == NULL ) hl_null_access();
	r15 = r1->depth_buffer;
	if( r4 != r15 && (!r4 || !r15 || String___compare(r4,(vdynamic*)r15) != 0) ) goto label$80733c3_22_71;
	r8 = r0->depthToRenderTarget;
	if( r8 == NULL ) hl_null_access();
	r4 = hl_vfields(r13)[1] ? (*(String*)(hl_vfields(r13)[1])) : (String)hl_dyn_getp(r13->value,150958933/*name*/,&$t_String);
	haxe_ds_StringMap_set(r8,r4,((vdynamic*)r2));
	r4 = hl_vfields(r13)[0] ? (*(String*)(hl_vfields(r13)[0])) : (String)hl_dyn_getp(r13->value,-40988873/*format*/,&$t_String);
	if( !r4 ) goto label$80733c3_22_40;
	r16 = (String)$s_;
	if( r4 != r16 && (!r4 || !r16 || String___compare(r4,(vdynamic*)r16) != 0) ) goto label$80733c3_22_42;
	label$80733c3_22_40:
	r12 = 1;
	goto label$80733c3_22_65;
	label$80733c3_22_42:
	if( !r4 ) goto label$80733c3_22_51;
	r12 = r4->length;
	r17 = 7;
	if( r12 != r17 ) goto label$80733c3_22_51;
	r18 = r4->bytes;
	r19 = (vbyte*)USTR("DEPTH16");
	r12 = hl_string_compare(r18,r19,r12);
	r17 = 0;
	if( r12 == r17 ) goto label$80733c3_22_62;
	label$80733c3_22_51:
	if( !r4 ) goto label$80733c3_22_60;
	r12 = r4->length;
	r17 = 7;
	if( r12 != r17 ) goto label$80733c3_22_60;
	r18 = r4->bytes;
	r19 = (vbyte*)USTR("DEPTH24");
	r12 = hl_string_compare(r18,r19,r12);
	r17 = 0;
	if( r12 == r17 ) goto label$80733c3_22_64;
	label$80733c3_22_60:
	r12 = 1;
	goto label$80733c3_22_65;
	label$80733c3_22_62:
	r12 = 5;
	goto label$80733c3_22_65;
	label$80733c3_22_64:
	r12 = 1;
	label$80733c3_22_65:
	if( r2 == NULL ) hl_null_access();
	r2->depthStencil = r12;
	r12 = r2->depthStencil;
	r20 = iron_RenderPath_createImage(r0,r1,r12);
	r2->image = r20;
	goto label$80733c3_22_72;
	label$80733c3_22_71:
	goto label$80733c3_22_15;
	label$80733c3_22_72:
	goto label$80733c3_22_85;
	label$80733c3_22_73:
	r9 = 0;
	r2->depthStencil = r9;
	r4 = r1->depth_buffer;
	r2->depthStencilFrom = r4;
	r9 = r2->depthStencil;
	r20 = iron_RenderPath_createImage(r0,r1,r9);
	r2->image = r20;
	r20 = r2->image;
	if( r20 == NULL ) hl_null_access();
	if( r5 == NULL ) hl_null_access();
	r21 = r5->image;
	kha_Image_setDepthStencilFrom(r20,r21);
	label$80733c3_22_85:
	goto label$80733c3_22_112;
	label$80733c3_22_86:
	r6 = false;
	r2->hasDepth = r6;
	r22 = r1->depth;
	if( !r22 ) goto label$80733c3_22_96;
	r22 = r1->depth;
	r9 = r22 ? r22->v.i : 0;
	r11 = 1;
	if( r11 >= r9 ) goto label$80733c3_22_96;
	r6 = true;
	r2->is3D = r6;
	label$80733c3_22_96:
	r23 = r1->is_cubemap;
	r6 = r23 ? r23->v.b : 0;
	if( !r6 ) goto label$80733c3_22_107;
	r6 = true;
	r2->isCubeMap = r6;
	r9 = 0;
	r2->depthStencil = r9;
	r9 = r2->depthStencil;
	r24 = iron_RenderPath_createCubeMap(r0,r1,r9);
	r2->cubeMap = r24;
	goto label$80733c3_22_112;
	label$80733c3_22_107:
	r9 = 0;
	r2->depthStencil = r9;
	r9 = r2->depthStencil;
	r20 = iron_RenderPath_createImage(r0,r1,r9);
	r2->image = r20;
	label$80733c3_22_112:
	return r2;
}

kha__Image iron_RenderPath_createImage(iron__RenderPath r0,iron__RenderTargetRaw r1,int r2) {
	String r16;
	kha__Image r20;
	bool r24;
	double r11, r12, r13, r15;
	vdynamic *r8, *r9, *r14, *r19, *r22, *r23;
	int *r5, *r25, *r26;
	vbyte *r17, *r18;
	int r3, r4, r7, r10, r21;
	if( r1 == NULL ) hl_null_access();
	r3 = r1->width;
	r4 = 0;
	if( r3 != r4 ) goto label$80733c3_23_7;
	r5 = NULL;
	r3 = kha_System_windowWidth(r5);
	goto label$80733c3_23_8;
	label$80733c3_23_7:
	r3 = r1->width;
	label$80733c3_23_8:
	r4 = r1->height;
	r7 = 0;
	if( r4 != r7 ) goto label$80733c3_23_14;
	r5 = NULL;
	r4 = kha_System_windowHeight(r5);
	goto label$80733c3_23_15;
	label$80733c3_23_14:
	r4 = r1->height;
	label$80733c3_23_15:
	r8 = r1->depth;
	if( !r8 ) goto label$80733c3_23_19;
	r8 = r1->depth;
	goto label$80733c3_23_21;
	label$80733c3_23_19:
	r7 = 0;
	r8 = hl_alloc_dynamic(&$t_i32);
	r8->v.i = r7;
	label$80733c3_23_21:
	r9 = r1->displayp;
	if( !r9 ) goto label$80733c3_23_49;
	if( r4 >= r3 ) goto label$80733c3_23_37;
	r11 = (double)r3;
	r9 = r1->displayp;
	r7 = r9 ? r9->v.i : 0;
	r12 = (double)r7;
	r13 = (double)r4;
	r12 = r12 / r13;
	r11 = r11 * r12;
	r7 = (int)r11;
	r3 = r7;
	r9 = r1->displayp;
	r7 = r9 ? r9->v.i : 0;
	r4 = r7;
	goto label$80733c3_23_49;
	label$80733c3_23_37:
	r11 = (double)r4;
	r9 = r1->displayp;
	r7 = r9 ? r9->v.i : 0;
	r12 = (double)r7;
	r13 = (double)r3;
	r12 = r12 / r13;
	r11 = r11 * r12;
	r7 = (int)r11;
	r4 = r7;
	r9 = r1->displayp;
	r7 = r9 ? r9->v.i : 0;
	r3 = r7;
	label$80733c3_23_49:
	r14 = r1->scale;
	if( !r14 ) goto label$80733c3_23_71;
	r11 = (double)r3;
	r14 = r1->scale;
	r12 = r14 ? r14->v.d : 0;
	r11 = r11 * r12;
	r7 = (int)r11;
	r3 = r7;
	r12 = (double)r4;
	r14 = r1->scale;
	r13 = r14 ? r14->v.d : 0;
	r12 = r12 * r13;
	r7 = (int)r12;
	r4 = r7;
	r7 = r8 ? r8->v.i : 0;
	r13 = (double)r7;
	r14 = r1->scale;
	r15 = r14 ? r14->v.d : 0;
	r13 = r13 * r15;
	r7 = (int)r13;
	r9 = hl_alloc_dynamic(&$t_i32);
	r9->v.i = r7;
	r8 = r9;
	label$80733c3_23_71:
	r10 = 1;
	if( r3 >= r10 ) goto label$80733c3_23_75;
	r7 = 1;
	r3 = r7;
	label$80733c3_23_75:
	r10 = 1;
	if( r4 >= r10 ) goto label$80733c3_23_79;
	r7 = 1;
	r4 = r7;
	label$80733c3_23_79:
	r9 = r1->depth;
	if( !r9 ) goto label$80733c3_23_196;
	r9 = r1->depth;
	r7 = r9 ? r9->v.i : 0;
	r10 = 1;
	if( r10 >= r7 ) goto label$80733c3_23_196;
	r16 = r1->format;
	if( !r16 ) goto label$80733c3_23_183;
	r16 = r1->format;
	if( !r16 ) goto label$80733c3_23_97;
	r7 = r16->length;
	r10 = 7;
	if( r7 != r10 ) goto label$80733c3_23_97;
	r17 = r16->bytes;
	r18 = (vbyte*)USTR("DEPTH16");
	r7 = hl_string_compare(r17,r18,r7);
	r10 = 0;
	if( r7 == r10 ) goto label$80733c3_23_155;
	label$80733c3_23_97:
	if( !r16 ) goto label$80733c3_23_106;
	r7 = r16->length;
	r10 = 3;
	if( r7 != r10 ) goto label$80733c3_23_106;
	r17 = r16->bytes;
	r18 = (vbyte*)USTR("R16");
	r7 = hl_string_compare(r17,r18,r7);
	r10 = 0;
	if( r7 == r10 ) goto label$80733c3_23_159;
	label$80733c3_23_106:
	if( !r16 ) goto label$80733c3_23_115;
	r7 = r16->length;
	r10 = 3;
	if( r7 != r10 ) goto label$80733c3_23_115;
	r17 = r16->bytes;
	r18 = (vbyte*)USTR("R32");
	r7 = hl_string_compare(r17,r18,r7);
	r10 = 0;
	if( r7 == r10 ) goto label$80733c3_23_163;
	label$80733c3_23_115:
	if( !r16 ) goto label$80733c3_23_124;
	r7 = r16->length;
	r10 = 2;
	if( r7 != r10 ) goto label$80733c3_23_124;
	r17 = r16->bytes;
	r18 = (vbyte*)USTR("R8");
	r7 = hl_string_compare(r17,r18,r7);
	r10 = 0;
	if( r7 == r10 ) goto label$80733c3_23_167;
	label$80733c3_23_124:
	if( !r16 ) goto label$80733c3_23_133;
	r7 = r16->length;
	r10 = 7;
	if( r7 != r10 ) goto label$80733c3_23_133;
	r17 = r16->bytes;
	r18 = (vbyte*)USTR("RGBA128");
	r7 = hl_string_compare(r17,r18,r7);
	r10 = 0;
	if( r7 == r10 ) goto label$80733c3_23_171;
	label$80733c3_23_133:
	if( !r16 ) goto label$80733c3_23_142;
	r7 = r16->length;
	r10 = 6;
	if( r7 != r10 ) goto label$80733c3_23_142;
	r17 = r16->bytes;
	r18 = (vbyte*)USTR("RGBA32");
	r7 = hl_string_compare(r17,r18,r7);
	r10 = 0;
	if( r7 == r10 ) goto label$80733c3_23_175;
	label$80733c3_23_142:
	if( !r16 ) goto label$80733c3_23_151;
	r7 = r16->length;
	r10 = 6;
	if( r7 != r10 ) goto label$80733c3_23_151;
	r17 = r16->bytes;
	r18 = (vbyte*)USTR("RGBA64");
	r7 = hl_string_compare(r17,r18,r7);
	r10 = 0;
	if( r7 == r10 ) goto label$80733c3_23_179;
	label$80733c3_23_151:
	r7 = 0;
	r19 = hl_alloc_dynamic(&$t_i32);
	r19->v.i = r7;
	r9 = r19;
	goto label$80733c3_23_182;
	label$80733c3_23_155:
	r7 = 3;
	r19 = hl_alloc_dynamic(&$t_i32);
	r19->v.i = r7;
	r9 = r19;
	goto label$80733c3_23_182;
	label$80733c3_23_159:
	r7 = 6;
	r19 = hl_alloc_dynamic(&$t_i32);
	r19->v.i = r7;
	r9 = r19;
	goto label$80733c3_23_182;
	label$80733c3_23_163:
	r7 = 5;
	r19 = hl_alloc_dynamic(&$t_i32);
	r19->v.i = r7;
	r9 = r19;
	goto label$80733c3_23_182;
	label$80733c3_23_167:
	r7 = 1;
	r19 = hl_alloc_dynamic(&$t_i32);
	r19->v.i = r7;
	r9 = r19;
	goto label$80733c3_23_182;
	label$80733c3_23_171:
	r7 = 2;
	r19 = hl_alloc_dynamic(&$t_i32);
	r19->v.i = r7;
	r9 = r19;
	goto label$80733c3_23_182;
	label$80733c3_23_175:
	r7 = 0;
	r19 = hl_alloc_dynamic(&$t_i32);
	r19->v.i = r7;
	r9 = r19;
	goto label$80733c3_23_182;
	label$80733c3_23_179:
	r7 = 4;
	r19 = hl_alloc_dynamic(&$t_i32);
	r19->v.i = r7;
	r9 = r19;
	label$80733c3_23_182:
	goto label$80733c3_23_186;
	label$80733c3_23_183:
	r7 = 0;
	r19 = hl_alloc_dynamic(&$t_i32);
	r19->v.i = r7;
	r9 = r19;
	label$80733c3_23_186:
	r21 = r8 ? r8->v.i : 0;
	r22 = NULL;
	r20 = kha_Image_create3D(r3,r4,r21,r9,r22);
	r23 = r1->mipmaps;
	r24 = r23 ? r23->v.b : 0;
	if( !r24 ) goto label$80733c3_23_195;
	if( r20 == NULL ) hl_null_access();
	r7 = 1000;
	kha_Image_generateMipmaps(r20,r7);
	label$80733c3_23_195:
	return r20;
	label$80733c3_23_196:
	r23 = r1->is_image;
	if( !r23 ) goto label$80733c3_23_296;
	r23 = r1->is_image;
	r24 = r23 ? r23->v.b : 0;
	if( !r24 ) goto label$80733c3_23_296;
	r16 = r1->format;
	if( !r16 ) goto label$80733c3_23_291;
	r16 = r1->format;
	if( !r16 ) goto label$80733c3_23_213;
	r7 = r16->length;
	r10 = 7;
	if( r7 != r10 ) goto label$80733c3_23_213;
	r17 = r16->bytes;
	r18 = (vbyte*)USTR("DEPTH16");
	r7 = hl_string_compare(r17,r18,r7);
	r10 = 0;
	if( r7 == r10 ) goto label$80733c3_23_270;
	label$80733c3_23_213:
	if( !r16 ) goto label$80733c3_23_222;
	r7 = r16->length;
	r10 = 3;
	if( r7 != r10 ) goto label$80733c3_23_222;
	r17 = r16->bytes;
	r18 = (vbyte*)USTR("R16");
	r7 = hl_string_compare(r17,r18,r7);
	r10 = 0;
	if( r7 == r10 ) goto label$80733c3_23_273;
	label$80733c3_23_222:
	if( !r16 ) goto label$80733c3_23_231;
	r7 = r16->length;
	r10 = 3;
	if( r7 != r10 ) goto label$80733c3_23_231;
	r17 = r16->bytes;
	r18 = (vbyte*)USTR("R32");
	r7 = hl_string_compare(r17,r18,r7);
	r10 = 0;
	if( r7 == r10 ) goto label$80733c3_23_276;
	label$80733c3_23_231:
	if( !r16 ) goto label$80733c3_23_240;
	r7 = r16->length;
	r10 = 2;
	if( r7 != r10 ) goto label$80733c3_23_240;
	r17 = r16->bytes;
	r18 = (vbyte*)USTR("R8");
	r7 = hl_string_compare(r17,r18,r7);
	r10 = 0;
	if( r7 == r10 ) goto label$80733c3_23_279;
	label$80733c3_23_240:
	if( !r16 ) goto label$80733c3_23_249;
	r7 = r16->length;
	r10 = 7;
	if( r7 != r10 ) goto label$80733c3_23_249;
	r17 = r16->bytes;
	r18 = (vbyte*)USTR("RGBA128");
	r7 = hl_string_compare(r17,r18,r7);
	r10 = 0;
	if( r7 == r10 ) goto label$80733c3_23_282;
	label$80733c3_23_249:
	if( !r16 ) goto label$80733c3_23_258;
	r7 = r16->length;
	r10 = 6;
	if( r7 != r10 ) goto label$80733c3_23_258;
	r17 = r16->bytes;
	r18 = (vbyte*)USTR("RGBA32");
	r7 = hl_string_compare(r17,r18,r7);
	r10 = 0;
	if( r7 == r10 ) goto label$80733c3_23_285;
	label$80733c3_23_258:
	if( !r16 ) goto label$80733c3_23_267;
	r7 = r16->length;
	r10 = 6;
	if( r7 != r10 ) goto label$80733c3_23_267;
	r17 = r16->bytes;
	r18 = (vbyte*)USTR("RGBA64");
	r7 = hl_string_compare(r17,r18,r7);
	r10 = 0;
	if( r7 == r10 ) goto label$80733c3_23_288;
	label$80733c3_23_267:
	r7 = 0;
	r19 = hl_alloc_dynamic(&$t_i32);
	r19->v.i = r7;
	goto label$80733c3_23_290;
	label$80733c3_23_270:
	r7 = 3;
	r19 = hl_alloc_dynamic(&$t_i32);
	r19->v.i = r7;
	goto label$80733c3_23_290;
	label$80733c3_23_273:
	r7 = 6;
	r19 = hl_alloc_dynamic(&$t_i32);
	r19->v.i = r7;
	goto label$80733c3_23_290;
	label$80733c3_23_276:
	r7 = 5;
	r19 = hl_alloc_dynamic(&$t_i32);
	r19->v.i = r7;
	goto label$80733c3_23_290;
	label$80733c3_23_279:
	r7 = 1;
	r19 = hl_alloc_dynamic(&$t_i32);
	r19->v.i = r7;
	goto label$80733c3_23_290;
	label$80733c3_23_282:
	r7 = 2;
	r19 = hl_alloc_dynamic(&$t_i32);
	r19->v.i = r7;
	goto label$80733c3_23_290;
	label$80733c3_23_285:
	r7 = 0;
	r19 = hl_alloc_dynamic(&$t_i32);
	r19->v.i = r7;
	goto label$80733c3_23_290;
	label$80733c3_23_288:
	r7 = 4;
	r19 = hl_alloc_dynamic(&$t_i32);
	r19->v.i = r7;
	label$80733c3_23_290:
	goto label$80733c3_23_293;
	label$80733c3_23_291:
	r7 = 0;
	r19 = hl_alloc_dynamic(&$t_i32);
	r19->v.i = r7;
	label$80733c3_23_293:
	r22 = NULL;
	r20 = kha_Image_create(r3,r4,r19,r22);
	return r20;
	label$80733c3_23_296:
	r16 = r1->format;
	if( !r16 ) goto label$80733c3_23_386;
	r16 = r1->format;
	if( !r16 ) goto label$80733c3_23_308;
	r7 = r16->length;
	r10 = 7;
	if( r7 != r10 ) goto label$80733c3_23_308;
	r17 = r16->bytes;
	r18 = (vbyte*)USTR("DEPTH16");
	r7 = hl_string_compare(r17,r18,r7);
	r10 = 0;
	if( r7 == r10 ) goto label$80733c3_23_365;
	label$80733c3_23_308:
	if( !r16 ) goto label$80733c3_23_317;
	r7 = r16->length;
	r10 = 3;
	if( r7 != r10 ) goto label$80733c3_23_317;
	r17 = r16->bytes;
	r18 = (vbyte*)USTR("R16");
	r7 = hl_string_compare(r17,r18,r7);
	r10 = 0;
	if( r7 == r10 ) goto label$80733c3_23_368;
	label$80733c3_23_317:
	if( !r16 ) goto label$80733c3_23_326;
	r7 = r16->length;
	r10 = 3;
	if( r7 != r10 ) goto label$80733c3_23_326;
	r17 = r16->bytes;
	r18 = (vbyte*)USTR("R32");
	r7 = hl_string_compare(r17,r18,r7);
	r10 = 0;
	if( r7 == r10 ) goto label$80733c3_23_371;
	label$80733c3_23_326:
	if( !r16 ) goto label$80733c3_23_335;
	r7 = r16->length;
	r10 = 2;
	if( r7 != r10 ) goto label$80733c3_23_335;
	r17 = r16->bytes;
	r18 = (vbyte*)USTR("R8");
	r7 = hl_string_compare(r17,r18,r7);
	r10 = 0;
	if( r7 == r10 ) goto label$80733c3_23_374;
	label$80733c3_23_335:
	if( !r16 ) goto label$80733c3_23_344;
	r7 = r16->length;
	r10 = 7;
	if( r7 != r10 ) goto label$80733c3_23_344;
	r17 = r16->bytes;
	r18 = (vbyte*)USTR("RGBA128");
	r7 = hl_string_compare(r17,r18,r7);
	r10 = 0;
	if( r7 == r10 ) goto label$80733c3_23_377;
	label$80733c3_23_344:
	if( !r16 ) goto label$80733c3_23_353;
	r7 = r16->length;
	r10 = 6;
	if( r7 != r10 ) goto label$80733c3_23_353;
	r17 = r16->bytes;
	r18 = (vbyte*)USTR("RGBA32");
	r7 = hl_string_compare(r17,r18,r7);
	r10 = 0;
	if( r7 == r10 ) goto label$80733c3_23_380;
	label$80733c3_23_353:
	if( !r16 ) goto label$80733c3_23_362;
	r7 = r16->length;
	r10 = 6;
	if( r7 != r10 ) goto label$80733c3_23_362;
	r17 = r16->bytes;
	r18 = (vbyte*)USTR("RGBA64");
	r7 = hl_string_compare(r17,r18,r7);
	r10 = 0;
	if( r7 == r10 ) goto label$80733c3_23_383;
	label$80733c3_23_362:
	r7 = 0;
	r19 = hl_alloc_dynamic(&$t_i32);
	r19->v.i = r7;
	goto label$80733c3_23_385;
	label$80733c3_23_365:
	r7 = 3;
	r19 = hl_alloc_dynamic(&$t_i32);
	r19->v.i = r7;
	goto label$80733c3_23_385;
	label$80733c3_23_368:
	r7 = 6;
	r19 = hl_alloc_dynamic(&$t_i32);
	r19->v.i = r7;
	goto label$80733c3_23_385;
	label$80733c3_23_371:
	r7 = 5;
	r19 = hl_alloc_dynamic(&$t_i32);
	r19->v.i = r7;
	goto label$80733c3_23_385;
	label$80733c3_23_374:
	r7 = 1;
	r19 = hl_alloc_dynamic(&$t_i32);
	r19->v.i = r7;
	goto label$80733c3_23_385;
	label$80733c3_23_377:
	r7 = 2;
	r19 = hl_alloc_dynamic(&$t_i32);
	r19->v.i = r7;
	goto label$80733c3_23_385;
	label$80733c3_23_380:
	r7 = 0;
	r19 = hl_alloc_dynamic(&$t_i32);
	r19->v.i = r7;
	goto label$80733c3_23_385;
	label$80733c3_23_383:
	r7 = 4;
	r19 = hl_alloc_dynamic(&$t_i32);
	r19->v.i = r7;
	label$80733c3_23_385:
	goto label$80733c3_23_388;
	label$80733c3_23_386:
	r7 = 0;
	r19 = hl_alloc_dynamic(&$t_i32);
	r19->v.i = r7;
	label$80733c3_23_388:
	r21 = r2;
	r5 = &r21;
	r25 = NULL;
	r26 = NULL;
	r20 = kha_Image_createRenderTarget(r3,r4,r19,r5,r25,r26);
	return r20;
}

kha__graphics4__CubeMap iron_RenderPath_createCubeMap(iron__RenderPath r0,iron__RenderTargetRaw r1,int r2) {
	kha__graphics4__CubeMap r9;
	String r3;
	int *r11;
	vdynamic *r8, *r10;
	vbyte *r6, *r7;
	int r4, r5;
	if( r1 == NULL ) hl_null_access();
	r3 = r1->format;
	if( !r3 ) goto label$80733c3_24_91;
	r3 = r1->format;
	if( !r3 ) goto label$80733c3_24_13;
	r4 = r3->length;
	r5 = 7;
	if( r4 != r5 ) goto label$80733c3_24_13;
	r6 = r3->bytes;
	r7 = (vbyte*)USTR("DEPTH16");
	r4 = hl_string_compare(r6,r7,r4);
	r5 = 0;
	if( r4 == r5 ) goto label$80733c3_24_70;
	label$80733c3_24_13:
	if( !r3 ) goto label$80733c3_24_22;
	r4 = r3->length;
	r5 = 3;
	if( r4 != r5 ) goto label$80733c3_24_22;
	r6 = r3->bytes;
	r7 = (vbyte*)USTR("R16");
	r4 = hl_string_compare(r6,r7,r4);
	r5 = 0;
	if( r4 == r5 ) goto label$80733c3_24_73;
	label$80733c3_24_22:
	if( !r3 ) goto label$80733c3_24_31;
	r4 = r3->length;
	r5 = 3;
	if( r4 != r5 ) goto label$80733c3_24_31;
	r6 = r3->bytes;
	r7 = (vbyte*)USTR("R32");
	r4 = hl_string_compare(r6,r7,r4);
	r5 = 0;
	if( r4 == r5 ) goto label$80733c3_24_76;
	label$80733c3_24_31:
	if( !r3 ) goto label$80733c3_24_40;
	r4 = r3->length;
	r5 = 2;
	if( r4 != r5 ) goto label$80733c3_24_40;
	r6 = r3->bytes;
	r7 = (vbyte*)USTR("R8");
	r4 = hl_string_compare(r6,r7,r4);
	r5 = 0;
	if( r4 == r5 ) goto label$80733c3_24_79;
	label$80733c3_24_40:
	if( !r3 ) goto label$80733c3_24_49;
	r4 = r3->length;
	r5 = 7;
	if( r4 != r5 ) goto label$80733c3_24_49;
	r6 = r3->bytes;
	r7 = (vbyte*)USTR("RGBA128");
	r4 = hl_string_compare(r6,r7,r4);
	r5 = 0;
	if( r4 == r5 ) goto label$80733c3_24_82;
	label$80733c3_24_49:
	if( !r3 ) goto label$80733c3_24_58;
	r4 = r3->length;
	r5 = 6;
	if( r4 != r5 ) goto label$80733c3_24_58;
	r6 = r3->bytes;
	r7 = (vbyte*)USTR("RGBA32");
	r4 = hl_string_compare(r6,r7,r4);
	r5 = 0;
	if( r4 == r5 ) goto label$80733c3_24_85;
	label$80733c3_24_58:
	if( !r3 ) goto label$80733c3_24_67;
	r4 = r3->length;
	r5 = 6;
	if( r4 != r5 ) goto label$80733c3_24_67;
	r6 = r3->bytes;
	r7 = (vbyte*)USTR("RGBA64");
	r4 = hl_string_compare(r6,r7,r4);
	r5 = 0;
	if( r4 == r5 ) goto label$80733c3_24_88;
	label$80733c3_24_67:
	r4 = 0;
	r8 = hl_alloc_dynamic(&$t_i32);
	r8->v.i = r4;
	goto label$80733c3_24_90;
	label$80733c3_24_70:
	r4 = 3;
	r8 = hl_alloc_dynamic(&$t_i32);
	r8->v.i = r4;
	goto label$80733c3_24_90;
	label$80733c3_24_73:
	r4 = 6;
	r8 = hl_alloc_dynamic(&$t_i32);
	r8->v.i = r4;
	goto label$80733c3_24_90;
	label$80733c3_24_76:
	r4 = 5;
	r8 = hl_alloc_dynamic(&$t_i32);
	r8->v.i = r4;
	goto label$80733c3_24_90;
	label$80733c3_24_79:
	r4 = 1;
	r8 = hl_alloc_dynamic(&$t_i32);
	r8->v.i = r4;
	goto label$80733c3_24_90;
	label$80733c3_24_82:
	r4 = 2;
	r8 = hl_alloc_dynamic(&$t_i32);
	r8->v.i = r4;
	goto label$80733c3_24_90;
	label$80733c3_24_85:
	r4 = 0;
	r8 = hl_alloc_dynamic(&$t_i32);
	r8->v.i = r4;
	goto label$80733c3_24_90;
	label$80733c3_24_88:
	r4 = 4;
	r8 = hl_alloc_dynamic(&$t_i32);
	r8->v.i = r4;
	label$80733c3_24_90:
	goto label$80733c3_24_93;
	label$80733c3_24_91:
	r4 = 0;
	r8 = hl_alloc_dynamic(&$t_i32);
	r8->v.i = r4;
	label$80733c3_24_93:
	r4 = r1->width;
	r10 = hl_alloc_dynamic(&$t_i32);
	r10->v.i = r2;
	r11 = NULL;
	r9 = kha_graphics4_CubeMap_createRenderTarget(r4,r8,r10,r11);
	return r9;
}

void iron_RenderPath_new(iron__RenderPath r0) {
	vvirtual *r10;
	haxe__ds__StringMap r5;
	hl__types__ArrayObj r1;
	hl_type *r3;
	bool r8;
	iron__RenderTarget r12;
	iron__object__LightObject r11;
	vclosure *r9;
	double r7;
	int r4;
	varray *r2;
	r3 = &$t_vrt_ee58142;
	r4 = 0;
	r2 = hl_alloc_array(r3,r4);
	r1 = hl_types_ArrayObj_alloc(r2);
	r0->depthBuffers = r1;
	r5 = (haxe__ds__StringMap)hl_alloc_obj(&$t_haxe_ds_StringMap);
	haxe_ds_StringMap_new(r5);
	r0->cachedShaderContexts = r5;
	r4 = 0;
	r0->loading = r4;
	r7 = 0.;
	r0->lastFrameTime = r7;
	r8 = false;
	r0->viewportScaled = r8;
	r8 = false;
	r0->scissorSet = r8;
	r5 = (haxe__ds__StringMap)hl_alloc_obj(&$t_haxe_ds_StringMap);
	haxe_ds_StringMap_new(r5);
	r0->depthToRenderTarget = r5;
	r5 = (haxe__ds__StringMap)hl_alloc_obj(&$t_haxe_ds_StringMap);
	haxe_ds_StringMap_new(r5);
	r0->renderTargets = r5;
	r9 = NULL;
	r0->commands = r9;
	r8 = false;
	r0->paused = r8;
	r4 = 0;
	r0->drawOrder = r4;
	r10 = NULL;
	r0->currentG = r10;
	r8 = false;
	r0->isProbe = r8;
	r8 = false;
	r0->isProbeCube = r8;
	r8 = false;
	r0->isProbePlanar = r8;
	r11 = NULL;
	r0->point = r11;
	r11 = NULL;
	r0->sun = r11;
	r11 = NULL;
	r0->light = r11;
	r12 = NULL;
	r0->currentTarget = r12;
	r4 = 0;
	r0->frame = r4;
	r7 = 0.;
	r0->frameTime = r7;
	r4 = 0;
	r0->frameScissorH = r4;
	r4 = 0;
	r0->frameScissorW = r4;
	r4 = 0;
	r0->frameScissorY = r4;
	r4 = 0;
	r0->frameScissorX = r4;
	r8 = false;
	r0->frameScissor = r8;
	return;
}

