// Generated by HLC 4.0.0 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <_std/Reflect.h>
#include <hl/natives.h>
extern String $s_set_;
String String___add__(String,String);
#include <hl/types/ArrayBase.h>
extern String $s_Invalid_function_;
String Std_string(vdynamic*);
extern hl_type $t_dyn;
vdynamic* hl_types_ArrayDyn_getDyn(hl__types__ArrayDyn,int);

bool Reflect_hasField(vdynamic* r0,String r1) {
	bool r2;
	vbyte *r4;
	int r3;
	if( r1 ) goto label$0858e10_1_3;
	r2 = false;
	return r2;
	label$0858e10_1_3:
	if( r1 == NULL ) hl_null_access();
	r4 = r1->bytes;
	r3 = hl_hash(r4);
	r2 = hl_obj_has_field(r0,r3);
	return r2;
}

vdynamic* Reflect_field(vdynamic* r0,String r1) {
	vdynamic *r2;
	vbyte *r4;
	int r3;
	if( r1 ) goto label$0858e10_2_3;
	r2 = NULL;
	return r2;
	label$0858e10_2_3:
	if( r1 == NULL ) hl_null_access();
	r4 = r1->bytes;
	r3 = hl_hash(r4);
	r2 = hl_obj_get_field(r0,r3);
	return r2;
}

void Reflect_setField(vdynamic* r0,String r1,vdynamic* r2) {
	vbyte *r4;
	int r3;
	if( r1 == NULL ) hl_null_access();
	r4 = r1->bytes;
	r3 = hl_hash(r4);
	hl_obj_set_field(r0,r3,r2);
	return;
}

void Reflect_setProperty(vdynamic* r0,String r1,vdynamic* r2) {
	String r4;
	vdynamic *r3, *r6;
	r4 = (String)$s_set_;
	r4 = String___add__(r4,r1);
	r3 = Reflect_field(r0,r4);
	if( !r3 ) goto label$0858e10_4_7;
	if( r3 == NULL ) hl_null_access();
	{
		vdynamic *args[] = {r2};
		r6 = (vdynamic*)hl_dyn_call((vclosure*)r3,args,1);
	}
	goto label$0858e10_4_8;
	label$0858e10_4_7:
	Reflect_setField(r0,r1,r2);
	label$0858e10_4_8:
	return;
}

vdynamic* Reflect_callMethod(vdynamic* r0,vdynamic* r1,hl__types__ArrayDyn r2) {
	String r9, r10;
	hl_type *r4, *r7;
	hl__types__ArrayBase r11;
	hl__types__ArrayDyn r3;
	vdynamic *r5, *r14;
	varray *r15, *r16;
	int r6, r8, r12, r13, r17, r18, r19, r20;
	r3 = r2;
	r4 = r1 ? ((vdynamic*)r1)->t : &hlt_void;
	r6 = r4->kind;
	r8 = 10;
	if( r6 == r8 ) goto label$0858e10_5_9;
	r9 = (String)$s_Invalid_function_;
	r10 = Std_string(r1);
	r9 = String___add__(r9,r10);
	hl_throw((vdynamic*)r9);
	label$0858e10_5_9:
	if( r2 == NULL ) hl_null_access();
	r11 = r2->array;
	if( r11 == NULL ) hl_null_access();
	r6 = r11->length;
	r8 = hl_type_args_count(r4);
	if( r6 >= r8 ) goto label$0858e10_5_17;
	r12 = r8;
	goto label$0858e10_5_18;
	label$0858e10_5_17:
	r12 = r6;
	label$0858e10_5_18:
	r5 = hl_get_closure_value(r1);
	if( !r5 ) goto label$0858e10_5_23;
	r14 = hl_no_closure(r1);
	r1 = r14;
	++r12;
	label$0858e10_5_23:
	r7 = &$t_dyn;
	r15 = hl_alloc_array(r7,r12);
	r16 = r15;
	if( r5 ) goto label$0858e10_5_38;
	r13 = 0;
	r17 = r6;
	label$0858e10_5_29:
	if( r13 >= r17 ) goto label$0858e10_5_37;
	r18 = r13;
	++r13;
	if( r3 == NULL ) hl_null_access();
	r14 = hl_types_ArrayDyn_getDyn(r3,r18);
	((vdynamic**)(r16 + 1))[r18] = r14;
	goto label$0858e10_5_29;
	label$0858e10_5_37:
	goto label$0858e10_5_52;
	label$0858e10_5_38:
	r13 = 0;
	((vdynamic**)(r15 + 1))[r13] = r5;
	r13 = 0;
	r17 = r6;
	label$0858e10_5_42:
	if( r13 >= r17 ) goto label$0858e10_5_52;
	r18 = r13;
	++r13;
	if( r3 == NULL ) hl_null_access();
	r14 = hl_types_ArrayDyn_getDyn(r3,r18);
	r20 = 1;
	r19 = r18 + r20;
	((vdynamic**)(r16 + 1))[r19] = r14;
	goto label$0858e10_5_42;
	label$0858e10_5_52:
	r14 = hl_call_method(r1,r16);
	return r14;
}

