// Generated by HLC 4.0.0 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <haxe/ds/IntMap.h>
#include <hl/natives.h>

void haxe_ds_IntMap_new(haxe__ds__IntMap r0) {
	hl_int_map *r1;
	r1 = hl_hialloc();
	r0->h = r1;
	return;
}

void haxe_ds_IntMap_set(haxe__ds__IntMap r0,int r1,vdynamic* r2) {
	hl_int_map *r4;
	r4 = r0->h;
	hl_hiset(r4,r1,r2);
	return;
}

