// Generated by HLC 4.0.0 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <hl/types/ArrayAccess.h>
extern String $s_Not_implemented;

vdynamic* hl_types_ArrayAccess_getDyn(hl__types__ArrayAccess r0,int r1) {
	String r2;
	r2 = (String)$s_Not_implemented;
	hl_throw((vdynamic*)r2);
}

void hl_types_ArrayAccess_setDyn(hl__types__ArrayAccess r0,int r1,vdynamic* r2) {
	String r3;
	r3 = (String)$s_Not_implemented;
	hl_throw((vdynamic*)r3);
}

void hl_types_ArrayAccess_blit(hl__types__ArrayAccess r0,int r1,hl__types__ArrayAccess r2,int r3,int r4) {
	String r5;
	r5 = (String)$s_Not_implemented;
	hl_throw((vdynamic*)r5);
}

