// Generated by HLC 4.0.0 (HL v4)
#ifndef INC_hl__types__BytesIterator_Single
#define INC_hl__types__BytesIterator_Single
typedef struct _hl__types__$BytesIterator_Single *hl__types__$BytesIterator_Single;
typedef struct _hl__types__BytesIterator_Single *hl__types__BytesIterator_Single;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <hl/types/ArrayBytes_Single.h>


struct _hl__types__$BytesIterator_Single {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
};
struct _hl__types__BytesIterator_Single {
	hl_type *$type;
	int pos;
	hl__types__ArrayBytes_Single a;
};
#endif

