// Generated by HLC 4.0.0 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <kha/graphics4/PipelineCache.h>
#include <hl/types/ArrayDyn.h>
#include <haxe/Log.h>
extern String s$projectionMatrix;
vvirtual* kha_graphics4_PipelineState_getConstantLocation(kha__graphics4__PipelineState,String);
extern haxe__$Log g$_haxe_Log;
extern hl_type t$vrt_329ffa8;
extern String s$kha_graphics4_Graphics2_hx;
extern hl_type t$String;
extern hl_type t$_i32;
extern String s$kha_graphics4_PipelineCache;
extern String s$new;
extern hl_type t$vrt_eaa6a3b;
extern String s$tex;
vvirtual* kha_graphics4_PipelineState_getTextureUnit(kha__graphics4__PipelineState,String);

void kha_graphics4_PipelineCache_new(kha__graphics4__PipelineCache r0,kha__graphics4__PipelineState r1) {
	String r5;
	vvirtual *r4, *r9, *r11;
	haxe__$Log r7;
	vclosure *r6;
	vdynamic *r2, *r8;
	int r10;
	hl_trap_ctx trap$0;
	r0->pipeline = r1;
	hl_trap(trap$0,r2,label$5ee06d7_1_8);
	if( r1 == NULL ) hl_null_access();
	r5 = (String)s$projectionMatrix;
	r4 = kha_graphics4_PipelineState_getConstantLocation(r1,r5);
	r0->projectionLocation = r4;
	hl_endtrap(trap$0);
	goto label$5ee06d7_1_22;
	label$5ee06d7_1_8:
	r7 = (haxe__$Log)g$_haxe_Log;
	r6 = r7->trace;
	if( r6 == NULL ) hl_null_access();
	r9 = hl_alloc_virtual(&t$vrt_329ffa8);
	r5 = (String)s$kha_graphics4_Graphics2_hx;
	if( hl_vfields(r9)[1] ) *(String*)(hl_vfields(r9)[1]) = (String)r5; else hl_dyn_setp(r9->value,37969014/*fileName*/,&t$String,r5);
	r10 = 39;
	if( hl_vfields(r9)[2] ) *(int*)(hl_vfields(r9)[2]) = (int)r10; else hl_dyn_seti(r9->value,371360620/*lineNumber*/,&t$_i32,r10);
	r5 = (String)s$kha_graphics4_PipelineCache;
	if( hl_vfields(r9)[0] ) *(String*)(hl_vfields(r9)[0]) = (String)r5; else hl_dyn_setp(r9->value,-63073762/*className*/,&t$String,r5);
	r5 = (String)s$new;
	if( hl_vfields(r9)[3] ) *(String*)(hl_vfields(r9)[3]) = (String)r5; else hl_dyn_setp(r9->value,302979532/*methodName*/,&t$String,r5);
	r11 = hl_to_virtual(&t$vrt_eaa6a3b,(vdynamic*)r9);
	r6->hasValue ? ((void (*)(vdynamic*,vdynamic*,vvirtual*))r6->fun)((vdynamic*)r6->value,r2,r11) : ((void (*)(vdynamic*,vvirtual*))r6->fun)(r2,r11);
	label$5ee06d7_1_22:
	hl_trap(trap$0,r8,label$5ee06d7_1_29);
	if( r1 == NULL ) hl_null_access();
	r5 = (String)s$tex;
	r4 = kha_graphics4_PipelineState_getTextureUnit(r1,r5);
	r0->textureLocation = r4;
	hl_endtrap(trap$0);
	goto label$5ee06d7_1_43;
	label$5ee06d7_1_29:
	r7 = (haxe__$Log)g$_haxe_Log;
	r6 = r7->trace;
	if( r6 == NULL ) hl_null_access();
	r9 = hl_alloc_virtual(&t$vrt_329ffa8);
	r5 = (String)s$kha_graphics4_Graphics2_hx;
	if( hl_vfields(r9)[1] ) *(String*)(hl_vfields(r9)[1]) = (String)r5; else hl_dyn_setp(r9->value,37969014/*fileName*/,&t$String,r5);
	r10 = 40;
	if( hl_vfields(r9)[2] ) *(int*)(hl_vfields(r9)[2]) = (int)r10; else hl_dyn_seti(r9->value,371360620/*lineNumber*/,&t$_i32,r10);
	r5 = (String)s$kha_graphics4_PipelineCache;
	if( hl_vfields(r9)[0] ) *(String*)(hl_vfields(r9)[0]) = (String)r5; else hl_dyn_setp(r9->value,-63073762/*className*/,&t$String,r5);
	r5 = (String)s$new;
	if( hl_vfields(r9)[3] ) *(String*)(hl_vfields(r9)[3]) = (String)r5; else hl_dyn_setp(r9->value,302979532/*methodName*/,&t$String,r5);
	r11 = hl_to_virtual(&t$vrt_eaa6a3b,(vdynamic*)r9);
	r6->hasValue ? ((void (*)(vdynamic*,vdynamic*,vvirtual*))r6->fun)((vdynamic*)r6->value,r8,r11) : ((void (*)(vdynamic*,vvirtual*))r6->fun)(r8,r11);
	label$5ee06d7_1_43:
	return;
}

