// Generated by HLC 4.0.0 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <kha/graphics2/GraphicsExtension.h>
#include <_std/Math.h>
extern $Math $g__Math;
#include <hl/natives.h>

void kha_graphics2_GraphicsExtension_drawArc(kha__graphics2__Graphics r0,double r1,double r2,double r3,double r4,double r5,double* r6,bool* r7,int* r8) {
	bool r10;
	$Math r14;
	double r9, r12, r13, r15, r19, r20, r21, r22, r23, r24, r25, r26, r27, r28;
	int r11, r17, r18;
	if( r6 ) goto label$3120bba_1_3;
	r9 = 1.;
	goto label$3120bba_1_4;
	label$3120bba_1_3:
	r9 = *r6;
	label$3120bba_1_4:
	if( r7 ) goto label$3120bba_1_7;
	r10 = false;
	goto label$3120bba_1_8;
	label$3120bba_1_7:
	r10 = *r7;
	label$3120bba_1_8:
	if( r8 ) goto label$3120bba_1_11;
	r11 = 0;
	goto label$3120bba_1_12;
	label$3120bba_1_11:
	r11 = *r8;
	label$3120bba_1_12:
	r14 = ($Math)$g__Math;
	r13 = r14->PI;
	r15 = 2.;
	r13 = r13 * r15;
	r12 = fmod(r4,r13);
	r4 = r12;
	r14 = ($Math)$g__Math;
	r13 = r14->PI;
	r15 = 2.;
	r13 = r13 * r15;
	r12 = fmod(r5,r13);
	r5 = r12;
	if( !r10 ) goto label$3120bba_1_33;
	if( !(r4 < r12) ) goto label$3120bba_1_32;
	r14 = ($Math)$g__Math;
	r13 = r14->PI;
	r15 = 2.;
	r13 = r13 * r15;
	r12 = r12 - r13;
	r5 = r12;
	label$3120bba_1_32:
	goto label$3120bba_1_40;
	label$3120bba_1_33:
	if( !(r12 < r4) ) goto label$3120bba_1_40;
	r14 = ($Math)$g__Math;
	r13 = r14->PI;
	r15 = 2.;
	r13 = r13 * r15;
	r12 = r12 + r13;
	r5 = r12;
	label$3120bba_1_40:
	r18 = 0;
	if( r18 < r11 ) goto label$3120bba_1_47;
	r12 = 10.;
	r13 = hl_math_sqrt(r3);
	r12 = r12 * r13;
	r17 = hl_math_floor(r12);
	r11 = r17;
	label$3120bba_1_47:
	r12 = r5 - r4;
	r13 = (double)r11;
	r12 = r12 / r13;
	r13 = hl_math_cos(r12);
	r15 = hl_math_sin(r12);
	r19 = hl_math_cos(r4);
	r19 = r19 * r3;
	r20 = hl_math_sin(r4);
	r20 = r20 * r3;
	r17 = 0;
	r18 = r11;
	label$3120bba_1_58:
	if( r17 >= r18 ) goto label$3120bba_1_79;
	++r17;
	r21 = r19 + r1;
	r22 = r20 + r2;
	r23 = r19;
	r24 = r13 * r19;
	r25 = r15 * r20;
	r24 = r24 - r25;
	r19 = r24;
	r24 = r13 * r20;
	r25 = r15 * r23;
	r24 = r24 + r25;
	r20 = r24;
	if( r0 == NULL ) hl_null_access();
	r26 = r19 + r1;
	r27 = r20 + r2;
	r28 = r9;
	r6 = &r28;
	((void (*)(kha__graphics2__Graphics,double,double,double,double,double*))r0->$type->vobj_proto[6])(r0,r21,r22,r26,r27,r6);
	goto label$3120bba_1_58;
	label$3120bba_1_79:
	return;
}

void kha_graphics2_GraphicsExtension_drawCircle(kha__graphics2__Graphics r0,double r1,double r2,double r3,double* r4,int* r5) {
	$Math r13;
	double r6, r11, r12, r14, r15, r16, r17, r18, r19, r20, r21, r22, r23, r24;
	int r7, r9, r10;
	if( r4 ) goto label$3120bba_2_3;
	r6 = 1.;
	goto label$3120bba_2_4;
	label$3120bba_2_3:
	r6 = *r4;
	label$3120bba_2_4:
	if( r5 ) goto label$3120bba_2_7;
	r7 = 0;
	goto label$3120bba_2_8;
	label$3120bba_2_7:
	r7 = *r5;
	label$3120bba_2_8:
	r10 = 0;
	if( r10 < r7 ) goto label$3120bba_2_15;
	r11 = 10.;
	r12 = hl_math_sqrt(r3);
	r11 = r11 * r12;
	r9 = hl_math_floor(r11);
	r7 = r9;
	label$3120bba_2_15:
	r11 = 2.;
	r13 = ($Math)$g__Math;
	r12 = r13->PI;
	r11 = r11 * r12;
	r12 = (double)r7;
	r11 = r11 / r12;
	r12 = hl_math_cos(r11);
	r14 = hl_math_sin(r11);
	r15 = r3;
	r16 = 0.;
	r9 = 0;
	r10 = r7;
	label$3120bba_2_27:
	if( r9 >= r10 ) goto label$3120bba_2_48;
	++r9;
	r17 = r15 + r1;
	r18 = r16 + r2;
	r19 = r15;
	r20 = r12 * r15;
	r21 = r14 * r16;
	r20 = r20 - r21;
	r15 = r20;
	r20 = r12 * r16;
	r21 = r14 * r19;
	r20 = r20 + r21;
	r16 = r20;
	if( r0 == NULL ) hl_null_access();
	r22 = r15 + r1;
	r23 = r16 + r2;
	r24 = r6;
	r4 = &r24;
	((void (*)(kha__graphics2__Graphics,double,double,double,double,double*))r0->$type->vobj_proto[6])(r0,r17,r18,r22,r23,r4);
	goto label$3120bba_2_27;
	label$3120bba_2_48:
	return;
}

void kha_graphics2_GraphicsExtension_fillCircle(kha__graphics2__Graphics r0,double r1,double r2,double r3,int* r4) {
	$Math r11;
	double r9, r10, r12, r13, r14, r15, r16, r17, r18, r19, r20, r21;
	int r5, r7, r8;
	if( r4 ) goto label$3120bba_3_3;
	r5 = 0;
	goto label$3120bba_3_4;
	label$3120bba_3_3:
	r5 = *r4;
	label$3120bba_3_4:
	r8 = 0;
	if( r8 < r5 ) goto label$3120bba_3_11;
	r9 = 10.;
	r10 = hl_math_sqrt(r3);
	r9 = r9 * r10;
	r7 = hl_math_floor(r9);
	r5 = r7;
	label$3120bba_3_11:
	r9 = 2.;
	r11 = ($Math)$g__Math;
	r10 = r11->PI;
	r9 = r9 * r10;
	r10 = (double)r5;
	r9 = r9 / r10;
	r10 = hl_math_cos(r9);
	r12 = hl_math_sin(r9);
	r13 = r3;
	r14 = 0.;
	r7 = 0;
	r8 = r5;
	label$3120bba_3_23:
	if( r7 >= r8 ) goto label$3120bba_3_42;
	++r7;
	r15 = r13 + r1;
	r16 = r14 + r2;
	r17 = r13;
	r18 = r10 * r13;
	r19 = r12 * r14;
	r18 = r18 - r19;
	r13 = r18;
	r18 = r10 * r14;
	r19 = r12 * r17;
	r18 = r18 + r19;
	r14 = r18;
	if( r0 == NULL ) hl_null_access();
	r20 = r13 + r1;
	r21 = r14 + r2;
	((void (*)(kha__graphics2__Graphics,double,double,double,double,double,double))r0->$type->vobj_proto[7])(r0,r15,r16,r20,r21,r1,r2);
	goto label$3120bba_3_23;
	label$3120bba_3_42:
	return;
}

