// Generated by HLC 4.0.0 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <hl/types/BytesIterator_hl_UI16.h>

void hl_types_BytesIterator_hl_UI16_new(hl__types__BytesIterator_hl_UI16 r0,hl__types__ArrayBytes_hl_UI16 r1) {
	r0->a = r1;
	return;
}

bool hl_types_BytesIterator_hl_UI16_hasNext(hl__types__BytesIterator_hl_UI16 r0) {
	bool r1;
	hl__types__ArrayBytes_hl_UI16 r4;
	int r2, r3;
	r2 = r0->pos;
	r4 = r0->a;
	if( r4 == NULL ) hl_null_access();
	r3 = r4->length;
	if( r2 < r3 ) goto label$c62a5bd_2_7;
	r1 = false;
	goto label$c62a5bd_2_8;
	label$c62a5bd_2_7:
	r1 = true;
	label$c62a5bd_2_8:
	return r1;
}

unsigned short hl_types_BytesIterator_hl_UI16_next(hl__types__BytesIterator_hl_UI16 r0) {
	hl__types__ArrayBytes_hl_UI16 r2;
	unsigned short r6;
	int r3, r4, r5;
	vbyte *r1;
	r2 = r0->a;
	if( r2 == NULL ) hl_null_access();
	r1 = r2->bytes;
	r3 = r0->pos;
	r4 = r3;
	++r3;
	r0->pos = r3;
	r5 = 1;
	r5 = r4 << r5;
	r4 = *(unsigned short*)(r1 + r5);
	r6 = (int)r4;
	return r6;
}

