// Generated by HLC 4.0.0 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <kha/LoaderImpl.h>
#include <hl/types/ArrayDyn.h>
#include <kha/korehl/Sound.h>
#include <haxe/io/Bytes.h>
extern hl_type $t_dyn;
extern hl_type $t_hl_types_ArrayDyn;
extern hl_type $t_kha_korehl_Sound;
void kha_korehl_Sound_new(kha__korehl__Sound,String,haxe__io__Bytes);
extern String $s_readable;
bool Reflect_hasField(vdynamic*,String);
extern hl_type $t_bool;
kha__Image kha_Image_fromFile(String,bool);
#include <hl/natives.h>
extern hl_type $t_kha_internal_BytesBlob;
extern hl_type $t_haxe_io_Bytes;
void haxe_io_Bytes_new(haxe__io__Bytes,vbyte*,int);
void kha_internal_BytesBlob_new(kha__internal__BytesBlob,haxe__io__Bytes);
extern hl_type $t_kha_Kravur;
void kha_Kravur_new(kha__Kravur,kha__internal__BytesBlob);
extern hl_type $t_fun_11ee11d;

void kha_LoaderImpl_loadSoundFromDescription(vdynamic* r0,vclosure* r1,vclosure* r2) {
	String r6;
	haxe__io__Bytes r9;
	kha__korehl__Sound r8;
	hl__types__ArrayDyn r4;
	vdynamic *r3;
	int r5;
	if( r0 == NULL ) hl_null_access();
	r3 = (vdynamic*)hl_dyn_getp((vdynamic*)r0,10018423/*files*/,&$t_dyn);
	r4 = (hl__types__ArrayDyn)hl_dyn_castp(&r3,&$t_dyn,&$t_hl_types_ArrayDyn);
	if( r4 == NULL ) hl_null_access();
	r5 = 0;
	r3 = ((vdynamic* (*)(hl__types__ArrayDyn,int))r4->$type->vobj_proto[0])(r4,r5);
	r6 = (String)r3;
	if( r1 == NULL ) hl_null_access();
	r8 = (kha__korehl__Sound)hl_alloc_obj(&$t_kha_korehl_Sound);
	r9 = NULL;
	kha_korehl_Sound_new(r8,r6,r9);
	r1->hasValue ? ((void (*)(vdynamic*,kha__Sound))r1->fun)((vdynamic*)r1->value,((kha__Sound)r8)) : ((void (*)(kha__Sound))r1->fun)(((kha__Sound)r8));
	return;
}

void kha_LoaderImpl_loadImageFromDescription(vdynamic* r0,vclosure* r1,vclosure* r2) {
	String r5;
	kha__Image r7;
	bool r3;
	hl__types__ArrayDyn r8;
	vdynamic *r4;
	int r9;
	r5 = (String)$s_readable;
	r3 = Reflect_hasField(r0,r5);
	if( !r3 ) goto label$00c322a_2_9;
	if( r0 == NULL ) hl_null_access();
	r4 = (vdynamic*)hl_dyn_getp((vdynamic*)r0,495394175/*readable*/,&$t_dyn);
	r3 = (bool)hl_dyn_casti(&r4,&$t_dyn,&$t_bool);
	if( !r3 ) goto label$00c322a_2_9;
	r3 = true;
	goto label$00c322a_2_10;
	label$00c322a_2_9:
	r3 = false;
	label$00c322a_2_10:
	if( r1 == NULL ) hl_null_access();
	if( r0 == NULL ) hl_null_access();
	r4 = (vdynamic*)hl_dyn_getp((vdynamic*)r0,10018423/*files*/,&$t_dyn);
	r8 = (hl__types__ArrayDyn)hl_dyn_castp(&r4,&$t_dyn,&$t_hl_types_ArrayDyn);
	if( r8 == NULL ) hl_null_access();
	r9 = 0;
	r4 = ((vdynamic* (*)(hl__types__ArrayDyn,int))r8->$type->vobj_proto[0])(r8,r9);
	r5 = (String)r4;
	r7 = kha_Image_fromFile(r5,r3);
	r1->hasValue ? ((void (*)(vdynamic*,kha__Image))r1->fun)((vdynamic*)r1->value,r7) : ((void (*)(kha__Image))r1->fun)(r7);
	return;
}

void kha_LoaderImpl_loadBlobFromDescription(vdynamic* r0,vclosure* r1,vclosure* r2) {
	String r10;
	haxe__io__Bytes r16;
	kha__internal__BytesBlob r15;
	hl__types__ArrayDyn r8;
	int *r11, *r13;
	vdynamic *r7;
	vbyte *r6, *r12, *r14;
	int r3, r5, r9;
	r3 = 0;
	r5 = 0;
	if( r0 == NULL ) hl_null_access();
	r7 = (vdynamic*)hl_dyn_getp((vdynamic*)r0,10018423/*files*/,&$t_dyn);
	r8 = (hl__types__ArrayDyn)hl_dyn_castp(&r7,&$t_dyn,&$t_hl_types_ArrayDyn);
	if( r8 == NULL ) hl_null_access();
	r9 = 0;
	r7 = ((vdynamic* (*)(hl__types__ArrayDyn,int))r8->$type->vobj_proto[0])(r8,r9);
	r10 = (String)r7;
	if( r10 == NULL ) hl_null_access();
	r6 = r10->bytes;
	r11 = &r5;
	r9 = 0;
	r12 = hl_utf16_to_utf8(r6,r9,r11);
	r13 = &r3;
	r14 = hl_kore_file_contents(r12,r13);
	if( r1 == NULL ) hl_null_access();
	r15 = (kha__internal__BytesBlob)hl_alloc_obj(&$t_kha_internal_BytesBlob);
	r16 = (haxe__io__Bytes)hl_alloc_obj(&$t_haxe_io_Bytes);
	haxe_io_Bytes_new(r16,r14,r3);
	kha_internal_BytesBlob_new(r15,r16);
	r1->hasValue ? ((void (*)(vdynamic*,kha__internal__BytesBlob))r1->fun)((vdynamic*)r1->value,r15) : ((void (*)(kha__internal__BytesBlob))r1->fun)(r15);
	return;
}

void kha_LoaderImpl_loadFontFromDescription__$1(vclosure* r0,kha__internal__BytesBlob r1) {
	kha__Kravur r3;
	if( r0 == NULL ) hl_null_access();
	r3 = (kha__Kravur)hl_alloc_obj(&$t_kha_Kravur);
	kha_Kravur_new(r3,r1);
	r0->hasValue ? ((void (*)(vdynamic*,kha__Kravur))r0->fun)((vdynamic*)r0->value,r3) : ((void (*)(kha__Kravur))r0->fun)(r3);
	return;
}

void kha_LoaderImpl_loadFontFromDescription(vdynamic* r0,vclosure* r1,vclosure* r2) {
	vclosure *r4;
	r4 = hl_alloc_closure_ptr(&$t_fun_11ee11d,kha_LoaderImpl_loadFontFromDescription__$1,r1);
	kha_LoaderImpl_loadBlobFromDescription(r0,r4,r2);
	return;
}

