// Generated by HLC 4.0.0 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <kha/Scheduler.h>
#include <kha/FrameTask.h>
extern hl_type $t_kha_FrameTask;
extern hl_type $t_dyn;
extern hl_type $t_hl_types_ArrayBytes_Float;
void hl_types_ArrayBytes_Float_new(hl__types__ArrayBytes_Float);
extern kha__$Scheduler $g__kha_Scheduler;
void hl_types_ArrayBytes_Float___expand(hl__types__ArrayBytes_Float,int);
double kha_Scheduler_realTime(void);
extern hl_type $t_kha_TimeTask;
#include <hl/natives.h>
hl__types__ArrayObj hl_types_ArrayObj_alloc(varray*);
#include <kha/Window.h>
#include <kha/Display.h>
kha__Window kha_Window_get(int);
bool kha_Window_get_vSynced(kha__Window);
kha__Display kha_Display_get_primary(void);
int kha_Display_get_frequency(kha__Display);
void kha_Scheduler_resetTime(void);
#include <kha/netsync/Session.h>
kha__netsync__Session kha_netsync_Session_the(void);
void kha_Scheduler_executeTimeTasks(double);
int hl_types_ArrayObj_push(hl__types__ArrayObj,vdynamic*);
bool hl_types_ArrayObj_remove(hl__types__ArrayObj,vdynamic*);
void kha_Scheduler_sortFrameTasks(void);
vdynamic* hl_types_ArrayObj_pop(hl__types__ArrayObj);
void kha_Scheduler_insertSorted(hl__types__ArrayObj,kha__TimeTask);
void kha_Scheduler_archiveTimeTask(kha__TimeTask,double);
double kha_System_get_time(void);
void kha_TimeTask_new(kha__TimeTask);
bool kha_Scheduler_addTimeTaskToGroup__$1(vclosure*);
extern hl_type $t_fun_3c2375f;
void hl_types_ArrayObj_insert(hl__types__ArrayObj,int,vdynamic*);
extern hl_type $t_fun_5ae4454;
extern hl_type $t_fun_dee1a83;
void hl_types_ArrayObj_sort(hl__types__ArrayObj,vclosure*);

int kha_Scheduler_sortFrameTasks__$2(vclosure* r0,vdynamic* r1,vdynamic* r2) {
	int r5;
	kha__FrameTask r3, r4;
	r3 = (kha__FrameTask)hl_dyn_castp(&r1,&$t_dyn,&$t_kha_FrameTask);
	r4 = (kha__FrameTask)hl_dyn_castp(&r2,&$t_dyn,&$t_kha_FrameTask);
	r5 = r0->hasValue ? ((int (*)(vdynamic*,kha__FrameTask,kha__FrameTask))r0->fun)((vdynamic*)r0->value,r3,r4) : ((int (*)(kha__FrameTask,kha__FrameTask))r0->fun)(r3,r4);
	return r5;
}

void kha_Scheduler_init() {
	hl__types__ArrayObj r10;
	hl_type *r12;
	bool r9;
	kha__$Scheduler r2;
	hl__types__ArrayBytes_Float r0;
	double r6;
	varray *r11;
	vbyte *r8;
	int r3, r4, r5, r7;
	r0 = (hl__types__ArrayBytes_Float)hl_alloc_obj(&$t_hl_types_ArrayBytes_Float);
	hl_types_ArrayBytes_Float_new(r0);
	r2 = (kha__$Scheduler)$g__kha_Scheduler;
	r2->deltas = r0;
	r3 = 0;
	r2 = (kha__$Scheduler)$g__kha_Scheduler;
	r4 = r2->DIF_COUNT;
	label$fe4f13c_2_7:
	if( r3 >= r4 ) goto label$fe4f13c_2_23;
	r5 = r3;
	++r3;
	r2 = (kha__$Scheduler)$g__kha_Scheduler;
	r0 = r2->deltas;
	if( r0 == NULL ) hl_null_access();
	r6 = 0.;
	r7 = r0->length;
	if( ((unsigned)r5) < ((unsigned)r7) ) goto label$fe4f13c_2_18;
	hl_types_ArrayBytes_Float___expand(r0,r5);
	label$fe4f13c_2_18:
	r8 = r0->bytes;
	r7 = 3;
	r7 = r5 << r7;
	*(double*)(r8 + r7) = r6;
	goto label$fe4f13c_2_7;
	label$fe4f13c_2_23:
	r9 = true;
	r2 = (kha__$Scheduler)$g__kha_Scheduler;
	r2->stopped = r9;
	r9 = true;
	r2 = (kha__$Scheduler)$g__kha_Scheduler;
	r2->frame_tasks_sorted = r9;
	r6 = kha_Scheduler_realTime();
	r2 = (kha__$Scheduler)$g__kha_Scheduler;
	r2->lastTime = r6;
	r2 = (kha__$Scheduler)$g__kha_Scheduler;
	r2->current = r6;
	r3 = 0;
	r2 = (kha__$Scheduler)$g__kha_Scheduler;
	r2->currentFrameTaskId = r3;
	r3 = 0;
	r2 = (kha__$Scheduler)$g__kha_Scheduler;
	r2->currentTimeTaskId = r3;
	r3 = 0;
	r2 = (kha__$Scheduler)$g__kha_Scheduler;
	r2->currentGroupId = r3;
	r12 = &$t_kha_TimeTask;
	r3 = 0;
	r11 = hl_alloc_array(r12,r3);
	r10 = hl_types_ArrayObj_alloc(r11);
	r2 = (kha__$Scheduler)$g__kha_Scheduler;
	r2->timeTasks = r10;
	r12 = &$t_kha_TimeTask;
	r3 = 0;
	r11 = hl_alloc_array(r12,r3);
	r10 = hl_types_ArrayObj_alloc(r11);
	r2 = (kha__$Scheduler)$g__kha_Scheduler;
	r2->pausedTimeTasks = r10;
	r12 = &$t_kha_TimeTask;
	r3 = 0;
	r11 = hl_alloc_array(r12,r3);
	r10 = hl_types_ArrayObj_alloc(r11);
	r2 = (kha__$Scheduler)$g__kha_Scheduler;
	r2->outdatedTimeTasks = r10;
	r12 = &$t_kha_TimeTask;
	r3 = 0;
	r11 = hl_alloc_array(r12,r3);
	r10 = hl_types_ArrayObj_alloc(r11);
	r2 = (kha__$Scheduler)$g__kha_Scheduler;
	r2->timeTasksScratchpad = r10;
	r12 = &$t_kha_FrameTask;
	r3 = 0;
	r11 = hl_alloc_array(r12,r3);
	r10 = hl_types_ArrayObj_alloc(r11);
	r2 = (kha__$Scheduler)$g__kha_Scheduler;
	r2->frameTasks = r10;
	r12 = &$t_kha_FrameTask;
	r3 = 0;
	r11 = hl_alloc_array(r12,r3);
	r10 = hl_types_ArrayObj_alloc(r11);
	r2 = (kha__$Scheduler)$g__kha_Scheduler;
	r2->toDeleteFrame = r10;
	return;
}

void kha_Scheduler_start(bool* r0) {
	hl__types__ArrayObj r16;
	kha__$Scheduler r5;
	bool r1, r2;
	kha__Display r6;
	kha__Window r3;
	kha__TimeTask r17;
	hl__types__ArrayBytes_Float r13;
	double r10, r11;
	vdynamic *r18;
	kha__FrameTask r20;
	varray *r19;
	vbyte *r15;
	int r4, r8, r9, r12, r14;
	if( r0 ) goto label$fe4f13c_3_3;
	r1 = false;
	goto label$fe4f13c_3_4;
	label$fe4f13c_3_3:
	r1 = *r0;
	label$fe4f13c_3_4:
	r4 = 0;
	r3 = kha_Window_get(r4);
	if( r3 == NULL ) hl_null_access();
	r2 = kha_Window_get_vSynced(r3);
	r5 = (kha__$Scheduler)$g__kha_Scheduler;
	r5->vsync = r2;
	r6 = kha_Display_get_primary();
	if( r6 == NULL ) hl_null_access();
	r4 = kha_Display_get_frequency(r6);
	r9 = 57;
	if( r4 < r9 ) goto label$fe4f13c_3_19;
	r9 = 63;
	if( r9 < r4 ) goto label$fe4f13c_3_19;
	r8 = 60;
	r4 = r8;
	label$fe4f13c_3_19:
	r10 = 1.;
	r11 = (double)r4;
	r10 = r10 / r11;
	r5 = (kha__$Scheduler)$g__kha_Scheduler;
	r5->onedifhz = r10;
	r2 = false;
	r5 = (kha__$Scheduler)$g__kha_Scheduler;
	r5->stopped = r2;
	kha_Scheduler_resetTime();
	r10 = kha_Scheduler_realTime();
	r5 = (kha__$Scheduler)$g__kha_Scheduler;
	r11 = r5->startTime;
	r10 = r10 - r11;
	r5 = (kha__$Scheduler)$g__kha_Scheduler;
	r5->lastTime = r10;
	r8 = 0;
	r5 = (kha__$Scheduler)$g__kha_Scheduler;
	r9 = r5->DIF_COUNT;
	label$fe4f13c_3_37:
	if( r8 >= r9 ) goto label$fe4f13c_3_53;
	r12 = r8;
	++r8;
	r5 = (kha__$Scheduler)$g__kha_Scheduler;
	r13 = r5->deltas;
	if( r13 == NULL ) hl_null_access();
	r10 = 0.;
	r14 = r13->length;
	if( ((unsigned)r12) < ((unsigned)r14) ) goto label$fe4f13c_3_48;
	hl_types_ArrayBytes_Float___expand(r13,r12);
	label$fe4f13c_3_48:
	r15 = r13->bytes;
	r14 = 3;
	r14 = r12 << r14;
	*(double*)(r15 + r14) = r10;
	goto label$fe4f13c_3_37;
	label$fe4f13c_3_53:
	if( !r1 ) goto label$fe4f13c_3_92;
	r8 = 0;
	r5 = (kha__$Scheduler)$g__kha_Scheduler;
	r16 = r5->timeTasks;
	label$fe4f13c_3_57:
	if( r16 == NULL ) hl_null_access();
	r12 = r16->length;
	if( r8 >= r12 ) goto label$fe4f13c_3_73;
	r12 = r16->length;
	if( ((unsigned)r8) < ((unsigned)r12) ) goto label$fe4f13c_3_65;
	r17 = NULL;
	goto label$fe4f13c_3_68;
	label$fe4f13c_3_65:
	r19 = r16->array;
	r18 = ((vdynamic**)(r19 + 1))[r8];
	r17 = (kha__TimeTask)r18;
	label$fe4f13c_3_68:
	++r8;
	if( r17 == NULL ) hl_null_access();
	r2 = false;
	r17->paused = r2;
	goto label$fe4f13c_3_57;
	label$fe4f13c_3_73:
	r8 = 0;
	r5 = (kha__$Scheduler)$g__kha_Scheduler;
	r16 = r5->frameTasks;
	label$fe4f13c_3_76:
	if( r16 == NULL ) hl_null_access();
	r12 = r16->length;
	if( r8 >= r12 ) goto label$fe4f13c_3_92;
	r12 = r16->length;
	if( ((unsigned)r8) < ((unsigned)r12) ) goto label$fe4f13c_3_84;
	r20 = NULL;
	goto label$fe4f13c_3_87;
	label$fe4f13c_3_84:
	r19 = r16->array;
	r18 = ((vdynamic**)(r19 + 1))[r8];
	r20 = (kha__FrameTask)r18;
	label$fe4f13c_3_87:
	++r8;
	if( r20 == NULL ) hl_null_access();
	r2 = false;
	r20->paused = r2;
	goto label$fe4f13c_3_76;
	label$fe4f13c_3_92:
	return;
}

void kha_Scheduler_executeFrame() {
	hl__types__ArrayObj r20, r21;
	bool r10;
	kha__netsync__Session r7;
	kha__$Scheduler r2, r9;
	kha__TimeTask r22;
	hl__types__ArrayBytes_Float r15, r18;
	vclosure *r26;
	double r0, r1, r4, r5, r6, r8, r11;
	vdynamic *r23;
	kha__FrameTask r25;
	varray *r24;
	vbyte *r17;
	int r12, r13, r14, r16, r19;
	r0 = kha_Scheduler_realTime();
	r2 = (kha__$Scheduler)$g__kha_Scheduler;
	r1 = r2->startTime;
	r0 = r0 - r1;
	r2 = (kha__$Scheduler)$g__kha_Scheduler;
	r4 = r2->lastTime;
	r1 = r0 - r4;
	r2 = (kha__$Scheduler)$g__kha_Scheduler;
	r4 = r2->current;
	r6 = 0.;
	if( !(r1 >= r6) ) goto label$fe4f13c_4_327;
	r7 = kha_netsync_Session_the();
	if( r7 ) goto label$fe4f13c_4_206;
	r2 = (kha__$Scheduler)$g__kha_Scheduler;
	r6 = r2->maxframetime;
	if( !(r6 < r1) ) goto label$fe4f13c_4_29;
	r2 = (kha__$Scheduler)$g__kha_Scheduler;
	r5 = r2->startTime;
	r9 = (kha__$Scheduler)$g__kha_Scheduler;
	r8 = r9->maxframetime;
	r6 = r1 - r8;
	r5 = r5 + r6;
	r2->startTime = r5;
	r2 = (kha__$Scheduler)$g__kha_Scheduler;
	r5 = r2->maxframetime;
	r1 = r5;
	r5 = r4 + r1;
	r4 = r5;
	goto label$fe4f13c_4_205;
	label$fe4f13c_4_29:
	r2 = (kha__$Scheduler)$g__kha_Scheduler;
	r10 = r2->vsync;
	if( !r10 ) goto label$fe4f13c_4_129;
	r2 = (kha__$Scheduler)$g__kha_Scheduler;
	r5 = r2->onedifhz;
	label$fe4f13c_4_34:
	r2 = (kha__$Scheduler)$g__kha_Scheduler;
	r11 = r2->onedifhz;
	r8 = r1 - r11;
	if( !(r5 < r8) ) goto label$fe4f13c_4_44;
	r2 = (kha__$Scheduler)$g__kha_Scheduler;
	r8 = r2->onedifhz;
	r6 = r5 + r8;
	r5 = r6;
	goto label$fe4f13c_4_34;
	label$fe4f13c_4_44:
	r1 = r5;
	r12 = 0;
	r2 = (kha__$Scheduler)$g__kha_Scheduler;
	r13 = r2->DIF_COUNT;
	r14 = 2;
	r13 = r13 - r14;
	label$fe4f13c_4_50:
	if( r12 >= r13 ) goto label$fe4f13c_4_91;
	r14 = r12;
	++r12;
	r2 = (kha__$Scheduler)$g__kha_Scheduler;
	r15 = r2->deltas;
	if( r15 == NULL ) hl_null_access();
	r16 = r15->length;
	if( ((unsigned)r14) < ((unsigned)r16) ) goto label$fe4f13c_4_61;
	r8 = 0.;
	goto label$fe4f13c_4_65;
	label$fe4f13c_4_61:
	r17 = r15->bytes;
	r16 = 3;
	r16 = r14 << r16;
	r8 = *(double*)(r17 + r16);
	label$fe4f13c_4_65:
	r6 = r1 + r8;
	r1 = r6;
	r2 = (kha__$Scheduler)$g__kha_Scheduler;
	r15 = r2->deltas;
	if( r15 == NULL ) hl_null_access();
	r2 = (kha__$Scheduler)$g__kha_Scheduler;
	r18 = r2->deltas;
	if( r18 == NULL ) hl_null_access();
	r19 = 1;
	r16 = r14 + r19;
	r19 = r18->length;
	if( ((unsigned)r16) < ((unsigned)r19) ) goto label$fe4f13c_4_79;
	r6 = 0.;
	goto label$fe4f13c_4_83;
	label$fe4f13c_4_79:
	r17 = r18->bytes;
	r19 = 3;
	r19 = r16 << r19;
	r6 = *(double*)(r17 + r19);
	label$fe4f13c_4_83:
	r16 = r15->length;
	if( ((unsigned)r14) < ((unsigned)r16) ) goto label$fe4f13c_4_86;
	hl_types_ArrayBytes_Float___expand(r15,r14);
	label$fe4f13c_4_86:
	r17 = r15->bytes;
	r16 = 3;
	r16 = r14 << r16;
	*(double*)(r17 + r16) = r6;
	goto label$fe4f13c_4_50;
	label$fe4f13c_4_91:
	r2 = (kha__$Scheduler)$g__kha_Scheduler;
	r15 = r2->deltas;
	if( r15 == NULL ) hl_null_access();
	r2 = (kha__$Scheduler)$g__kha_Scheduler;
	r12 = r2->DIF_COUNT;
	r13 = 2;
	r12 = r12 - r13;
	r13 = r15->length;
	if( ((unsigned)r12) < ((unsigned)r13) ) goto label$fe4f13c_4_102;
	r8 = 0.;
	goto label$fe4f13c_4_106;
	label$fe4f13c_4_102:
	r17 = r15->bytes;
	r13 = 3;
	r13 = r12 << r13;
	r8 = *(double*)(r17 + r13);
	label$fe4f13c_4_106:
	r6 = r1 + r8;
	r2 = (kha__$Scheduler)$g__kha_Scheduler;
	r12 = r2->DIF_COUNT;
	r8 = (double)r12;
	r6 = r6 / r8;
	r1 = r6;
	r2 = (kha__$Scheduler)$g__kha_Scheduler;
	r15 = r2->deltas;
	if( r15 == NULL ) hl_null_access();
	r2 = (kha__$Scheduler)$g__kha_Scheduler;
	r12 = r2->DIF_COUNT;
	r13 = 2;
	r12 = r12 - r13;
	r13 = r15->length;
	if( ((unsigned)r12) < ((unsigned)r13) ) goto label$fe4f13c_4_122;
	hl_types_ArrayBytes_Float___expand(r15,r12);
	label$fe4f13c_4_122:
	r17 = r15->bytes;
	r13 = 3;
	r13 = r12 << r13;
	*(double*)(r17 + r13) = r5;
	r6 = r4 + r1;
	r4 = r6;
	goto label$fe4f13c_4_205;
	label$fe4f13c_4_129:
	r12 = 0;
	r2 = (kha__$Scheduler)$g__kha_Scheduler;
	r13 = r2->DIF_COUNT;
	r14 = 1;
	r13 = r13 - r14;
	label$fe4f13c_4_134:
	if( r12 >= r13 ) goto label$fe4f13c_4_162;
	r14 = r12;
	++r12;
	r2 = (kha__$Scheduler)$g__kha_Scheduler;
	r15 = r2->deltas;
	if( r15 == NULL ) hl_null_access();
	r2 = (kha__$Scheduler)$g__kha_Scheduler;
	r18 = r2->deltas;
	if( r18 == NULL ) hl_null_access();
	r19 = 1;
	r16 = r14 + r19;
	r19 = r18->length;
	if( ((unsigned)r16) < ((unsigned)r19) ) goto label$fe4f13c_4_150;
	r5 = 0.;
	goto label$fe4f13c_4_154;
	label$fe4f13c_4_150:
	r17 = r18->bytes;
	r19 = 3;
	r19 = r16 << r19;
	r5 = *(double*)(r17 + r19);
	label$fe4f13c_4_154:
	r16 = r15->length;
	if( ((unsigned)r14) < ((unsigned)r16) ) goto label$fe4f13c_4_157;
	hl_types_ArrayBytes_Float___expand(r15,r14);
	label$fe4f13c_4_157:
	r17 = r15->bytes;
	r16 = 3;
	r16 = r14 << r16;
	*(double*)(r17 + r16) = r5;
	goto label$fe4f13c_4_134;
	label$fe4f13c_4_162:
	r2 = (kha__$Scheduler)$g__kha_Scheduler;
	r15 = r2->deltas;
	if( r15 == NULL ) hl_null_access();
	r2 = (kha__$Scheduler)$g__kha_Scheduler;
	r12 = r2->DIF_COUNT;
	r13 = 1;
	r12 = r12 - r13;
	r13 = r15->length;
	if( ((unsigned)r12) < ((unsigned)r13) ) goto label$fe4f13c_4_172;
	hl_types_ArrayBytes_Float___expand(r15,r12);
	label$fe4f13c_4_172:
	r17 = r15->bytes;
	r13 = 3;
	r13 = r12 << r13;
	*(double*)(r17 + r13) = r1;
	r5 = 0.;
	r12 = 0;
	r2 = (kha__$Scheduler)$g__kha_Scheduler;
	r13 = r2->DIF_COUNT;
	label$fe4f13c_4_180:
	if( r12 >= r13 ) goto label$fe4f13c_4_198;
	r14 = r12;
	++r12;
	r2 = (kha__$Scheduler)$g__kha_Scheduler;
	r15 = r2->deltas;
	if( r15 == NULL ) hl_null_access();
	r16 = r15->length;
	if( ((unsigned)r14) < ((unsigned)r16) ) goto label$fe4f13c_4_191;
	r8 = 0.;
	goto label$fe4f13c_4_195;
	label$fe4f13c_4_191:
	r17 = r15->bytes;
	r16 = 3;
	r16 = r14 << r16;
	r8 = *(double*)(r17 + r16);
	label$fe4f13c_4_195:
	r6 = r5 + r8;
	r5 = r6;
	goto label$fe4f13c_4_180;
	label$fe4f13c_4_198:
	r2 = (kha__$Scheduler)$g__kha_Scheduler;
	r12 = r2->DIF_COUNT;
	r8 = (double)r12;
	r6 = r5 / r8;
	r5 = r6;
	r6 = r4 + r5;
	r4 = r6;
	label$fe4f13c_4_205:
	goto label$fe4f13c_4_208;
	label$fe4f13c_4_206:
	r5 = r4 + r1;
	r4 = r5;
	label$fe4f13c_4_208:
	r2 = (kha__$Scheduler)$g__kha_Scheduler;
	r2->lastTime = r4;
	r2 = (kha__$Scheduler)$g__kha_Scheduler;
	r10 = r2->stopped;
	if( r10 ) goto label$fe4f13c_4_215;
	r2 = (kha__$Scheduler)$g__kha_Scheduler;
	r2->current = r4;
	label$fe4f13c_4_215:
	r12 = 0;
	r2 = (kha__$Scheduler)$g__kha_Scheduler;
	r20 = r2->pausedTimeTasks;
	label$fe4f13c_4_218:
	if( r20 == NULL ) hl_null_access();
	r14 = r20->length;
	if( r12 >= r14 ) goto label$fe4f13c_4_235;
	r14 = r20->length;
	if( ((unsigned)r12) < ((unsigned)r14) ) goto label$fe4f13c_4_226;
	r22 = NULL;
	goto label$fe4f13c_4_229;
	label$fe4f13c_4_226:
	r24 = r20->array;
	r23 = ((vdynamic**)(r24 + 1))[r12];
	r22 = (kha__TimeTask)r23;
	label$fe4f13c_4_229:
	++r12;
	if( r22 == NULL ) hl_null_access();
	r5 = r22->next;
	r5 = r5 + r1;
	r22->next = r5;
	goto label$fe4f13c_4_218;
	label$fe4f13c_4_235:
	r2 = (kha__$Scheduler)$g__kha_Scheduler;
	r10 = r2->stopped;
	if( !r10 ) goto label$fe4f13c_4_258;
	r12 = 0;
	r2 = (kha__$Scheduler)$g__kha_Scheduler;
	r20 = r2->timeTasks;
	label$fe4f13c_4_241:
	if( r20 == NULL ) hl_null_access();
	r14 = r20->length;
	if( r12 >= r14 ) goto label$fe4f13c_4_258;
	r14 = r20->length;
	if( ((unsigned)r12) < ((unsigned)r14) ) goto label$fe4f13c_4_249;
	r22 = NULL;
	goto label$fe4f13c_4_252;
	label$fe4f13c_4_249:
	r24 = r20->array;
	r23 = ((vdynamic**)(r24 + 1))[r12];
	r22 = (kha__TimeTask)r23;
	label$fe4f13c_4_252:
	++r12;
	if( r22 == NULL ) hl_null_access();
	r5 = r22->next;
	r5 = r5 + r1;
	r22->next = r5;
	goto label$fe4f13c_4_241;
	label$fe4f13c_4_258:
	kha_Scheduler_executeTimeTasks(r4);
	r12 = 0;
	r2 = (kha__$Scheduler)$g__kha_Scheduler;
	r20 = r2->outdatedTimeTasks;
	label$fe4f13c_4_262:
	if( r20 == NULL ) hl_null_access();
	r14 = r20->length;
	if( r12 >= r14 ) goto label$fe4f13c_4_284;
	r14 = r20->length;
	if( ((unsigned)r12) < ((unsigned)r14) ) goto label$fe4f13c_4_270;
	r22 = NULL;
	goto label$fe4f13c_4_273;
	label$fe4f13c_4_270:
	r24 = r20->array;
	r23 = ((vdynamic**)(r24 + 1))[r12];
	r22 = (kha__TimeTask)r23;
	label$fe4f13c_4_273:
	++r12;
	if( r22 == NULL ) hl_null_access();
	r5 = r22->next;
	r8 = 10.;
	r6 = r4 - r8;
	if( !(r5 < r6) ) goto label$fe4f13c_4_283;
	r2 = (kha__$Scheduler)$g__kha_Scheduler;
	r21 = r2->timeTasksScratchpad;
	if( r21 == NULL ) hl_null_access();
	r13 = hl_types_ArrayObj_push(r21,((vdynamic*)r22));
	label$fe4f13c_4_283:
	goto label$fe4f13c_4_262;
	label$fe4f13c_4_284:
	r12 = 0;
	r2 = (kha__$Scheduler)$g__kha_Scheduler;
	r20 = r2->timeTasksScratchpad;
	label$fe4f13c_4_287:
	if( r20 == NULL ) hl_null_access();
	r14 = r20->length;
	if( r12 >= r14 ) goto label$fe4f13c_4_304;
	r14 = r20->length;
	if( ((unsigned)r12) < ((unsigned)r14) ) goto label$fe4f13c_4_295;
	r22 = NULL;
	goto label$fe4f13c_4_298;
	label$fe4f13c_4_295:
	r24 = r20->array;
	r23 = ((vdynamic**)(r24 + 1))[r12];
	r22 = (kha__TimeTask)r23;
	label$fe4f13c_4_298:
	++r12;
	r2 = (kha__$Scheduler)$g__kha_Scheduler;
	r21 = r2->outdatedTimeTasks;
	if( r21 == NULL ) hl_null_access();
	r10 = hl_types_ArrayObj_remove(r21,((vdynamic*)r22));
	goto label$fe4f13c_4_287;
	label$fe4f13c_4_304:
	r2 = (kha__$Scheduler)$g__kha_Scheduler;
	r20 = r2->timeTasksScratchpad;
	if( r20 == NULL ) hl_null_access();
	r12 = r20->length;
	r13 = 0;
	if( r13 >= r12 ) goto label$fe4f13c_4_327;
	r2 = (kha__$Scheduler)$g__kha_Scheduler;
	r20 = r2->timeTasksScratchpad;
	if( r20 == NULL ) hl_null_access();
	r2 = (kha__$Scheduler)$g__kha_Scheduler;
	r21 = r2->timeTasksScratchpad;
	if( r21 == NULL ) hl_null_access();
	r12 = 0;
	r13 = r21->length;
	if( ((unsigned)r12) < ((unsigned)r13) ) goto label$fe4f13c_4_322;
	r22 = NULL;
	goto label$fe4f13c_4_325;
	label$fe4f13c_4_322:
	r24 = r21->array;
	r23 = ((vdynamic**)(r24 + 1))[r12];
	r22 = (kha__TimeTask)r23;
	label$fe4f13c_4_325:
	r10 = hl_types_ArrayObj_remove(r20,((vdynamic*)r22));
	goto label$fe4f13c_4_304;
	label$fe4f13c_4_327:
	kha_Scheduler_sortFrameTasks();
	r12 = 0;
	r2 = (kha__$Scheduler)$g__kha_Scheduler;
	r20 = r2->frameTasks;
	label$fe4f13c_4_331:
	if( r20 == NULL ) hl_null_access();
	r14 = r20->length;
	if( r12 >= r14 ) goto label$fe4f13c_4_358;
	r14 = r20->length;
	if( ((unsigned)r12) < ((unsigned)r14) ) goto label$fe4f13c_4_339;
	r25 = NULL;
	goto label$fe4f13c_4_342;
	label$fe4f13c_4_339:
	r24 = r20->array;
	r23 = ((vdynamic**)(r24 + 1))[r12];
	r25 = (kha__FrameTask)r23;
	label$fe4f13c_4_342:
	++r12;
	r2 = (kha__$Scheduler)$g__kha_Scheduler;
	r10 = r2->stopped;
	if( r10 ) goto label$fe4f13c_4_357;
	if( r25 == NULL ) hl_null_access();
	r10 = r25->paused;
	if( r10 ) goto label$fe4f13c_4_357;
	r10 = r25->active;
	if( !r10 ) goto label$fe4f13c_4_357;
	r26 = r25->task;
	if( r26 == NULL ) hl_null_access();
	r10 = r26->hasValue ? ((bool (*)(vdynamic*))r26->fun)((vdynamic*)r26->value) : ((bool (*)(void))r26->fun)();
	if( r10 ) goto label$fe4f13c_4_357;
	r10 = false;
	r25->active = r10;
	label$fe4f13c_4_357:
	goto label$fe4f13c_4_331;
	label$fe4f13c_4_358:
	r12 = 0;
	r2 = (kha__$Scheduler)$g__kha_Scheduler;
	r20 = r2->frameTasks;
	label$fe4f13c_4_361:
	if( r20 == NULL ) hl_null_access();
	r14 = r20->length;
	if( r12 >= r14 ) goto label$fe4f13c_4_381;
	r14 = r20->length;
	if( ((unsigned)r12) < ((unsigned)r14) ) goto label$fe4f13c_4_369;
	r25 = NULL;
	goto label$fe4f13c_4_372;
	label$fe4f13c_4_369:
	r24 = r20->array;
	r23 = ((vdynamic**)(r24 + 1))[r12];
	r25 = (kha__FrameTask)r23;
	label$fe4f13c_4_372:
	++r12;
	if( r25 == NULL ) hl_null_access();
	r10 = r25->active;
	if( r10 ) goto label$fe4f13c_4_380;
	r2 = (kha__$Scheduler)$g__kha_Scheduler;
	r21 = r2->toDeleteFrame;
	if( r21 == NULL ) hl_null_access();
	r13 = hl_types_ArrayObj_push(r21,((vdynamic*)r25));
	label$fe4f13c_4_380:
	goto label$fe4f13c_4_361;
	label$fe4f13c_4_381:
	r2 = (kha__$Scheduler)$g__kha_Scheduler;
	r20 = r2->toDeleteFrame;
	if( r20 == NULL ) hl_null_access();
	r12 = r20->length;
	r13 = 0;
	if( r13 >= r12 ) goto label$fe4f13c_4_398;
	r2 = (kha__$Scheduler)$g__kha_Scheduler;
	r20 = r2->frameTasks;
	if( r20 == NULL ) hl_null_access();
	r2 = (kha__$Scheduler)$g__kha_Scheduler;
	r21 = r2->toDeleteFrame;
	if( r21 == NULL ) hl_null_access();
	r23 = hl_types_ArrayObj_pop(r21);
	r25 = (kha__FrameTask)r23;
	r10 = hl_types_ArrayObj_remove(r20,((vdynamic*)r25));
	goto label$fe4f13c_4_381;
	label$fe4f13c_4_398:
	return;
}

void kha_Scheduler_executeTimeTasks(double r0) {
	hl__types__ArrayObj r2;
	bool r12;
	kha__$Scheduler r3;
	kha__TimeTask r5, r11;
	vclosure *r13;
	double r9, r10, r14;
	vdynamic *r6;
	varray *r7;
	int r1, r4;
	label$fe4f13c_5_0:
	r3 = (kha__$Scheduler)$g__kha_Scheduler;
	r2 = r3->timeTasks;
	if( r2 == NULL ) hl_null_access();
	r1 = r2->length;
	r4 = 0;
	if( r4 >= r1 ) goto label$fe4f13c_5_100;
	r3 = (kha__$Scheduler)$g__kha_Scheduler;
	r2 = r3->timeTasks;
	if( r2 == NULL ) hl_null_access();
	r1 = 0;
	r4 = r2->length;
	if( ((unsigned)r1) < ((unsigned)r4) ) goto label$fe4f13c_5_15;
	r5 = NULL;
	goto label$fe4f13c_5_18;
	label$fe4f13c_5_15:
	r7 = r2->array;
	r6 = ((vdynamic**)(r7 + 1))[r1];
	r5 = (kha__TimeTask)r6;
	label$fe4f13c_5_18:
	r3 = (kha__$Scheduler)$g__kha_Scheduler;
	r3->activeTimeTask = r5;
	r3 = (kha__$Scheduler)$g__kha_Scheduler;
	r5 = r3->activeTimeTask;
	if( r5 == NULL ) hl_null_access();
	r9 = r5->next;
	if( !(r0 >= r9) ) goto label$fe4f13c_5_98;
	r3 = (kha__$Scheduler)$g__kha_Scheduler;
	r5 = r3->activeTimeTask;
	if( r5 == NULL ) hl_null_access();
	r9 = r5->next;
	r3 = (kha__$Scheduler)$g__kha_Scheduler;
	r11 = r3->activeTimeTask;
	if( r11 == NULL ) hl_null_access();
	r10 = r11->period;
	r9 = r9 + r10;
	r5->next = r9;
	r3 = (kha__$Scheduler)$g__kha_Scheduler;
	r2 = r3->timeTasks;
	if( r2 == NULL ) hl_null_access();
	r3 = (kha__$Scheduler)$g__kha_Scheduler;
	r5 = r3->activeTimeTask;
	r12 = hl_types_ArrayObj_remove(r2,((vdynamic*)r5));
	r3 = (kha__$Scheduler)$g__kha_Scheduler;
	r5 = r3->activeTimeTask;
	if( r5 == NULL ) hl_null_access();
	r12 = r5->active;
	if( !r12 ) goto label$fe4f13c_5_89;
	r3 = (kha__$Scheduler)$g__kha_Scheduler;
	r5 = r3->activeTimeTask;
	if( r5 == NULL ) hl_null_access();
	r13 = r5->task;
	if( r13 == NULL ) hl_null_access();
	r12 = r13->hasValue ? ((bool (*)(vdynamic*))r13->fun)((vdynamic*)r13->value) : ((bool (*)(void))r13->fun)();
	if( !r12 ) goto label$fe4f13c_5_89;
	r3 = (kha__$Scheduler)$g__kha_Scheduler;
	r5 = r3->activeTimeTask;
	if( r5 == NULL ) hl_null_access();
	r9 = r5->period;
	r10 = 0.;
	if( !(r10 < r9) ) goto label$fe4f13c_5_85;
	r3 = (kha__$Scheduler)$g__kha_Scheduler;
	r5 = r3->activeTimeTask;
	if( r5 == NULL ) hl_null_access();
	r9 = r5->duration;
	r10 = 0.;
	if( r9 == r10 ) goto label$fe4f13c_5_79;
	r3 = (kha__$Scheduler)$g__kha_Scheduler;
	r5 = r3->activeTimeTask;
	if( r5 == NULL ) hl_null_access();
	r9 = r5->duration;
	r3 = (kha__$Scheduler)$g__kha_Scheduler;
	r5 = r3->activeTimeTask;
	if( r5 == NULL ) hl_null_access();
	r10 = r5->start;
	r3 = (kha__$Scheduler)$g__kha_Scheduler;
	r5 = r3->activeTimeTask;
	if( r5 == NULL ) hl_null_access();
	r14 = r5->next;
	r10 = r10 + r14;
	if( !(r9 >= r10) ) goto label$fe4f13c_5_85;
	label$fe4f13c_5_79:
	r3 = (kha__$Scheduler)$g__kha_Scheduler;
	r2 = r3->timeTasks;
	r3 = (kha__$Scheduler)$g__kha_Scheduler;
	r5 = r3->activeTimeTask;
	kha_Scheduler_insertSorted(r2,r5);
	goto label$fe4f13c_5_88;
	label$fe4f13c_5_85:
	r3 = (kha__$Scheduler)$g__kha_Scheduler;
	r5 = r3->activeTimeTask;
	kha_Scheduler_archiveTimeTask(r5,r0);
	label$fe4f13c_5_88:
	goto label$fe4f13c_5_97;
	label$fe4f13c_5_89:
	r3 = (kha__$Scheduler)$g__kha_Scheduler;
	r5 = r3->activeTimeTask;
	if( r5 == NULL ) hl_null_access();
	r12 = false;
	r5->active = r12;
	r3 = (kha__$Scheduler)$g__kha_Scheduler;
	r5 = r3->activeTimeTask;
	kha_Scheduler_archiveTimeTask(r5,r0);
	label$fe4f13c_5_97:
	goto label$fe4f13c_5_99;
	label$fe4f13c_5_98:
	goto label$fe4f13c_5_100;
	label$fe4f13c_5_99:
	goto label$fe4f13c_5_0;
	label$fe4f13c_5_100:
	r5 = NULL;
	r3 = (kha__$Scheduler)$g__kha_Scheduler;
	r3->activeTimeTask = r5;
	return;
}

void kha_Scheduler_archiveTimeTask(kha__TimeTask r0,double r1) {
	return;
}

double kha_Scheduler_time() {
	kha__$Scheduler r1;
	double r0;
	r1 = (kha__$Scheduler)$g__kha_Scheduler;
	r0 = r1->current;
	return r0;
}

double kha_Scheduler_realTime() {
	double r0;
	r0 = kha_System_get_time();
	return r0;
}

void kha_Scheduler_resetTime() {
	hl__types__ArrayObj r6;
	kha__$Scheduler r4;
	hl__types__ArrayBytes_Float r12;
	kha__TimeTask r9;
	double r0, r2, r3;
	vdynamic *r10;
	vbyte *r14;
	varray *r11;
	int r5, r7, r8, r13;
	r0 = kha_System_get_time();
	r4 = (kha__$Scheduler)$g__kha_Scheduler;
	r3 = r4->startTime;
	r2 = r0 - r3;
	r4 = (kha__$Scheduler)$g__kha_Scheduler;
	r4->startTime = r0;
	r5 = 0;
	r4 = (kha__$Scheduler)$g__kha_Scheduler;
	r6 = r4->timeTasks;
	label$fe4f13c_9_9:
	if( r6 == NULL ) hl_null_access();
	r8 = r6->length;
	if( r5 >= r8 ) goto label$fe4f13c_9_29;
	r8 = r6->length;
	if( ((unsigned)r5) < ((unsigned)r8) ) goto label$fe4f13c_9_17;
	r9 = NULL;
	goto label$fe4f13c_9_20;
	label$fe4f13c_9_17:
	r11 = r6->array;
	r10 = ((vdynamic**)(r11 + 1))[r5];
	r9 = (kha__TimeTask)r10;
	label$fe4f13c_9_20:
	++r5;
	if( r9 == NULL ) hl_null_access();
	r3 = r9->start;
	r3 = r3 - r2;
	r9->start = r3;
	r3 = r9->next;
	r3 = r3 - r2;
	r9->next = r3;
	goto label$fe4f13c_9_9;
	label$fe4f13c_9_29:
	r5 = 0;
	r4 = (kha__$Scheduler)$g__kha_Scheduler;
	r7 = r4->DIF_COUNT;
	label$fe4f13c_9_32:
	if( r5 >= r7 ) goto label$fe4f13c_9_48;
	r8 = r5;
	++r5;
	r4 = (kha__$Scheduler)$g__kha_Scheduler;
	r12 = r4->deltas;
	if( r12 == NULL ) hl_null_access();
	r3 = 0.;
	r13 = r12->length;
	if( ((unsigned)r8) < ((unsigned)r13) ) goto label$fe4f13c_9_43;
	hl_types_ArrayBytes_Float___expand(r12,r8);
	label$fe4f13c_9_43:
	r14 = r12->bytes;
	r13 = 3;
	r13 = r8 << r13;
	*(double*)(r14 + r13) = r3;
	goto label$fe4f13c_9_32;
	label$fe4f13c_9_48:
	r3 = 0.;
	r4 = (kha__$Scheduler)$g__kha_Scheduler;
	r4->current = r3;
	r3 = 0.;
	r4 = (kha__$Scheduler)$g__kha_Scheduler;
	r4->lastTime = r3;
	return;
}

int kha_Scheduler_addBreakableTimeTaskToGroup(int r0,vclosure* r1,double r2,double* r3,double* r4) {
	hl__types__ArrayObj r14;
	kha__$Scheduler r10;
	bool r9;
	kha__TimeTask r7;
	double r5, r6, r12, r13;
	int r11;
	if( r3 ) goto label$fe4f13c_10_3;
	r5 = 0.;
	goto label$fe4f13c_10_4;
	label$fe4f13c_10_3:
	r5 = *r3;
	label$fe4f13c_10_4:
	if( r4 ) goto label$fe4f13c_10_7;
	r6 = 0.;
	goto label$fe4f13c_10_8;
	label$fe4f13c_10_7:
	r6 = *r4;
	label$fe4f13c_10_8:
	r7 = (kha__TimeTask)hl_alloc_obj(&$t_kha_TimeTask);
	kha_TimeTask_new(r7);
	r9 = true;
	r7->active = r9;
	r7->task = r1;
	r10 = (kha__$Scheduler)$g__kha_Scheduler;
	r11 = r10->currentTimeTaskId;
	++r11;
	r10->currentTimeTaskId = r11;
	r7->id = r11;
	r7->groupId = r0;
	r10 = (kha__$Scheduler)$g__kha_Scheduler;
	r12 = r10->current;
	r12 = r12 + r2;
	r7->start = r12;
	r12 = 0.;
	r7->period = r12;
	r13 = 0.;
	if( r5 == r13 ) goto label$fe4f13c_10_28;
	r7->period = r5;
	label$fe4f13c_10_28:
	r12 = 0.;
	r7->duration = r12;
	r13 = 0.;
	if( r6 == r13 ) goto label$fe4f13c_10_35;
	r12 = r7->start;
	r12 = r12 + r6;
	r7->duration = r12;
	label$fe4f13c_10_35:
	r12 = r7->start;
	r7->next = r12;
	r10 = (kha__$Scheduler)$g__kha_Scheduler;
	r14 = r10->timeTasks;
	kha_Scheduler_insertSorted(r14,r7);
	r11 = r7->id;
	return r11;
}

int kha_Scheduler_addTimeTaskToGroup(int r0,vclosure* r1,double r2,double* r3,double* r4) {
	vclosure *r8;
	double r5, r6, r9, r10;
	int r7;
	if( r3 ) goto label$fe4f13c_11_3;
	r5 = 0.;
	goto label$fe4f13c_11_4;
	label$fe4f13c_11_3:
	r5 = *r3;
	label$fe4f13c_11_4:
	if( r4 ) goto label$fe4f13c_11_7;
	r6 = 0.;
	goto label$fe4f13c_11_8;
	label$fe4f13c_11_7:
	r6 = *r4;
	label$fe4f13c_11_8:
	r8 = hl_alloc_closure_ptr(&$t_fun_3c2375f,kha_Scheduler_addTimeTaskToGroup__$1,r1);
	r9 = r5;
	r3 = &r9;
	r10 = r6;
	r4 = &r10;
	r7 = kha_Scheduler_addBreakableTimeTaskToGroup(r0,r8,r2,r3,r4);
	return r7;
}

bool kha_Scheduler_addTimeTaskToGroup__$1(vclosure* r0) {
	bool r2;
	if( r0 == NULL ) hl_null_access();
	r0->hasValue ? ((void (*)(vdynamic*))r0->fun)((vdynamic*)r0->value) : ((void (*)(void))r0->fun)();
	r2 = true;
	return r2;
}

int kha_Scheduler_addTimeTask(vclosure* r0,double r1,double* r2,double* r3) {
	double r4, r5, r7, r8;
	int r6;
	if( r2 ) goto label$fe4f13c_13_3;
	r4 = 0.;
	goto label$fe4f13c_13_4;
	label$fe4f13c_13_3:
	r4 = *r2;
	label$fe4f13c_13_4:
	if( r3 ) goto label$fe4f13c_13_7;
	r5 = 0.;
	goto label$fe4f13c_13_8;
	label$fe4f13c_13_7:
	r5 = *r3;
	label$fe4f13c_13_8:
	r6 = 0;
	r7 = r4;
	r2 = &r7;
	r8 = r5;
	r3 = &r8;
	r6 = kha_Scheduler_addTimeTaskToGroup(r6,r0,r1,r2,r3);
	return r6;
}

void kha_Scheduler_insertSorted(hl__types__ArrayObj r0,kha__TimeTask r1) {
	kha__TimeTask r8;
	double r6, r11;
	vdynamic *r9;
	varray *r10;
	int r2, r4, r5, r7;
	r2 = 0;
	if( r0 == NULL ) hl_null_access();
	r4 = r0->length;
	label$fe4f13c_14_3:
	if( r2 >= r4 ) goto label$fe4f13c_14_23;
	r5 = r2;
	++r2;
	if( r0 == NULL ) hl_null_access();
	r7 = r0->length;
	if( ((unsigned)r5) < ((unsigned)r7) ) goto label$fe4f13c_14_12;
	r8 = NULL;
	goto label$fe4f13c_14_15;
	label$fe4f13c_14_12:
	r10 = r0->array;
	r9 = ((vdynamic**)(r10 + 1))[r5];
	r8 = (kha__TimeTask)r9;
	label$fe4f13c_14_15:
	if( r8 == NULL ) hl_null_access();
	r6 = r8->next;
	if( r1 == NULL ) hl_null_access();
	r11 = r1->next;
	if( !(r11 < r6) ) goto label$fe4f13c_14_22;
	hl_types_ArrayObj_insert(r0,r5,((vdynamic*)r1));
	return;
	label$fe4f13c_14_22:
	goto label$fe4f13c_14_3;
	label$fe4f13c_14_23:
	if( r0 == NULL ) hl_null_access();
	r2 = hl_types_ArrayObj_push(r0,((vdynamic*)r1));
	return;
}

int kha_Scheduler_sortFrameTasks__$1(kha__FrameTask r0,kha__FrameTask r1) {
	int r2, r3;
	if( r0 == NULL ) hl_null_access();
	r2 = r0->priority;
	if( r1 == NULL ) hl_null_access();
	r3 = r1->priority;
	if( r3 >= r2 ) goto label$fe4f13c_15_7;
	r2 = 1;
	return r2;
	label$fe4f13c_15_7:
	r2 = r0->priority;
	r3 = r1->priority;
	if( r2 >= r3 ) goto label$fe4f13c_15_12;
	r2 = -1;
	return r2;
	label$fe4f13c_15_12:
	r2 = 0;
	return r2;
}

void kha_Scheduler_sortFrameTasks() {
	hl__types__ArrayObj r3;
	kha__$Scheduler r2;
	bool r1;
	vclosure *r4, *r5;
	static vclosure cl$0 = { &$t_fun_5ae4454, kha_Scheduler_sortFrameTasks__$1, 0 };
	r2 = (kha__$Scheduler)$g__kha_Scheduler;
	r1 = r2->frame_tasks_sorted;
	if( !r1 ) goto label$fe4f13c_16_4;
	return;
	label$fe4f13c_16_4:
	r2 = (kha__$Scheduler)$g__kha_Scheduler;
	r3 = r2->frameTasks;
	if( r3 == NULL ) hl_null_access();
	r4 = &cl$0;
	if( r4 ) goto label$fe4f13c_16_11;
	r5 = NULL;
	goto label$fe4f13c_16_12;
	label$fe4f13c_16_11:
	r5 = hl_alloc_closure_ptr(&$t_fun_dee1a83,kha_Scheduler_sortFrameTasks__$2,r4);
	label$fe4f13c_16_12:
	hl_types_ArrayObj_sort(r3,r5);
	r1 = true;
	r2 = (kha__$Scheduler)$g__kha_Scheduler;
	r2->frame_tasks_sorted = r1;
	return;
}

