// Generated by HLC 4.0.0 (HL v4)
#ifndef INC_kha__Shaders
#define INC_kha__Shaders
typedef struct _kha__$Shaders *kha__$Shaders;
typedef struct _kha__Shaders *kha__Shaders;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <kha/graphics4/FragmentShader.h>
#include <kha/graphics4/VertexShader.h>


struct _kha__$Shaders {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
	String Material_mesh_fragData0;
	kha__graphics4__FragmentShader Material_mesh_frag;
	String Material_mesh_vertData0;
	kha__graphics4__VertexShader Material_mesh_vert;
	String Material_shadowmap_fragData0;
	kha__graphics4__FragmentShader Material_shadowmap_frag;
	String Material_shadowmap_vertData0;
	kha__graphics4__VertexShader Material_shadowmap_vert;
	String painter_colored_fragData0;
	kha__graphics4__FragmentShader painter_colored_frag;
	String painter_colored_vertData0;
	kha__graphics4__VertexShader painter_colored_vert;
	String painter_image_fragData0;
	kha__graphics4__FragmentShader painter_image_frag;
	String painter_image_vertData0;
	kha__graphics4__VertexShader painter_image_vert;
	String painter_text_fragData0;
	kha__graphics4__FragmentShader painter_text_frag;
	String painter_text_vertData0;
	kha__graphics4__VertexShader painter_text_vert;
	String painter_video_fragData0;
	kha__graphics4__FragmentShader painter_video_frag;
	String painter_video_vertData0;
	kha__graphics4__VertexShader painter_video_vert;
	String pass_copy_fragData0;
	kha__graphics4__FragmentShader pass_copy_frag;
	String pass_vertData0;
	kha__graphics4__VertexShader pass_vert;
	vclosure* init;
};
struct _kha__Shaders {
	hl_type *$type;
};
#endif

