// Generated by HLC 4.0.0 (HL v4)
#ifndef INC_kha__input__SensorType
#define INC_kha__input__SensorType
typedef struct _kha__input__$SensorType *kha__input__$SensorType;
#include <hl/Enum.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <hl/natives.h>
#include <hl/types/ArrayObj.h>


struct _kha__input__$SensorType {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __ename__;
	hl_bytes_map* __emap__;
	hl__types__ArrayObj __constructs__;
	varray* __evalues__;
};
#endif

