// Generated by HLC 4.0.0 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <kha/_Assets/FontList.h>
vdynamic* Reflect_field(vdynamic*,String);
extern hl_type $t_kha_Kravur;
extern hl_type $t_dyn;
extern hl_type $t_String;
#include <hl/natives.h>
extern String $s_font_default;
hl__types__ArrayObj hl_types_ArrayObj_alloc(varray*);
extern hl_type $t_vrt_5860716;
extern String $s_font_default_ttf;
extern hl_type $t_hl_types_ArrayObj;
extern String $s_font;
#include <hl/ctx/29e9ba.h>
#include <hl/types/ArrayDyn.h>
#include <haxe/Log.h>
extern haxe__$Log $g__haxe_Log;
extern hl_type $t_vrt_329ffa8;
extern String $s_kha_internal_AssetsBuilder_hx;
extern hl_type $t_i32;
extern String $s_kha__Assets_FontList;
extern String $s_font_defaultLoad;
extern hl_type $t_vrt_eaa6a3b;
extern hl_type $t_ctx_729e9ba;
extern hl_type $t_fun_c640101;
extern hl_type $t_fun_c110581;
void kha_Assets_loadFont(String,vclosure*,vclosure*,vvirtual*);
void kha_Kravur_unload(kha__Kravur);

kha__Kravur kha__Assets_FontList_get(kha___Assets__FontList r0,String r1) {
	kha__Kravur r3;
	vdynamic *r2;
	r2 = Reflect_field(((vdynamic*)r0),r1);
	r3 = (kha__Kravur)hl_dyn_castp(&r2,&$t_dyn,&$t_kha_Kravur);
	return r3;
}

void kha__Assets_FontList_new(kha___Assets__FontList r0) {
	String r5;
	vvirtual *r6;
	hl__types__ArrayObj r1;
	hl_type *r3;
	kha__Kravur r7;
	int r4;
	varray *r2;
	r3 = &$t_String;
	r4 = 1;
	r2 = hl_alloc_array(r3,r4);
	r5 = (String)$s_font_default;
	r4 = 0;
	((String*)(r2 + 1))[r4] = r5;
	r1 = hl_types_ArrayObj_alloc(r2);
	r0->names = r1;
	r6 = hl_alloc_virtual(&$t_vrt_5860716);
	r5 = (String)$s_font_default;
	if( hl_vfields(r6)[1] ) *(String*)(hl_vfields(r6)[1]) = (String)r5; else hl_dyn_setp(r6->value,150958933/*name*/,&$t_String,r5);
	r3 = &$t_String;
	r4 = 1;
	r2 = hl_alloc_array(r3,r4);
	r5 = (String)$s_font_default_ttf;
	r4 = 0;
	((String*)(r2 + 1))[r4] = r5;
	r1 = hl_types_ArrayObj_alloc(r2);
	if( hl_vfields(r6)[0] ) *(hl__types__ArrayObj*)(hl_vfields(r6)[0]) = (hl__types__ArrayObj)r1; else hl_dyn_setp(r6->value,10018423/*files*/,&$t_hl_types_ArrayObj,r1);
	r5 = (String)$s_font;
	if( hl_vfields(r6)[2] ) *(String*)(hl_vfields(r6)[2]) = (String)r5; else hl_dyn_setp(r6->value,218690500/*type*/,&$t_String,r5);
	r0->font_defaultDescription = ((vdynamic*)r6);
	r5 = (String)$s_font_default;
	r0->font_defaultName = r5;
	r7 = NULL;
	r0->font_default = r7;
	return;
}

void kha__Assets_FontList_font_defaultLoad__$2(vclosure* r0,kha__Kravur r1) {
	if( r0 == NULL ) hl_null_access();
	r0->hasValue ? ((void (*)(vdynamic*))r0->fun)((vdynamic*)r0->value) : ((void (*)(void))r0->fun)();
	return;
}

void kha__Assets_FontList_font_defaultLoad__$1(venum* r0,vdynamic* r1) {
	vvirtual *r4;
	vclosure *r3;
	r3 = ((Enum$t_ctx_729e9ba*)r0)->p0;
	if( r3 == NULL ) hl_null_access();
	r4 = ((Enum$t_ctx_729e9ba*)r0)->p1;
	r3->hasValue ? ((void (*)(vdynamic*,vdynamic*,vvirtual*))r3->fun)((vdynamic*)r3->value,r1,r4) : ((void (*)(vdynamic*,vvirtual*))r3->fun)(r1,r4);
	return;
}

void kha__Assets_FontList_font_defaultLoad(kha___Assets__FontList r0,vclosure* r1,vclosure* r2) {
	String r8, r14;
	vvirtual *r7, *r10;
	venum *r12;
	haxe__$Log r6;
	vclosure *r4, *r5, *r11, *r13;
	int r9;
	if( !r2 ) goto label$da98f21_5_3;
	r4 = r2;
	goto label$da98f21_5_20;
	label$da98f21_5_3:
	r6 = (haxe__$Log)$g__haxe_Log;
	r5 = r6->trace;
	r7 = hl_alloc_virtual(&$t_vrt_329ffa8);
	r8 = (String)$s_kha_internal_AssetsBuilder_hx;
	if( hl_vfields(r7)[1] ) *(String*)(hl_vfields(r7)[1]) = (String)r8; else hl_dyn_setp(r7->value,37969014/*fileName*/,&$t_String,r8);
	r9 = 144;
	if( hl_vfields(r7)[2] ) *(int*)(hl_vfields(r7)[2]) = (int)r9; else hl_dyn_seti(r7->value,371360620/*lineNumber*/,&$t_i32,r9);
	r8 = (String)$s_kha__Assets_FontList;
	if( hl_vfields(r7)[0] ) *(String*)(hl_vfields(r7)[0]) = (String)r8; else hl_dyn_setp(r7->value,-63073762/*className*/,&$t_String,r8);
	r8 = (String)$s_font_defaultLoad;
	if( hl_vfields(r7)[3] ) *(String*)(hl_vfields(r7)[3]) = (String)r8; else hl_dyn_setp(r7->value,302979532/*methodName*/,&$t_String,r8);
	r10 = hl_to_virtual(&$t_vrt_eaa6a3b,(vdynamic*)r7);
	r12 = hl_alloc_enum(&$t_ctx_729e9ba,0);
	((Enum$t_ctx_729e9ba*)r12)->p0 = (vclosure*)r5;
	((Enum$t_ctx_729e9ba*)r12)->p1 = (vvirtual*)r10;
	r11 = hl_alloc_closure_ptr(&$t_fun_c640101,kha__Assets_FontList_font_defaultLoad__$1,r12);
	r4 = ((vclosure*)r11);
	label$da98f21_5_20:
	r8 = (String)$s_font_default;
	r13 = hl_alloc_closure_ptr(&$t_fun_c110581,kha__Assets_FontList_font_defaultLoad__$2,r1);
	r7 = hl_alloc_virtual(&$t_vrt_329ffa8);
	r14 = (String)$s_kha_internal_AssetsBuilder_hx;
	if( hl_vfields(r7)[1] ) *(String*)(hl_vfields(r7)[1]) = (String)r14; else hl_dyn_setp(r7->value,37969014/*fileName*/,&$t_String,r14);
	r9 = 144;
	if( hl_vfields(r7)[2] ) *(int*)(hl_vfields(r7)[2]) = (int)r9; else hl_dyn_seti(r7->value,371360620/*lineNumber*/,&$t_i32,r9);
	r14 = (String)$s_kha__Assets_FontList;
	if( hl_vfields(r7)[0] ) *(String*)(hl_vfields(r7)[0]) = (String)r14; else hl_dyn_setp(r7->value,-63073762/*className*/,&$t_String,r14);
	r14 = (String)$s_font_defaultLoad;
	if( hl_vfields(r7)[3] ) *(String*)(hl_vfields(r7)[3]) = (String)r14; else hl_dyn_setp(r7->value,302979532/*methodName*/,&$t_String,r14);
	r10 = hl_to_virtual(&$t_vrt_eaa6a3b,(vdynamic*)r7);
	kha_Assets_loadFont(r8,r13,r4,r10);
	return;
}

void kha__Assets_FontList_font_defaultUnload(kha___Assets__FontList r0) {
	kha__Kravur r2;
	r2 = r0->font_default;
	if( r2 == NULL ) hl_null_access();
	kha_Kravur_unload(r2);
	r2 = NULL;
	r0->font_default = r2;
	return;
}

