// Generated by HLC 4.0.0 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <iron/data/TShaderConstant.h>

void iron_data_TShaderConstant_new(iron__data__TShaderConstant r0,String r1,String r2,String r3,kha__arrays__Float32ArrayPrivate r4,kha__arrays__Float32ArrayPrivate r5,kha__arrays__Float32ArrayPrivate r6,vdynamic* r7,vdynamic* r8,vdynamic* r9) {
	r0->name = r1;
	r0->type = r2;
	r0->link = r3;
	r0->vec4 = r4;
	r0->vec3 = r5;
	r0->vec2 = r6;
	r0->_float = r7;
	r0->bool = r8;
	r0->_int = r9;
	return;
}

