// Generated by HLC 4.0.0 (HL v4)
#ifndef INC_iron__data__TWorldData
#define INC_iron__data__TWorldData
typedef struct _iron__data__$TWorldData *iron__data__$TWorldData;
typedef struct _iron__data__TWorldData *iron__data__TWorldData;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <iron/data/TProbeData.h>
#include <kha/arrays/Float32ArrayPrivate.h>


struct _iron__data__$TWorldData {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
};
struct _iron__data__TWorldData {
	hl_type *$type;
	String name;
	int background_color;
	iron__data__TProbeData probe;
	kha__arrays__Float32ArrayPrivate sun_direction;
	vdynamic* turbidity;
	vdynamic* ground_albedo;
	String envmap;
};
#endif

